### ISSUE TITLE
[Feature Request] Ability to choose ports 1400/1401, use custom DNS

### ISSUE THREAD

**Issue by RandomUserName22** [mullvad/mullvadvpn-app#1009]
Subject says it all.

Would like the Windows application to allow use of custom DNS servers and non-hijacking ports.  Yes, some may think this drops security a notch, but if you trust the DNS server for the benefits of the custom DNS, it's worth it.

**Comment by RandomUserName22** [comment]
Where are we at with this?

**Comment by faern** [comment]
Custom DNS is being tracked over at #473. And no, no progress yet.

**Comment by faern** [comment]
Closing this since it's about something another earlier issue is already tracking the progress of.
