### ISSUE TITLE
[Feature Request] Ability to change language from the GUI?

### ISSUE THREAD

**Issue by smokes** [mullvad/mullvadvpn-app#1019]
It currently automatically assumed I want to use my system's language. An option in the GUI to change the language would be very much appreciated.

**Comment by faern** [comment]
This has actually been in our backlog for a while. It will be implemented. Expect it to arrive in version `2019.8` or maybe `2019.9`.

**Comment by smokes** [comment]
Awesome, Is there anyway to currently change the language from some settings file? gui_settings.json maybe?

**Comment by faern** [comment]
Not from any settings file. But you can override the locale with the environment variable `MULLVAD_LOCALE`. Please see this FAQ entry for details: https://mullvad.net/en/guides/faq/#44

**Comment by faern** [comment]
It has been possible to change the language from the GUI for a few versions now. So I'm closing this issue.
