### ISSUE TITLE
[Feature request] Add autocompletion for arguments in CLI program

### ISSUE THREAD

**Issue by awsms** [mullvad/mullvadvpn-app#1035]
I just found annoying to have to manually type the whole commands, so I ended up using the GUI.

Could you implement an autocompletion, like the nordvpn expressvpn pia etc linux cli programs do? It would be great.

There is also no manual and the -h argument is pretty minimalistic, nothing is explained (how to find all the locations, set a killswitch etc)

**Comment by faern** [comment]
Adding CLI autocompletion is in the backlog! It will arrive in some not too distant future release! :)

Regarding help text and manuals. Yeah we know the current CLI is quite minimalistic. It has not gotten the same UX attention as the GUI. We will work on improving this over time.

Regarding "killswitch", that's on by default in our app, or there is no way to turn it off. If you connect, the app fully protects you until you explicitly disconnect again. You can read this recent blogpost from us for a more detailed explanation: https://mullvad.net/en/blog/2019/7/12/whats-app/

**Comment by faern** [comment]
This was finally merged in #1038. This adds shell completion for bash and zsh on Linux and zsh only on macOS. Will be part of the next release.
