### ISSUE TITLE
[Feature request] Add support for WireGuard private key extraction

### ISSUE THREAD

**Issue by chandradeepdey** [mullvad/mullvadvpn-app#1051]
Since the maximum number of WireGuard keys associated with an account is limited, this will help with dual boot setups. Otherwise at least 2 of the 5 keys are spent on the same device.

**Comment by faern** [comment]
The private WireGuard key used by the app can be found in the file `account-history.json`. This file is located in different directories on different platforms, see the readme for all paths: https://github.com/mullvad/mullvadvpn-app/#cache

We don't want making extracting the key possible from the UI in any way. Manually handling the private key is a security risk and users should normally never have to do this.

**Comment by Mikaela** [comment]
Where exactly is `account-history.json` on Windows 10? I am able to find it on Linux, but after mounting Windows `C:\` under Linux I am unable to find it.

The place where I would expect to find it would be `/mnt/windows/Users/mikae/AppData/Local/Mullvad VPN` but it's content is: ` blob_storage  'Code Cache'   GPUCache   logs  'Network Persistent State'` while under Linux `/var/cache/mullvad-vpn` contains `account-history.json  api-ip-address.txt  relays.json`.

**Comment by faern** [comment]
Quoting from the readme I linked above:
> On Windows, when a process runs as a system service the variable %LOCALAPPDATA% expands to C:\Windows\system32\config\systemprofile\AppData\Local.

So check under `C:\Windows\system32\config\systemprofile\AppData\Local\Mullvad VPN\`

**Comment by Mikaela** [comment]
Thank you, I missed that part looking just at the tables
