### ISSUE TITLE
[Question] Where is the locations endpoint?

### ISSUE THREAD

**Issue by kkoomen** [mullvad/mullvadvpn-app#1103]
I'm trying to figure out where the endpoint is in the desktop app where it fetching all the locations from. Can someone provide me a link to the file where this is done?

**Comment by faern** [comment]
Do you mean the GeoIP lookups it does to figure out which IP (and location) you are behind while not connected to a tunnel? We use our own service https://am.i.mullvad.net for that. The code for the lookup is here: https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-daemon/src/geoip.rs
