### ISSUE TITLE
Unclear error message when no account is configured

### ISSUE THREAD

**Issue by YaLTeR** [mullvad/mullvadvpn-app#1112]
When no account is configured, mullvad_daemon will always fail with `Blocked(TunnelParameterError(NoMatchingRelay))`, which is furthermore made worse by `mullvad connect` reporting `Failure to generate tunnel parameters: description() is deprecated; use Display`.

**Comment by faern** [comment]
Thanks for reporting this!
We will for sure make the CLI error message better.
Not sure if we want to complicate the `BlockReason` to avoid the `NoMatchingRelay` but we'll consider it.

**Comment by faern** [comment]
The CLI already reports a better error message. On latest master it says:
```
Tunnel status: Blocked: Failure to generate tunnel parameters: Failure to select a matching tunnel relay
```
Maybe you run an old version of the app? However, the message above is not reported by `mullvad connect`, because that command does not print anything. But rather `mullvad status` after trying to connect with no account number.

**Comment by YaLTeR** [comment]
> Maybe you run an old version of the app?

I use the one from the [mullvad-vpn AUR package](https://aur.archlinux.org/packages/mullvad-vpn/):
```
Current version: 2019.7
Supported: true
Latest version: 2019.7
```

> However, the message above is not reported by mullvad connect, because that command does not print anything. But rather mullvad status after trying to connect with no account number.

Yeah, that's what I meant, sorry.

**Comment by jneidel** [comment]
> ```
> Tunnel status: Blocked: Failure to generate tunnel parameters: Failure to select a matching tunnel relay
> ```

I got here looking up that error message. It was not clear to me previously that it would have to do with the account (it got revoked, as I found out with `mullvad account get`) and it could be communicated clearer.

**Comment by LSgeo** [comment]
Came here via google. I believe the fix for me was among the following:

1. [Update mullvad client](https://mullvad.net/en/help/install-mullvad-app-linux/)
2. Update the relay list `mullvad relay update`
3. Re-select relay settings with `mullvad relay set location --help`
