### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by Perflyst** [mullvad/mullvadvpn-app#1126]
The first beta for the android app is available, thank you for this!

Please consider to publish the android app on F-Droid, the most popular repository for android FOSS applications. You also would be the first VPN company which provides an open source app downloadable from F-Droid.

More information is available on the [F-Droid documentation](https://f-droid.org/en/docs/FAQ_-_App_Developers/).

**Comment by faern** [comment]
We will definitely publish the app on F-Droid. It's in the backlog and it will happen. But we are still in very early stages of the Android app, the very first beta just came out. When things stabilizes a bit we will be available both on Google Play and F-Droid.

**Comment by rakshazi** [comment]
Waiting for it :)
Btw, you can create your own f-droid repo on github pages (as static site)

**Comment by Perflyst** [comment]
I am against an own F-Droid repo, that makes no sense. I can publish any (malicious) binary I want on a my self managed F-Droid.

**Comment by Andrewskiz** [comment]
+1 looking foward to F-Droid release

**Comment by grrrrr** [comment]
I'll second a mullvad owned f-droid repo.  If even initially just for beta users,  it would make installing and updating a lot more manageable than having to side load.    Though given the delay of releases from f-droid official  it would be nice to have the final non  beta version on a mullvad repo as they can better control the release schedule

> I am against an own F-Droid repo, that makes no sense. I can publish any (malicious) binary I want on a my self managed F-Droid.

@perflyst, I am not sure your logic is right.  The F-droid repo would be owned and controlled by Mullvad.   If you are worried about them uploading a malicious binary to it, there is nothing to stop them doing it with the links to the beta apk on their site [here](https://mullvad.net/en/download/beta/) or even the github releases page.

**Comment by ProgressiveArchitect** [comment]
@grrrrr 
> If you are worried about them uploading a malicious binary to it, there is nothing to stop them doing it with the links to the beta apk on their site

Making the Mullvad App a Reproducible Build would provide some protection against this.

**Comment by eldervamp** [comment]
Now that the Mullvad app is on Google Play Store. I'm also waiting for Mullvad to appear on F-Droid :).

**Comment by dngray** [comment]
[Daniel](https://www.privacytools.io/about/) here from PrivacyTools. We would very much like to make F-Droid a base requirement of our [criteria](https://www.privacytools.io/providers/vpn/#criteria) for being listed.

I'd very much like to see Mullvad on F-Droid. Recently [ProtonVPN](https://github.com/ProtonVPN/android-app/issues/1) submitted theirs for inclusion and [IVPN](https://www.ivpn.net/blog/ivpn-for-android-is-now-available-on-f-droid) has also.  We would really like to see reproducible builds for all our recommended VPN providers.

Every so often, we like to tighten the requirements. This helps us send dozens of applications to the trash for non compliance. We like to have an easy reason to deny the crappy providers from even being considered 🙂.

**Comment by Mhowser** [comment]
Can't wait for this to happen, will be keeping my eyes on this.

**Comment by faern** [comment]
We will look into this now when we are done publishing on Google Play.

**Comment by cyanlemons** [comment]
Now that Mullvad has been published on the Google Play Store, I would imagine the F-Droid investigation begins?

**Comment by faern** [comment]
We are now available on F-Droid since yesterday: https://f-droid.org/packages/net.mullvad.mullvadvpn/
