### ISSUE TITLE
Issue with the latest release (Linux)

### ISSUE THREAD

**Issue by fwanky** [mullvad/mullvadvpn-app#1133]
Hey there, love mullvad. Favourite vpn i've ever used.
Sadly though, when recently updating to the latest version on Arch Linux, I can't start the gui at all anymore.

Here's the error I get;

```/usr/bin/mullvad-vpn: line 5: /usr/bin/mullvad-gui: No such file or directory```

**Comment by faern** [comment]
Ah. This is because the start script, `mullvad-vpn` expect the GUI binary (`mullvad-gui`) to be available in the same directory as itself (`/opt/Mullvad VPN/`). So it's not a bug with the app per se. It sounds like the Arch installation packaging is moving `mullvad-vpn` to `/usr/bin/` when it should not.

**Comment by fwanky** [comment]
Is there some script I need to move here then?
I really wanna try out the new features :(

**Comment by fwanky** [comment]
It seems to be that it's already in /opt/mullvad-vpn/? Confuzed..

```004 /o/m > ls | grep mullvad
mullvad-gui
mullvad-vpn```

**Comment by faern** [comment]
What happens if you run `which mullvad-vpn`? If arch does *copy* it to `/usr/bin/` it can very well exist in both places.

As a hacky fix, you can edit your `mullvad-vpn` script to start `/opt/Mullvad\ VPN/mullvad-gui` instead of trying to start it from it's own dir:
```bash
#!/usr/bin/env bash
set -eu

exec "/opt/Mullvad VPN/mullvad-gui" --no-sandbox "$@"

```

**Comment by fwanky** [comment]
```
012 ~ > which mullvad-vpn
/usr/bin/mullvad-vpn
```
I'll give the hacky fix a go, hacky fix = best fix.

**Comment by fwanky** [comment]
Yeah, it works..
Quick out of context, question, can you not do bridging with wireguard as your selected tunnel protocol?
Isn't wireguard the default for doing multihop when out of the client anyways?

**Comment by faern** [comment]
You currently can't do bridging/multi hop with WireGuard with this app, no. That is OpenVPN only for now.

**Comment by fwanky** [comment]
Ah damn! 
Okay, i'll close this, can't wait till for bridging with WireGuard though.
