### ISSUE TITLE
Failed to generate and verify wireguard key

### ISSUE THREAD

**Issue by xxyzz** [mullvad/mullvadvpn-app#1142]
I want to try the new features but get these two errors:
<img width="320" alt="Screen Shot 2019-09-28 at 22 26 53" src="https://user-images.githubusercontent.com/21101839/65818134-27344780-e241-11e9-8fd0-a321ae25e6de.png">
<img width="320" alt="Screen Shot 2019-09-28 at 22 28 16" src="https://user-images.githubusercontent.com/21101839/65818135-27ccde00-e241-11e9-9473-6215ecd15da2.png">
I'm using the 2019.8 version app on macOS 10.14.6.

**Comment by faern** [comment]
Please contact support@mullvad.net for help with using the app. Please send a problem report from within the app, then they will have the app logs they need to diagnose the problem you are having.
