### ISSUE TITLE
Android: Mullvad tray Icon not clearing on close. 

### ISSUE THREAD

**Issue by cybrnook** [mullvad/mullvadvpn-app#1164]
Samsung S10+ w/ Android 9 running the latest 2019.8- beta1 Mullvad app. 

When using the app,  two icons appear in the tray,  both the default android vpn icon as well add the mullvad icon. Both show the connection as active,  and both offer a disconnect option.  When disconnecting through the mullvad icon, the android vpn icon closes,  but the mullvad icon remains and cannot be swiped away.  When disconnecting using the android vpn icon,  both the vpn and the mullvad icon are cleared which would be expected. 

Else the mullvad icon remains stuck in the tray. I know there is a quit button within the settings of the app, but I would expect disconnecting and swiping away the icon would also close the app.

**Comment by faern** [comment]
I have never seen the WireGuard app show any notification at all. Maybe you mean the Android VPN icon? The key shaped icon usually shown on the right hand side? That is an Android OS specific icon shown whenever there is any VPN active. You would get it if you ran the vanilla OpenVPN app as well.

I guess we have a bug related to trying to disconnect via the default Android VPN notification then. We'll look into it, thanks for reporting!

**Comment by cybrnook** [comment]
@faern you are absolutely correct. I updated my wording to reflect properly. I have been using the wireguard app for so long, I always refereed to the andorid vpn icon as wireguard.

But the rest of the scenario holds true, which is likely similar to behavior and linked to my other bug: https://github.com/mullvad/mullvadvpn-app/issues/1165

**Comment by faern** [comment]
The reason why we have a dedicated notification button for our app in addition to the default Android VPN icon is for multiple reasons:
* We can show the user the current state directly in the notifications
* We can allow disconnecting/connecting from the notifications (this will improve even more later)
* It prohibits Android from killing our app. There are some problems with Android where it might randomly kill apps that don't have notifications. We try to keep our app running (to keep the phone safe) by having a notification, prohibiting Android from killing us.

**Comment by cybrnook** [comment]
No worries, I actually like the dedicated Mullvad notification icon. I would have just assumed that when I disconnect from the VPN, I would then be able to swipe away the icon and have the app close, which is not the behavior. Instead we have to go into the app directly, hit the gear, and then "quit", OR, disconnect using the Android VPN tray icon. Thanks for the quick responses @faern , I have thoroughly been enjoying my Mullvad membership!

**Comment by Flat** [comment]
I opened another issue as I didn't see this one, but I've written up the relevant reasons for why the app does this and I don't see why it can't be dismissed.

> Currently when `tunnelState = TunnelState.Disconnected` the notification is still set to run in the foreground only showing a notification with the text `R.string.unsecured` and the rich notification button `R.string.connect`; Due to running in the foreground however the notification cannot be dismissed unless the app is killed. Upon disconnection [stopForeground with the STOP_FOREGROUND_DETACH](https://developer.android.com/reference/kotlin/android/app/Service#stop_foreground_detach) flag should be used. This will allow a user to either reconnect through the notification or dismiss it if they do not intend to reconnect. This only works on API > 24 so a check would be needed, and if API < 24 the notification would need to be recreated as a plain notification and the foreground notification removed.

If this route is taken after tapping reconnect it can be started in the foreground again.

**Comment by faern** [comment]
It is in our backlog to allow dismissing the notification if the app is not currently protecting the phone connection. We'll get to it after more core stuff, such as tunnel stability and similar.

**Comment by faern** [comment]
In the latest version of the app, 2020.2-beta1, it's possible to swipe away the notification icon when the VPN is disconnected and the UI not in focus. So I'm closing this issue as resolved.
