### ISSUE TITLE
Android: "Quit" from within the application doesn't close

### ISSUE THREAD

**Issue by cybrnook** [mullvad/mullvadvpn-app#1165]
Samsung S10+ w/ Android 9 running the latest 2019.8- beta1 Mullvad app.

When connected to a server,  go into the gear and press quit. This does not disconnect and quit as expected. Instead it disconnects the server,  but you have to press quit again to actually close the app.

**Comment by faern** [comment]
We are aware of a few bugs around the quit behavior not fully working in some situations/on some devices. Please wait for the next beta and see if it works better there.

**Comment by faern** [comment]
We have fixed a number of issues related to the quit button lately. Please try to upgrade to the latest version. Hopefully that should fix it. Re-open the issue if this is still a problem on `2020.2-beta1`.
