### ISSUE TITLE
2019.9-beta1 Unsupported Version

### ISSUE THREAD

**Issue by telans** [mullvad/mullvadvpn-app#1186]
As the title says. This has not shown for any previous beta versions.

![Screenshot_20191009_092141](https://user-images.githubusercontent.com/45819748/66430270-42edd980-ea09-11e9-8b79-3f05140572fa.png)

![Screenshot_20191009_092213](https://user-images.githubusercontent.com/45819748/66430299-526d2280-ea09-11e9-98b2-6b8b2f1b727a.png)

**Comment by faern** [comment]
The app is not released on our website yet. We uploaded it on github a bit too early this time. As soon as the app is available on the website it should stop saying it's unsupported. Or within 24 hours from us marking it as supported. This warning should go away automatically soon.

**Comment by telans** [comment]
Thanks, perhaps a string change removing `Update available` if current version > site version, would be a good idea? @faern
