### ISSUE TITLE
[Feature Request] Option to enable Local Network Sharing on Android,

### ISSUE THREAD

**Issue by shashikantx** [mullvad/mullvadvpn-app#1199]
Am on 2019.9-beta1 Android, It is working great so far.

But It will be great if Local Network Sharing is implemented sooner, as it is very necessary feature have to be able to do local streaming to/from media server and PCs.

**Comment by faern** [comment]
It's a planned feature. Will be available in a not too distant release.

**Comment by articlecat** [comment]
This feature was added to version 2020.2. See #1461.

**Comment by faern** [comment]
Yes, this is now available in the latest beta, `2020.2-beta1`. So I'm closing this issue.
