### ISSUE TITLE
Cylance blocks Mullvad during installation

### ISSUE THREAD

**Issue by emilnd** [mullvad/mullvadvpn-app#1235]
Today I tried to install Mullvad 2019.9 on Windows 10. This on a freshly installed computer since 3 weeks back. I have no installation of Mullvad on this computer before.
The computer uses Cylance as antivirus and during the install it blocked a couple of .dll.

I have not seen this before on other computers with Cylance, though it may be about a year since I did an fresh install and not just updating Mullvad.

Dialog in the installation from Mullvad:
![Mullvad-install-dialog](https://user-images.githubusercontent.com/41476744/68531426-5050f900-0312-11ea-9760-75f90d6e5952.png)

Cylance version: 2.0.1540.8
![cylance-events-mullvad-install](https://user-images.githubusercontent.com/41476744/68531385-0a943080-0312-11ea-873c-96cd472808f6.png)
![cylance-threats-mullvad-install](https://user-images.githubusercontent.com/41476744/68531386-0a943080-0312-11ea-9d06-83a8c4255d92.png)

**Comment by faern** [comment]
For help with using the app, please contact support@mullvad.net

**Comment by emilnd** [comment]
Ok, I'll go there next time.
By the way, I tried once more today installing Mullvad and it actually worked fine this time.
