### ISSUE TITLE
[Feature Request] Custom DNS in Mullvad client

### ISSUE THREAD

**Issue by Yinchie** [mullvad/mullvadvpn-app#1236]
I would like to request this feature so I can keep my connection secured with the Mullvad VPN and would like to have additional DNS security with the use of DNSCrypt and or additional ad/malware blocking on a DNS level.

Right now I am unable to do so unless I make use of the OpenVPN client but I noticed some things don't work correctly the same way as the Mullvad VPN client.

So I am hoping for an advanced feature allowing users to enter their own DNS server.

**Comment by faern** [comment]
We will eventually implement this. But this issue is a duplicate of #473, so closing this issue.

**Comment by tuqueque** [comment]
Hi, I just wanted to say that I'm also a Mullvad client, I started using DNSCrypt-proxy recently (Manjaro Linux), and of course, Mullvad stopped working with the message:
```
BLOCKING INTERNET
Failed to set system DNS server
```
I've already read issue #473 and I know this is somewhat in the roadmap, but in 45 days my yearly subscription ends and I don't plan to renew it until this feature is in place. Hopefully this it not too far away in your to-do list and soon enough I'll be back as a Mullvad user/client.

Thank you for a great product anyways!
