### ISSUE TITLE
[Linux, usability improvement] Open Mullvad app directly when clicking on Mullvad icon in taskbar

### ISSUE THREAD

**Issue by akej74** [mullvad/mullvadvpn-app#1239]
I'm using Linux Mint 19.2 with Cinnamon (default config, no UI/Desktop customizations). When clicking on the Mullvad icon in the taskbar, a field with the text "Mullvad" is opened and I need to click on this as well to open the Mullvad app.

It's would be preferred if the app opened immediately when clicking on the taskbar icon, as is the case with most other apps.

**Comment by faern** [comment]
> It's would be preferred if the app opened immediately when clicking on the taskbar icon, as is the case with most other apps.

Yes, yes it would. We also want this. But we don't know how to do this with Electron. It has been like this for quite some time. We have not prioritized the issue very high. But we also don't know how to fix it. This is the type of taskbar entry Electron gives us by default.

**Comment by akej74** [comment]
Thanks for the reply, it seems this a problem in later versions of Electron, see [Electron Issue #19941](https://github.com/electron/electron/issues/14941). It's affecting many other apps built on Electron as well.

**Comment by faern** [comment]
A lot has changed since since this issue was posted. And tray icons on Linux is a mess. We do the best we can with the APIs that are provided by the desktop environments and Electron. Closing this since we won't really do more than we can.
