### ISSUE TITLE
[Question] How does Mullvad connect with openvpn endpoints?

### ISSUE THREAD

**Issue by kkoomen** [mullvad/mullvadvpn-app#1248]
I want to connect with an openvpn endpoint, for example: `us-nyc-002` via the command line using openvpn and a mullvad endpoint. How can I achieve this? I know I can do `openvpn --config myfile.conf` but since mullvad doesn't use config files for openvpn, I have no idea how to achieve this with mullvad.

**Comment by faern** [comment]
Do you mean via the Mullvad VPN app, or with vanilla OpenVPN?

If you mean with our own app, then see the CLI guide here: https://mullvad.net/en/help/how-use-mullvad-cli/

Closing since this is not really an issue with the app. Please contact support@mullvad.net for further help with using the app.

**Comment by kkoomen** [comment]
With vanilla openvpn. Any idea?

**Comment by faern** [comment]
You can download OpenVPN configs from our website: https://mullvad.net/download/config/

Please contact support@mullvad.net if you need further assistance.
