### ISSUE TITLE
mullvad wireguard problem

### ISSUE THREAD

**Issue by muluser** [mullvad/mullvadvpn-app#1254]
hello
i am having problem generating wireguard keys using my mullvad app or the terminal commands,
screenshots are attached to this email
i use this system
Linux my-pc 5.3.11-1-MANJARO #1 SMP PREEMPT Wed Nov 13 12:21:14 UTC 2019 x86_64 GNU/Linux

[gold@gold-pc ~]$ mullvad tunnel wireguard key generate
Error: Failed to communicate with mullvad-daemon over RPC
Caused by: JSON-RPC 2.0 Error: Internal error (Internal error)
[gold@gold-pc ~]$

please help me fix this, i tried a lot of things but it is not working.
thank you
![Screenshot from 2019-11-21 14-57-09](https://user-images.githubusercontent.com/58038890/69345925-39939600-0c72-11ea-92df-de56478d12dc.png)

**Comment by faern** [comment]
Please always contact support@mullvad.net for help with our service and app.

Check out your wireguard key management page after logging in to our website: https://mullvad.net/account/ports/. If you already have five active keys you need to manually revoke one on the website before the app works.
