### ISSUE TITLE
[Feature Request] Automatically connect when launching specific application

### ISSUE THREAD

**Issue by Booteille** [mullvad/mullvadvpn-app#1259]
Hi!

I would love to see an option to automatically enable the vpn for specific application (or at least when specific application are started).
This would avoid to use an application through an insecure connection.

I know there is an option to always connect on startup but I don't want to always use the VPN. I want to use it only with specific applications.

**Comment by ProgressiveArchitect** [comment]
What you are referring to is the functionality that "Split Tunneling" delivers. Mullvad's developers already have this on their roadmap as a planned feature.

Clarification: A Split Tunneling feature wouldn't auto-launch Mullvad in connection to other application launches. However, it would allow users to Blacklist applications they don't want running through Mullvad. Which means you could simply blacklist every application on your computer except the one you want running through the Mullvad VPN connection, which would achieve the exact same outcome/result that you are requesting.

**Comment by faern** [comment]
We are not going to implement that the app automatically connects when a certain program is started. That is not in scope. But as outlined by @ProgressiveArchitect we will have split tunneling, which in some cases can solve the same problems.

Going to close this as the feature this issue talks about is probably not going to be implemented. The issue for split tunneling can be found over at #781
