### ISSUE TITLE
[Feature Request] Android: Activate VPN on start-up

### ISSUE THREAD

**Issue by articlecat** [mullvad/mullvadvpn-app#1260]
The Android app (as of version 2019.10-beta1) is missing the option to activate the VPN on start-up. This feature is available on the desktop apps as the "Launch app on start-up" option in Settings -> Preferences.

Having this feature would ensure that the phone's connection is protected even after a reboot.

**Comment by rascarlo** [comment]
@articlecat for such thing, I use the android built-in always on vpn settings

**Comment by p3yot3** [comment]
The built-in android allways on settings does not start the secure connection, it only starts the Mullvad client (at least on my device). I still have to activate the secure connection manually.

**Comment by ricklepick** [comment]
+++1. I came here today to suggest this very thing (connect VPN on app start). Failing that, anyone know how to make it happen with Tasker?

**Comment by articlecat** [comment]
@rascarlo I have Mullvad as the "Always-on VPN" in the Android settings, but Mullvad doesn't turn on when I reboot the phone. The "Disconnected from always-on VPN" notification does show up, however. This is on Android 9 Pie.

**Comment by articlecat** [comment]
@ricklepick Automation apps like Tasker can open Mullvad, but unfortunately, it doesn't look like there is any way to turn on the VPN outside of the Mullvad app interface.

**Comment by ricklepick** [comment]
Today in the "Changed" section under Android on of https://mullvad.net/en/download/beta/ it says this:

_"Connect automatically if **MullvadVpnService** is started with an intent which has the ### android.net.VpnService action. Effectively, this should enable Always On behavior on Android versions where it's supported."_

Any way this can be leveraged in Tasker I wonder?

**Comment by pinkisemils** [comment]
If you send an Intent with the action set to whatever `VpnService.SERVICE_INTERFACE` is, then the service should connect automatically. The relevant code is [here](https://github.com/mullvad/mullvadvpn-app/blob/master/android/src/main/kotlin/net/mullvad/mullvadvpn/service/MullvadVpnService.kt#L88).

**Comment by member584681** [comment]
I have tested this and cam confirm it works on my android phone with android 9.
Settings->Connections->More connection settings->VPN->Mullvad VPN tap cogwheel->Set " Always-on VPN.
Previously before I did this I had to manually turn on mullvad VPN each.time. Now it does it automagically on restarting the phone😁.

**Comment by articlecat** [comment]
This feature also works for me on version 2020.1-beta1 when "Always-on VPN" is enabled. Thanks for implementing this!

**Comment by faern** [comment]
> whatever VpnService.SERVICE_INTERFACE is

Did anyone manage to do this via tasker? If so, what was the value/steps to configure it?
