### ISSUE TITLE
[Linux] replace gconf2 dependency with gsettings-desktop-schemas

### ISSUE THREAD

**Issue by Taijian** [mullvad/mullvadvpn-app#1269]
The readme states that the Linux client depends on the gconf2 package for the GUI client to work.

Now, gconf has been deprecated by the GNOME project since 2013 and replaced by gsettings-desktop-schemas. The last commit to gconf was in October 2015 (https://gitlab.gnome.org/Archive/gconf/commits/master), whereas https://gitlab.gnome.org/GNOME/gsettings-desktop-schemas is being actively developed. 

Also, I've experimented with simply removing gconf in my local install (seeing as gsettings in already installed as part of a 'normal' Gnome install) and voilá, the Mullvad App still works, even without gconf.

**Comment by faern** [comment]
The README is probably just outdated. That part is from way back when we used Electron <something very old version>. Our rpm/deb releases does not depend on `gconf2`.
