### ISSUE TITLE
Building from source

### ISSUE THREAD

**Issue by yochananmarqos** [mullvad/mullvadvpn-app#1275]
I followed the instructions I found here and am working on a PKGBUILD for the AUR (Arch User Repository).

[WIP PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/mullvad-vpn)

[Build log](https://gist.github.com/yochananmarqos/233132116901fd46d0da4f47c4b20a64)

I emailed support earlier, but the error has now changed and this seems to be the better place to address this.

**Comment by faern** [comment]
Could you paste the error you are getting here? I don't see any error in that very long log (that also has color escape codes which makes it hard to read.)

I'm not sure why you are going through the hell that is building all these third party stuff from source.

**Comment by faern** [comment]
If you build from source, you sadly won't have our release gpg signature to verify against. You can still verify the individual git tags for each release of course. But that's one extra step of indirection for the pkgbuild.

Also, all needed dependencies are submodules to our git repo. So if you just check it out recursively you should get all you need, instead of downloading a tarball of our source and then checking out the dependencies manually.

**Comment by pinkisemils** [comment]
Having looked at the PKGBUILD, I think there could be some improvements. I'm not sure what your motivations are for building _everything_ from source, if I wanted a bespoke pacman installer, I'd just build our daemon and GUI application and rely on the binary artifacts we've built already. The binary artifacts we have are either static executables (OpenVPN, Shadowsocks) or statically linkable libraries (OpenSSL for HTTPS in the daemon). The issue with building all of these is that you'll have to build all the dependencies for them too -all of this labor just to get to something that is _almost_ identical to what you have in the Arch repos already, except statically linked.

If I was tasked with making a bespoke pacman package, I'd start with just compiling the daemon and getting the GUI working without recompiling OpenVPN and OpenSSL and Shadowsocks. 

Having said that, the build log isn't being very cooperative - but it seems like you might be missing `libpam`. We plan on removing this dependency of OpenVPN the next time we revise that build.

**Comment by yochananmarqos** [comment]
I've updated both the PKGBUILD and the build log posted above. I received an error building the daemon:
```
error: could not find native static library `wg`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `talpid-core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

I have `wireguard-tools` installed which includes `/usr/bin/wg`

**Comment by faern** [comment]
You need `libwg.a`. That is a statically compiled version of `wireguard-go` with some custom code added by us for logging.

**Comment by faern** [comment]
All you need is available as ready compiled binaries in `dist-assets/binaries/x86_64-unknown-linux-gnu/`

**Comment by yochananmarqos** [comment]
I've got it working now, thanks again for the help!

**Comment by yochananmarqos** [comment]
After building clean, somehow the `dist/linux-unpacked` directory is not being populated. I've updated the PKGBUILD and build log in the first post.

**Comment by yochananmarqos** [comment]
@faern @pinkisemils Any ideas?

2019-12-02T18_20_37_622Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/sbin/npm', 'run', 'pack:linux' ]
2 info using npm@6.12.1
3 info using node@v13.2.0
4 verbose run-script [ 'prepack:linux', 'pack:linux', 'postpack:linux' ]
5 info lifecycle mullvad-vpn@2019.9.0~prepack:linux: mullvad-vpn@2019.9.0
6 info lifecycle mullvad-vpn@2019.9.0~pack:linux: mullvad-vpn@2019.9.0
7 verbose lifecycle mullvad-vpn@2019.9.0~pack:linux: unsafe-perm in lifecycle true
8 verbose lifecycle mullvad-vpn@2019.9.0~pack:linux: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/yochanan/Documents/AUR/mullvad-vpn/src/mullvadvpn-app/gui/node_modules/.bin:/home/yochanan/.local/bin:/usr/sbin:/sbin:/bin:/usr/games:/home/yochanan/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
9 verbose lifecycle mullvad-vpn@2019.9.0~pack:linux: CWD: /home/yochanan/Documents/AUR/mullvad-vpn/src/mullvadvpn-app/gui
10 silly lifecycle mullvad-vpn@2019.9.0~pack:linux: Args: [ '-c', 'gulp pack-linux' ]
11 silly lifecycle mullvad-vpn@2019.9.0~pack:linux: Returned: code: 1  signal: null
12 info lifecycle mullvad-vpn@2019.9.0~pack:linux: Failed to exec pack:linux script
13 verbose stack Error: mullvad-vpn@2019.9.0 pack:linux: `gulp pack-linux`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1023:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:281:5)
14 verbose pkgid mullvad-vpn@2019.9.0
15 verbose cwd /home/yochanan/Documents/AUR/mullvad-vpn/src/mullvadvpn-app/gui
16 verbose Linux 5.4.1-2-MANJARO
17 verbose argv "/usr/bin/node" "/usr/sbin/npm" "run" "pack:linux"
18 verbose node v13.2.0
19 verbose npm  v6.12.1
20 error code ELIFECYCLE
21 error errno 1
22 error mullvad-vpn@2019.9.0 pack:linux: `gulp pack-linux`
22 error Exit status 1
23 error Failed at the mullvad-vpn@2019.9.0 pack:linux script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by pronebird** [comment]
@yochananmarqos try google for `ERR_ELECTRON_BUILDER_CANNOT_EXECUTE` which appears in your logs.

**Comment by pronebird** [comment]
@yochananmarqos you miss a lot of files under `dist-assets/`. `./build.sh` should take care of that.

**Comment by yochananmarqos** [comment]
@pronebird Aha! I ended up copying them manually:
```
	cp dist-assets/binaries/x86_64-unknown-linux-gnu/{openvpn,sslocal} \
		dist-assets/
	cp target/release/*talpid_openvpn_plugin* dist-assets/
	cp target/release/{mullvad,mullvad-daemon,mullvad-problem-report} \
		dist-assets/
```
For some reason, the `relays.json` never gets generated. It still complains it can't find it, but everything builds. I snagged it out of the `.deb` and tossed it in manually:
```
	cp "$srcdir/relays.json" dist-assets/
```

I'm now doing a clean build to make sure I didn't miss anything like I did the first time I thought I had a successful build. Thanks for the pointers.

**Comment by faern** [comment]
`relays.json` is downloaded/generated in `build.sh`. We make every built artifact contain the very latest server list at that moment in time.

**Comment by yochananmarqos** [comment]
@faern I tried adding line 138 - 158 of `build.sh`, but it failed with no error. It's frowned upon to run an outside script in a PKGBUILD, so I'm trying to avoid just doing `./build.sh`.

**Comment by pronebird** [comment]
@yochananmarqos how can something fail with no error? Either way, you can run the cURL request we have there and then extract the `result` field into the `dist-assets/relays.json`. However note that you'd benefit from running `./build.sh` because it does a lot of things like stripping binaries and making them more compact etc.

**Comment by yochananmarqos** [comment]
@pronebird `makepkg` automatically strips binaries, see [makepkg.conf(5)](https://www.archlinux.org/pacman/makepkg.conf.5.html).

Since the script to update the relays won't run in the PKGBUILD for some reason, I've put it in a separate bash script that is called in the PKGBUILD.

**Comment by yochananmarqos** [comment]
So far so good and no one is complaining about the AUR packages not building. I'm now verifying the git tags, see [my commit](https://aur.archlinux.org/cgit/aur.git/commit/?h=mullvad-vpn&id=396d2b55aa29189ccf6098e886dfbe57a431a58c). I think that covers everything. 

One last thing: Is there a way to populate the dist/linux-unpacked directory without building the DEB & RPM?

**Comment by yochananmarqos** [comment]
Forgot to close this, all is well. You can see the working packages in the AUR.

**Comment by faern** [comment]
We have received some complaint that the app now takes an awful long time to install/upgrade on Arch. Since you build everything from source, including OpenSSL etc. I would expect that from Gentoo, but not anyone else :)

But since we don't maintain this third party package we can't really decide. We might provide an official package at some point that is pre-built.

**Comment by yochananmarqos** [comment]
@faern Before I took over maintainership of the `mullvad-vpn` AUR package, it was improperly using the `.deb` release as the source. AUR packages are required to build from source unless it's submitted as a binary package with a `-bin` extension; i.e., `mullvad-vpn-bin`. 

I now maintain [`mullvad-vpn`](https://aur.archlinux.org/packages/mullvad-vpn/) / [`mullvad-vpn-beta`](https://aur.archlinux.org/packages/mullvad-vpn-beta/) that build from source and [`mullvad-vpn-bin`](https://aur.archlinux.org/packages/mullvad-vpn-bin/) / [`mullvad-vpn-beta-bin`](https://aur.archlinux.org/packages/mullvad-vpn-beta-bin/) that use the `.deb` release. If folks don't want to wait a few minutes for it to build, they can install the binary package instead. It only takes about 10 or 15 minutes on my Ryzen 5 laptop. 

I'm not building OpenSSL from source, see the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mullvad-vpn). Any Rust package takes awhile to build.

All Arch packages build from source, see the [Arch Build System](https://wiki.archlinux.org/index.php/Arch_Build_System) wiki article. Packages in the [Arch repos](https://www.archlinux.org/packages/) are already built, however packages in the [Arch User Repository](https://wiki.archlinux.org/index.php/Arch_User_Repository) (AUR) must be built by the user.

**Comment by mshavliuk** [comment]
> You need `libwg.a`. That is a statically compiled version of `wireguard-go` with some custom code added by us for logging.

> All you need is available as ready compiled binaries in `dist-assets/binaries/x86_64-unknown-linux-gnu/`

Is there some way to get it for `armv7l`? I'm receiving the same error `could not find native static library wg` while trying to compile it for Raspberry Pi 4
