### ISSUE TITLE
Mullvad CLI Windows 10

### ISSUE THREAD

**Issue by rdebruin** [mullvad/mullvadvpn-app#1281]
Mullvad CLI cannot be started from a DOS box. Reason: C:\Program Files\Mullvad VPN\resources is not added to the PATH.

C:\Users\ruudd>mullvad
'mullvad' is not recognized as an internal or external command,
operable program or batch file.

Current PATH with Mullvad Release version 2019.9 version installed:

C:\Users\ruudd>path
PATH=C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\ruudd\AppData\Local\Microsoft\WindowsApps

Using Windows 10 Pro (latest version)

**Comment by faern** [comment]
When you say dos box, do you mean the "command prompt" (`cmd.exe`)?

Works for me here. So I can't reproduce the issue. Please go via support for help using the app. You can send a problem report from within the app (settings cog wheel icon -> Report a problem), that way support will have access to the installation log and might be able to diagnose the problem.

**Comment by rdebruin** [comment]
Yes, the "command prompt". Installed it multiple times with the same result
from scratch. I have send a problem report.

Op vr 29 nov. 2019 om 09:59 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by rdebruin** [comment]
I have send the report two times, but no answer yet. Installed Mullvad on my "work laptop" and on another laptop with a fresh copy of Windows 10 Pro installed. No other programs involved. In both cases Mullvad is not added to the PATH so I can't run Mullvad CLI from a DOS command prompt. Of course, it runs fine when starting it from the Mullvad directory itself,

**Comment by faern** [comment]
Have you tried with the 2019.10 release of our app that recently came out? It does include improved PATH handling on Windows and might fix your issues.

**Comment by rdebruin** [comment]
Hi Linus,

Yes, I did. I installed 2019.10 on two different Windows 10 (Pro) laptops.
One of the laptops had a clean Windows 10 Pro install without any other
programs installed.

In both cases the PATH was not modified by Mullvad after installation.

Now I think that the Mullvad CLI is not used a lot in a WIndows 10
environment, I still think it would be nice if it would work.

I have send a report via the Mullvad app.

Regards, Ruud.

Op di 7 jan. 2020 om 11:07 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by rdebruin** [comment]
Hi Linus,

Found a solution: Install Mullvad as Administrator under Windows 10. Then
the PATH is updated and Mullvad CLI works perfectly.

Regards, Ruud.

Op di 7 jan. 2020 om 11:07 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by faern** [comment]
That's veeeery strange. Because the first thing the installer does when running as your normal user is to elevant itself to admin privileges. Basically everything the installer does needs to be done as admin, not just editing the PATH.

**Comment by rdebruin** [comment]
I am the only user on WIndows 10 Pro, but it is also Administrator. When
installing a program, it runs by default in user mode. It looks like the
elevating to Admin mode does not work as expected on my two laptops.


I installed Windows 10 again from scratch, no changes to the UAC or Windows
defender with the same result with Mullvad. So installing with right-click
on the Mullvad executable with "run as Administrator" works great otherwise
a no-go.



Op di 7 jan. 2020 om 21:37 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by faern** [comment]
Do you get the UAC dialog when starting the installer or does it not even show that?
Can you specify what exact version of Windows 10 it is you have and if you have any idea what more might have happened to trigger this? We can't reproduce.

**Comment by rdebruin** [comment]
The only question I get is: Do you allow this app to make changes to your
device?

I will ask around in the Dutch VPN forum about the problem I have. Check if
others have seen this behaviour. I will let you know.

Regards, Ruud.

Op di 7 jan. 2020 om 22:25 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by rdebruin** [comment]
Found something:

When I create a new local account with user rights, the system asks at
installation of Mullvad for the Admin password and the PATH is updated.

When I use my account used at the installation of Windows 10 Pro (Microsoft
account), it never updates the PATH.

Can you see if this is correct? That is, with a user account with admin
status the PATH is not updated?

Regards, Ruud.

Op di 7 jan. 2020 om 11:07 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by faern** [comment]
Having a single admin account on a Windows computer is very common. That's basically the setup we try the most often, and it works fine for us. I have tried it here with Windows 10 Pro (1903)

The installer would not be able to install the program into `C:\Program Files` nor register a system boot service or install the TAP driver without being an admin user. So in the cases where the PATH is not updated for you, but the rest of the app installs fine it *must* already be running as admin. There must be something else that causes it to not update the PATH.

But it's kind of impossible for us to fix since we can't reproduce it and you are the only one who has reported this. :thinking:

**Comment by rdebruin** [comment]
We found the case and a solution. See this message from Stefan (Mullvad).
So all you need is a reboot when installed under a admin account.

*Hi Ruud,*

*That's a good find! It kind of happens to me too. When the new account is
an admin and I open the Command Prompt after installing Mullvad and run
"path" it does not show the path to Mullvad. However the path has been
added to the Registry which I can see when I double click on "path" in the
Environment folder in the Registry. I can also see it if I Run the command
"systempropertiesadvanced" and go to Environment Variables > (the lower
window section) > Path.*

*The path does not get added for the user until I reboot Windows or if I
run the Command Prompt as administrator or open systempropertiesadvanced.*

*Do you experience the same??*

*Best regards,*

*Stefan*


Op vr 10 jan. 2020 om 10:52 schreef Linus Färnstrand <
notifications@github.com>:

**Comment by dlon** [comment]
You have to open a new cmd process to see changes made to PATH in the registry. A reboot should not be necessary.

**Comment by rdebruin** [comment]
You have to open a DOS prompt with "Run as Administrator", else it won't work.

**Comment by dlon** [comment]
Closed since it's expected behavior.
