### ISSUE TITLE
Windows client download keeps failing

### ISSUE THREAD

**Issue by cellulosa** [mullvad/mullvadvpn-app#1314]
Hi guys,

any idea on why the download of the windows client keeps on failing?

![Capture](https://user-images.githubusercontent.com/1758593/70322422-f9abe180-1821-11ea-802a-673708c76ed0.PNG)

**Comment by faern** [comment]
That is strange. I have no idea. Try with another browser and/or try downloading it from our official site maybe: https://mullvad.net/download/

**Comment by cellulosa** [comment]
Same issue.

It seems it has to do with Windows Defender - when I added the download folder among the exclusions it worked fine.

**Comment by mvd-ows** [comment]
Can you go and check recent event log entries to see if there's more information there? Right-click on the start button and select `Event Viewer`. Navigate to `Application and Services Logs` -> `Microsoft` -> `Windows` -> `Windows Defender` and select the `Operational` log. See if there are any events with IDs `1116` or `1117`. If you can't find any events with those IDs, see if there events with other IDs and with a log message mentioning the installer binary.

**Comment by cellulosa** [comment]
hi @mvd-ows, unfortunately nothing comes up. I have also tried to clear the logs and re-download the client without the exclusion; the download is still removed but nothing is being logged at all from Windows Defender... Really strange. Is there anything else I could do to investigate this further?

**Comment by mvd-ows** [comment]
Do you run any other endpoint security software? If so, maybe it's trying to be smart and will monitor/use Defender's settings. If there are no pop-ups or logs that can be associated with Defender, I'd say the issue you're seeing is likely tied to some other piece of software.

Did you at some point try the following?

- Remove exclusion.
- Disable Defender.
- (Reboot for good measure.)
- Download app.

Same results for this test?

**Comment by faern** [comment]
This issue has not seen any updates or new info in a long time now. I will close the issue. Feel free to re-open it if this is still a problem.
