### ISSUE TITLE
Android beta2 has no settings

### ISSUE THREAD

**Issue by tycrek** [mullvad/mullvadvpn-app#1319]
- App: 2019.10beta2
- Android: 9.0
- Phone: LG G7 (no root)

**Problem**:

The android app for Beta 2 has no settings. There is a settings menu with Account, Wireguard Key, App Version link, and Report Issue. There are no options for changing protocols, ports, bridge mode, etc.

**Comment by faern** [comment]
That's how every Android beta we have released so far looks. It's a bit short on features so far. We focus on stability before functionality. So this is not an issue, it's just not implemented yet :)
