### ISSUE TITLE
Poor readability with text from map/ui

### ISSUE THREAD

**Issue by jbergstroem** [mullvad/mullvadvpn-app#1320]
<img width="318" alt="Screen Shot 2019-12-09 at 10 44 09 AM" src="https://user-images.githubusercontent.com/176984/70443370-c7df8880-1a76-11ea-9e8b-7cfbf83e88fb.png">

Some combinations of locations and edge servers result in very poor readability. Perhaps dim/remove background text as it becomes overlayed.

- Using MacOS 10.15.1
- Mullvad client 2019.9

**Comment by faern** [comment]
Thanks for the input. We have considered removing the text from the map completely.

**Comment by ace2k** [comment]
@faern
You could put the info in a box like this.
Here's quick mockup with drop shadow and blur filter.

![mullvad-02](https://user-images.githubusercontent.com/46848252/72376346-146d5200-370e-11ea-8549-53f0b70a8c13.png)

**Comment by faern** [comment]
This has now been resolved by removing all the text from the map. The latest version of the app (2020.2) does not have city names in the background.
