### ISSUE TITLE
updated Android beta2, but still notice update available

### ISSUE THREAD

**Issue by cmmei** [mullvad/mullvadvpn-app#1329]
Device: Nokia 6 
System: Android 9

I have downloaded and installed Android beta2 from GitHub, but it still notices me update available.

![](https://i.loli.net/2019/12/10/uEey49pHsmRUlvd.png)

**Comment by faern** [comment]
See if it goes away after 24 hours. That's how often this app checks its version compatibility. We should make it so it's correct directly after upgrade of course. I just want to know if this is the issue you are having here or something else.

Thanks for reporting this.

**Comment by cmmei** [comment]
Thank you. I got it. This can be closed.

在 2019年12月10日週二 17:17，Linus Färnstrand <notifications@github.com> 寫道：
