### ISSUE TITLE
[Feature request] Multihop configuration

### ISSUE THREAD

**Issue by rakshazi** [mullvad/mullvadvpn-app#1341]
Hello,
Could you add multihop support to app, please?

Didn't see it in windows, Linux and android app, but it's the very cool and useful feature!

Thank you

**Comment by Mikaela** [comment]
It's in the Linux app (and probably Windows, but I haven't tried on it), but not in Android that I can see.

* https://mullvad.net/en/help/how-use-bridge-mode/

**Comment by faern** [comment]
Exactly as @Mikaela points out, use the bridge mode. It exists on all desktop platforms, but not yet on mobile. Using a bridge effectively makes the tunnel multi hop.

**Comment by Mikaela** [comment]
Is there a separate issue about mobile support or could this be reopened for it?

**Comment by faern** [comment]
I personally don't feel the need to have a github issue on the topic. Multihop for mobile is on the roadmap. Some unknown distance in the future. The mobile apps are not even released yet (yeah, Android is in beta) so we are currently focusing on a minimum viable product there.
