### ISSUE TITLE
[Bug][Minor] Android displays "Update Available" when there is no APK available

### ISSUE THREAD

**Issue by bradynpoulsen** [mullvad/mullvadvpn-app#1342]
With the `2019.10` being released today, the Android app displays that there is an update available. When I load the website up, the "latest" Android update displayed is `2019.10-beta2`.

While there _SHOULD_ perhaps be a `2019.10` stable release for Android as well, my recommendation is for the app to verify that there is a new update available for its respective platform before displaying that there is a new update available.

Screenshots for completeness:

<table>
<tr>
<td>

![Screenshot_20191213-003116](https://user-images.githubusercontent.com/5748275/70779027-e2e51d80-1d40-11ea-9398-54e02cfe2b2a.png)

</td><td>

![Screenshot_20191213-003416](https://user-images.githubusercontent.com/5748275/70779099-08722700-1d41-11ea-8602-fd0a0b733b94.png)

</td></tr></table>

**Comment by faern** [comment]
Thanks for reporting this. We know there are some issues in the first 24 hours of us releasing a new app, due to delayed fetching of the latest info from the existing apps. Could you please report back whether or not this message goes away for you within 24 hours or not?

**Comment by bradynpoulsen** [comment]
As described, the update notifications appear to have been cleared within 24 hours of updating. I did update another Android device this morning that showed the `2019.10` update for a few hours but has also since cleared up.

**Comment by faern** [comment]
Good. We'll make sure to fix this issue before `2020.1` :)
