### ISSUE TITLE
[Feature Request][Android] Support for allowing certain apps to bypass the VPN?

### ISSUE THREAD

**Issue by steamp0rt** [mullvad/mullvadvpn-app#1343]
For example, allowing Netflix/Disney+/etc to ignore the VPN. In addition, some apps like KDE Connect won't work through VPNs.

Like, similar to the PIA app.

**Comment by faern** [comment]
Duplicate of #781. Closing this issue.

**Comment by steamp0rt** [comment]
Oh thanks, I looked to see if this would be a duplicate, but I didn't think of it as "split traffic"!
