### ISSUE TITLE
Latest Windows app reporting that it's out-of-date

### ISSUE THREAD

**Issue by reybango** [mullvad/mullvadvpn-app#1352]
Hey there, I just downloaded 2019.10 for Windows from the Mullvad.net site and after upgrading from the previous version, I'm seeing the following message saying that the app is out of date. Is this a known issue? I've attached a screenshot so you can see the issue.

![mullvad-app-version](https://user-images.githubusercontent.com/1748/71023719-508ea200-20d1-11ea-9551-3f04d25e541c.png)

**Comment by faern** [comment]
This is a known issue. See #1342.
