### ISSUE TITLE
Memory Leak in gnome-shell

### ISSUE THREAD

**Issue by Dashon1** [mullvad/mullvadvpn-app#1357]
Hey I'm having trouble with the mullvad vpn client app for linux causing a memory leak in gnome-shell.

Here I have listed steps to reproduce as well as things I have tried to remedy the problem.

. Install ubuntu 19.10

2. Download latest.deb file from mullvad website here: https://mullvad.net/en/download/

3. Name of file after downloading: MullvadVPN-2019.10_amd64.deb

4. Install

5. Run the mullvad app

6. Notice gnome-shell freezes for a few seconds. Amount of time it freezes varies from time to time but no more than 10 seconds.

7. Open gnome-system-monitor

8. Notice a sizable increase in memory allocation to gnome-shell. It varies each time. I have noticed upwards of 1 gb being used. I wanted to be as accurate as possible so I am doing this as I type and in this particular instance I have noticed an increased of around 400 MiB

Steps taken to Fix:

1. Uninstall and reinstall mullvad -----Conclusion - Did not work.

2. Uninstall all extensions except for the 4 that I knew were working before the slowdown ----- Conclusion - Did not work.

3. Install older version of mullvad app -----Conclusion did not work.

4. Fresh install of ubuntu 19.10 -----Conclusion - Fixed slightly, the app still freezes gnome-shell for the length of time stated earlier but the memory leak is not as big or non existent. Right now I am seeing aproximatley 150 Mib left over. However after performing this test again gnome-shell shot up to using 1 Gib. All of this as reported by gnome-system-monitor

Thoughts currently: maybe some update to one of the libraries that the app relies on has caused a problem.

P.S.

    Hope this helps. Let me know if there is anymore information I can provide.

**Comment by faern** [comment]
Maybe they don't handle tray icons very well these days?

Try installing the package `libappindicator3-1` if it's not already installed and see if that makes any difference. If `libappindicator1` see if you can uninstall it maybe? WARNING: Make sure this won't break anything before doing so. If `apt` tells you that uninstalling `libappindicator1` will force uninstall a lot of other dependents then don't do it.

**Comment by Dashon1** [comment]
@faern I do have the package libappindicator3-1 installed. Seems it was installed automatically. The package libappindicator1 is not installed according to "apt list libappindicator1".

**Comment by faern** [comment]
Ok. Sounds more like a problem with gnome-shell than our app. But with your instructions above we might be able to reproduce it at some point and see if there is anything we can do.

**Comment by Dashon1** [comment]
@faern Alright well thanks for the help after playing around a bit more, I can tell you that using mullvad from the command line works perfectly fine (honestly I might prefer this way) ,so it seems to be a problem only affecting the gui. Don't know if that would be useful but thought I would bring it to your attention.

**Comment by faern** [comment]
Closing this as the issue is stale by now. Maybe it's automatically fixed by us upgrading Electron or gnome-shell improving some of their code. Please reopen if this is still a major issue.
