### ISSUE TITLE
Android: doesn't install on some custom ROMs on older Devices 

### ISSUE THREAD

**Issue by sozifa** [mullvad/mullvadvpn-app#1368]
The app refuses to install on unofficial Lineage 14.1 ROMs (Android 7.1.2) with the error Android 5.0 min .... not sure what are the variables checked by the apk ... tested with Nexus 5 (hammerhead) and nexus 7 2012 WiFi (grouper)

**Comment by Atrate** [comment]
Try installing from the terminal if you have root and post the error message from there

```
pm install <apk file>
```

**Comment by faern** [comment]
We have now bumped the minimum required Android version from 5 to 7. Other than that I have no idea if there are any updates to this issue. Is it still hard/impossible to install on Lineage?

**Comment by Rawa** [comment]
Stale, closing
