### ISSUE TITLE
Huge battery drain at android 9 

### ISSUE THREAD

**Issue by Ud4ba** [mullvad/mullvadvpn-app#1372]
Hello guys and thank your for your wonderful job . I run android 9 (aosp) at 2019.10-beta2 with redmi 4a . 
I have -always on VPN and the battery drain is huge . is there any update coming soon ? is it known?

**Comment by faern** [comment]
That is unfortunate. Some users don't experience much battery usage from our app, but some do. We are looking into the matter and we will try to fix it. Thanks for reporting.

**Comment by faern** [comment]
Do you have any numbers on how huge it is? If you go to the battery section of the settings, how many percent of the total battery is reported as consumed my Mullvad VPN?

**Comment by DennisTheMenace81** [comment]
Hi same problem here the settings tells me after one week, the battery usage is 199,97% 
Samsung Galaxy S9 (Android 9)

**Comment by Ud4ba** [comment]
I cant provide you any numbers because i have disable health services . 
but since i started using mullvap vpn i noticed that the battery leves are going down like crazy .

**Comment by DennisTheMenace81** [comment]
Maybe the reason why we're noticing that is because we used an other vpn before, I'm also new to mullvad. The Android App of my old vpn was ipsec based. I thought an advanced of wireguard is that it uses less battery. The Android App of my old vpn provider showed a battery usage of about 4 to 5%. Since I switched, the health service says 199,97% Mullvad App. It also makes a lot more internet traffic, but this doesn't bothers me

**Comment by Ud4ba** [comment]
Before i used protonvpn free edition . with minimun battery usage . but now i thing something is up

**Comment by DennisTheMenace81** [comment]
But strangely enough, on my Tablet, galaxy tab s4, the battery usage is only 0,4%

**Comment by faern** [comment]
This Android app is still in beta. We are currently issuing a continuous stream of ping packets to ensure the tunnel works. This is probably what causes your CPU and radio chips to stay awake and drain battery. Interesting enough this does not really impact battery usage much on a lot of phones, which is why we have not been in a rush to fix it.

We are currently working on replacing the constant pinging with better ways of ensuring the tunnel works. Next beta of the Android app will likely have very different logic for this. Please try it when it comes and see if you notice any improvements.

**Comment by Medvosteri** [comment]
Mobile Data + Mullvad app = No Doze/Deep Sleep.
Wi-Fi + Mullvad app = 'Normal' Doze/Deep Sleep.

Dozing issue seems to be mainly coming from the following (kernel-)wakelocks on my device:

"IPA_CLIENT_APPS_LAN_CONS"
"IPA_WS"

Tested with 'BetterBatteryStats' app.

**Comment by anderssonola** [comment]
OnePlus 5T with android 9, my mullvadVPN app uses 40-60% of the battery

**Comment by Ud4ba** [comment]
thats bad if this issue is not 1st priority ... protonVPN announces that their vpn becomes open source.

**Comment by faern** [comment]
This is being actively worked on. Next beta should hopefully be better.

**Comment by DennisTheMenace81** [comment]
As an alternative you can use the official wireguard App, it has an better battery usage on my galaxy s9

**Comment by realmain** [comment]
On Android 9 on my Samsung Note 9, Mullvad Android App uses about 40-60% battery, whereas if I use Wireguard, it uses about 10% per day.

**Comment by DennisTheMenace81** [comment]
For me the huge battery usage is gone with the new 2020.1 beta1
(Samsung Galaxy S9)

**Comment by realmain** [comment]
Yup. The newest version fixed the battery drain issue for me as well.

**Comment by faern** [comment]
Closing this since people have reported that it's fixed in the latest releases.

**Comment by stevenfang1997** [comment]
After the new update(2020.6-beta1), the app drains a lot of battery. The previous version was fine. I'm on Android 8.1.

**Comment by baltuonis** [comment]
The latest 3-4 version were draining a lot fo battery.
Xiaomi MIUI Global 11.0.1 (was draining with v 10 too)

**Comment by wardboumans** [comment]
I'm getting drain as well since a week or so. On android 7. Battery stats always show Mullvad on top. Currently 43% of battery is Mullvad. This wasn't the case before.

**Comment by faern** [comment]
@wardboumans Which version of the app are you running? We had huge battery drain in `2020.6-beta1` but fixed it in `2020.6-beta2`. If you run that latest version and still see more battery usage than average we probably have another bug maybe.

**Comment by wardboumans** [comment]
@faern I notice i'm running beta2, strange. I installed the app 2-2,5 weeks ago. I didn't notice an app update. So it's strange i start noticing it now. Normally I easily make it through the day now early evening it's ~15%. And i'm far from a heavy user. I also getting notifications that 'an app is using a lot of resources, do you want to optimize? (its Mullvad)'. Didn't get those in the beginning.

If there some other way I can diagnose this future? (I'm running root).

**Comment by faern** [comment]
What phone model + brand are you using? You can try sending us a problem report from within the app. Explain in the problem report text message that you see huge battery drains and that you have been talking to us on github.

**Comment by baltuonis** [comment]
![Screenshot_2020-09-20-02-16-32-011_com miui securitycenter](https://user-images.githubusercontent.com/188666/93956071-d31f4e80-fd40-11ea-8298-728263036b45.jpg)

Using latest version for Android + MIUI 10. Big battery drain.
