### ISSUE TITLE
Dns leak after reboot when the android beta 1 2020 automatically connects 

### ISSUE THREAD

**Issue by DennisTheMenace81** [mullvad/mullvadvpn-app#1453]
Hi after an reboot the app automatically connects to an server, when I check the am.i.mullvad.net site I have an dns leak, the leak is gone after i disconnect and reconnect again. The dns leak only happens after a reboot and the automatically connect but only on my galaxy tab s4 android 9 tablet, on my android 10 phone this doesn't happens

**Comment by pinkisemils** [comment]
This seems like a bug with Android, as the same exact code runs when you connect manually and during startup. We'll look into this to see if we can mitigate the issue.

**Comment by DennisTheMenace81** [comment]
Sometimes I have to disconnect and reconnect 2 times before the dns leaks are gone. So it happens not only during startup also a few times during a manually reconnect.
But mostly after startup, and like I said only on my android 9 tablet I had sent a problem report yesterday

**Comment by DennisTheMenace81** [comment]
Are there any new information about that dns leak after a reboot, on the Samsung Galaxy Tab s4 ? This don't happens if I use the official wireguard app

**Comment by DennisTheMenace81** [comment]
Ok I had installed the new 2020.4.1 version and the problem still exists, but with that new auto connect option I can control it, so when I have it turned of, my connection is blocked till I manually connect (always on vpn in android option activated) . So that's good because I don't have a dns leak after a reboot because my connection is blocked till I manually connect. I can live with that.
Thanks for this auto connect option, it solved my problem 
Sorry for my bad English 
GreetZ
