### ISSUE TITLE
[Feature] Quick settings icon on Android

### ISSUE THREAD

**Issue by Atrate** [mullvad/mullvadvpn-app#1466]
Many other VPN applications such as OpenVPN, Wireguard or Viscerion provide a custom tile that can be added to the quick settings (pull down statusbar options).

Would be nice if Mullvad also supported that.

**Comment by faern** [comment]
I suppose this is for Android you mean? Yes, we might look into that feature.

**Comment by faern** [comment]
The quick setting tile has been available in the Android app for a few versions now. Closing this issue as resolved.
