### ISSUE TITLE
Android: Add option to 'connect on start'

### ISSUE THREAD

**Issue by ricklepick** [mullvad/mullvadvpn-app#1474]
I'd love to have an option in the Android app that causes it to connect automatically when the app opens, to the last location it was connected when the app closed. 

Use case:
- I arrive at work
- Phone connects to work's OPEN Wi-Fi
- _Tasker_ recognizes connection to work Wi-Fi
- _Tasker_ task fires to turn my volumes down low (so as to not bother fellow workers with my chirping phone)
- _Tasker_ task also launches Mullvad android app
- Mulvad app connects automatically to last location (this is a settings option that I've enabled).

This last part is the ask. Thank you for your consideration

**Comment by faern** [comment]
If the app is started with the right intent, it will automatically connect. See this other issue on activating the VPN on start: https://github.com/mullvad/mullvadvpn-app/issues/1260#issuecomment-583387306.

We might add a more convenient way of making the app always auto-connect when opened later. But there are some UX issues around that that has to be figured out first. Hopefully you can solve the issue with the linked comment.

**Comment by ricklepick** [comment]
I saw that. Couldn't figure out how to do it with Tasker. :-(   I don't want an always-on VPN (not sure if that's mandatory).

I'll have another look.

**Comment by faern** [comment]
You don't need always on VPN. The thing is that *if* you enable always on VPN then Android will automatically start our app with the intent specified in that comment. And that will trigger the app to auto-connect. So if you don't have always on VPN but configure tasker to start our app with that same intent, then the app will think it's started by the system and will auto-connect.

**Comment by ricklepick** [comment]
Thanks!  Eagerly looking forward to that.

Today I can use Tasker "Send Intent" action in a task to start "OpenVPN for Android", have it open my "HOME" profile and **connect** by doing this:

Action: android.intent.action.MAIN
Cat: none
Extra: de.blinkt.openvpn.shortcutProfileName:HOME
Package: de.blinkt.openvpn
Class: de.blinkt.openvpn.LaunchVPN
Target: Activity
(all other settings left at default)

Not sure how this could be done with MullVad

**Comment by pinkisemils** [comment]
Technically, you should be able to start it with `am startservice net.mullvad.mullvadvpn/.service.MullvadVpnService -a android.net.VpnService`, but on a regular, non-rooted phone, the adb user lacks the `android.permission.BIND_VPN_SERVICE` permission. The command desugars to something akin to:
```
Action: android.net.VpnService
Package: net.mullvad.mullvadvpn
Class: net.mullvad.mullvadvpn.service.MullvadVpnService
Target: Service
```
But after trying it with Tasker, it seems like Tasker lacks the correct permission to start a VPN service. We'll look at adding other ways to get this working.

**Comment by ricklepick** [comment]
Thanks again!

**Comment by faern** [comment]
Being added in #1488

**Comment by faern** [comment]
This has now been merged. So it will be available in the next release.
