### ISSUE TITLE
Exhausted namespace when forcing adapter rename

### ISSUE THREAD

**Issue by datastory** [mullvad/mullvadvpn-app#1476]
Installation of client v. 2020.1 fails on error _Fatal error during driver installation: Exhausted namespace when forcing adapter rename._

Clean reinstall did not solve the problem.

Win 10 Enterprise v. 10.0.18363.

**Comment by faern** [comment]
Thanks for reporting this. We are aware due to more users contacting our support about it as well. We are looking into the problem.

**Comment by faern** [comment]
This has been fixed in the latest release, 2020.2. Please upgrade to that version to resolve this issue.
