### ISSUE TITLE
IPv6 traffic does not exit on Mullvad Android App

### ISSUE THREAD

**Issue by nickz26** [mullvad/mullvadvpn-app#1490]
When using Mullvad for Android App, and connecting to a server, upon visiting websites such as ipleak.net , ip6.me , etc, I found that it is unable to communicate any IPv6 traffic, but when I use the Mullvad VPN app for Desktop or the WireGuard for Android app, it is able to tunnel both IPv4 and IPv6.

You can recreate this bug by connecting to a server on Mullvad for Android, and then visiting ipleak.net and seeing the failed IPv6 test, or visiting ip6only.me , and it will fail to resolve entirely, whereas on Mullvad PC app or Android WireGuard app it would work. This bug is present in the most recent release 2020.2-beta1

**Comment by Atrate** [comment]
Can reproduce

**Comment by jvff** [comment]
Hello :) Could you please verify if this is still an issue with the latest beta version?

**Comment by nickz26** [comment]
Hi there. This is no longer an issue on the latest beta version, thanks for the fix

-------- Original Message --------

**Comment by jvff** [comment]
Great! Thanks :)
