### ISSUE TITLE
Tray icon bug

### ISSUE THREAD

**Issue by mastercoldcoder** [mullvad/mullvadvpn-app#1492]
Hello , i just installed Mullvad 2020.2 on my debian 10 buster LXQT and i found a little bug on the tray icon, bad display.

<a href="https://imgbb.com/"><img src="https://i.ibb.co/KyKWVpc/capture.png" alt="capture" border="0"></a>

The problem was not present on previous versions.

**Comment by faern** [comment]
Yeah we recently replaced the icon to make it slightly larger. The result was that it turned out blurry on some platforms. We are working on fixing this for the coming release.

**Comment by mastercoldcoder** [comment]
Thanks keep it up the good work, +1 mullvad

**Comment by faern** [comment]
The tray icon has been reworked a bit since a few versions now. And we have done other Electron tray icon upgrades. So hopefully this should be resolved already. Please reopen if this is still an issue.
