### ISSUE TITLE
regression? Mullvad VPN app no longer automatically reconnects after wake

### ISSUE THREAD

**Issue by emacsomancer** [mullvad/mullvadvpn-app#1497]
Using the latest 2020.2 on Linux with Wireguard, after resuming the machine after a suspend, the Mullvad VPN app no longer automatically reconnects. I have to 'cancel' the current connection and then click 'connect' again. Previous versions did not have this issue.

**Comment by pinkisemils** [comment]
What distribution and kernel version is this?

**Comment by emacsomancer** [comment]
I'm using [Nix's version of MullvadVPN](https://github.com/NixOS/nixpkgs/pull/80159) on [Void](voidlinux.org). Kernel version 5.4.19.

**Comment by faern** [comment]
Does the new reconnect button (reload icon next to the cancel/disconnect) work?

Please send a problem report via the app. Then our support will have access to some logs.

**Comment by emacsomancer** [comment]
I sent  a problem report via the app. yes the reconnect button works.

**Comment by faern** [comment]
Is this still an issue in the latest version? Try the latest beta if it does not work on stable maybe?

**Comment by fuzebox1** [comment]
I am also having this problem on Arch, standard mullvad app. I have to change server to reconnect after suspend.

**Comment by emacsomancer** [comment]
Seems to be resolved in newer versions.

**Comment by jmcantrell** [comment]
This does not work in the latest version on arch linux. I opened an issue before I found this one: https://github.com/mullvad/mullvadvpn-app/issues/2744.
