### ISSUE TITLE
No VPN connection without having the gui/tray running

### ISSUE THREAD

**Issue by Eyenseo** [mullvad/mullvadvpn-app#1509]
In previous versions (2019.10 & maybe 2020.1) the gui/tray application didn't have to be open to have a vpn connection. With 2020.2  closing the gui will close the VPN connection ~and without opening the application no vpn connection will be made on startup~. mullvad-daemon.service is running without error and writes in the log that the disconnect was intended.

OS: Arch Linux 
Package: mullvad-vpn-2020.2-3

Edit: On startup an connection is made.

**Comment by faern** [comment]
Nothing has changed with regards to this. You can still use the VPN without the GUI just fine.

When you quit the GUI process it does disconnect the VPN connection if there is one. That has been the behavior for very long. So you are correct, but it was the same in 2019.10 as well. You can still reconnect it via the CLI.

If you want the `mullvad-daemon` to connect on boot you can set that flag with the CLI:
```
$ mullvad auto-connect set on
```
