### ISSUE TITLE
[Feature request] Add support for AndroidTV

### ISSUE THREAD

**Issue by Wejde** [mullvad/mullvadvpn-app#1530]
Would be nice to have support for AndroidTV. Yes the app works on AndroidTV, but it automatically starts in portrait mode, so you have to tilt your head to be able to use it. Would be nice if the app could start in landscape mode when it’s used on AndroidTV.

**Comment by axti** [comment]
Hello. It should work well and accessible from Android TV. Few PRs were made for this: #2193 #2196 #2480 #2515
Please install latest version and let us know if you have any issues on TV.
