### ISSUE TITLE
[Feature request] Allow to prefer Wireguard protocol

### ISSUE THREAD

**Issue by maximbaz** [mullvad/mullvadvpn-app#1532]
Wireguard is a modern protocol and I'd like to use it whenever available, but fallback to OpenVPN in restricted networks where Wireguard is blocked.

Right now if I set `mullvad relay set tunnel-protocol any`, I will always be connected to OpenVPN, even if Wireguard is available. My only way is to set `# mullvad relay set tunnel-protocol wireguard`, but then in restricted networks I entirely lose connectivity.

```
Arch Linux

# mullvad version
Current version: 2020.3
	Is supported: true
	Is up to date: true
Latest version: 2020.3
```

**Comment by faern** [comment]
WireGuard will become the default protocol rather soon. Give it one or maybe two more versions.

**Comment by faern** [comment]
WireGuard is the default protocol on Linux and macOS since release `2020.4`. So using that version or a newer one and setting the `tunnel-protocol` to `any` will default to WireGuard and only fall back to OpenVPN if there is some problem.
