### ISSUE TITLE
Make all screens scrollable on Android

### ISSUE THREAD

**Issue by chandradeepdey** [mullvad/mullvadvpn-app#1535]
Similar to #1496, for the main screen instead. The buttons are unreachable in split screen mode otherwise.

**Comment by chandradeepdey** [comment]
Oh, I think all screens need to be scrollable.
![IMG_20200512_041805](https://user-images.githubusercontent.com/21266577/81619615-9d1fa480-9407-11ea-97c5-15ebffc8db6c.jpg)

**Comment by faern** [comment]
Thanks for the report and for the screenshot. We have in our backlog to make it possible to use the app in split screen mode.

**Comment by chandradeepdey** [comment]
#1804 #1810 #1812 #1813
