### ISSUE TITLE
[Linux] Torrent trackers not working when using Wireguard

### ISSUE THREAD

**Issue by yochananmarqos** [mullvad/mullvadvpn-app#1540]
In the last week or so, all torrent trackers in qBittorrent show they're not working. I tried Deluge as well with the same result. Everything works properly with Mullvad disconnected. The timing seems to coincide with upgrading the Mullvad app from 2020.2 to 2020.3.

I emailed support, then figured out that the issue only occurs when connected to a Wireguard server. As soon as I switched to an OpenVPN server, things returned to normal.

Mullvad VPN 2020.3
qBittorrent 4.2.1
GNOME 3.34.4
Manjaro Linux

**Comment by jamerst** [comment]
Behaviour with trackers seems to be a bit odd. Some trackers were showing as not working with a Wireguard server, but some others were still showing as working.

After switching to an OpenVPN server and back again to Wireguard, the trackers started working again.

Mullvad VPN 2020.3
qBittorrent 4.2.1
Fedora 31

**Comment by yochananmarqos** [comment]
I tried the same thing, but to no avail. I also tried WireGuard itself with the following packages:

`networkmanager-wireguard-git`-r87.0e1124d-1
`wireguard-dkms`-0.0.20200215-1
`wireguard-tools`-1.0.20200206-2

**Comment by rascarlo** [comment]
I have the same problem

**Comment by yochananmarqos** [comment]
It seems to be a `libtorrent-rasterbar` issue, there's an open QBittorrent issue regarding it: [issue with wireguard](https://github.com/qbittorrent/qBittorrent/issues/12072).

**Comment by arvidn** [comment]
this is supposed to be fixed in libtorrent-1.2.5

**Comment by rascarlo** [comment]
fixed on qbittorent 4.2.2 with libtorrent-rasterbar 1.2.5

**Comment by yochananmarqos** [comment]
This is indeed fixed as mentioned. Closing.
