### ISSUE TITLE
[Feature Request] Random Server Select

### ISSUE THREAD

**Issue by IceCryptonym** [mullvad/mullvadvpn-app#1542]
Having an option in the settings for Mullvad to randomly select a server when it starts would be nice.

**Comment by faern** [comment]
It does by default. If you enable the "Auto-connect" feature it will automatically connect when you launch the app (the GUI). And connecting always picks a random server within your configured constraints. If you have selected a specific city it will pick a random server in that city, and if you select a specific country it will pick a random server in that country. It will also honor other settings, such as VPN protocol etc.

But from every server that matches the settings, it picks one on random already.

If you want it to not stay within a specific country you can set your location constraints to *anywhere* in the world via the CLI via this command:

```
mullvad relay set location any
```

See our CLI guide for more info on the CLI in general: https://mullvad.net/en/help/how-use-mullvad-cli/

**Comment by cristianovitorino** [comment]
> ```
> mullvad relay set location any
> ```

Is there a way to do something similar on Android?

**Comment by faern** [comment]
No. People are not really encouraged to have the app pick a server randomly from *all* servers. On average that would likely give a worse server than a country you know you have decent connection speed to.

But we will eventually have a favorite servers feature. Then you can create a set of countries to pick from, that will almost work out the same way.

**Comment by cristianovitorino** [comment]
> No. People are not really encouraged to have the app pick a server randomly from _all_ servers. On average that would likely give a worse server than a country you know you have decent connection speed to.

I see. I understand. I've read somewhere about it before, about zeroing in on a server that is stable to you. But I still think it's nice to have the **option** to be able to prioritize randomness over speed/stability if we want/choose to. Like we're able to do that currently with the CLI command on Desktop, which is really nice. Would be even better to have that as an button on the UI. But it's not possible on mobile.

How about a feature that changes server/regions when the app detects a persistent unstable/slow connection between you and said server? A speed/reliability test could choose a better one.

> But we will eventually have a favorite servers feature. Then you can create a set of countries to pick from, that will almost work out the same way.

If it can pick it automatically yes, manually, no. Will there be a "Choose a random region on startup" option on that feature?

So many other VPNs have these kind of features and I miss them.

Do you guys have some sort of open roadmap that subscribers can follow progress? Are you guys working on these kind of features? Do you have a blog or person on the team that deliver fresh news about new features that we can subscribe too. Newsletters perhaps?

I'm loving Mullvad so far, by the way, I don't consider these must-haves, but more like nice-to-haves. I really lile how Mullvad behaves currently, but would be nice to have these features if they don't compromise security nor perfomance. Would be nice to see Mullvad improve feature wise.

Features like:
- Choose random region on startup.
- Choose fastest server amongst all regions on startup.
- Change server if the connection becomes unstable or slow.

And thanks for answering my previous question, I appreciate that.

**Related issues**
#1113
#1487
