### ISSUE TITLE
[Feature Request] Exclude Application Tunneling

### ISSUE THREAD

**Issue by bradynpoulsen** [mullvad/mullvadvpn-app#1545]
I would like to create a blacklist of applications that I need to not be routed through the Mullvad VPN.

I saw the Split Tunneling feature request, however, that appears to be moving towards IP range blacklisting. I cannot predict the IP ranges of these SaaS applications due to their distributed and dynamic cloud nature (ie, Netflix, Hulu, Disney+, etc).

**Comment by faern** [comment]
We are currently working on the split tunneling feature. And yes, it will be per application and not per IP range, since we think it's much more common to want to exclude entire applications.

**Comment by ciehanski** [comment]
> We are currently working on the split tunneling feature.

Any timeline available to expect split tunneling? :)

**Comment by 8227846265** [comment]
+1

**Comment by faern** [comment]
Going to close this as split tunneling (application based tunnel exclusion) is being tracked in #780 

Split tunneling is already available in the latest beta for Linux, but only via the CLI. We are currently working on implementing it for Windows as well, and we will expose it in a more user friendly way in the graphical interface later as well.
