### ISSUE TITLE
[Question] Why is the Mullvad client so large in filesize? (66MB)

### ISSUE THREAD

**Issue by pythonInRelay** [mullvad/mullvadvpn-app#1572]
Just a quick question, I'll close the ticket after I get a good answer.

As the title says, why is the client so large? I realise it's now bundled with Wireguard but I remember the client being a LOT smaller previously.

What changed (apart from bundling Wireguard which is only a few MB)?

**Comment by faern** [comment]
Neither WireGuard, nor OpenVPN or Shadowsocks or any of that contribute noticeably to the file size. The vast majority of the size comes from the fact that the GUI uses Electron, which in turn bundles all of the Chromium browser engine and surrounding resources. This is a bit unfortunate. But it was the only way to get a UI working for all platforms within reasonable time.

Given that you quote 66 MiB I assume you are mostly interested in the Windows version of the app. We can go way back to the very first release of the Windows app, [2018.2](https://github.com/mullvad/mullvadvpn-app/releases/tag/2018.2). You can see that the installer for that version was 77 MiB. So it has not really increased much overall. Instead the size has gone up and down over many releases as we have upgraded Electron and added other features as well as done some optimizations here and there to cut out some dead weight.

Maybe you refer to our old and deprecated Python 2 client that has not existed for years? That one was considerably smaller indeed. But they are not really comparable in features nor looks nor security. File size is almost the only benefit that old version had. It was way less secure and it looked very ugly compared to this one.

**Comment by pythonInRelay** [comment]
Thanks a lot for such a detailed answer. I didn't realise it uses Electron because it was made in Rust.

**Comment by faern** [comment]
The system service managing the security and VPN tunnels is indeed written in Rust (And C++ on Windows). The CLI is written in Rust as well. However, the GUI is a TypeScript program running on Electron.

**Comment by smartynov** [comment]
I second that, dedicating 500 mb for a VPN client feels terribly wrong....

**Comment by entozoon** [comment]
Circling back to this all these years later, is it time to look into another GUI technique, or access to the CLI directly?
Electron requiring more storage than Halflife is madness..

**Comment by zach-is-my-name** [comment]
Any updates? 548.8 MB on Mac.

**Comment by nschumac** [comment]
> Any updates? 548.8 MB on Mac.

Yeah this is rediculous

**Comment by acorello** [comment]
Perhaps worth considering the [Fyne UI toolkit](https://fyne.io) for a future lightweight client? It's written in Go and cross-platform by design, including iOS and Android. It's already been adopted by Tailscale (another VPN provider), apparently.

**Comment by jbhuang** [comment]
please update this. 500mb+ on Mac. That's ridiculous for VPN app. It also looks super sketchy when I am first downloading it.

**Comment by tinyhaggis** [comment]
Have you considered rewriting the client in Tauri/Rust?  It would be much smaller and give a significant performance boost.  It supports Linux, macOS, Windows, Android and iOS
