### ISSUE TITLE
<Feature request> Mac - app visible in toolbar in different user profiles

### ISSUE THREAD

**Issue by mikesk8** [mullvad/mullvadvpn-app#1587]
It would be very useful to be able to change at least the country in different user profiles on Mac. 

The app is running under my user name. However, there are more users working on the same computer having different user profiles. Once they login to their own profiles they cannot see the app in the toolbar and therefore they cannot change the country.

Thanks,
Michael

**Comment by faern** [comment]
Just start the app as the other users as well. There can be multiple instances of the graphical user interface running at the same time.

The "Mullvad VPN" app is just the graphical interface. All the VPN tunnel handling and system security is handled in a system wide daemon process named `mullvad-daemon` that runs in the background as the system superuser. The "Mullvad VPN" app just controls this system service.

**Comment by mikesk8** [comment]
Thank you! easy solution :)
