### ISSUE TITLE
Add instructions for Solus and NetworkManager Applet

### ISSUE THREAD

**Issue by baimafeima** [mullvad/mullvadvpn-app#16]
Apologies for posting this here but as the Linux version is not available, I would have to configure Mullvad for my operating system of choice, `Solus` (https://distrowatch.org/table.php?distribution=solus). Could you please add instructions in the _Guides_ section on your website how to use Mullvad on Solus? `NetworkManager Applet`, the notification area applet for managing network devices and connections, is already pre-installed and I would use this to connect to your servers. The instructions found on your website were for other operating systems and/or a bit too complicated to follow. Is there also any chance to post all Guides additionally here on GitHub? The reason is because your website is censored where I live and I have to use another VPN to access it.

**Comment by faern** [comment]
Sorry, but we don't have a beta of this app ready for Linux yet. We are working on Linux and Windows support, but for now the new app is macOS only.

For Linux you can either try our current VPN program: https://mullvad.net/en/download/
We have a guide for how to install that program on a few Linux distros, not for Solus, but it might still be of help to you maybe: https://mullvad.net/en/guides/installing-mullvad-client-linux/

Or you can run vanilla OpenVPN. We don't have a guide for Solus specifically, but we have one for NetworkManager here: https://mullvad.net/en/guides/linux-openvpn-installation/

If you are still having problems you can contact our support at support@mullvad.net to get more specific help. We can't handle support cases here on Github.

**Comment by camdenorrb** [comment]
Can you reopen this?

**Comment by camdenorrb** [comment]
Can you reopen this @faern

**Comment by faern** [comment]
If you would like guides for things we currently don't have guides for you should email our support or ping our twitter account.

The idea about publishing guides on github is a very good idea though. I have forwarded that idea to the website developers. Thanks for that :+1:

This is the repository for the Mullvad VPN app. So the issue section is about the app specifically. Not about Mullvad or its website in general. As such, issues like this should not be posted here, and we can't have them open and track them here.
