### ISSUE TITLE
Issue -> Mullvad + NextDNS

### ISSUE THREAD

**Issue by scafroglia93** [mullvad/mullvadvpn-app#1623]
I would like to be able to use nextdns in mating with mullvad but, on pc I am unable because the selected dns are those of mullvad making it impossible to use

**Comment by Atrate** [comment]
Duplicate of #473

**Comment by p1r473** [comment]
I cant connect to Mullvad while Pihole enabled.
I got an error about DNS System Preference couldn't be changed.

**Comment by faern** [comment]
@p1r473 Please send a problem report to our support via the app. It's under settings -> report a problem.

**Comment by p1r473** [comment]
I reported it in the app already
![image](https://user-images.githubusercontent.com/9235633/79001295-35cab800-7b1c-11ea-94d0-f9c1ee679ea5.png)
