### ISSUE TITLE
Mullvad VPN keeps stopping when trying to connect via app shortcut tile

### ISSUE THREAD

**Issue by Dartan** [mullvad/mullvadvpn-app#1636]
I can never connect via the app shortcut tile as I always get a popup saying Mullvap VPN keeps stopping. I can connect through the app itself and can disconnect via the app shortcut tile though.

**Comment by faern** [comment]
Please make the app crash by using the shortcut tile. Then send a problem report to us via the in-app "report a problem" feature. That way we will get the log and might have a chance of finding why it crashes.

**Comment by Dartan** [comment]
Just sent it. Thanks!

**Comment by jvff** [comment]
Hello :)

This issue should now be fixed in the `2020.5-beta1` version. Would it be possible for you to please verify if this is still an issue?

Thanks!

**Comment by Dartan** [comment]
I just tried it and it's working now.

Thanks!
