### ISSUE TITLE
[Feature Request] ondemand option for iOS

### ISSUE THREAD

**Issue by midi** [mullvad/mullvadvpn-app#1649]
## Issue report

Operating system: iOS 13.4

App version: First App store release

### Issue description

Thanks for the first version of the iOS app.
Please add on-demand mode to ensure after a restart etc. the connection is automatically done again.
This is currently missing and as result traffic flows outside the VPN after a restart, until the VPN is manually enabled again.
According to the documentation traffic leaks should be avoided and privacy preserving defaults be used. Therefore this should be a high priority I think and set as default option.
Wireguard and Passepartout for example have this as option.

**Comment by pronebird** [comment]
@midi thanks for reporting this. We're aware of the On-demand VPN on iOS and looking into adding this sometime soon.

**Comment by pronebird** [comment]
Merged in https://github.com/mullvad/mullvadvpn-app/pull/1656. In testing & QA stage. Should be a part of the upcoming update, hopefully before the end of this week.

**Comment by pronebird** [comment]
Please update to Mullvad VPN 2020.2 via AppStore. On-demand VPN is automatically enabled for all new VPN configurations, and existing configuration when connecting VPN inside the app.

You can verify that on-demand VPN is enabled by going to iPhone Settings > VPN and tapping on ℹ️  next to WireGuard (Mullvad VPN). "Connect On Demand" toggle should be visible and enabled.
