### ISSUE TITLE
[Feature Request] Support Android work profiles (Android Enterprise)

### ISSUE THREAD

**Issue by articlecat** [mullvad/mullvadvpn-app#1650]
## Feature request

Operating system: Android 9

App version: 2020.4-beta1

### Feature description

The Mullvad Android app does not function inside [Android work profiles](https://developer.android.com/work/managed-profiles). When opening the Mullvad app in the work profile, the app crashes immediately.

Android work profiles are marketed to corporate users as [Android Enterprise](https://developer.android.com/work/) (which used to be known as Android for Work). This feature allows two isolated copies of an Android app to installed on the phone at the same time (one in the default "personal" profile and one in a new "work" profile). Android work profiles can be accessed through FOSS Android apps including [Shelter](https://github.com/PeterCxy/Shelter) and [Island](https://github.com/oasisfeng/island). The feature is built into Android 5+, and does not use Google Play Services.

A VPN only affects the applications in the profile from which it runs in. The Mullvad app runs in the default personal profile without crashing, but leaves all apps in the work profile unprotected. To protect apps in the work profile, the Mullvad app needs to be able to run in the work profile. I've tested the Mullvad app in the following configurations:

* **Installed on personal profile:** Does not crash
* **Installed on work profile:** Crashes immediately
* **Installed on both profiles:** Personal profile instance does not crash, work profile instance crashes immediately

The [WireGuard Android app](https://f-droid.org/en/packages/com.wireguard.android) works properly in the work profile, and can be used as a workaround. However, it would be much more convenient to have access to the Mullvad app in the work profile, which would provide automatic key rotation and a better user experience.

**Comment by jvff** [comment]
Hello :)

Thanks for the detailed report! We've implemented initial support in the new version. Could you please check if it's still an issue in the 2020.4-beta3 version?

**Comment by pinkisemils** [comment]
Should be fixed as of #1662.

**Comment by articlecat** [comment]
@jvff Mullvad version 2020.4-beta3 works perfectly in the Android work profile. Thank you for addressing this so quickly!
