### ISSUE TITLE
Tray icon goes away after locking/unlocking the screen

### ISSUE THREAD

**Issue by bungabunga** [mullvad/mullvadvpn-app#1659]
## Issue report

Operating system: Ubuntu 19.10, Ubuntu 20.04

App version: Mullvad 2020.4-beta2

### Issue description

Mullvand app's tray icon is only present from the start and unitl locking the screen. After unlocking it it's gone, but VPN is working normally.

I think it's probably a known issue that many other Electron apps are having too. Gnome and Chromium teams both claims they're not responsible. The issue wasn't present on Mullvand 2020.3, I think due to older Electron version.

https://github.com/ubuntu/gnome-shell-extension-appindicator/issues/220

https://bugs.chromium.org/p/chromium/issues/detail?id=1042098#c9

a possible workaronund:

https://github.com/zulip/zulip-desktop/issues/910

**Comment by faern** [comment]
Thanks for reporting this! We are looking into it.

**Comment by MartinPL** [comment]
Looks like icon is add only when app i started and that is the issue. Definitely wrong repo.

**Comment by faern** [comment]
We will downgrade to Electron 7 again for now. There is currently no good workarounds available. Then we will monitor the existing issues and see if Chromium, Gnome or someone else develops a good fix upstream.

**Comment by MartinPL** [comment]
https://github.com/MartinPL/Tray-Icons-Reloaded (from master) + https://git.sr.ht/~steef/snixembed may fix this, but didn't test this app. (`Ubuntu indicator / KStatusNotifierItem/AppIndicator Support` need to be disabled)

**Comment by vladimiry** [comment]
See https://github.com/electron/electron/pull/23674.

**Comment by faern** [comment]
This should have been fixed by the Electron 7 downgrade. And we are currently upgrading to Electron 8 again, but the release where they fixed this issue.
