### ISSUE TITLE
[Feature request] iOS app notification on disconnect

### ISSUE THREAD

**Issue by mikesk8** [mullvad/mullvadvpn-app#1668]
Hello,

I have created a new one as this one was bundled in kill switch, which was already closed:) 

Basically, on disconnect the VPN icon disappears in the iPhone bar; however, this is easily being missed (happened to me and my mates using your app several times). Would be beneficial to get a more visible notification the secure connection is lost, e.g. via notifications. 

Best regards,
Michael

**Comment by faern** [comment]
It should never disconnect unless you explicitly disconnect it yourself. We knew this was an issue for some people with the first release, `2020.1`. We activated on-demand VPN in `2020.2`.

Please first verify if you do get unwanted disconnects in the latest version of the app. If you don't this is not something we need to fix.

**Comment by mikesk8** [comment]
No issues identified and therefore I will close it. Thank you!
