### ISSUE TITLE
gpg: Can't check signature: No public key

### ISSUE THREAD

**Issue by Tumeez** [mullvad/mullvadvpn-app#1691]
Operating system: Windows 10 Enterprise
App version: 2020.4-beta2

When I tried to verify GPG key, it said that:

`gpg --verify MullvadVPN-2020.4-beta2.exe.asc MullvadVPN-2020.4-beta2.exe
gpg: Signature made 04/08/20 14:45:04 FLE Daylight Time
gpg:                using RSA key CA83A46153BC58D69518ED49A26581F219C8314C
gpg: Can't check signature: No public key`

**Comment by faern** [comment]
You need our code signing key imported into your gpg keyring first. You can find the key and a guide on how to verify signatures at https://mullvad.net/help/open-source/

**Comment by faern** [comment]
I'm closing this issue as the key should indeed be available already.
