### ISSUE TITLE
Labels for WireGuard keys

### ISSUE THREAD

**Issue by procdaddy11** [mullvad/mullvadvpn-app#1702]
I'd like it if I could add a label to the wire guard keys so I can remember what is what.

**Comment by faern** [comment]
This is something the infrastructure would need to support first. So not an app issue per se. We do know that WireGuard key identification is troublesome currently! This has been wildly debated internally. But it's a tougher issue than one would expect, if we want to remain privacy friendly.

For the same reason that we don't let users choose their own account name, if we let people name their keys they might name them `device-on-address-xx-yy`, which is information we don't want to have. And the most effective way of making sure we don't have it is to not let users give it to us.

But ideally we will find some way of making it easier to identify keys.

**Comment by juggeroid** [comment]
Maybe provide a unique non-identifiable dictionary labels, such as _alpha_, _bravo_, _charlie_, ...?

**Comment by fnkr** [comment]
Or maybe icons/emojis could be used to label devices.

| Use | Icon | Public key | Creted  | Revoke  |
| ------ | ------ | ------ |  ------ |  ------ |
| x | 📱 | ABC... | 2020-06-22 | x |
| x | 💻 | DEF... | 2020-06-22 | x |
| x | 🖥 | GHI... | 2020-06-22 | x |
| x | 🖨 | JKL... | 2020-06-22 | x |
| x | 📡 | MNO... | 2020-06-22 | x |

**Comment by thematrixdev** [comment]
thumb up for this little tweak

**Comment by faern** [comment]
We are going to re-work how WireGuard keys are handled in the app completely. After that is done none of this is needed/relevant any more. But thank you for your ideas.
