### ISSUE TITLE
DNS resolution doesn't work with auto-connect

### ISSUE THREAD

**Issue by jkuehnemundt** [mullvad/mullvadvpn-app#1715]
## Issue report

Operating system: Debian 9

App version: mullvad-cli 2020.3

### Issue description

When mullvad is set to auto-connect, the status tells me it is connected to the server, but the DNS resolution doesn't work. Everytime I have to disconnect and connect again, to get it work.

**Comment by faern** [comment]
Please take these kind of issues with support. This would be very hard to solve without client logs. You can send a problem report from within the app with a description of your problem and support will automatically get it.

Please note that Debian 9 is not supported by us any longer. It has already reached EOL. We support Debian 10+.
