### ISSUE TITLE
Getting a prompt to update to latest version when I am already on the latest Beta

### ISSUE THREAD

**Issue by TheNightRider12** [mullvad/mullvadvpn-app#1719]
## Issue report
Getting prompted to update the app even though I am on the latest Beta (2020.4-beta4). 

Operating system: Windows 10. 1909

App version: 2020.4-beta4

### Issue description
I installed 2020.4-beta4 yesterday and I just noticed today that I get a popup on the main screen that shows the world map with the text on top "Update Available. Install Mullvad VPN (2020.3) to stay up to date". I also see in settings a red exclamation mark next to "App Version" and I see (correctly) 2020.4-beta4. But below that I see the text "Update available, download to remain safe."

**Comment by faern** [comment]
Have you gone into the settings and disabled the beta program? If so, there is a bug currently where it would recommend you get the latest stable release. Which currently is older than the version you are running. We are working on a fix for this. But for now you can enable the beta program under Settings -> Preferences. This will inform the app that you are indeed happy with running this beta that you are running.

**Comment by OnlinePlayer865** [comment]
I have not joined the beta program via settings. I have downloaded all of the releases from the GitHub releases page. But enabling the beta program via settings and restarting the app seems to have fixed the issue. Thank you!

**Comment by faern** [comment]
The beta program should be enabled automatically once you install and run a beta version. That's the plan. But maybe we have a bug there. It's automatically activated for me. But anyway, we are re-working the beta program anyway.

**Comment by hulthe** [comment]
This seems to have been fixed sometime in the last 4 years. Feel free to comment/re-open if you're still experiencing this issue.
