### ISSUE TITLE
It's not a issue just a dream ! Would it be possible to use your app with my wireguard server ?

### ISSUE THREAD

**Issue by skaox** [mullvad/mullvadvpn-app#1732]
H3ll0,

I've taken one month with you (3 days left) for trying to bypass a streaming service with geo-ip restriction (Di***y+) but like with my dedicated server it didn't work...
Most of the time I was detected like I was in Sweden and wanted to be like in France.

Anyway I would like to say a big THANK YOU for what you're doing using wireguard, the services, price, documentation and this nice app.

After one month of searching I didn't found a decent wireguard GUI Desktop (not a web ui) like yours for Linux (Ubuntu mate 20.04) so this why I would like to know if it would be possible to use your app with my personal wireguard server ?

I will have to feed relays.json with my own ok I know... I'm a dreamer.

Thank you in advance.

**Comment by faern** [comment]
Check out the CLI. Using custom servers is already built in:
```
mullvad relay set custom wireguard --help
```
There you can configure a custom WireGuard server to use.

No need to edit `relay.json` or other app files you are not supposed to touch :)

**Comment by faern** [comment]
Closing this as it should already be possible to do this.
