### ISSUE TITLE
Mullvad Android app UX pushing Disconnect button off screen

### ISSUE THREAD

**Issue by narration-sd** [mullvad/mullvadvpn-app#1736]
## Issue report

Operating system: Android 7.1.1

App version: 2020.4.beta3, continuing on fresh 2020.4.beta4 just loaded

### Issue description

This is simply a UX implementation needing improvement -- two ways.  What happens is that with long site names, such as Los Angeles, CA, USA, the panel for this expands so that the buttons are pushed down, with the Disconnect button nearly off screen. 

When it is, attempting to tap it somehow results in a double-tap or similar event/s, so that the disconnect happens, but then a reconnect instantly occurs. You have to Switch Location to be able to get a workable Disconnect button, not I am sure what you had in mind. 

The problem occurs on any long name, not just in North America. I would suggest the following:
- first of all, there's too much extra blank space reserved _below_ the location name, between the text and the buttons below. Depending on what UI component elements are involved, this might need just a margin/padding change, or something else, but it is simple.
- You may think to have done this padding to allow space for the server details dropdown, but there seems to be too much for this -- unless there are really long, wrapped or extra vertical server strings I haven't seen
- In the text itself, for USA you are mixing naming states and naming the country, insisting the country go on a separate line. That itself may be proper for longer country names, but then there are good alternatives.
- Once you fix the over-spacing vertically, if there isn't some actual need for that, and if there is, then you can consider how you are formatting the locations.
  - for the US, it probably isn't really needed to show the State code (e.g. CA) 
  - but if you want to, or not, you'll want to consider really long city names possible in the world, now or for future server sites
  - I know you like the 'big letters - I'm simple' appearance of Mullvad, and I smile at what is probably a good and sendible marketing move, but it feels you could go definitely smaller for the font size of locations. That wouild be a simple and reliable fix, so that cities always fit on one line, including the state code for countries that need them.
  -- if you don't like to change that to make an always-consistent design, then to compute height would allow you to set a suitable font size differently for locations that need this.
  -- always, the font height needs to be reckoned against how much space you really need for the ip numbers drop-down.  The buttons must never be allowed to move, become even partially off screen.

I am viewing on I think roughly the minimum phone screen size, a Motorola G4 Play. There may be one step smaller -- the IPhone 5, I think, but you must discover this to cover your design, of course.

Thanks, and again, I smile each time I use Mullvad -- quite appreciate what you are doing.

**Comment by chandradeepdey** [comment]
Related to #1535

**Comment by narration-sd** [comment]
update: looks like there's a reasonable if a bit hinky workaround now -- which does work, so that we can reach the buttons, by scrolling down when location strings are long...

**Comment by Rawa** [comment]
We've rewritten these screens in compose and they are scrollable nowadays, I'm gonna close this ticked with that it has been fixed. If there is any new issue please file a new ticket.

**Comment by narration-sd** [comment]
I'd just like to confirm that the fixes have seemed quite good -- haven't had any problems with the UX in a long time, so thanks.

It's still a very 'personal' approach, from Mullvad. No doubt the mole likes it :)

You've got me here, so will be reporting one long term bug that doesn't seem to go away...hope you are looking into a nice holidays season, sincerely!

**Comment by Rawa** [comment]
Glad to hear you like it! Please do report all the bugs you find, and we'll try our best to fix them. 🙏

**Comment by narration-sd** [comment]
Ok,  you've got it :)

https://github.com/mullvad/mullvadvpn-app/issues/5478

Take care...
