### ISSUE TITLE
Android: split screen changes current screen

### ISSUE THREAD

**Issue by chandradeepdey** [mullvad/mullvadvpn-app#1737]
## Issue report

Operating system: Android 7, MIUI 11

App version: 2020.4-beta4

### Issue description
Title

### Issue Replication
1) Go to WireGuard key settings
2) switch to split screen mode
App will switch to the main screen
3) Make app full screen again
Pressing back now will cause the app to behave as if it was still on WireGuard key settings, user will be brought to Settings > Advanced

A different screen may be selected in (1) for a different result in (2) and (3)

**Comment by faern** [comment]
Thanks. We will look into this.

**Comment by chandradeepdey** [comment]
#1809
