### ISSUE TITLE
[Feature Request] Add Firewall support

### ISSUE THREAD

**Issue by ph00lt0** [mullvad/mullvadvpn-app#1747]
In [this issue](https://github.com/mullvad/mullvadvpn-app/issues/473) users request adding a DNS to do filtering of connections with a pi-hole or AdGuard. Instead of doing this I would like to suggest firewall settings within the Mullvad app per device or account.
I think this is a better approach because you do not need a third party services like AdGuard and this will work on any network, a pi-hole only helps when you are at home. 

Best would be if host files could be selected or imported as in app from [Blokada](https://blokada.org/) and allow users to block domains such as *.facebook.net completely.

**Comment by faern** [comment]
Implementing a firewall is out of scope for a VPN app, at least this VPN app and for the foreseeable future.
