### ISSUE TITLE
Show the list of Wireguard servers when Tunnel is set to Automatic

### ISSUE THREAD

**Issue by acrostich** [mullvad/mullvadvpn-app#1780]
## Issue report

Operating system: macOS Mojave 10.14.6

App version: 2020.4

### Issue description

When the Tunnel is set to Automatic, the list of servers displayed does not include the Wireguard servers. If one clicks on a server, then OpenVPN is used, which does make sense as the servers are OpenVPN ones. 

As in Automatic mode, Wireguard is tried first, the list of Wireguard servers should (also) be displayed. If one selects a country or a town, then a Wireguard server will be chosen. However if you want a specific Wireguard server, one has to disable the Automatic mode and set it to Wireguard, then the list of servers will be that of the Wireguard servers.

A workaround I have found when occasionally wanting a specific server in a town that doesn't have too many is to leave the Tunnel in Automatic mode, but click the reselect button (the circle arrow) again and again until the wanted server is selected.

**Comment by faern** [comment]
Ah. Thanks for reporting this. We made WireGuard the default, but forgot about the location selection :)

We will fix this for the upcoming release.

**Comment by acrostich** [comment]
Fixed in 2020.5-beta2
