### ISSUE TITLE
[Feature Request] Hide world map on desktop

### ISSUE THREAD

**Issue by contentkraft** [mullvad/mullvadvpn-app#1781]
I enjoy the Mullvad app a lot, but I’ve never liked the world map after switching to Wireguard. The animation is simply too slow. It made sense when we used to connect via OpenVPN, but now it’s sluggish and awkward watching the connection animation jump around on the map connecting via WG takes less than a second, yet the animation takes longer.

Would it be possible to have an option to hide the world map completely and display only the server list like on iOS? And please don’t introduce the map on iOS unless it’s optional 😅

**Comment by faern** [comment]
I'm sorry, but we do plan on bringing the map to iOS :)

We will consider making it optional. But given that the map is present, do you see any way it can be improved? What part of it pan over to your server location makes using the app feel worse than not having a map? The tunnel works the same no matter how fast or slow the map pans. And the map will finish reaching its destination in just a second or two. You do not need to sit and watch the animation :)

**Comment by contentkraft** [comment]
One thing to improve: If you are in Asia, the map scrolls to the left when you connect to a U.S. server. Why not the shorter distance to the right?

Still, I don’t think the map brings anything useful to the table (unless it’s a way to teach people geography – I wouldn’t need it 😜).

**Comment by faern** [comment]
We might introduce the setting just to save resources on low power devices. But removing it just for the sake of removing it will likely not be supported. It's not there to teach geography. but just give an indication to the user where "the internet" thinks the user is currently located. Sorry, it's simply part of the UX for this app.
