### ISSUE TITLE
Chinese ISPs to block TCP ports 80, 8080, and 443 by January 11, 2018

### ISSUE THREAD

**Issue by baimafeima** [mullvad/mullvadvpn-app#18]
https://www.networkworld.com/article/3245795/sd-wan/china-to-block-sd-wan-and-vpn-traffic-by-jan-11.html
Any plans?

**Comment by faern** [comment]
Blocking port 443 will cause problems for the parts of the app that uses https to fetch server lists and account metadata etc. We already have plans on making this communication happen inside of the VPN tunnel, thus it should not be a problem when that is implemented. That is however not scheduled for the next release, probably the one after that.

I don't see this will limit the ability to set up the VPN tunnel itself though.

**Comment by baimafeima** [comment]
> Except if one is using an obfuscation protocol based on those ports.

I have to obfuscate traffic through stunnel. Will the new app feature in-built obfuscation options to select via a drop-down menu to make this process easier for end-users?

**Comment by faern** [comment]
A long term goal is to include easy-to-use obfuscation, absolutely! But this is not planned for the near future, we first must get the app to work on all platforms for example.

I'm going to close this issue as it's not related to the immediate development of the app. If you need help with setting up obfuscation or similar please contact support@mullvad.net

I will try to remember to add some general milestones to the readme, so it becomes possible to know approximately what is planned for and how far into the future it is.
