### ISSUE TITLE
Support for Android TV

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#1826]
### Description

Hello, I would like to request support for Android TV (e.g. Nvidia Shield Pro and Mi Box S)

Since there's already support for Android, why not extend it to Android TV? 

Only my Android TVs are currently not connected with Mullvad.

For your consideration. Thank you.

**Comment by faern** [comment]
Thank you. We are aware of this and we will fix it sometime. But we focus on making the Android app stable and usable on phones before we will expand too much to other devices. It will arrive eventually.

**Comment by p3yot3** [comment]
+1 for this feature!!

**Comment by axti** [comment]
Hello. it should work well and accessible from Android TV. Few PRs were made for this: #2193 #2196 #2480 #2515 
Please let us know if you have issues on TV with latest version.

**Comment by kevinoconnor7** [comment]
@axti looks like `2021.1-beta1` has been released but the Play Store doesn't let me install it on my Shield TV. Do you need to update the Play Store listing to explicitly declare support for Android TV devices?

**Comment by axti** [comment]
Hello @kevinoconnor7. Thank you for your comment. 
Some additional information was missed on the Play Store and now it is fixed and you are able to find the app. Enjoy.

**Comment by kevinoconnor7** [comment]
Worked like a charm. Thanks @axti!
