### ISSUE TITLE
[Linux] NetworkManager shows limited connectivity if started when Mullvad is on

### ISSUE THREAD

**Issue by articlecat** [mullvad/mullvadvpn-app#1845]
## Issue report

Operating system: Linux

App version: 2020.4

### Issue description

NetworkManager shows limited connectivity when a network connection is established when the Mullvad client is running and either of the following is true:
* The client is connected to Mullvad.
* The client is attempting to connect to Mullvad.

When this occurs, the `nmcli g` command returns the following:

```
STATE                  CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
connected (site only)  limited       enabled  enabled  enabled  enabled 
```

Desktop environments show the limited connectivity in various ways. For example, GNOME Shell displays a question mark on the Wi-Fi icon in the system menu of the top bar.

When "Launch app on start-up" is turned on in the Mullvad client, this issue occurs every time the computer starts up and persists throughout the desktop session. The only way to restore "full" connectivity to NetworkManager is to turn off Mullvad VPN and restart NetworkManager with `sudo systemctl restart NetworkManager`. At this point, `nmcli g` returns the expected output:

```
STATE      CONNECTIVITY  WIFI-HW  WIFI     WWAN-HW  WWAN    
connected  full          enabled  enabled  enabled  enabled 
```

NetworkManager's status depends on whether Mullvad VPN is on or off when it starts. Turning Mullvad VPN on or off after NetworkManager starts does not affect NetworkManager's status until NetworkManager is restarted.

**Comment by Atrate** [comment]
>  NetworkManager's status depends on whether Mullvad VPN is on or off when it starts. Turning Mullvad VPN on or off after NetworkManager starts does not affect NetworkManager's status until NetworkManager is restarted.

It might be worth reporting this upstream, to NM itself

**Comment by faern** [comment]
Indeed sounds like a bug in network manager. The way I understand your report you do have working internet while it says `limited`? If so, it's NM showing the wrong status.

I do not know how NM figure out connectivity. It could be that we do something to the routing table that they don't anticipate. Or the strict firewall rules that makes it think the internet is unreachable.

**Comment by dkbg** [comment]
I've noticed the same problem. I've [reported it upstream to NetworkManager](https://gitlab.freedesktop.org/NetworkManager/NetworkManager/-/issues/494).

**Comment by HK53** [comment]
I am having the same problem!

**Comment by articlecat** [comment]
This issue is now resolved for me. With Mullvad 2021.2 and NetworkManager 1.30.2, NetworkManager now shows full connectivity on start-up. Disconnecting and reconnecting to Wi-Fi or to the VPN does not cause NetworkManager to show limited connectivity anymore.
