### ISSUE TITLE
Incorrect & inconsistent days left

### ISSUE THREAD

**Issue by acrostich** [mullvad/mullvadvpn-app#1846]
## Issue report

Operating system: iOS 13.5.1
App version: 2020.3

Operating system: macOS 10.14.6
App version: 2020.4

### Issue description

The iOS app was reporting my account had expired. As per an earlier response I logged out of it and back in. This does now show a number of days remaining.

The iOS app reports 9 days left.
The macOS app reports 10 days left.

One of the two, at least, must be wrong!

**Comment by faern** [comment]
That sounds like a rounding error. I don't have in my head exactly how both of these platforms work. But I assume at the time you had ~9.5 days left and one rounded it up and one down.

What you are talking about now is the short form of the time left, shown on the account button directly in the settings, right? If you indeed care in detail about how much time you have left you can click that button to go to the account view and see the exact date and time that the account will expire.

**Comment by acrostich** [comment]
Account expiry is on 24 Jun 2020 around 15:40. (Wondering if there's any privacy risk to give the exact expiry time so I'm including a close by time.)

I checked a bit before midnight so it must have been about 9 days, 15 hours and 50 or so minutes to expiry.

It doesn't matter much how it is rounded, but it would make sense to be rounded the same way in all Mullvad apps, using the same algorithm when there has to be different code bases.

**Comment by buggmagnet** [comment]
This shouldn't be an issue anymore, marking this as closed.
