### ISSUE TITLE
[Android] Can't open settings since I've upgraded to 2020.5-beta2

### ISSUE THREAD

**Issue by bungabunga** [mullvad/mullvadvpn-app#1852]
## Issue report

Operating system: GrapheneOS (Android 10)

App version: 2020.5.beta 2

### Issue description

Can't open settings menu. If I tap the icon nothing happens.

**Comment by faern** [comment]
That is really strange. Thanks for reporting this. We have tested the app on Android 10, so maybe it's only on this specific device or this specific rom. Are you sure this behavior is new in `2020.5-beta2` and `2020.5-beta1` worked fine? And try clicking multiple times in that approximate region, I'm thinking if maybe the hitbox has become smaller or moved a bit? Any extra info like that would help us debug the problem.

**Comment by Atrate** [comment]
Can't reproduce

HavocOS (Android 10)
2020.5.beta 2

**Comment by bungabunga** [comment]
I correct myself: actually the whole screen is unresponsive. can't tap on anything. I even restarted app, cleared cache. will reinstall beta 1, just to make sure it's not the same.

**Comment by faern** [comment]
In `2020.5-beta2` we prevented clicks to the app if there are other apps drawing on top of our app. This is in order to mitigate a type of attack called tapjacking. Do you maybe have some other app drawing on top? Such as ascreen dimming app or anything?

**Comment by bungabunga** [comment]
no I don't have any app of that type installed.

I played a bit with beta1 and beta2, installed both from scratch...

beta1: everything is working normally.

beta2: when i install app only first tap is responsive, it doesn't matter where I tap. any following tap is unresponsive.

**Comment by faern** [comment]
Really strange indeed. We have numerous Android 10 devices where it works fine and we can't reproduce this ourselves. So any more input on how to trigger it and under what setup etc would greatly help. Otherwise we have to wait and see if more users get similar problems or not.

**Comment by bungabunga** [comment]
I've opened another issue on GrapheneOS GitHub issues page, maybe it's developer has a clue.

**Comment by tomkel** [comment]
Did Mullvad enable a new feature to lockdown touches when another app with overlay drawing permissions was enabled ?

**Comment by bungabunga** [comment]
sorry, i was convinced i wasn't using an app with overlay but i found out i actually was.
