### ISSUE TITLE
Files in /usr/local cause issues in Fedora Silverblue

### ISSUE THREAD

**Issue by wasv** [mullvad/mullvadvpn-app#1861]
## Issue report

Operating system: Fedora Silverblue 32

App version: 2020.4 (during installation)

### Issue description

When attempting to install the latest version of the app, it appears there are zsh-autocompletion files being added to /usr/local/share instead of /usr/share. This causes an issue in Silverblue and other rpm-ostree based distros due to projectatomic/rpm-ostree#233.

The issue could potentially be fixed by putting the auto completion files in /usr/share instead of /usr/local/share. I'm pretty sure this would be the convention for pre-packaged apps anyways, since /usr/local/ is usually reserved for apps not managed by the distro's package manager.

From what I can tell this is a separate issue from #1570. That issue was with files being added to /opt, which from what I understand did not exist in older versions of silverblue. However, /opt is now a symlink to /var/opt, so I didn't need to do the workaround mentioned there.

**Comment by nlordell** [comment]
Yes you are correct, the issue with `/opt/Mullvad VPN` not existing after install is now fixed! Indeed, there is now an `/opt -> /var/opt` so this is no longer an issue :tada:.

However, there are still SELinux policy issues preventing `mullvad-daemon` being executed as a systemd service because of the `lib_t` file context, which results in SELinux permission errors when accessing the `/var/*` files:
```
$ ls -Z '/opt/Mullvad VPN/resources/mullvad-daemon'
system_u:object_r:lib_t:s0 '/opt/Mullvad VPN/resources/mullvad-daemon'
$ journalctl -u mullvad-daemon.service '/opt/Mullvad VPN/resources/mullvad-daemon' | tail -n 8
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: [mullvad_daemon::account_history][INFO] Opening account history file in /var/cache/mullvad-vpn/account-history.json
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: [mullvad_daemon::relays][DEBUG] Relay list updater thread has finished
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: [mullvad_daemon][ERROR] Error: Unable to initialize daemon
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: Caused by: Unable to load account history with wireguard key cache
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: Caused by: Unable to read account history file
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: Caused by: Permission denied (os error 13)
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: [mullvad_daemon][DEBUG] Process exiting with code 1
Jun 23 13:20:42 silverblue32 mullvad-daemon[7480]: [mullvad_daemon][INFO] Management interface shut down
```

**Comment by faern** [comment]
The zsh completions were moved to `/usr/share` in the rpm in PR #1869. Hopefully this should resolve this issue. If you want, you can try it out by building the rpm from source. Or you can wait for the next beta/stable release.
