### ISSUE TITLE
Mac OS X 10.11 El Capitan Support?

### ISSUE THREAD

**Issue by hacker112** [mullvad/mullvadvpn-app#1864]
Is Mac OS X 10.11 El Capitan not supported anymore or has the app (version 2020.4) just not been tested on El Capitan. Version 2020.3 works fine on El Capitan but on the download page it says "Works on macOS High Sierra (10.13) or later (64 bit only)" for the version 2020.4 on the webpage.

**Comment by faern** [comment]
The app no longer officially supports anything older than 10.13, correct. We do not do any automatic or manual testing on any macOS older than 10.13. It might of course still work fine, we do not know and we do not give any guarantees.

Older macOS versions are not supported by Apple. If there are no security patches from the vendor that unavoidably means there will be security holes eventually. So we strongly recommend against running software that the vendor no longer support. As a result we do not support those versions either.
