### ISSUE TITLE
error when trying to change app name in windows

### ISSUE THREAD

**Issue by sajadabasi** [mullvad/mullvadvpn-app#1872]
## Issue report

Operating system: Windows 10
App version: 2020.5

### Issue description

I'm trying to change the app name but when i do this i can create windows exe file but during installation i get this error:
```
fatal error during driver installation: failed to create virtual adapter: error 0x103
```
thanks.

**Comment by faern** [comment]
What do you mean by "change app name" exactly? Are you building this app from source code and you changed the name somewhere? If so, where did you change it?

**Comment by sajadabasi** [comment]
hi @faern i want to change app name and compile it from source what should i change?

**Comment by faern** [comment]
I don't know. Since we have never tried to change it ourselves. There are probably very many places to replace it fully. That depend a lot on what aspect of the app you want to rename.

**Comment by pronebird** [comment]
@sajadabasi I suggest you to search and replace all occurrences of the application name in your favourite text editor. The driver itself is probably have to be signed to install properly.

**Comment by faern** [comment]
I'm going to close this as it's not clear if this is still a problem or not.
