### ISSUE TITLE
Hard blocking by Mullvad on Win10 startup

### ISSUE THREAD

**Issue by narration-sd** [mullvad/mullvadvpn-app#1875]
## Issue report

Operating system: Windows 10 very latest

App version: 2020.5beta2

### Issue description

@faern , Linus, I've been religiously following your betas and updates, and the Android app is now quite solid -- the workaround for long placenames is functional, and the rest is just reliable - appreciated.

On Win10, though, throught the latest release/s also, there's a problem I'd imagine you'd especially like to see dealt with as Mozilla are widening their advertising for 'their', really Mullvad, VPN.  

I've watched what happens pretty carefully, and it boils down to this:
- something like half the time, on boot Mullvad tries and fails to connect
- it's pretty clear this is due to the safety through network blocking by (also latest) Norton 360, until it's up and ready to provide its firewall, etc..
- each time this happens, I have no internet, again properly through disconnected Mullvad, and can then recover by Cancel in the Mullvad UX, then, if I've waited long enough so that Norton has released net connectiviity, the Secure my Network Connection button will relaunch Mullvad successfully.
- no problems at all once I do achieve the Mullvad connection, and I would say I reasonably exercise it, often over long hours

Solution?  Well, as you know Windows has in past had odd add-ons that could space out booting app and service launches. These were not highly successful, nor were they suitable for non-technical persons; as welll, Microsoft updates tended to kill them.

So it seems a reliable route would be to have Mullvad do more or less what I do manually, though it can do it much more nicely itself, and achieve connection more rapidly, which means transparently to  that person.

Simply, this would be to have it poll at a reasonable rate, when it can't first-time connect, until it gains its desired connection. 

The rate could be on an Advanced Setting to allow adjustment if there are any unexpected issues, but could I suspect transparently be rather rapid - 1 per second if there's no reason why not...?

Thanks, and cheers  on how well Mullvad works. There are the odd things like it still apparently having some servers on location services registered as Romania, but from a higher level support conversation, I guess there's not much you can do about that.  Hazards of the internet :)

**Comment by narration-sd** [comment]
You know, I think you may have done something in the final 2020.5 Mullvad Windows which fixes this.

So far, for days, it's connected smoothly on laptop boot. I'll give it a few more days and assure, also I sometimes do multiple boots in a day, but if solid, I'll close this -- leaving it up as much as anything so you can see your apparent success.

Android 2020.5 has been equally smooth -- thanks...takk

**Comment by narration-sd** [comment]
Ah, @faern  Linus, unfortunately the problem isn't gone -- failed to connect just now on bootup.

But, this has given me a chance observe all the more closely, and maybe point to where the issue begins, which should be a help to arriving at an actual fix.


- The laptop is rebooted, logged into,  Windows UX first comes up
- in the small icons to right, Mullvad begins to appear, also pops a toast saying it's blocked, or disconnected? Don't remember
- Mullvad announces it's attempting to connect
- soon, it announces it's blocked, and the small icon shows the red within green rectangle
- Very Important Point, I think: at this point, the Mullvad UX pane will say that it is _blocked_
- indeed, no further attempt will be made, or is it succeed???
- until I use the Cancel button on the Mullvad pane
- _Now_ we see something; that the Mullvad pane had been showing its not-anywhere map location
- _But_ once Cancel is hit,, the display moves deliberately to show my actual, non-vpn location
- once that happens, I can use Secure My Location, and always Mullvad will connect, after which no trouble for rest of even many hours session.

So:  I think that Mullvad not only blocks the internet for appreciated safety, but blocks  itself -- even if is  properly trying again to  get the connection, after the internet is available -- we are presuming the initial unavailablity is due to Norton 360's safe holdoff for itself to be ready.

I hope this helps, Linus, because it's a pretty good problem, especially will be for the non-technical person.

Thanks,
Clive

**Comment by narration-sd** [comment]
An update on this, as it continues to be a problem - 30% or so of the time, Mullvad 'blocks' and will not connect on Win10 reboot.

It's perhaps becoming clear this is duet to making only one try by Mullvad, while security programs of quality properly and totally block network connections until they're fully up and running. This is a safety feature of Norton 360, popular example, and the one I'm running for its top scores.

Startup positioning and interval vary with software installs and upgrades, of course. Thus I think the answer is for Mullvad to keep trying, at intervals, when it doesn't connect at first. I can do this manually, and find that it may take 30 seconds at least past where Mullvad comes up enough to make first attempt and block. I try every 5 seconds or so, and maybe that's a good automatic retry interval?  A starting place, at least.

Thanks, @faern Linus, for your work and team overall, and when you can get to this. I think I'm not the only one.

Clive

**Comment by narration-sd** [comment]
I know, this, again.  I probably have more startup programs than some on Windows, yes, but really this is the only problem I see with Mullvad, and it is very constent. Something around 30-40% of bootups, Mullvad simply doesn't connect Says it blocks.

I have to use what becomes the Disconnect button, wait a bit, then manually hit connect again. If I've waited long enough, it does, and after that no issues at all.

It does seem a very simple fix; a timeout and retry until the little fellow connects, Making the timeout something like 5sec will mean that there won't be a feeling of waiting, once it actually will be able to connect on a cycle.

Since June, and I will say, please, bitte, snälla du 

I've just installed the latest Beta, but no mention of this, so I do. I see most of recent effort has been on Linux - reminds me to also try it there. Local VMs have run fine through the Windows Mullvad, but I can also do it independently, to help your tests, and will.

**Comment by faern** [comment]
I can't recall hearing about this issue a lot from other users. But support is much more suited for these type of issues. The know if others have had it and they will be know how to fix it if there is a known fix. Please contact support@mullvad.net instead.

**Comment by narration-sd** [comment]
Thanks for coming back, Linus.

I did contact support, several times.  But you and I both should understand that there can't be a fix for this except by Mullvad becoming able to manage retries.

There were once add-ons for Windows which could help re-order and delay add-on executions at startup. They don't exist any more, perhaps prohibited. And the only ability Win10 has itself is to disable startups or not.

In any case, such an adjustment is not something a general user would be prepared to make, suspect we would agree.

I'm sure you and the team have a lot on the plate, but the auto-retry seems it  would be very valuable to include in this beta's release; and not much programming effort to provide, not so?

Thanks, @faern 
Clive

**Comment by dlon** [comment]
Please reopen if you're still having issues
