### ISSUE TITLE
android:  differentiate mullvad icon in status bar when connected or not

### ISSUE THREAD

**Issue by grrrrr** [mullvad/mullvadvpn-app#1879]
Currently when you start Mullvad client (2020.5-beta2) on Android you get an solid white icon of the mole in the status bar, regardless of whether the vpn is connected or not.

It would be useful if this icon could change depending on the VPN status

e.g   solid white for connected
        outline only when disconnected.

This would help to see at a glance, without having to swipe down to see the notification bar, that the VPN state on the phone

**Comment by faern** [comment]
When Android is connected via VPN it always shows a key icon in the area next to the battery level/clock etc. This can be used to see the current status.

But it might not hurt to also alternate the icon of course.

**Comment by Rawa** [comment]
We nowadays show color on the topbar if you are secured or not. This issue is completed and a bit legacy, closing. Please open a new ticket if you have a new issue or if you feel this ticket has not been solved.
