### ISSUE TITLE
Mullvad Linux clients interferes with Podman in Fedora

### ISSUE THREAD

**Issue by valmar** [mullvad/mullvadvpn-app#1893]
Operating system: Linux Fedora 32

App version: 2020.05

The Mullvad client seems to interfere with the ability to run podman containers in Fedora 32, due to its usage of cgroup. 

After Mullvad is installed (it does not need to be started!), launching a non-privilieged podman container results in the following error:

Error: creating cgroup directory `/sys/fs/cgroup/net_cls/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-<random string here>.scope`: No such file or directory: OCI runtime command not found error

Looking at this bug report:

https://github.com/containers/libpod/issues/5703

I run the following command on my service:

findmnt -R /sys/fs/cgroup

This gives me:

TARGET                   SOURCE  FSTYPE  OPTIONS
/sys/fs/cgroup           cgroup2 cgroup2 rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate
└─/sys/fs/cgroup/net_cls net_cls cgroup  rw,relatime,seclabel,net_cls

net_cls here seems to use cgroup v1 and this configuration appears not to be supported (see the bug report).

Removing the Mullvad client and rebooting solves the issue (and the net_cls mount point disappears)

ValMar

**Comment by pinkisemils** [comment]
This will be fixed in `crun` [here](https://github.com/containers/crun/pull/436), but we'll also change the daemon to mount our cgroup hierarchy in `/dev/mullvad-exclude` to prevent any other potential clashes.

**Comment by pinkisemils** [comment]
In fact, even when mounting the old cgroup controller elsewhere, the `runc` bug still manifests and podman fails to run.
```
[e@localhost ~]$ mount | grep cgr
cgroup2 on /sys/fs/cgroup type cgroup2 (rw,nosuid,nodev,noexec,relatime,seclabel,nsdelegate)
net_cls on /run/mvd-net-cls type cgroup (rw,relatime,seclabel,net_cls)
[e@localhost ~]$ podman run -it bash
Error: creating cgroup directory `/sys/fs/cgroup/net_cls/user.slice/user-1000.slice/user@1000.service/user.slice/libpod-6a52817239deeb7a04d9d73097292d6018b88e29d8137f07b0490eb61466c631.scope/container`: No such file or directory: OCI runtime command not found error
```

In the upcoming release, you will be able to control where the daemon will mount the `net_cls` controller, but the daemon will only mount it if it isn't mounted already.

**Comment by valmar** [comment]
Thank you for working on this. Let me know if I can help by testing

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pinkisemils** [comment]
The unfortunate fact of the matter is that you'll have to wait until `crun` is fixed for this to work nicely, as even if the controller is mounted elsewhere, `podman` will still fail to run. As a quick and hacky fix, you can just compile the branch of `runc` I mentioned above and use that binary instead and then `podman` should work fine, but I can not attest to the stability/safety of a dev branch build of `crun`, so proceed at your own risk.

**Comment by valmar** [comment]
Thank you and don't worry, I can wait. Actually, thank you for your work on this problem!

Valerio

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hyperreal42** [comment]
I can confirm this bug on Fedora 32 x86_64 with Mullvad VPN client and Podman. I can also confirm using the branch of crun that @pinkisemils mentioned above works / fixes the issue.

To save other potential users with the same issue the trouble, here are the steps I took to get this working:
### Install requirements
`sudo dnf install -y make python git gcc automake autoconf libcap-devel systemd-devel yajl-devel libseccomp-devel go-md2man glibc-static python3-libmount libtool`

### Clone the dev version of crun for the specified branch
`git clone -b cgroupv2-skip-join-other-controllers https://github.com/giuseppe/crun.git`
`cd crun`

### Compile new crun binary
`./autogen.sh`
`./configure`
`make`

### Install into /usr/local
`sudo make install`

Then reboot.

**Comment by pinkisemils** [comment]
Just to be clear, we do not recommend running development builds just for the sake of safety - carry on at your own risk.
