### ISSUE TITLE
Can't install Docker with mullvad running

### ISSUE THREAD

**Issue by hovancik** [mullvad/mullvadvpn-app#1902]
## Issue report

Operating system:  Debian Sid

App version:  2020.5

### Issue description

Installation of docker fails https://docs.docker.com/engine/install/debian/

```
Setting up docker-ce (5:19.03.12~3-0~debian-buster) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Tue 2020-07-07 09:15:08 CEST; 4ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 22524 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 22524 (code=exited, status=1/FAILURE)
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

I think this is relevant from syslog:

```
Jul  7 09:15:12 sidbook dockerd[22674]: time="2020-07-07T09:15:12.858972027+02:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Jul  7 09:15:12 sidbook dockerd[22674]: failed to start daemon: Error initializing network controller: list bridge addresses failed: PredefinedLocalScopeDefaultNetworks List: [172.17.0.0/16 172.18.0.0/16 172.19.0.0/16 172.20.0.0/16 172.21.0.0/16 172.22.0.0/16 172.23.0.0/16 172.24.0.0/16 172.25.0.0/16 172.26.0.0/16 172.27.0.0/16 172.28.0.0/16 172.29.0.0/16 172.30.0.0/16 172.31.0.0/16 192.168.0.0/20 192.168.16.0/20 192.168.32.0/20 192.168.48.0/20 192.168.64.0/20 192.168.80.0/20 192.168.96.0/20 192.168.112.0/20 192.168.128.0/20 192.168.144.0/20 192.168.160.0/20 192.168.176.0/20 192.168.192.0/20 192.168.208.0/20 192.168.224.0/20 192.168.240.0/20]: no available network
Jul  7 09:15:12 sidbook systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
```

Local network sharing is enabled. 
The only way to continue install is to quit mullvad.

**Comment by pinkisemils** [comment]
Have you tried allowing LAN traffic?

**Comment by pinkisemils** [comment]
I set up a fresh Debian unstable VM today and I could not reproduce this with the 2020.5 release - the `docker-ce` package installed without a hitch and the service is up and running. 

I was using the `buster` repositories, as Docker does not support unstable or testing releases -
```
deb https://download.docker.com/linux/debian buster stable
```

I can also confirm that I managed to install `docker-ce` without enabling LAN traffic. And `docker run curlimages/curl -- https://am.i.mullvad.net` runs just fine without enabling LAN traffic as well. Is there anything else that you think might be different about your setup?

**Comment by hovancik** [comment]
Interesting. Not sure what the difference could be. Maybe VM is doing the difference? 

I also was doing this on fresh install.

**Comment by pinkisemils** [comment]
A difference might be that I have not installed a desktop environment on that machine.

**Comment by fuzebox1** [comment]
I have no problem installing docker on Arch behind VPN, but running dockerd when VPN is active does not work, it is a known issue. The VPN covers the whole ip range, and docker wants an ip. You would have to exclude some IPs from the vpn - but idk if thats possible with the way mullvad has things set up. Id like to see an option in the app "allow docker" or something.

**Comment by pinkisemils** [comment]
I wonder if it's a specific docker runtime that is having trouble acquiring IP addresses. I'll try Arch as well, but last time I was running on Arch, there were no issues with Docker.

**Comment by pinkisemils** [comment]
It seems to me that it works fine after a reboot. The `docker.service` systemd unit was failing to start at first, but after rebooting, it was fine. Since docker creates it's own network, you may need to alow lan traffic for it to work. The specifics of why it fails elude me still.

**Comment by dlon** [comment]
Is this still an issue? Please reopen if it is.
