### ISSUE TITLE
Mullvad App using Wireguard on Fedora Linux not loading wireguard kernel module

### ISSUE THREAD

**Issue by seekermoc** [mullvad/mullvadvpn-app#1911]
## Issue report

Operating system: Fedora 32 Linux w/ kernel 5.7.x

App version: 2020.5

### Issue description

Mullvad App using Wireguard on Fedora Linux not loading wireguard kernel module

I'm not sure if this is an issue, or if I'm just misunderstanding something, but I was under the impression that the wireguard kernel module was required to use a wireguard VPN protocol on Linux. The wireguard guide at https://mullvad.net/en/help/tag/wireguard/ also specifically mentions using modprobe to load the wireguard module. However, wireguard appears to be working in the app even without loading the kernel module, and manually loading the module with modprobe doesn't seem to affect how the app works in any way.

If that is the case, then what is the point of the wireguard kernel module, and how does it interact (or not) with the mullvad app? Does loading it bring any benefit in addition to the app when using wireguard (faster processing, stronger security, etc)? If so, they why doesn't the app automatically load the module? If not, why mention loading the module on the mullvad.net wireguard help site?

**Comment by pinkisemils** [comment]
The app is currently using the userspace implementation on all platforms, but there is a plan to use the kernel module if it's available.

**Comment by faern** [comment]
> why mention loading the module on the mullvad.net wireguard help site?

That FAQ entry you are referring to is if you use vanilla WireGuard without our custom app. You can use vanilla WireGuard towards our servers. Then you have to set it up yourself. For example via the kernel module.

As @pinkisemils points out, we currently don't use the kernel module, but rather `wireguard-go` which is a userspace implementation. As built in kernel support for WireGuard is getting more and more popular, we will update the app to use the kernel module if it's available. It should give better performance and hopefully be more stable. But the userspace version has the benefit that it works everywhere, no matter the kernel.

**Comment by seekermoc** [comment]
Okay, thanks for the response!
