### ISSUE TITLE
Can't create wireguard key, and then error attempting to send issue report within the app

### ISSUE THREAD

**Issue by hugbubby** [mullvad/mullvadvpn-app#1921]
## Issue report

Operating system:Android 10, OnePlus

App version: 2020.5

### Issue description

"Failed to generate wireguard key" when trying to connect, or create/generate a new wireguard key
"Failed to send problem report" when trying to send a problem report to mullvad within the app

How can I access the logs myself so I can figure out what the issue is?

**Comment by faern** [comment]
Try to disconnect the app and then send a problem report. I don't know what state you are in, but I suspect the app is in the blocking state due to trying to connect but there is no WireGuard key. Then it will block the internet, as such sending problem reports will not work. Click "Cancel"/"Disconnect" on the main app screen and try to send a problem report after that and see if it helps.

**Comment by kaijuagenda** [comment]
Can replicate the issue here.

@faern  it's not because the VPN is connected either when attempting to send a bug report.

App Version: 2020.5 (via F-Droid & Direct Download)

Device: LG-H918 (LG V20 for TMO)
OS: Android 10
ROM: LineageOS 17.1
GSF & GApp Env: No GSF, No GApps

**Comment by adityasubathu** [comment]
I faced this on 2020.5 stable build on Manjaro 20.0.3. Correspondence with the support staff concluded that something in my system was blocking Mullvad VPN's access to api.mullvad.net. Even after a clean os installation, the issue didn't go away. SOOOO I installed 2020.4 and et voilà !! I am able to generate AND verify a wireguard key now.

Another related bug that I noticed with 2020.5 is that the app is unable to show the date of the subscription validity. This does not happen with 2020.4

**Comment by jvff** [comment]
Is this still an issue with the Android app version 2020.6-beta2?

**Comment by pinkisemils** [comment]
The only relevant change was that we added a new trusted certificate to our API client.
Could you try and replicate this with OpenSSL's command line client by using the cert that is available in our repository as such -
`echo "Q" | openssl s_client -connect 193.138.218.78:443 -CAfile mullvad-rpc/old_le_root_cert.pem -tls1_2  -verify_return_error -no-CApath -no-CAfile -verify_hostname api.mullvad.net  -security_debug_verbose || echo "Failed to connect"`

`echo "Q" | openssl s_client -connect api.mullvad.net:443 -CAfile mullvad-rpc/old_le_root_cert.pem -tls1_2  -verify_return_error -no-CApath -no-CAfile -verify_hostname api.mullvad.net  -security_debug_verbose || echo "Failed to connect"`
You must adjust the path to the root certificate if you are not running the command from the root of our repository.

Try both commands and see if the output ends with `Failed to connect` (the failure case) or `Done` (the success case). In the failure case, it'd be great if you pasted the output from each of those commands. 

Also, would you feel comfortable sharing which ISP you are using?

**Comment by faern** [comment]
I'm closing this as inactive. If OP or anyone else is still having this issue please ping me and provide some more details on how it misbehave on latest stable version of the app.
