### ISSUE TITLE
Show me the best location, server to use right now

### ISSUE THREAD

**Issue by daraul** [mullvad/mullvadvpn-app#1925]
Sometimes I don't care which server I'm on, and just want the best possible connection while keeping myself secured.  The only criteria I can think of right now to pick the "best" server might be latency, but there might be others I'm not equipped to describe right now.

**Comment by faern** [comment]
Automatic "best server" has been requested before. But it's more problematic than it sounds like to implement. I have described this in another issue: https://github.com/mullvad/mullvadvpn-app/issues/1099#issuecomment-531109148

**Comment by daraul** [comment]
I see, thanks for the heads up.

**Comment by Orbsynated** [comment]
Any update on this? it would be nice if I could use the reconnect command via the cli to connect to the best, lowest latency server(preferably wireguard and not openvpn).
Also, Issue 1099 has been deleted so I can't view your explanation regarding this implementation @faern .

**Comment by faern** [comment]
Too bad my explanation is gone :/

To answer the question briefly: No there is no update on this and we don't plan on implementing it. Latency is a very bad measurement of suitability for the connection. Latency varies over time. Latency is not an indication of bandwidth. And also, to figure out the latency we would need to ping every server, which would be noisy on the network, easy to fingerprint and all. We think this type of solution has many downsides and very few upsides, it does not even solve the issue of finding the best server.

**Comment by faern** [comment]
Do you actually experience such different latency between servers in the same country? Our servers are not overloaded. No server basically ever reach their bandwidth limits. In contrast to most other VPN providers we only run bare metal servers with plenty of bandwidth, no virtual machines. So we do not need to factor in load into the equation. My guess is that you have different peering to different data centers maybe :thinking:
