### ISSUE TITLE
Installation Aborted

### ISSUE THREAD

**Issue by iLostMyXbox21** [mullvad/mullvadvpn-app#1937]
**Operating System:** Windows 10 Pro | Version 1909 | OS Build 18363.959
**Installer Version:** 2020.5.0

**Error:**  "Installation Aborted" \n "Setup was not completed successfully"

**More Details:**
-- Progress bar stops at about 1/8 of the way (approx)
-- Previous installation worked, would not connect so i tried to uninstall and reinstall
-- Reinstalled the installer 4 times, all giving the same error
-- Installer stops as soon as it is launched
No further errors are given except the one i stated above

**Comment by dlon** [comment]
Thanks for reporting this. Is there any information in `C:\ProgramData\Mullvad VPN\install.log`? If so, it might be useful.

**Comment by faern** [comment]
Please mind that the app logs can contain some semi-sensitive information locally on your computer. If you send a problem report through the app it will automatically redact such info from the logs and send them to our support. If they are not directly able to help they can escalate to us developers.
