### ISSUE TITLE
Client window does not show on top

### ISSUE THREAD

**Issue by Scarsz** [mullvad/mullvadvpn-app#1943]
## Issue report

Operating system: Windows 10

App version: 2020.5

### Issue description

When gaming, I want to turn the VPN off for as low ping as I can get. The Mullvad client does not show up on top when you click the tray icon though. This is an issue for games running in borderless fullscreen because they *do* render on top. You can press the Windows key to bring the taskbar up, and while clicking the Mullvad task tray icon, the game takes priority over that window so the window doesn't get shown.

Only games that I've tested this with are Apex Legends & Escape from Tarkov but I believe this is an issue with borderless fullscreen, not any specific game logic. The only way to get around this issue I've figured out is to set my primary monitor in Windows to my secondary monitor (so the task tray appears there instead) or completely closing the game just to turn the VPN off, unfortunately.

**Comment by faern** [comment]
Thank you for reporting this. We are investigating if we can make our GUI show up on top of fullscreen games.

**Comment by Scarsz** [comment]
Another workaround for people with multiple monitors is to use the `Win+Shift+Arrow` hotkey to move the windows around. Not completely ideal, of course, but beats having to close the game and only takes a couple seconds.
