### ISSUE TITLE
[Feature Request] Automatic startup on login, without prompt for password.

### ISSUE THREAD

**Issue by drasbeck** [mullvad/mullvadvpn-app#195]
It would heighten the UX of the already very smooth macOS client, with an in-app option to run the client on login, without prompting for the password. Or at least the password part, since it is fairly easy to start anything at login within macOS.
Apart from the UX perspective, the connection is also open until the Mullvad client blocks it, which only happens _after_ entering administrator credentials.

Is such a change to the implementation at all possible? Are there security issues related to doing so?

**Comment by pronebird** [comment]
Hi,

This has been implemented but not released yet. The relevant part of the app that needs elevated permissions will be installed as a system service once and won't prompt for password on each start of the app.

**Comment by drasbeck** [comment]
This is great news, I am looking forward to seeing this implemented. Give the word if you need any testing done. =)

**Comment by pronebird** [comment]
@drasbeck Please take a look at the most recent pre-release (look for macOS installer package with`.pkg` extension) that installs a tiny bit of our app as a system service that runs with elevated permissions to maintain the secure connection. No more annoying password prompts! 

https://github.com/mullvad/mullvadvpn-app/releases/tag/2018.2-beta1

**Comment by drasbeck** [comment]
Hi I'm testing now and everything seems alright on my end. 👍

**Comment by pronebird** [comment]
@drasbeck great to hear that! 👍 Closing as resolved.
