### ISSUE TITLE
iOS app (2020.3) shows few days left on the account; desktop Mac 2020.5 app shows a year 

### ISSUE THREAD

**Issue by mikesk8** [mullvad/mullvadvpn-app#1963]
iOS app (2020.3) shows few days left on the account; desktop Mac 2020.5 app shows a year

**Comment by pronebird** [comment]
Hi,

This is already addressed and the fix will be released along with the upcoming app update. Until then, please log out and log back in. That should fetch the correct expiry.

Cheers,
Andrej

**Comment by mikesk8** [comment]
thank you!

**Comment by faern** [comment]
Closing since this is fixed.
