### ISSUE TITLE
Cannot install in Silverblue

### ISSUE THREAD

**Issue by Pobega** [mullvad/mullvadvpn-app#2057]
## Issue report

Operating system: Fedora Silverblue 32

App version: MullvadVPN-2020.5_x86_64.rpm

### Issue description

When installing using `rpm-ostree install` it fails out with an error:

```
error: Importing package 'mullvad-vpn': Unsupported path: /usr/local/share/zsh/site-functions/_mullvad
```

Additional output from the failure links to this Github issue: https://github.com/projectatomic/rpm-ostree/issues/233

Currently working around the issue by using `wg-quick` via systemd, but would much prefer to have the desktop application available.

**Comment by Pobega** [comment]
I actually realize how that there is already:
https://github.com/mullvad/mullvadvpn-app/issues/1861
and https://github.com/mullvad/mullvadvpn-app/issues/1570

So I'm closing this since it's just extra noise, apologies.

**Comment by securityopa** [comment]
Here is a solution I found:
https://pcforum.org/wiki/entry/12-how-to-install-mullvad-vpn-on-fedora-silverblue/
