### ISSUE TITLE
[Feature] OpenBSD Support

### ISSUE THREAD

**Issue by itsmekevin212124** [mullvad/mullvadvpn-app#2079]
Hello!
I'm not entirely certain if a port is possible, but I would love to see an OpenBSD port of the Mullvad VPN app! :)

___________________________________

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=92823749)](https://www.bountysource.com/issues/92823749-feature-openbsd-support)

**Comment by faern** [comment]
That is likely not going to happen in any foreseeable future. I agree it would be cool! But the amount of work needed to make it work does not compare favourably with the number of potential users. It's not only the initial chunk of code to make it functional. It's also the commitment to continuously maintain it and properly test it before each release.
