### ISSUE TITLE
Active connection prevents Windows 10 hotspot

### ISSUE THREAD

**Issue by BuzzKnightbeer** [mullvad/mullvadvpn-app#2083]
I'm on the latest Windows 10 Pro and use the 2020.5 Mullvad client.

I was able to pass the Mullwad Wireguard connection through to the built-in Windows 10 hotspot connection by making it available for sharing and forward it to the Windows hotspot connection. Now every device connected to the hotspot uses automatically the Mullvad connection which I can verify by opening the Mullvad homepage on a device and it shows that I'm connected to the server I picked on the computer that created the hotspot.

The only problem I have is that when there is an active connection on my PC, Windows says I have no available connection to create a hotspot. So every time I want to switch it on, I have to disable the VPN, enable the hotspot, and then re-enable the VPN.

This behaviour is independent of the previous setup and happens also when the Wireguard connection is not shared to the hotspot connection. I just wanted to explain what my setup and use-case is.

Is there a way to get this working without having to disable the VPN first?

**Comment by faern** [comment]
For help using the app please contact our support at support@mullvad.net
