### ISSUE TITLE
Electron for a simple login app? why?

### ISSUE THREAD

**Issue by RUSshy** [mullvad/mullvadvpn-app#2091]
Why do i need a full browser sitting in the system tray only just to login?

Why people bloat everything they touch

You had 1 job, and you failed

**Comment by pronebird** [comment]
Hi,

Well this is simply offensive towards the developers. You probably noticed the amount of work that's been put into what you call a "login app". If it was that simple to developer & distribute to multiple Linux distributions, Windows and macOS with just a few developers at our disposal, we would definitely go fully native right from the start. It doesn't mean that the desktop app will be using Electron forever, but it's been quite helpful so far and helped us roll out a lot of features relative quickly. Both our mobile apps are fully native.

I'd like to note that you can use our CLI tools instead, which consume very little memory and are pretty handy.

Cheers,
Andrej

**Comment by faern** [comment]
It does login indeed. It also does nice and easy server and location selection. Allows changing a lot of settings and getting information about what they do. Allow you to view and rotate your WireGuard key. See info about your account, such as remaining time. Easily send support requests to us. See the current status of the tunnel and where it's connected etc.
