### ISSUE TITLE
Split Tunneling on android doesnt stay active

### ISSUE THREAD

**Issue by UserOfStuff** [mullvad/mullvadvpn-app#2093]
## Issue report

Operating system: Android 9

App version: 2020.6-beta2

### Issue description

Hello, 

I am using the latest version of Mullvad, from F-droid, and I am having some issues with split tunneling. I personally use split tunneling to block internet access to apps I don't want connecting to the internet (using the built in kill switch on Android). My issue is that split tunneling does not always work. For example, if I restart my phone, an app that I have enabled in split tunneling is not actually using the split tunneling feature. Split tunneling only starts to work again if I go into the app and go the the split tunneling page. I don't have to do anything on the page, split tunneling is already on, all I have to do is go to the page itself. Hopefully I explained the issue clearly. Any help will be much appreciated!

Thanks

edit: forgot to mention that I don't need to restart my phone for split tunneling to stop working. The first time I noticed I was just using my phone regularly.

**Comment by faern** [comment]
Thanks for reporting this. We are aware of this bug and a fix has already been merged in #2075. The next release will have this resolved. Leaving this issue open until said release is out.

**Comment by faern** [comment]
This fix has been released a long time ago already. Closing.
