### ISSUE TITLE
[beta] connection fails if port 53 is used to connect to wireguard

### ISSUE THREAD

**Issue by kubrickfr** [mullvad/mullvadvpn-app#2094]
Operating system: arch linux, kernel 5.8.7

App version: 2020.6-beta2-dev-265024 2020-09-09

With the latest git version of the app, including using the linux kernel implementation of wireguard, the connection fails if port 53 is used to connect to wireguard.

**Comment by faern** [comment]
Thanks for reporting this. We will look into it!

**Comment by faern** [comment]
We have tested this now and everything works fine on Ubuntu 20.04 and Fedora 32. We have not tried it on arch. Can you reliably reproduce the problem and can you maybe try choosing another location/server?

If you still have trouble, please send a problem report through the app.

**Comment by kubrickfr** [comment]
You are correct, maybe it was just the provider I was using at the time that was blocking port 53 and I blamed it on the new feature... Is there a way I can configure which implementation to use (go/kernel) so I can test it?

**Comment by faern** [comment]
Currently no. It will try with the kernel version and if it works it will use it. We might add an environment variable that can force usage of the userspace version, but it's not there yet.

**Comment by faern** [comment]
If you are building from source I assume you are comfortable editing it a little bit. You can just remove the highlighted section here and build, then it won't use the kernel WireGuard implementation at all: https://github.com/mullvad/mullvadvpn-app/blob/master/talpid-core/src/tunnel/wireguard/mod.rs#L132-L146

**Comment by kubrickfr** [comment]
I now think it was just my mobile provider that blocked UDP 53 while roaming, or something like that.
