### ISSUE TITLE
Bug: Login Failed — Internal Error (iOS 12)

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#2108]
## Issue report

Operating system: iPhone 6 (iOS 12.4.8)

App version: 2020.4

### Issue description

When trying to logged in. It says "Internal Error" and I can't sign in.

**Comment by faern** [comment]
Can you reliably reproduce this? Does it happen every time? Sadly we don't have any built in problem reports for iOS yet, so a bit hard for us to get hold of the relevant logs that might help debug this.

**Comment by 8227846265** [comment]
It happens when trying to log in.

**Comment by 8227846265** [comment]
Found the issue. It's related to the current # of WireGuard keys. If your total # of WireGuard keys is already 5. Logging in to the iOS app will show "Internal Error", I presume this is because an account can only support a maximum of 5 devices.

Releasing WireGuard keys and creating new ones fixes the issue.

**Comment by pronebird** [comment]
@8227846265 what version of the app do you have installed? I believe we have fixed this issue, i.e we display "too many wireguard keys" but maybe something went wrong on our side (once again).

**Comment by 8227846265** [comment]
**Issue report**
Operating system: iPhone 6 (iOS 12.4.8)

App version: 2020.4
