### ISSUE TITLE
OpenVPN support on the iOS app 

### ISSUE THREAD

**Issue by Strykeros** [mullvad/mullvadvpn-app#2110]
## Issue report

Operating system: IOS 12.4

App version: 2020.4

### Issue description

I would like to see the OpenVPN support on the app, cause it is known to be more private. For now I can only connect through Wireguard protocol. Thank you.

**Comment by kah0922** [comment]
https://github.com/mullvad/mullvadvpn-app/issues/1210#issuecomment-660912263

Looks like that's not happening, which blows IMO. Especially since the Shadowsocks app makes crashlytics requests. 

I really do hope they reconsider this decision.

**Comment by faern** [comment]
What makes you think OpenVPN is more private? More private in what sense?

OpenVPN was not designed with battery powered mobile roaming devices in mind. It uses way more battery than WireGuard and handles roaming between networks far worse. On top of that it's a way bigger and older code base and relies on the also way older and larger OpenSSL. This historical baggage makes it harder to audit and keep secure as well.

There are no plans on supporting OpenVPN in our mobile apps. WireGuard is simply way more fit for that purpose. And our desktop apps go more and more towards WireGuard as the default protocol. Windows is the only platform where we still use OpenVPN by default.

> since the Shadowsocks app makes crashlytics requests.

Our app **does not** make crashlytics requests. And even after we include some obfuscation protocol (shadowsocks or other) the app will not make such requests.

**Comment by carbongreat13** [comment]
> What makes you think OpenVPN is more private? More private in what sense?

The Wireguard server software should keep a log. This is hard coated and should not be able to be no-logged.

Have you patched Wireguard so that it does not log? Or are you logging it?

**Comment by carbongreat13** [comment]
And one more thing: OpenVPN is audited, but Wireguard is not.
Also, OpenVPN with TCP is more resistant to Great Firewall than Wireguard with UDP.
