### ISSUE TITLE
[Incompatibility] Mullvad & Adguard

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#2113]
## Issue report

Operating system: Windows 10 x64 (Latest Stable)

App version: 2020.5

### Issue description

- If AdGuard's DNS Module* is enabled with any default or custom DoH DNS server and Mullvad VPN is enabled.
- Then after my PC sleeps and re-awakens. DNS queries becomes blocked.

**When trying to visit a website:**

- Brave Browser shows ERR_NAME_NOT_RESOLVED
- Microsoft Edge shows DNS_PROBE_FINISHED_NO_INTERNET

**Note:**

- As Mullvad VPN hijacks all DNS queries, is there any solution for this for both apps to be compatible.
- I already contacted AdGuard's support and they deemed that it's a problem with Mullvad's side.
- All of Mullvad VPN settings is by default except for the following
A. Local Network Sharing = Enabled
B. Always Require VPN = Enabled

Reference:
* https://kb.adguard.com/en/general/dns-filtering-android (Also applies for the Windows implementation)

**Comment by faern** [comment]
Currently the Mullvad VPN app assumes it can take total control over the machine's DNS settings and enforce them as strongly as it can. We are aware this causes some issues with some more custom DNS setups and third party software that also want to manage DNS. We are slowly moving towards supporting custom DNS and maybe other ways of allowing advanced users to better tweak what Mullvad does to the system.

**Comment by auswalk** [comment]
Try this it works for me:
in /etc/systemd/resolved.conf

`
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See resolved.conf(5) for details

[Resolve]
#DNS=
#FallbackDNS=
#Domains=
#LLMNR=no
#MulticastDNS=no
#DNSSEC=no
#DNSOverTLS=no
#Cache=no-negative
**DNSStubListener=yes**
#ReadEtcHosts=yes
`

So then /etc/resolv.conf:
`
nameserver 127.0.0.1
#nameserver 10.64.0.1
nameserver fc00:bbbb:bbbb:bb01::1
# Too many DNS servers configured, the following entries may be ignored.
nameserver fd00:1::1
search lan
`

**Comment by 8227846265** [comment]
I suppose the recent update of Mullvad fixes the issue of custom DNS. I'm closing this thread now. :)
