### ISSUE TITLE
Impossible to switch locations when using firestick

### ISSUE THREAD

**Issue by ydewit** [mullvad/mullvadvpn-app#2129]
The android apk is usable in my firestick to the extent that I can establish a Wireguard connection. However, I can do that only to the default location, which is Sweden. When I try to switch the location by expanding the specific country, I can not select any of the servers that show up.

I am using the latest firestick 4K and this apk version: https://mullvad.net/media/app/MullvadVPN-2020.6-beta2.apk.

**Comment by faern** [comment]
Thanks for reporting this. We are aware the app does not work well on TV devices such as the firestick. The app has not been designed with those platforms in mind. But we will improve the usability there when time allows!

**Comment by ydewit** [comment]
Yes, I understand!

Just one note, though. I am sure there are tons of usability improvements that can be done and that could be a considerable effort, but the app is functional on my Firestick with the exception of selecting the country and server. Maybe there is a simple UI change to address that? I think all the other limitations we can live with for a while until a major release comes along.

**Comment by jvff** [comment]
Hello! This should now be fixed by #2177. The change was included in the release version `2020.8-beta1`.

Please reopen this issue or open a new one if the issue still exists.
