### ISSUE TITLE
[Incompatibility] Amnis Torrent Player & Mullvad

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#2130]
## Issue report

Operating system: Xiaomi Mi Box (Android 10) / Pocophone F1 (Android 10)

**App version: (Tested for the following apps)**
- Mullvad Android Official App v2020.4 (Pocophone)
- OpenVPN for Android v0.7.19 (Mi Box & Pocophone)

### Issue description

When connected to Mullvad. Amnis Torrent Player when loading a VPN will have 0 Kbps to 50 Kbps download speed.

**Link:**
Amnis: https://play.google.com/store/apps/details?id=com.amnis&hl=en

I highly suggest trying it on your device to experience the issue directly.

**Server Tested:**
- Singapore
- Hong Kong

**Comment by faern** [comment]
For help using the app and get performance tips please contact our support at support@mullvad.net
