### ISSUE TITLE
Android 11: DownloadManager won't download 

### ISSUE THREAD

**Issue by y20k** [mullvad/mullvadvpn-app#2170]
## Issue report

Operating system: Android 11

App version: 2020.6-beta2 (F-Droid)

### Issue description
This may be a very specific problem. Feel free to close this issue. I just wanted to bring it to your attention. The problem is present in Android 11. I was using Android 9 before and it never came up.

I am the developer of a lesser known podcast app. My app downloads RSS feeds and audio files using [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager). RSS feeds are fetched via [NETWORK_MOBILE](https://developer.android.com/reference/android/app/DownloadManager.Request#NETWORK_MOBILE) and [NETWORK_WIFI](https://developer.android.com/reference/android/app/DownloadManager.Request#NETWORK_WIFI). Audio files are downloaded **via NETWORK_WIFI only**.

When my phone is accessing the internet via the Mullvad app, DownloadManager will download RSS files, but will not download audio files.

The thing is: When I am connecting to Mullvad using the vanilla Wireguard app, everything works fine.

**Comment by faern** [comment]
Thanks for reporting this. I highly suspect this is because of this: #2104. We recently made sure to not mark the VPN connection as metered. So it's likely this is already resolved in `master` and will be included in the next release.

**Comment by y20k** [comment]
Yes that is probably the issue. I replicated the problem by marking a plain Wi-Fi connection (without any VPN) as "metered" in the Android Emulator. In this test DownloadManager did also not download files, when configured with a NETWORK_WIFI-only restriction.

**Comment by y20k** [comment]
@faern just fyi. v2020.8-beta1 fixes the issue for me. Thanks

**Comment by Zhuinden** [comment]
https://stackoverflow.com/a/64640927/2413303
