### ISSUE TITLE
Application overrides local firewall settings

### ISSUE THREAD

**Issue by not-enought** [mullvad/mullvadvpn-app#2171]
## Issue report

Operating system: MacOS

App version: 2020.5

### Issue description

Application doesnt respect local filtering rules.

Default settings used by application overrides local filtering rules and allow all outgoing internet connections.
"Local network sharing" allows only full LAN access or full blocking.

-- 

Please respect local settings and do not override them by default.
- Add only rules required for VPN and/or more restrictive rules like DNS blocking.
- Less restrictive filtering should explicitly set by user in application settings.

Add option to disable "Local network sharing" setting

or 

Change "Local network sharing" to "Disable local network sharing"
- If "Disable local network sharing" = true, disable LAN access.
- If "Disable local network sharing" = false, use only minimum required rules

**Comment by faern** [comment]
Thanks for reporting this. Yes we know we take full control over the firewall. But we will look into maybe relaxing the rules in such a way that a normal user are equally safe as now, but power users can customize their firewall to some degree.

**Comment by not-enought** [comment]
How exactly do your settings help to users? Is there any way to not change current firewall settings?

These settings make sense only for users without firewall, everyone else is probably less safe cause your overrides their settings and never mention it.

Where exactly can user find information about this behavior? 

Is this behavior specific for macos?

**Comment by faern** [comment]
> Is there any way to not change current firewall settings?

No. All current versions of this app will force these firewall rules. There are discussions on allowing power users to disable the firewall module in the app, but this has not been implemented yet.

> These settings make sense only for users without firewall

Yes. Which is the vast majority of users. During the three years this app has existed and done exactly this to the user's firewall no one has contacted us about this. You are the first as far as I know :)

I agree it's very limiting towards power users who want custom firewall rules. But given how very few people on macOS do have custom firewall rules, it has not made a lot of sense prioritizing fixing it so far.

> Where exactly can user find information about this behavior?

We have documentation outlining roughly how the security in the app is implemented here: https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md. But it does not explicitly state that it overrules any other firewall rules the user might have.

> Is this behavior specific for macos?

Not really. We do something very similar on all platforms.

However. It's possible to work with firewall chain/anchor priorities and orders to make your custom rules be evaluated before ours, and take precedence. But that's not how we intend things to be done. All of that is on the users own risk.

**Comment by DPTJKKVH** [comment]
I usually try to not revive "dead" tickets but this one tickles my fancy.

I'm on Ubuntu Linux and for years I maintain my iptables rules where I only allow the TUN device to connect to specific IP addresses. With Wireguard I do the same simply with an appropiately named allow rule for Wireguards "network device". 

It is somewhat cumbersome to always update all the IP addresses of the VPN servers I want to use but this has proven to be water tight for years so I don't intend to stop relying on it.

Now with wireguards static keys and IP addresses I do jealously look at the mullvad client and its automatic key rotation. However I played around with it and noticed that it doesn't seem to use iptables to block network traffic. So I am rather scared that it either bypasses my iptables rules or manipulates them.

I also don't understand how mullvad blocks traffic without iptables.

**Comment by DPTJKKVH** [comment]
I did some additional reading. Does the following scenario check out?

I set my iptables to block everything by default and add no additional rules.

I set Mullvad to VPN only mode (so block everything but VPN traffic).

If the mullvad process for some reason crashes the default firewall rules will apply = block everything.

**Comment by faern** [comment]
> I read that it uses nftables, which is interesting since I don't have those installed. I also don't know if nftables and iptables mingle well together.

You don't have the userspace tools for *manipulating* nftables rules installed. Nftables itself is part of your kernel. Our app uses netlink to talk directly to the kernel. If you install the nftables userspace tools you can view the rules we set in the system.

No, usually they don't play very well together. But in practice this has worked out well for us so far. I guess most users don't have iptables rules that might collide with ours in place.

> So I am rather scared that it either bypasses my iptables rules or manipulates them.

We don't touch iptables in any way. We only use nftables. Both iptables and nftables uses netfilter underneath. So it all boils down to what netfilter priorities your hooks have compared to ours. If yours have higher priority they will be evaluated first, and vice versa.

> If the mullvad process for some reason crashes the default firewall rules will apply = block everything.

You don't need custom rules for this. The Mullvad app has this kill switch built in. The app always has persistent firewall rules applied that only allows the things that should be allowed. If the app crashes the nftables rules are still present and no traffic will leak. The only time the app removes these rules is if you explicitly exit the app or click "disconnect" in it. And you can even remove that special case by enabling `Always require VPN` under the advanced settings, then the app will never remove the blocking firewall rules.

If the app crashes the only traffic that will be allowed is whatever traffic was being allowed at the time it crashed. If you were connected or connecting to a VPN server that would mean only traffic to exactly that VPN server IP would be allowed, nothing else (modulo DHCP and some other core functionality to make your device function sanely)

**Comment by DPTJKKVH** [comment]
Many thanks for the detailed answers @faern .

Please allow me one more question: You say persientent firewall rules are applied. How exactly do you do this?

I use iptables-persistent on Ubuntu. Do you use an equivalent for nftables in the mullvad client?

If I enable "Always require VPN", does the persistence method Mullvad uses ensure that nftables are properly applied at boot/login (or survive a reboot) even if the Mullvad client fails to start in the first place?

**Comment by faern** [comment]
> I use iptables-persistent on Ubuntu. Do you use an equivalent for nftables in the mullvad client?

Sorry, that's not what I meant by persistent. I was unclear. Our firewall rules do not survive a reboot. I just meant that they are not automatically wiped if the `mullvad-daemon` process dies. The firewall rules live in netfilter in the kernel and is not tied to our daemon process is what I meant.

> If I enable "Always require VPN", does the persistence method Mullvad uses ensure that nftables are properly applied at boot/login (or survive a reboot) even if the Mullvad client fails to start in the first place?

The `mullvad-daemon` is startted by systemd, and the daemon applies the blocking rules kind of instantly when starting. So yes, it does apply blocking on boot. But it depends on what you mean by "fails to start". No if the `mullvad-daemon` does not start at all it naturally does not apply any firewall rules. So the firewall rules are only applied if the daemon is able to get far enough into the initialization routine to apply them. However, I have not heard of a single case where it has failed so drastically that this ever happened or caused a leak. I'm not so sure having a separate `iptables-persistent` systemd service would be much more reliable. Except for the fact that you can make your service maybe load a little bit earlier or something like that.

You do what feels right for you. But our daemon has been designed with the intention of blocking immediately on bootup and keeping the user from leaking any network traffic when `Always require VPN` has been enabled. If you find any potential leak windows please report them as security bugs!

**Comment by DPTJKKVH** [comment]
Again many thanks for your answers and sorry for kind of highjacking this issue. I only asked because I did not find any documentatio on those details.

**Comment by faern** [comment]
This has been fixed on macOS in #2460. So I'm closing this issue.
