### ISSUE TITLE
No "Report a problem" in Settings on iOS

### ISSUE THREAD

**Issue by jirir** [mullvad/mullvadvpn-app#2178]
## Issue report

Operating system: iOS 14.01

App version: 2020.4

### Issue description

When creating a New Issue here on GitHub the template says:

> * you ran into a problem with the app - Send a problem report directly from
within the app. Go to Settings -> Report a problem.

There is no "Settings –> Report a problem" option.

**Comment by faern** [comment]
Yes. iOS does not have that feature yet. But it's coming in a future release.
