### ISSUE TITLE
Constant VPN disconnections on Linux

### ISSUE THREAD

**Issue by jamerst** [mullvad/mullvadvpn-app#2186]
## Issue report

Operating system: Linux (Fedora 32)

App version: 2020.6-beta3 (also occurs on 2020.5)

### Issue description

I am experiencing constant VPN disconnects when using the Mullvad desktop application. These seem to occur seemingly randomly at intervals ranging from 30 minutes to 2 hours. This issue does not occur under Windows on the same machine, nor does it occur on another Fedora 32 machine which connects to Mullvad directly using generated config files and wg-quick. This also occurs for both Wireguard and OpenVPN connections.

I found [this](https://www.reddit.com/r/mullvadvpn/comments/g0owz2/mullvad_networkmanager_disconnects_solution/) reddit post, which when applied appeared to reduce the time taken to reconnect, but did not stop the disconnects.

Logs for mullvad-daemon and NetworkManager are attached, but they don't look to be particularly useful.

[mullvad-daemon.log](https://github.com/mullvad/mullvadvpn-app/files/5397980/mullvad-daemon.log)
[NetworkManager.log](https://github.com/mullvad/mullvadvpn-app/files/5397981/NetworkManager.log)

**Comment by faern** [comment]
Thanks for reporting this. We'll see if we can find what causes it.

**Comment by Evernow** [comment]
I am also experiencing this on Fedora 32.

**Comment by pinkisemils** [comment]
This is a known issue - a workaround is to use systemd-resolved or have NetworkManager manage DNS via `resolvconf`. The plan is to fix this in the upcoming release.
This is basically our fault for trying to manage DNS on a per-interface basis via NetworkManager without setting any of the other config via NetworkManager. This will be resolved by using NetworkManager to setup the WireGuard interface in full in an upcoming release.

**Comment by pinkisemils** [comment]
Another workaround is to force our daemon to use the userspace implementation for WireGuard.
This can be done by setting an environment variable for the daemon: `sudo systemctl edit mullvad-daemon` and add
```
[Service]
Environment="TALPID_FORCE_USERSPACE_WIREGUARD=1"
```
Afterwards, you have to restart the daemon - `sudo systemctl restart mullvad-daemon`. The environment variable should be removed once we've fixed the bug.

**Comment by jamerst** [comment]
This still doesn't appear to be fixed in 2020.7-beta1. I'm still getting disconnected frequently on both Wireguard and OpenVPN.

I'll update to beta2 now, but the changelog doesn't appear to change anything related, so I doubt it will make any difference.

Logs:
[mullvad-daemon.log](https://github.com/mullvad/mullvadvpn-app/files/5549686/mullvad-daemon.log)
[NetworkManager.log](https://github.com/mullvad/mullvadvpn-app/files/5549687/NetworkManager.log)
