### ISSUE TITLE
Fails to start on Kubuntu 18.04

### ISSUE THREAD

**Issue by nextgenthemes** [mullvad/mullvadvpn-app#222]
```
mullvad   
Using GTK2
changing directory to /usr/lib/python2.7/dist-packages/mullvad
Setting logging directory to /home/x/.cache/mullvad/log

(mullvad:19845): GLib-GObject-WARNING **: 00:15:44.974: cannot register existing type 'GdkDisplayManager'

(mullvad:19845): GLib-CRITICAL **: 00:15:44.974: g_once_init_leave: assertion 'result != 0' failed

(mullvad:19845): GLib-GObject-CRITICAL **: 00:15:44.974: g_object_new_with_properties: assertion 'G_TYPE_IS_OBJECT (object_type)' failed
```
If its just some GTK lib missing that should be a dependency of the .deb. Otherwise it should be possible to run this on KDE and not require Gnome.

**Comment by faern** [comment]
The error you are pasting seems to be from our "old" VPN client written in Python 2. This repository is for the complete rewrite we are working on that will work a lot better across all platforms. So far this new version is only released for macOS, but Linux releases will be coming soon.

We are aware the old Python client does not work on any version of Ubuntu 18.04. We are sorry for this, and are aiming at fixing it by releasing this new version as soon as possible. Until then I think you will have to use vanilla OpenVPN. Please contact support@mullvad.net if you need help, or check out our guides at https://mullvad.net/en/guides/
