### ISSUE TITLE
Hey Mullvad, show some love to laptop users

### ISSUE THREAD

**Issue by jererobles** [mullvad/mullvadvpn-app#2248]
## Issue report

Operating system: macOS Big Sur

App version: 2020.6

### Issue description

I get that you make it near impossible to use custom DNS and will try to manipulate the OS settings for privacy's sake. But if I enable Mullvad at home where I have a custom DNS and connect to my home Wi-Fi, you should notice when I'm at the office connected to the office's Wi-Fi that if I disable Mullvad then you shouldn't restore the custom DNS that I use at home.

Great service regardless.

**Comment by faern** [comment]
Thanks for reporting this. This sounds like a bug where we restore the wrong settings if the device change network while connected. We'll look into it!

**Comment by faern** [comment]
Please also know that built in custom DNS support is on the way in the app :)

**Comment by faern** [comment]
@jererobles Does this happen every time? We think this is a race condition. So most likely it just happens sometimes. But under certain setups maybe it happens more often than under others. We'll have to test Big Sur a bit more I guess.

**Comment by jererobles** [comment]
Hey @faern thanks for looking into this. Not really every time, it happens sporadically. Definitely could be related to Big Sur, hopefully it will be fixed by the time Apple seeds retail version today.

**Comment by faern** [comment]
I think the bug is on our end, just that maybe it happens more frequently on Big Sur. We are not sure yet. But the bug has been registered internally and we'll hopefully look into it soon.

**Comment by pinkisemils** [comment]
Would you mind sending a problem report so we can see some logs?

**Comment by jererobles** [comment]
Sure, how can I gather the logs ?

>

**Comment by faern** [comment]
It's built into the app. Go to Settings -> Report a problem.

**Comment by jererobles** [comment]
Sent. Note that the earliest entries in the log are from less than a week ago, not sure if it contains valuable info.

**Comment by faern** [comment]
I'm closing this as pretty stale. I'm not sure if we are still having this issue or not. Also, we have introduced custom DNS since this was posted.
