### ISSUE TITLE
Wrong link for CLI installation guide in "Install Mullvad app on Linux" on webpage

### ISSUE THREAD

**Issue by v34xjf2770** [mullvad/mullvadvpn-app#2252]
In the guide for CLI installation of Mullvad on Linux the links for both Debian and Fedora is wrong.

"wget --content-disposition https://mullvad.net/download/deb/latest" the link should be https://mullvad.net/download/app/deb/latest/
Notice the "/app/". The same goes for Fedora users.

Link to guide:
https://mullvad.net/en/help/install-mullvad-app-linux/

Best regards

**Comment by faern** [comment]
We are working on this. We will reply to this issue and close it once the website has been deployed with working links.

**Comment by simonasker** [comment]
Guides are updated now!
