### ISSUE TITLE
[Feature Request] Add subcommand alias to `mullvad relay set relay`

### ISSUE THREAD

**Issue by rgo3** [mullvad/mullvadvpn-app#2267]
## Feature Request
Hi Mullvad!

Would it be possible to add an alias to the command `mullvad relay set relay` so one could have `mullvad relay set host` instead? To me that would improve the UX of the CLI. I don't know much Rust but from what I could find the `clap` cli library you are using easily supports it.

Happy to try and add this myself if maintainers accept the request.

**Comment by faern** [comment]
I don't think an alias is needed. I think we can just rename `relay set relay` to `relay set hostname`, it's probably a better name to begin with.

**Comment by faern** [comment]
Feel free to submit a PR if you'd like. Thank you.

**Comment by rgo3** [comment]
I was suggesting an alias, to stay backwards compatible for people using `relay set relay`.

**Comment by faern** [comment]
We don't need to have a 100% stable CLI interface. People can re-learn/update scripts. And the feature is very new.
