### ISSUE TITLE
Mullvad breaks DNS resolution on Linux when using NetworkManager with dnsmasq after the 2020.7 update

### ISSUE THREAD

**Issue by jkcdarunday** [mullvad/mullvadvpn-app#2295]
## Issue report

Operating system: ArchLinux

App version: 2020.7

### Issue description

Starting 2020.7, all DNS resolutions now fail after connecting to a Mullvad server using the Mullvad linux app. I rolled back and confirmed that this does not occur on 2020.6.

I investigated and it seems that switching from `dns=dnsmasq` to `dns=systemd-resolved` in `/etc/NetworkManager/conf.d/dns.conf` resolves this and placing it back makes the issue occur again.

**Comment by pinkisemils** [comment]
This should be fixed as of #2296.
