### ISSUE TITLE
Launching app from split tunneling does not change ipv6

### ISSUE THREAD

**Issue by adityasubathu** [mullvad/mullvadvpn-app#2307]
## Issue report

Operating System: Manjaro Linux
KDE Plasma Version: 5.20.3
KDE Frameworks Version: 5.76.0
OS Type: 64-bit

App version: 2020.7

### Issue description

Launching an app from split tunneling changes the ipv4 address to the original one but ipv6 remains the same as mullvad's connected servers. I will attach a screenshot below:

![.](https://user-images.githubusercontent.com/16309657/100333958-2f307880-2ff9-11eb-80a5-77b5e8a989ac.png)

**Comment by dlon** [comment]
This issue has been fixed and will not be present in the next release.
