### ISSUE TITLE
Xbox live multiplayer - Strict NAT (blocked server connectivity) 

### ISSUE THREAD

**Issue by pocahontasholocaust** [mullvad/mullvadvpn-app#2313]
## Issue report

Operating system: Windows 

App version: 2020.7 

### Issue description

Teredo is qualified yet my NAT type is forced to strict from moderate - UPnP is recognised as being off and so
I can't connect to xbox live multiplayer. I'm unsure whether it's an issue with port forwarding and firewalls, microsoft, or
VPNs in general. Split tunneling in the future would fix this issue, but I'd like to know if it's possible to use VPN.
I apologise if this issue is trivial or otherwise irrelevant, I'm not knowledgeable in this stuff.

**Comment by faern** [comment]
Please contact support@mullvad.net for help with using the app.
