### ISSUE TITLE
Failed to set DNS

### ISSUE THREAD

**Issue by Stibax** [mullvad/mullvadvpn-app#2332]
## Issue report

Operating system: Manjaro

App version: 2020.7
### Issue description

hi, it's about ten days, maybe after some manjaro major updates, that when i start the os, the automatic connection work like espected. if i try to change the server (actualy i always use wireguard) it works everytime if i do in the first 5 minutes after boot, but if i try to change server later the mullvad app says "failed to set system dns server" and i have to reboot to make mullvad working again.

This is the output of journalctl of mullvad-daemon:

dic 04 19:04:28 stibax-manjaro mullvad-daemon[1171]: [talpid_core::dns][INFO] Setting DNS servers to 10.64.0.1
dic 04 19:04:28 stibax-manjaro mullvad-daemon[1171]: [talpid_core::dns::imp][DEBUG] Managing DNS via network manager
dic 04 19:04:43 stibax-manjaro mullvad-daemon[1171]: [talpid_core::tunnel_state_machine::connected_state][ERROR] Error: Failed to set DNS
dic 04 19:04:43 stibax-manjaro mullvad-daemon[1171]: Caused by: Error in NetworkManager DNS monitor
dic 04 19:04:43 stibax-manjaro mullvad-daemon[1171]: Caused by: Device inactive: 10

I have tried to return back to 2020.6 but the same problem came up, so i think it was a recent manjaro updates that broke something. 
Thanks

**Comment by Nuxio12** [comment]
Hi, 

I can confirm this problem. Although, for me I do not have to reboot the computer to make it work again. When the 'error' appears I press reconnect multiple times and after a few tries it connects properly again. I use OpenVPN and Bridge mode.

Cheers

OS: Manjaro
App version: 2020.7

**Comment by pinkisemils** [comment]
We don't officially support Manjaro, but I'll look into it.

**Comment by pinkisemils** [comment]
Have you enabled the network connectivity check in NetworkManager?

**Comment by Stibax** [comment]
> Have you enabled the network connectivity check in NetworkManager?

What you mean for connectifity check?
I have done some research and i think it's active. i have in cinnamon under privacy cheched the "connectivity check" and i have a file in /etc/NetworkManager/conf.d/20-connectivity.conf with the following line:
[connectivity]
uri=http://www.archlinux.org/check_network_status.txt.
You mean this?
thanks for your replay.

**Comment by pinkisemils** [comment]
And when our daemon is running and trying to connect, could you please run 
```bash
dbus-send --system \
  --dest=org.freedesktop.NetworkManager \
  --print-reply \
  /org/freedesktop/NetworkManager \
  org.freedesktop.DBus.Properties.Get \
   string:org.freedesktop.NetworkManager string:ConnectivityCheckEnabled
```
and post the output here? It might not be something you consciously have enabled, but it's a setting that might be enabled by default. Our daemon tries to disable it when connecting due to it potentially hanging NetworkManager due to our firewall rules blocking the connectivity check.

I can't seem to reproduce the issue. You may also try and enable more verbose logging for NetworkManager and post NetworkManager logs, as long as you feel comfortable doing so. You can get the logs via `journalctl -u NetworkManager`, but by default NM doesn't log too much, so you'll have to [enable](https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html#id-1.2.3.10) them via the config file. After you have enabled the extra logging, it'd be nice to see both our daemon logs and NetworkManager logs to correlate the issues with the device not being ready fast enough.

**Comment by Stibax** [comment]
Hi,
so this is the output:
method return time=1607381590.588334 sender=:1.3 -> destination=:1.1455 serial=3975 reply_serial=2
   variant       boolean true

For the verbose log, i have tryed to search how to change the verbosity and i end up to add to the Networkmanager.conf the following line:
[logging]
level=DEBUG
domains=ALL
 I'm a linux noob, so i don't know if it's the right way, so sorry if i've done wrong.
i have attached the logs of networkmanager and mullvad-daemon of the last boot till the time when the problem came up.
[mullvad-daemon.log](https://github.com/mullvad/mullvadvpn-app/files/5655712/mullvad-daemon.log)
[networkmanager.log](https://github.com/mullvad/mullvadvpn-app/files/5655713/networkmanager.log)
Thanks again for your help.
Have a nice day.

**Comment by dpanter** [comment]
I ran into similar problems today on Debian sid/KDE Plasma and spent some time wrestling with systemd-resolved. Maybe something in this story can help you guys.

Noticed I still had PIA installed from back when they were a reasonable option, uninstalled it and rebooted, bam - DNS issues when connecting with Mullvad.
Don't have resolvconf or openresolv installed. I did have dnsmasq-base installed, probably a fix from long ago when Steam had a meltdown and people couldn't download anything. Good times. Anyway...

Turns out networkmanager had written /etc/resolv.conf as a file, and I believe systemd wants that to symlink to /run/systemd/resolve/resolv.conf instead. This probably happened after PIA was removed.

So, long story slightly less long: uninstalled PIA from within their client, rebooted, purged dnsmasq-base, disabled/stopped systemd-resolved.service, symlinked as mentioned, enabled/started systemd-resolved.service, purged/reinstalled Mullvad app, connected with Mullvad wireguard on port 53, now have a new connection in networkmanager under WireGuard VPN called wg-mullvad - and DNS is working again. resolv.conf now correctly contains both my routers IP and the DNS IP provided by Mullvad.
Check status and Mullvad logs to make sure there are no errors about port conflicts, dns stubs etc.


Commands for reference. Copypasta with caution.
```
sudo apt purge dnsmasq* resolvconf* openresolv
<uninstall PIA & Mullvad>
<reboot>
sudo systemctl disable systemd-resolved.service
sudo systemctl stop systemd-resolved.service
sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
sudo systemctl enable systemd-resolved.service
sudo systemctl start systemd-resolved.service
sudo dpkg -i MullvadVPN-2020.7_amd64.deb
systemctl status systemd-resolved.service
```

Good luck. _I'm going to have angry dreams about systemd tonight._

**Comment by hovancik** [comment]
Not sure if same issue, but seen error with not being able to set DNS. App has connected then but there is no internet when VPN is on. Debian sid.

**Comment by pinkisemils** [comment]
@dpanter NetworkManager will write a plain file in `/etc/resolv.conf` if it detects that there is no file there already. This is OK, and our app should work in this case. If you have `systemd-resolved` running and working, it should still work, as NetworkManager should detect that and configure DNS via `systemd-resolved`. The logs above indicate that this is an issue with NetworkManager itself, it's spending too much time waiting for a device to become active. I can only speculate as to why it's not becoming active at this point in time.

@Stibax it seems like the network connectivity check is still enabled. This might be what's blocking the device from working. Does turning it off via
```bash
sudo dbus-send --system \
  --dest=org.freedesktop.NetworkManager \
  --print-reply \
  /org/freedesktop/NetworkManager \
  org.freedesktop.DBus.Properties.Set \
   string:org.freedesktop.NetworkManager string:ConnectivityCheckEnabled variant:bool:false
```
Subsequently, you might want to restart network manager via `systemctl restart NetworkManager` and try and reconnect again.

@hovancik, are you seeing the same log entries as the ones posted above? If not, it might be a completely different issue. It'd be great if you were to send a problem report via the app so we can inspect the logs.

Ultimately, if you are experiencing issues with NetworkManager, you can bypass it entirely and just have our daemon write the DNS config to `/etc/resolv.conf` directly. All you need to do is set an [environment variable](https://github.com/mullvad/mullvadvpn-app#environment-variables-controlling-the-execution) for the daemon via `systemctl edit mullvad-daemon` - 
```systemd
[Service]
Environment="TALPID_DNS_MODULE=static-file"
```

**Comment by pizzadude** [comment]
I have the same issue in Fedora 33 after a NetworkManager update from the updates-testing repos. Doing the above systemctl edit mullvad-daemon fixed the issue for now.

**Comment by pizzadude** [comment]
Also, if I disable connectivity checking by moving /usr/lib/NetworkManager/conf.d/20-connectivity-fedora.conf somewhere else, the wireguard interface is tun0. Without moving it, the wireguard interface is wg-mullvad, and NetworkManager is aware that it's connected to a VPN.

Disabling connectivity checking doesn't appear to fix the problems setting DNS though, and that environment variable still needs to be set.

**Comment by pinkisemils** [comment]
@pizzadude Would you mind providing some daemon logs for the issues you're having? You'd have to unset that environment variable and break it again for a connection or two. There were some issues with configuring DNS via NM in the 2020.7 release, but those should be addressed in an upcoming release.

**Comment by pizzadude** [comment]
In order to reproduce this issue again for the logs, I had to undo both changes, meaning, enabling NetworkManager connectivity check again, and unsetting the environment variable.

Here are some logs. Not sure if they are of any use.

mullvad-daemon:

```
[2020-12-09 08:04:02.548][talpid_core::dns][INFO] Setting DNS servers to 10.64.0.1
[2020-12-09 08:04:02.560][talpid_core::dns::imp][DEBUG] Managing DNS via network manager
[2020-12-09 08:04:02.586][mullvad_daemon][DEBUG] New tunnel state: Connected <censored>
[2020-12-09 08:04:02.594][mullvad_daemon::management_interface][DEBUG] get_current_location
[2020-12-09 08:04:02.633][mullvad_daemon][WARN] Unable to fetch GeoIP location: Error: Hyper error
Caused by: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
Caused by: dns error: failed to lookup address information: Temporary failure in name resolution
Caused by: failed to lookup address information: Temporary failure in name resolution
[2020-12-09 08:04:04.552][mullvad_daemon::management_interface][DEBUG] disconnect_tunnel
[2020-12-09 08:04:04.553][mullvad_daemon][DEBUG] Target state Secured => Unsecured
[2020-12-09 08:04:04.553][mullvad_daemon][WARN] Unable to send target state to the daemon command sender
[2020-12-09 08:04:04.553][talpid_core::dns][INFO] Resetting DNS
[2020-12-09 08:04:04.560][mullvad_daemon][DEBUG] New tunnel state: Disconnecting(Nothing)
[2020-12-09 08:04:04.561][talpid_core::routing::imp::imp][DEBUG] Clearing routes
[2020-12-09 08:04:04.578][talpid_core::tunnel_state_machine::connecting_state][DEBUG] Tunnel monitor exited with block reason: None
[2020-12-09 08:04:04.579][talpid_core::firewall][INFO] Resetting firewall policy
[2020-12-09 08:04:04.579][talpid_core::firewall::imp][DEBUG] Removing table and chain from netfilter
[2020-12-09 08:04:04.580][mullvad_daemon][DEBUG] New tunnel state: Disconnected
[2020-12-09 08:04:04.586][mullvad_daemon::management_interface][DEBUG] get_current_location
[2020-12-09 08:04:05.119][mullvad_daemon::geoip][DEBUG] Unable to fetch I   Pv6 GeoIP location: Hyper error
```

When connected to mullvad, DNS is not changed in resolv.conf

**Comment by hovancik** [comment]
> It should be worth noting that I didn't have these issues with this version of mullvad vpn app until after updating NetworkManager today in Fedora from the testing repo.

same for me, not sure what was updated but stopped working after updates

**Comment by dpanter** [comment]
Is it possible you guys updated to systemd 247? I did that on December 5th and didn't have any problems before that, although I can't say it was the cause of my DNS woes.

**Comment by pinkisemils** [comment]
It'd be a lot easier to figure out the issues where you _don't end up in the blocked state but DNS doesn't work_ by opening a new issue, and reporting specifically what OS are you using and which version of SystemD, NetworkManager and our client is being used.

**Comment by pizzadude** [comment]
Enable updates-testing repos in Fedora to get the latest updates.

systemd-246.7-2.fc33.x86_64
NetworkManager-1.26.6-1.fc33.x86_64
mullvad-vpn-2020.7.0-1.x86_64

**Comment by pizzadude** [comment]
Also, the people above using Debian were not using Debian testing, they were using Debian sid which is "unstable" not "testing".

**Comment by dpanter** [comment]
I upgraded network-manager from 1.27.91-2 to **1.28.0-1** on December 7. It's a definite possibility the problem appeared after that.

Debian users might like this little [bash script](https://gist.github.com/dpanter/49f04fc4dafcaa3be8f1725382aceb05) to quickly check dpkg logs.

**Comment by pinkisemils** [comment]
I don't keep my debian-unstable VM up to date, but I did upgrade my packages just now, and 2020.7 still works and is able to set DNS properly via NetworkManager version 1.28.0-1.

@pizzadude I could easily get this to fail via OpenVPN and the userspace WireGuard implementation, have you tried using WireGuard?

**Comment by dpanter** [comment]
Might be worth mentioning this Debian bug report for network-manager.
[#972688 - 1.27.91-1 blows away existing dns nameservers when VPN activates](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=972688)

**Comment by pinkisemils** [comment]
There also seems to be a related Fedora issue about [NetworkManager version 1.26.6](https://bodhi.fedoraproject.org/updates/FEDORA-2020-7851982ff6).

**Comment by pinkisemils** [comment]
@dpanter Please post comments about your specific issues in #2339.

**Comment by Stibax** [comment]
> @Stibax it seems like the network connectivity check is still enabled. This might be what's blocking the device from working. Does turning it off via
> 
> ```shell
> sudo dbus-send --system \
>   --dest=org.freedesktop.NetworkManager \
>   --print-reply \
>   /org/freedesktop/NetworkManager \
>   org.freedesktop.DBus.Properties.Set \
>    string:org.freedesktop.NetworkManager string:ConnectivityCheckEnabled variant:bool:false
> ```
> 
> Subsequently, you might want to restart network manager via `systemctl restart NetworkManager` and try and reconnect again.
> 
hi, sorry i have understand that i have to enable the connectivity check, so i only check if it was enable; my missunderstanding.
I've try to disable via your command but it prompt me the following:

dbus-send: Unknown type "bool"

So i cannot answer if it solve the problem.
thanks

**Comment by pinkisemils** [comment]
I do apologize, the correct type name is _boolean_, the following should definitely work:
```bash
sudo dbus-send --system \
  --dest=org.freedesktop.NetworkManager \
  --print-reply \
  /org/freedesktop/NetworkManager \
  org.freedesktop.DBus.Properties.Set \
   string:org.freedesktop.NetworkManager string:ConnectivityCheckEnabled variant:boolean:false
```

**Comment by Stibax** [comment]
> I do apologize, the correct type name is _boolean_, the following should definitely work:
> 
> ```shell
> sudo dbus-send --system \
>   --dest=org.freedesktop.NetworkManager \
>   --print-reply \
>   /org/freedesktop/NetworkManager \
>   org.freedesktop.DBus.Properties.Set \
>    string:org.freedesktop.NetworkManager string:ConnectivityCheckEnabled variant:boolean:false
> ```
Hi the above command works, and now if i pass the command to check if is enable or disable it output this:

method return time=1607624119.199282 sender=:1.4 -> destination=:1.1980 serial=9493 reply_serial=2
   variant       boolean false

So for what i understand now the connectivity check is disable.

Now with it disable, it seems that the problem was almost solved, i mean sometime mullvad app failed and give me dns error, but most of the time when i change server it works. Before when it started the error it cannot connect animore.
I post the logs of networkmanager and mullvad-daemon after the connectivity check was disable.
Thanks a lot for you support.
[networkmanager-noCC.log](https://github.com/mullvad/mullvadvpn-app/files/5674868/networkmanager-noCC.log)
[mullvad-daemon-noCC.log](https://github.com/mullvad/mullvadvpn-app/files/5674871/mullvad-daemon-noCC.log)

**Comment by Stibax** [comment]
Hi, me again. After i post the above replay, i tried to change the server again and the problem appeared again, now i cannot connect anymore whith the same dns error. The difference is that it happens later from the boot that before.
[mullvad-daemon-noCC.log](https://github.com/mullvad/mullvadvpn-app/files/5674932/mullvad-daemon-noCC.log)
[networkmanager-noCC.log](https://github.com/mullvad/mullvadvpn-app/files/5674933/networkmanager-noCC.log)

**Comment by pinkisemils** [comment]
I think the issue might still be the connectivity check. Would you mind testing the latest [beta](https://mullvad.net/en/download/linux/#beta)? Since you're on arch, you might have to download the binary beta [PKGBUILD](https://aur.archlinux.org/packages/mullvad-vpn-beta-bin/) and adjust it to unpack the new RPM (building from source might be a bit more involved, but if you want to, you can do that too).

**Comment by pizzadude** [comment]
Sorry to hijack the issue again, but the latest beta fixed my issue.

**Comment by djibux** [comment]
I am experiencing this issue on Debian Testing after upgrading `network-manager` to `1.28.0-1` (from `1.27.91-2`)
Upgrading Mullvad App to beta also fixed the issue. Thanks @pizzadude

**Comment by Stibax** [comment]
> I think the issue might still be the connectivity check. Would you mind testing the latest [beta](https://mullvad.net/en/download/linux/#beta)? Since you're on arch, you might have to download the binary beta [PKGBUILD](https://aur.archlinux.org/packages/mullvad-vpn-beta-bin/) and adjust it to unpack the new RPM (building from source might be a bit more involved, but if you want to, you can do that too).

Hi, so the latest beta 2020.8-beta2 resolve the problem, no more failed to set system dns. Thanks. I think we can close this issue.

**Comment by hovancik** [comment]
For me it kinda solves the issue: I still have to reconnect on mullvad app every time OS starts to connect to the internet.
