### ISSUE TITLE
Add setting for custom dns

### ISSUE THREAD

**Issue by HoboDev** [mullvad/mullvadvpn-app#2335]
## Issue report

Operating system: Linux 5.8.0-2parrot1-amd64

App version: 2020.7

### Issue description

Mullvad overrides /etc/resolv.conf so while using the VPN I have to manually add the local nameserver as first to resolve my VM names. It would be great, if there was an option to include an entry on connect.

**Comment by faern** [comment]
We are currently working on custom DNS. It will likely be part of the next release. Also, this is a duplicate of #473
