### ISSUE TITLE
DNS not being set in Fedora 33 with latest systemd and NetworkManager from updates-testing repos

### ISSUE THREAD

**Issue by pizzadude** [mullvad/mullvadvpn-app#2339]
This is a continuation of my issue in https://github.com/mullvad/mullvadvpn-app/issues/2332 .

I have stated the issue in that bug, which is that after updates to NetworkManager and systemd, in Fedora 33, from the updates-testing repos, the Mullvad VPN app fails to set DNS and it stays at the regular DNS servers which I have set via NetworkManager, resulting in no internet access while connected to the VPN.

/etc/resolv.conf is it's own file, not a symlink, managed by NetworkManager.

The versions of packages:

systemd-246.7-2.fc33.x86_64
NetworkManager-1.26.6-1.fc33.x86_64
mullvad-vpn-2020.7.0-1.x86_64

You need to enable updates-testing repos to get them currently.

```
cat /etc/yum.repos.d/fedora-updates-testing.repo
[updates-testing]
name=Fedora $releasever - $basearch - Test Updates
#baseurl=http://download.example/pub/fedora/linux/updates/testing/$releasever/Everything/$basearch/
metalink=https://mirrors.fedoraproject.org/metalink?repo=updates-testing-f$releasever&arch=$basearch
enabled=1
countme=1
repo_gpgcheck=0
type=rpm
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-$releasever-$basearch
skip_if_unavailable=False

```

change enabled=0 (default) to enabled=1 under [updates-testing].

Then do sudo dnf update --refresh to get these versions. Then reboot and try using Mullvad and notice it doesn't change the DNS server.

If you don't receive the latest version, wait a bit or use the VPN to change to a country where mirrors are more updated.

Also I use Fedora KDE if that matters.

**Comment by pizzadude** [comment]
Entering the following via "systemctl edit mullvad-daemon"
```
[Service]
Environment="TALPID_DNS_MODULE=static-file"
```
and restarting the mullvad-daemon works around the issue.

**Comment by pinkisemils** [comment]
I've reproduced this issue using the testing repos. Not really sure what's the underlying issue, but I'm still investigating.

**Comment by pinkisemils** [comment]
I don't keep my debian-unstable VM up to date, but I did upgrade my packages just now, and 2020.7 still works and is able to set DNS properly via NetworkManager version 1.28.0-1. But the daemon doesn't use NetworkManager to manage DNS there, because `/var/run/NetworkMnaager/resolv.conf` doesn't exist.

@pizzadude I could easily get this to fail via OpenVPN and the userspace WireGuard implementation, have you tried using WireGuard?

There also seems to be a related Fedora issue about [NetworkManager version 1.26.6](https://bodhi.fedoraproject.org/updates/FEDORA-2020-7851982ff6).

**Comment by pizzadude** [comment]
I have the wireguard kernel module loaded, so the mullvad app *should* be using it.

**Comment by pinkisemils** [comment]
It might not if you've set the environment [variable](https://github.com/mullvad/mullvadvpn-app#building-and-running-the-desktop-electron-gui-app) to force the use of the userspace implementation.

**Comment by pizzadude** [comment]
I did not set such a variable.

**Comment by pizzadude** [comment]
Seems to be fixed in latest beta.

**Comment by faern** [comment]
Glad to hear that! :tada:
Expect this version to go stable early next year sometime.

**Comment by SecT0uch** [comment]
Manjaro user here, 
This issue is still present with the last AUR package: "mullvad-vpn 2021.1-1".
But works fine with the beta. When can we expect the stable version to include the changes ?
