### ISSUE TITLE
No app icon in AndroidTV

### ISSUE THREAD

**Issue by Dartan** [mullvad/mullvadvpn-app#2348]
## Issue report

Operating system: AndroidTV on Nvidia Shield

App version: 2020.8-beta1

### Issue description

After installing the Mullvad app there isn't an app icon created. In order to run the app I have to go into settings and then all apps and start it from there.

Also, would it be possible to get AndroidTV listed as a valid device in the Play Store so it can be installed from there instead of having to side load it?

**Comment by kevinoconnor7** [comment]
According to #2196 it's supposed to be marked as supporting TV devices. @jvff is there still more work required or does something just need to be updated in the Google Play Console?

**Comment by axti** [comment]
Fixed in #2480 and #2515
