### ISSUE TITLE
[Linux] [Feature request] CLI split tunnel app launch

### ISSUE THREAD

**Issue by DevPre24** [mullvad/mullvadvpn-app#2351]
Other than having the option to launch an app with split tunneling from the GUI (Advanced options), it would be nice if it was possible to launch it from the linux cli, without having to retrieve the PID of the process.

Examples:
`mullvad split-tunnel cmd /usr/bin/chromium`
`mullvad split-tunnel cmd steam`

Why you might ask (Why don't you use the PID subcommand)? Well it would be more userfriendly (and fool proof) and would allow to create launch shortcuts (.desktop) easily. One might want to launch steam in a split tunnel for lower latency, or another browser for those sites that block VPNs by default, directly from their Desktop Environment app launchers.

**Comment by faern** [comment]
It already is possible. We ship the `mullvad-exclude` binary which is what the GUI uses to spawn excluded processes. Try `mullvad-exclude steam` for example.

**Comment by DevPre24** [comment]
> It already is possible. We ship the `mullvad-exclude` binary which is what the GUI uses to spawn excluded processes. Try `mullvad-exclude steam` for example.

Wonderful, thanks for the help and quick response, closing the issue.
