### ISSUE TITLE
"cannot install from unsigned repo"

### ISSUE THREAD

**Issue by HK53** [mullvad/mullvadvpn-app#2361]
Apologies for the newby question. I actually have a lot of experience in IT, but Linux (Ubuntu 20.4 KDE) is a new adventure.

I want to install 2020.8 beta 2 but I am getting the error ""cannot install from unsigned repo". Trying to figure this out I noticed only now that also the upgrade from 2020.6 to 2020.7 also was not successful.

When I open the download with Software Install after a brief moment I get a 'Remove' button and the info of the opened .deb. So I figured it was installed, but not...

When I open the dowload with Discover there is an Install button, I need to enter the system password and then the message "cannot install from unsigned repo" appears.

Any help would be greatly appreciated.

H

**Comment by faern** [comment]
Could you try installing via the terminal and see if that helps? Open up your terminal app and run:
```
$ sudo apt install ./Downloads/MullvadVPN-2020.8-beta2_amd64.deb
```
Or whatever the relative path to the downloaded deb file is for you.

**Comment by HK53** [comment]
Wonderful! That worked like a breeze.

**Comment by faern** [comment]
Glad to hear you got the software working. We might still have a bug with the graphical package manager there, we'll look into that. Thanks for reporting.
