### ISSUE TITLE
[Debian 10 XFCE 4.12] Icon not showing in alt-tab, tray and app bar

### ISSUE THREAD

**Issue by etiennebaque** [mullvad/mullvadvpn-app#2363]
## Issue report

Operating system: Linux Debian 10 Stable - Desktop environment: XFCE 4.12

App version: 2020.7 (and at least the 3 previous ones)

### Issue description

The Mullvad icon is not showing up in the tray, alt-tab switcher and in the application bar. Instead, a generic window icon is showing up.

For example, with Firefox, a terminal and the Mullvad client opened, I see the following:

- tray:

![Screenshot_2020-12-16_21-19-05](https://user-images.githubusercontent.com/1527188/102402372-f6c2ff80-3fe4-11eb-9efa-56b00964139a.png)

- alt-tab switcher:
![export](https://user-images.githubusercontent.com/1527188/102402474-165a2800-3fe5-11eb-9023-eed9b28c20b6.png)

- application bar (left corner):

![Screenshot_2020-12-16_21-19-41](https://user-images.githubusercontent.com/1527188/102402494-207c2680-3fe5-11eb-9d17-638ded25390d.png)

Is it a bug? or is there something that's not properly configured on my machine?

**Comment by raksooo** [comment]
Thanks for reporting! It's now been fixed and merged to master and will be included in 2020.9.

**Comment by etiennebaque** [comment]
> Thanks for reporting! It's now been fixed and merged to master and will be included in 2020.9.

Great! Thank you so much for quickly fixing this! :+1:
