### ISSUE TITLE
Re-introduce 'Quit App' button

### ISSUE THREAD

**Issue by remonator** [mullvad/mullvadvpn-app#2366]
## Issue report

Operating system: Android 8

App version: 2020.8-beta1

### Issue description

I suggest to re-introduce the "Quit App" button in the app's settings (see screenshot).
Closing the app by dismissing the notification is not working reliably (the notification keeps popping up sometimes immediately after), and it requires multiple manual steps (disconnect, dismiss, and maybe close the app from the app switcher) instead of a button that would combine all of them.

![image](https://user-images.githubusercontent.com/54318829/102595586-20307800-4118-11eb-869d-c29c98de31b8.png)

**Comment by faern** [comment]
We had numerous similar issues with the quit button. You were probably lucky you did not see those on your phone.

Yes the swiping of the notification does have bugs at the moment, but we are working on resolving them. That the new way has temporary bugs does not justify adding in the old way. We should focus on fixing the bugs.

**Comment by faern** [comment]
Not having the quit button seems to work really well for the vast majority. We have heard very few complaints about removing it. So I'm going to close this. If there are issues with not being able to swipe away the app then please report those specifically and we should of course fix them!
