### ISSUE TITLE
[Feature Request] - DNS tracker and ad blocking

### ISSUE THREAD

**Issue by mystic-githuber** [mullvad/mullvadvpn-app#2367]
DNS option that blocks ads, adware, malicious websites and data harvesting trackers.

**Comment by faern** [comment]
The latest beta has support for setting a custom DNS. So you can set it to a DNS that blocks the things you want blocked. It's currently limited to a DNS resolver on your LAN however. This limitation will be lifted in the future.

Mullvad does not host any ad blocking DNS resolver for you. At least not at the moment.

**Comment by mystic-githuber** [comment]
@faern 
This is good news. I'll close the issue.
