### ISSUE TITLE
(feature request) mullvad vpn ipad screen size support 

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#2386]
hi i have a feature request to add for the mullvad ios app is it possible to add ipad screen size support for the mullvad app its not ideal to use a iphone sized app for an ipad.

**Comment by faern** [comment]
It's on the roadmap to create an iPad design of the app. But it will be nicer integrated with the larger screen than just a scaled up version of the phone, which is why it takes a while.

**Comment by faern** [comment]
We added a special UI for the iPad in our latest release of the app. Please upgrade to 2021.2 and it should be there.
