### ISSUE TITLE
[Feature Request] Adblocking/Antitracking/Malware Protection DNS Feature For Android

### ISSUE THREAD

**Issue by Jpersh27** [mullvad/mullvadvpn-app#2392]
[Feature Request]
1.) When could we expect to see an Adblocking/Antitracking/Malware Protection DNS Feature for Mullvad on Android?

Similar other VPN services that offer this feature have it built into there applications or this feature is done at the DNS level on there own DNS servers when your connected to the VPN service on one of there vpn applications. 

Examples of other VPN Services with this feature include: 1.) Proton VPN- ''Net shield" 2.) Nord VPN- ''Cyber Sec'' 3.) Surf Shark- ''Clean Web'' 4.) Wind Scribe- "Robert'' or 5.) IVPN- ''Anti Tracker'' and many other VPN services are starting to follow suit and introduce similar related features to there applications.  

I am also aware of the similar closed issue #2367 and ''Faern" stated the following in that closed issue: 

"The latest beta has support for setting a custom DNS. So you can set it to a DNS that blocks the things you want blocked. It's currently limited to a DNS resolver on your LAN however. This limitation will be lifted in the future.

Mullvad does not host any ad blocking DNS resolver for you. At least not at the moment.''

I assume that the setting of a custom DNS is currently only limited to the latest beta build for windows for the application which was released on Dec 11th as 2020.8-beta-2.

2.) When could we expect this feature to come to the Android version of Mullvad?

**Comment by faern** [comment]
1. If you mean in the sense that it's built into the app and fully automated and hosted by us: Not sure. We want to create this, but it's not yet clear when. We have not really started, so don't expect 100% integrated automation in the near future.

2. Custom DNS on Android will come in the next release. I don't have any ETA, but it's probably not more than a few weeks away.

**Comment by Jpersh27** [comment]
Thank you for the reply and for the information. I will look out for the custom DNS feature in the coming weeks on Android.

I will close this issue for now.

**Comment by xelamade** [comment]
Could we get this on cross-platform rather than on *just* android too?

**Comment by faern** [comment]
Yes. Custom DNS is landing on all desktop apps in the coming release as well. My answer to (2) was just about when it will land on stable for Android.

**Comment by tommytran732** [comment]
Now that Mullvad has DOH servers with adblocking, maybe you could make adblocking available for the client? It would be great to have DNS blackholing for the entire device rather than just the browser.

**Comment by sith-on-mars** [comment]
> Yes. Custom DNS is landing on all desktop apps in the coming release as well. My answer to (2) was just about when it will land on stable for Android.

Any news on iOS? Seems iOS is really bar-bone functional-wise at this point.

**Comment by glomeg132** [comment]
I managed to use Mullvad with a secure DNS server on Mac OS and iOS. The DNS server uses ad blocking and was natively integrated into the system. Visit dnsforge.de and download the dnsforge-doh.mobileconfig (DoH) profile which can be installed on Mac OS and iOS. On Mac OS you can use Mullvad app without any changes. Just connect and check https://www.dnsleaktest.com. On iOS I use Wireguard app with deleted DNS-setting. It works perfect.
![Bildschirmfoto 2021-04-01 um 16 10 58](https://user-images.githubusercontent.com/42551964/113306926-df462300-9304-11eb-9671-eb55a7f431d0.png)

**Comment by dchakro** [comment]
@glomeg132 Could you share a step-by-step for the uninitiated ? I'm new to the mullvad family and this is a very important feature for me.

**Comment by faern** [comment]
Our desktop (beta) and stable iOS apps now have built in toggles for ad- and tracker- blocking. This has not yet landed on Android. But you can get the exact same result by just using our special in-tunnel DNS IPs that perform blocking of certain domains. Please see this blog post: https://mullvad.net/en/blog/2021/5/27/how-set-ad-blocking-our-app/

I'm closing this issue as it's now possible to use our ad-blocking resolvers. It will be even more convenient in the future when we have a simple toggle for it in the preferences.
