### ISSUE TITLE
Bypass Wine App

### ISSUE THREAD

**Issue by zefrs** [mullvad/mullvadvpn-app#2398]
Hey there,

I doubt that this would be possible, however thought i would ask...
With the Split Tunneling feature in the Linux app now, what are the chances we could open a wine app to bypass the tunnel?

Regards,
zefrs

**Comment by faern** [comment]
Have you tried excluding it from the tunnel with the bundled CLI tool for starting processes excluded from the tunnel? Try:
```
mullvad-exclude wine /path/to/application.exe
```

If that does not work. You can try starting it as normal and then excluding the already running PIDs with:
```
mullvad split-tunnel pid add <pid>
```

**Comment by zefrs** [comment]
Hi @faern, apologies, i did not even check the CLI commands...
I've tested these and the fist does not seem to work and the second disconnects me, which is not ideal but will work for now.

Out of curiosity, any ideas when the split tunneling feature will be available for MacOS?

**Comment by pinkisemils** [comment]
> I've tested these and the fist does not seem to work and the second disconnects me
Could you elaborate on this? If the second command causes the tunnel to be disconnected, it's a rather serious bug and we'd appreciate if you sent us a problem report.

**Comment by zefrs** [comment]
@pinkisemils, i should have mentioned, i'm bypassing a game, when i run the command it disconnects me from the game which is understandable and no issue with Mullvad.

**Comment by pinkisemils** [comment]
Are you trying to host a game server by any chance? That currently isn't supported by the app. 

As for MacOS, currently there is no timeline for that.

**Comment by kajlando** [comment]
For "mullvad split-tunnel pid" subcommand "list" works but how I can see apps that I added to mullvad-exclude?

**Comment by faern** [comment]
Processes split by starting them with `mullvad-exclude <command>` should show up in `mullvad split-tunnel pid list`. They do when I test it here.

**Comment by kajlando** [comment]
Is there any way to split an app permanently? This command does it only temporarily.
