### ISSUE TITLE
(manual config) how to direct my own wireguard connection to mullvad?

### ISSUE THREAD

**Issue by thematrixdev** [mullvad/mullvadvpn-app#2416]
(I am sorry if here may not be the suitable place to ask.)

I have been running my own Wireguard-VPN and AdGuard-DNS on Vultr. Recently I want to add some more anonymous by routing the connection exiting from Mullvad, and using my own DNS at the same time.

i.e.
[[[My-PC]]] ------(Wireguard)------> [[[Vultr (Wireguard, AdGuard)]]] -----(Wireguard)------> [[[Mullvad]]]

Beside my own Wireguard, I have created a Wireguard client with the configuration generated here:
https://mullvad.net/en/account/#/wireguard-config/

May I know what should be set in iptables so as to route the connection from my Wireguard subnet (e.g. 10.0.0.0/24) to Mullvad's?

Thanks.

**Comment by faern** [comment]
Please direct any service usage questions to support@mullvad.net, thank you.
