### ISSUE TITLE
[Feature request] Allow split tunneling per IP address, not just program. 

### ISSUE THREAD

**Issue by diademiemi** [mullvad/mullvadvpn-app#2420]
I have two LANs at home (192.168.1.0/24 and 192.168.2.0/24) and I have a DNS running on 192.168.2.250, however if I try to connect to this (or any services from it) it doesn't work from the 192.168.1.0/24 LAN. 
A feature which allows the user to define subnets which can bypass the VPN would fix this issue for me and provide new functionality too.
On Linux, it's already very easy to do so, in my case it was just `ip route add 192.168.1.0/24 dev enp9s0 via 192.168.2.254`. If Mullvad could have a graphical utility or at least a way to automatically run such a script if it connects would be great. 
I'm not sure about Windows or Android support.

**Comment by pinkisemils** [comment]
We kind-of already support this - just don't remove your route for the subnets and it should _just work_, if you enable LAN traffic. If you make your DHCP server publish the routes you need, the config will work automatically on all of your devices. In the short term, we don't plan on implementing specific features for this kind of a use case, but we may allow splitting traffic by IP or either a hostname in the future.

**Comment by kajlando** [comment]
Please consider supporting also IP split tunneling
