### ISSUE TITLE
Feature request: add OpenVPN over Shadowsocks to iOS client

### ISSUE THREAD

**Issue by xelamade** [mullvad/mullvadvpn-app#2426]

**Comment by faern** [comment]
We are not planning on adding OpenVPN to the mobile apps at all. It's not good for battery life or roaming. WireGuard is much better suited for a mobile use case. Yes, we do know WireGuard over Shadowsocks does not currently work. So it might not be ideal for some censorship circumvention. But we'd rather work on that than adding OpenVPN support. We track WireGuard over Shadowsocks in #1049, so I'm going to close this issue. Thanks for your interest in the app.
