### ISSUE TITLE
[Android Feature Request]- Ability to Choose which default UDP Port Wireguard Uses.

### ISSUE THREAD

**Issue by Jpersh27** [mullvad/mullvadvpn-app#2430]
@faern Sorry I wasn't more specific in the title in my previous issue that I opened in the repository. However, I did close the previous one and opened another one with the correct title.

1.) Now is there any plans to add this feature into the Android version of Mullvad?

• I currently only use Mullvad on my Android devices. I ran into connection issues specifically on open public WiFi networks when using the Mullvad Android App.

• However, I don't have any issues with the application on my home internet.

Thanks again and looking forward to your reply.

**Comment by faern** [comment]
Are you sure selecting specific ports will help? They might treat port 53 differently to make DNS work. But if they are blocking UDP on that network I doubt selecting ports will help (except port 53)

Yes. We want to implement port selection on mobile as well. But we might limit it to Automatic or 53 as on desktop unless there is some good indications some other specific port help unblock people.

**Comment by Jpersh27** [comment]
@faern Thanks for the reply again and I do think the ability to tunnel over a different UDP port would especially help on strict public WiFi or Home WiFi provided by a strict ISP.

1.) Any ETA on when we can expect the custom DNS on Android?

2.) Any ETA on when port selection might come to Android Devices? This year at some point? 

3.) If you do indeed go through with limiting port selection what default port would Wireguard use? (Using the Automatic option)

• I do think providing a few alternative port options would help especially with some common ones being blocked by ISP in the USA. I Listed a example of 2 Huge ISPs in the USA “Xfinity" by (Comcast) and “Spectrum" by (Charter) that restricts/blocks the use of certain ports.

• https://www.xfinity.com/support/articles/list-of-blocked-ports

https://www.spectrum.net/support/internet/blocked-ports/

**Comment by faern** [comment]
1) It's already in our `master` branch. It will come in the next release.

2) Should be easy to implement, but we have not started. Expect it in one to two releases.

3) Both your links show very few UDP ports as blocked. Currently our app selects randomly in a very large range. So if the only ports that are blocked for you are the ones listed there the app should already work. I suspect it's not the ISP but the public wifi provider that has simply blocked all of UDP. Some types of attacks come from UDP, so some public internet access places just block the entire protocol as a way to bluntly deal with these type of attacks.

We will likely allow users to specifically choose port 53 (same as DNS, often not blocked for that reason) and 51820 (WireGuards default port, so makes sense to be able to use it).

**Comment by Jpersh27** [comment]
@faern Thanks again for the reply.

1.) Any news on when the release date is? 

2.) Any Idea of what Third party DNS services would work with Mullvad? Any internal testing been done or recommendations?

(Popular DNS Services Include: AdGuard, and Next DNS)

• Yes it is indeed the Public WIFI providers after further testing. However not all UDP traffic is blocking on some of the public WiFi networks I use frequently. 

3.) Other than the Two UDP ports 53 and 51820 is there any plans to implement support for other ones? Or ones that are being considered?

**Comment by Jpersh27** [comment]
• @faern I was just wondering if you have had a moment to look over my most recent comment and answer the 3 questions I posted a few days ago?

• Thank you and I hope too hear back from you soon.

**Comment by faern** [comment]
We don't have ETAs for our software. The next Android release is anything between a week and a few months away.

Initially custom DNS will only work with **local** resolvers. You can't use it with any public IPs, such as `1.1.1.1` or anything. And that's not an app limitation. That's because our servers hijack all DNS requests in order to prevent leaks. In the future this won't happen for app tunnels, so apps can send out DNS to any resolver they want.

We currently have no plan on adding anything but `53` and `51820`. But that's because we don't have any proof there are networks where they won't work where other ports will work. If you have a specific port and you know it will work where those two ports won't then please post that port and we can consider it.

**Comment by mkeedlinger** [comment]
Hi! This would also be very helpful for me. For some reason when I use the app I've noticed that when I switch from wifi to 4g the VPN seems to be blocked, but this is resolved if I download a config that uses port 53 for the wireguard app.

**Comment by macman31** [comment]
This was a really frustrating experience for me when we were in a company offsite in a hotel: the port UDP 51820 was blocked and traffic on port UDP 53 was intercepted by the network of the hotel to handle redirection to the captive portal of the hotel.

However with a bit of trial and error I found out that the port UDP 5060 (SIP) was open on the hotel network, and usable on Mullvad servers : I am technical enough that it was just an annoyance for me to have to setup a custom WireGuard config on my laptop/mobile phone to use this port, however what was really frustrating was that I had to setup a custom WireGuard config for each non-technical people in the group with their own Mullvad account, both on mobile phone and on their computer, and teach them how to run this specific config as they were only used to the Mullvad app.

I am not asking for the specific port UDP 5060 to be added to the list of port options in the Mullvad app: maybe at another hotel this port would be closed, but maybe another port would be open, for example UDP port 5349 for STUN/TURN, UDP port 10000 for VoIP applications/video bridges, or UDP port 19295 for Google Talk, etc.
 
A great thing is that Mullvad servers accept WireGuard connections on ports 53, 4000-33433, 33565-51820 and 52000-60000 (which was an information surprisingly hard to find, I had to look up the javascript validation code for the "Custom port" field of the "WireGuard configuration file generator" page to find this info).

So it would be great to have the option to pick any of those ports, in both the desktop and in the mobile app (where it is currently impossible to chose a specific port): this would make it way easier to get VPN Connectivity (especially for non-technical people) when we find an open UDP port on a filtered network that is also in the range of what is accepted by Mullvad servers.

**Comment by mkeedlinger** [comment]
> Mullvad servers accept WireGuard connections on ports 53, 4000-33433, 33565-51820 and 52000-60000

Good to know!

> UDP 5060 ... UDP port 5349 for STUN/TURN, UDP port 10000 for VoIP applications/video bridges, or UDP port 19295 for Google Talk

Also helpful, I'll give those a shot and see if I get an improvement. Using port 53 has still felt sluggish compared to without the VPN.

**Comment by faern** [comment]
> A great thing is that Mullvad servers accept WireGuard connections on ports 53, 4000-33433, 33565-51820 and 52000-60000 (which was an information surprisingly hard to find

I forwarded this feedback to the website team. Maybe they can add it to the server list at https://mullvad.net/servers.

> So it would be great to have the option to pick any of those ports, in both the desktop and in the mobile app

It's in the backlog to add the options `Auto`, `53` and `51820` on Android. But with this new problem presented it would make sense to allow any port, and not just those three.

On desktop you can set the WireGuard port to anything with the CLI. Run this command:

```
mullvad relay set tunnel wireguard --protocol udp --port 5060
```

Please mind that the command is likely going to change very soon when we rework the `--protocol` part. But it works on the current release.

**Comment by macman31** [comment]
> I forwarded this feedback to the website team. Maybe they can add it to the server list at https://mullvad.net/servers.

I think it's best if it appears somewhere in the WireGuard FAQ: https://mullvad.net/en/help/tag/wireguard/

> It's in the backlog to add the options Auto, 53 and 51820 on Android. But with this new problem presented it would make sense to allow any port, and not just those three.

Nice! And yeah I think this feature should be made simple enough for people to use, so I also think that it would be nice to be able to choose any supported port through the Mullvad desktop app (and iOS?) in addition to the Android app.
Thanks for acknowledging the issue. I'm looking forward to this feature!

**Comment by Rawa** [comment]
This has already been released, closing
