### ISSUE TITLE
Windows reinstall failure: Installation Aborted

### ISSUE THREAD

**Issue by cyberswat** [mullvad/mullvadvpn-app#2441]
This was previously reported in https://github.com/mullvad/mullvadvpn-app/issues/1937 but was closed without providing helpful information.

## Issue report

Operating system: 

Edition	Windows 10 Pro
Version	20H2
Installed on	‎7/‎11/‎2020
OS build	19042.746
Experience	Windows Feature Experience Pack 120.2212.551.0

App version: 
I think the installed version is 2020.7.0

### Issue description

I can not use the app anymore. It shows a "connecting to mullvad services" screen when launching that does not go away. Attempting to uninstall it with windows to install a new version produces a windows error that it can not find the `Uninstall Mullvad VPN.exe` file. Navigating to the path shown by windows displays the uninstall executable but launching it states the file is corrupted and unreadable.

Attempted reinstalls with both `MullvadVPN-2020.7` and `MullvadVPN-2021.1-beta2` but both stop progressing early in the installation with an "Installation Aborted - Setup was not completed successfully." message.

Attempting to access the install.log file in C:\ProgramData\Mullvad VPN shows that it has not been modified in about two weeks and the file is recognized as a binary. The other log files are text files and are readable.

I'm using the Microsoft Defender Antivrus and Firewall, but have not received any notifications that they are blocking the app.

**Comment by faern** [comment]
The reinstalls are probably failing because it tries to run the uninstaller for the existing version and that is corrupt? Sounds to me like either some anti virus is trying to be smart and screw stuff up, or the uninstaller is actually corrupted on disk.

But as with any usage problems, first and foremost contact our support. They can probably help you way better than we can here: support@mullvad.net

**Comment by cyberswat** [comment]
Sounds reasonable. I switched to wireguard running mullvad tunnels in the meantime. Thanks for the redirect to support.
