### ISSUE TITLE
2021.2 Windows Detects Trojan.GenAsa!PU7UbAzIEaI on Yandex

### ISSUE THREAD

**Issue by graintiger** [mullvad/mullvadvpn-app#2502]
Running the 2021.2 installer through Virus Total suggests Trojan.GenAsa!PU7UbAzIEaI present accordining to Yandex. No other detections.

As per https://www.virustotal.com/gui/file/a96483eecbc58da8a8dc696946300a5d6c4e8fe05f4d38ea264b41db711a77dc/detection

Checking 2021.2-beta1 the same detection is present: https://www.virustotal.com/gui/file/a59646058f57f21c012b8c52e2728f3a904d9fbde17135ca39cc0df37ffa9515/detection

Same detection also present for 2021.1: https://www.virustotal.com/gui/file/bed42a7cb009ebd027194f20940b2b9856037a0e581a9bdfaf9b325b8d2f6af3/detection

Is this a false positive? Can it safely be ignored in regard to installation of the application?

**Comment by faern** [comment]
There are almost always false positives in anti virus engines when we release new versions. It takes a little while after release until they start "accepting" our binaries. Going through virustotal with only one false positive is a *good result* ;)

If you want to be completely sure no one has tampered with the version of our installer that you have I would highly recommend that you verify it with GnuPG: https://mullvad.net/en/help/verifying-signatures/.

And also: Always download our app directly from our own website, mullvad.net, or from the release tags here on github.

**Comment by faern** [comment]
I'm going to close this since I'm pretty sure this is not a problem with the app.
