### ISSUE TITLE
Allow Local Network Sharing Without Leaking DNS?

### ISSUE THREAD

**Issue by graintiger** [mullvad/mullvadvpn-app#2506]
Is it possible?

For example running the VPN on a host Windows PC - but allow RDP connections from the local network (192.168.1.x) to said system but without leaking DNS externally outside of the home network?

**Comment by faern** [comment]
Yes. That is the default/the only way. Even when you allow local network sharing DNS is always forced to go out via the VPN tunnel.

**Comment by faern** [comment]
I'm going to close this as I don't think it's an issue with the app, nor a feature request as it already works like this. Please re-open if I have misunderstood.
