### ISSUE TITLE
Feature Request: Connect on System Boot

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#2536]
Hello, I would like to request a cool feature that will make Mullvad VPN more awesome.

There's a feature in VyprVPN called "Connect on System Boot" on the Startup Options of their app.
![image](https://user-images.githubusercontent.com/66582769/110111018-9d4fbd00-7dea-11eb-962c-b694a39413ea.png)

Based on experience, it's really effective in tandem with kill switch wherein during login process on Windows. The VPN is already connected before their VPN application opens.

Thus, the user doesn't really have to worry about applications not loading properly due to internet connection anymore if the kill switch is enabled and the VPN is trying to connect during boot up process.

**Comment by faern** [comment]
We already support this. Enable both "Launch app on start-up" **and** "Auto-connect** in the preferences. Then the system service (`mullvad-daemon`) will activate the secured state directly when it's started (early on boot) and keep the network blocked until it can establish a tunnel.  We have just not exposed any setting that directly say this. But it's implied that wanting to launch on startup and wanting to connect on launch equals blocking + connecting asap on boot (before login)

**Comment by 8227846265** [comment]
Oh, I didn't know this but glad to hear that it's already available. :)
