### ISSUE TITLE
Does Mullvad has anything like it ?

### ISSUE THREAD

**Issue by CruiseMan** [mullvad/mullvadvpn-app#2542]
I'm very concern about this https://twitter.com/ivRodriguezCA/status/1367879728821047301 and want to ask if Mullvad does anything that could compromise my security ?

**Comment by faern** [comment]
I looked through that Twitter thread, and we don't do anything like that. At all. We don't use any homegrown crypto, old weak ciphers or hardcoded short passwords for anything. We spend considerable time staying up to date with latest best practices and we never compromise in any area when it comes to the security of our users and our infrastructure.

But this repository is only about the app itself really. If you are concerned or want a better answer, I suggest you contact support@mullvad.net
