### ISSUE TITLE
Windows audio stops working when Mullvad is connected

### ISSUE THREAD

**Issue by 1player** [mullvad/mullvadvpn-app#2564]
## Issue report

Operating system: Windows 10 20H2

App version: 2021.2

### Issue description

PC audio stops working when Mullvad is connected

### Steps to reproduce

1. Check local audio is working with VLC, in-browser with YouTube and using Windows control panel.
2. Connect to any Mullvad endpoint
3. Notice audio is now mute. YouTube plays, volume is unchanged, no audio.
4. Disconnect from Mullvad servers
5. Audio is works again.

FWIW, I haven't had any issue last time I used the app 6 months ago, and my on-board audio is a Realtek chip using its latest drivers (released some time in 2021)

**Comment by mvd-ows** [comment]
What kind of speakers are you using, how are they connected?

**Comment by 1player** [comment]
Wired.

I managed to fix it by trying 3 different versions of Realtek drivers until this didn't happen again. Still I do not know how a VPN app can affect the audio subsystem.
