### ISSUE TITLE
Mullvad operate only with custom dns option

### ISSUE THREAD

**Issue by Stibax** [mullvad/mullvadvpn-app#2570]
## Issue report

Operating system: Manjaro 5.4.101-1-MANJARO

App version: 2021.1

### Issue description

Hi, the mullvad tunnel works only if i put my custom dns, if i untoggle the dns the connection stop.
The custom dns i use is the ip adress of my pfsense proxmox vm in my small server and it uses dns over tls configured in the dns resolver. i attach the log of mullvad daemon and networkmanager.
[Thanks]
[networkmanager.log](https://github.com/mullvad/mullvadvpn-app/files/6136401/networkmanager.log)
[mullvad-daemon.log](https://github.com/mullvad/mullvadvpn-app/files/6136402/mullvad-daemon.log)

**Comment by pinkisemils** [comment]
If NetworkManager is managing DNS via writing to `/etc/resolv.conf` directly, then it will fail to manage DNS. Please use `systemd-resolved`. The daemon should work around this issue in a 2021.2.

**Comment by Stibax** [comment]
I'm sorry i have made a mistake! I'm using already 2021.2, so the logs are taken from that version! So the problem for me it's still present! Thanks.

**Comment by Stibax** [comment]
So i've resolve the problem. I'm a linux noob but i try to learn. So your comment about system-resolved lead me to the arch wiki page and  i've followed the istruction about enable the service and make a simlink like this ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf, and now the mullvad daemon are able to set the mullvad dns so the tunnel works like espected without provide a custom dns. Thanks for point me to the right direction.
