### ISSUE TITLE
Updates on Android 2021.1 Update And Mullvad Custom DNS Servers-

### ISSUE THREAD

**Issue by Jpersh27** [mullvad/mullvadvpn-app#2611]
• Hello @faern you explained to me about 3 and a half weeks ago In Issue #2507 that there was no new updates on when a new update would come out for Android devices. 

• You explained to me that there was a additional Android Developer added to the Android team and it now consist of both @jvff and @axti. You also explained they are working on numerous things to improve the Android application.

• The Four Major things are listed below:

• Finishing the refactoring process (Splitting the app into more processes) 

• Making the split tunneling view a lot nicer

• Get rid of some memory leaks

• Custom DNS

• I have a few questions for you @faern or either one of the Android Developers @jvff or @axti If they have time to respond to the 4 questions I listed below please and thank you.

1.) Any progress made on the above Android application Improvements and will we see an Android 2021.1 update in the near future? 

(The Android application is now the most outdated and is now the only version that was last updated in 2020. I also saw on your Websites blog that version 2021.1 was released on IOS on March, 16th 2021. I provided a screenshot here down below of the IOS version history)

![IMG_20210323_231732.jpg](https://user-images.githubusercontent.com/77606699/112249341-f8c4dc00-8c2d-11eb-8ab0-3b76a8cb6a0f.jpg)

2.) Will I be able to select and use either one of the new Mullvad Public Encrypted DNS Services as a Custom DNS server in the new Android application update when available?

(adblock.doh.mullvad.net or doh.mullvad.net)

3.) What Ads does the basic Adblocking DNS Service block by default? What Ad block list or Host File list do you use to block Ads? Any plans to expand your DNS Blocking capabilities and allow Custom block list similar to the NextDNS service?

•https://nextdns.io/

![IMG_20210323_234536.jpg](https://user-images.githubusercontent.com/77606699/112251558-e3ea4780-8c31-11eb-87e4-064746eee4ec.jpg)

4.) Lastly are there any plans to make it Mandatory or force the application to Automatically rotate Wireguard Keys every 1 too 7 days on Android Devices? 
(Currently there is no limit and I believe 7 days should be the maximum time frame for a key to last before it expires and a new one is issued)

• Thank you and have a nice rest of your day today and thank you again for your time and consideration.

**Comment by faern** [comment]
> 1.) Any progress made on the above Android application Improvements and will we see an Android 2021.1 update in the near future?

As I said, no ETAs. But yes, we are closing in on a release. Basically just waiting for translations to be done now.

> 2.) Will I be able to select and use either one of the new Mullvad Public Encrypted DNS Services as a Custom DNS server in the new Android application update when available?

Nope. Not inside the app. The app does not know about/care for/support the new beta encrypted DNS from Mullvad at all. But encrypted DNS is an Android system setting that our app can't even control. So you can use it *outside* of our app just fine. You can already today use it with Android, with or without our app. Check out our guide: https://mullvad.net/en/help/dns-over-https-and-dns-over-tls/

> 3.) What Ads does the basic Adblocking DNS Service block by default? What Ad block list or Host File list do you use to block Ads? Any plans to expand your DNS Blocking capabilities and allow Custom block list similar to the NextDNS service?

Please ask support@mullvad.net. This question is not app related.

> 4.) Lastly are there any plans to make it Mandatory or force the application to Automatically rotate Wireguard Keys every 1 too 7 days on Android Devices?

The app is already rotating the key every 7 days. You can't disable this, so it's already mandatory. The next release will have this shortened to 4 days.
