### ISSUE TITLE
Add support for adaptive icons on Android

### ISSUE THREAD

**Issue by JacobDB** [mullvad/mullvadvpn-app#2617]
## Issue report

Operating system: Android 11

App version: 2020.8-beta1

### Issue description

Since 8.0, Android has supported "adaptive icons." This means that the user can choose the shape of all of their icons on their home screen. It's taken years, but most apps (at least, most that I have installed) have now been updated to support this new system. Unfortunately, Mullvad still has not updated after almost 4 years. I would greatly appreciate it if a future update would contain support for this feature. It's very quick to implement, and could probably be done within an hour for someone who knows what they're doing (I don't have much experience with app development, otherwise I'd make a pull request).

- Demonstration: https://imgur.com/a/p3DqBCi
- Documentation: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by faern** [comment]
Cool feature. We'll see what we can do about it. Thanks.

**Comment by axti** [comment]
Fixed in #2643 . Please wait next Android release.
