### ISSUE TITLE
[Feature Request] Apple Silicon M1 Native version for macOS

### ISSUE THREAD

**Issue by lgrthm** [mullvad/mullvadvpn-app#2625]
Since the current version is running on the Rosetta translation layer, it would be great to get a native version as Apple moves further towards all in-house chips.

**Comment by raksooo** [comment]
This is currently being worked on and will hopefully be finished pretty soon.

**Comment by lgrthm** [comment]
> This is currently being worked on and will hopefully be finished pretty soon.

Great to hear, looking forward to it.

**Comment by yuiOpS** [comment]
> This is currently being worked on and will hopefully be finished pretty soon.

Does this also mean that we'll finally get a Linux ARM64 release?

**Comment by faern** [comment]
This will reduce some blockers for looking looking into arm64 on Linux yes. I can't give any promises as to wether or not we will be making official releases or not. But hopefully we can significantly lower the barrier for building it from source for arm64 at least.

**Comment by simonsaysthis** [comment]
> This is currently being worked on and will hopefully be finished pretty soon.

Hello. Wanted to ask if this is already finished? Will this be a special installer or just released as an app upgrade?

**Comment by faern** [comment]
We will release a single pkg file that is a universal installer. So you should be able to upgrade how you usually upgrade and just get the native support with the next release.

**Comment by simonsaysthis** [comment]
> We will release a single pkg file that is a universal installer. So you should be able to upgrade how you usually upgrade and just get the native support with the next release.

Thank you very much. Looking forward to it

**Comment by faern** [comment]
Our latest beta release is a universal installer with native Apple Silicon (M1) support. https://github.com/mullvad/mullvadvpn-app/releases/tag/2021.4-beta1.
