### ISSUE TITLE
OpenVpn support & Custom DNS

### ISSUE THREAD

**Issue by vahidx4r4x** [mullvad/mullvadvpn-app#2626]
## Issue report

Operating system:  android 8

App version:  2020.8-beta1

### Issue description

Hi
Please add support for OpenVpn on Android(WireGuard is not working in our country) and add option to change the DNS.

**Comment by faern** [comment]
Hi. We are not planning on adding OpenVPN support to mobile platforms. But we are planning on adding bridge/obfuscation support. So hopefully that should allow you to use WireGuard in the future.

Custom DNS is also coming really really soon! But there is a separate issue for that. So I'm closing this.
