### ISSUE TITLE
[Feature Requests] (Linux) Better GUI support for split tunneling and other.

### ISSUE THREAD

**Issue by kajlando** [mullvad/mullvadvpn-app#2676]
[2021.3-beta1]
By better I mean adding:
"mullvad split-tunnel pid" as well as "mullvad-exclude x" or "mullvad-exclude wine x" to GUI (and a list to check which apps has been added)
Also, it would be great if there was a switch to turn on or off split tunnelng for certain apps because current GUI option is time consuming.
An option to exlude IP in GUI as as well in the terminal (mullvad split-tunnel ip) but it was already submited.

(other) Fast connect (fastest connection), random connect (random connection), resizing GUI size (or/and scaling: 125%,150% etc.), profiles (saving options: countries, protocols), pinning various settings to system tray (maybe also to GUI app main page) like split tunneling to open it quickly from the tray (or GUI app).
Thanks for your product, it's awesome.

**Comment by faern** [comment]
Thanks for your feedback. But there are numerous other open issues on split tunneling. Let's keep split tunneling discussion to those. And it's not constructive to shotgun approach having very many feature requests in a single issue. So I'm going to close this.

Why we can't/won't provide a fastest connection type of server selection has been explained in detail in other threads. See https://github.com/mullvad/mullvadvpn-app/issues/1542

For random server, see #1542

We are working on a feature to allow custom server lists. This will solve some parts of what you ask for.

**Comment by kajlando** [comment]
Thanks for your reply.

**Comment by faern** [comment]
Please don't spam every thread touching a subject you want to tell us something about. It's already unfortunate that there are so many threads regarding split tunneling. The situation does not get better by repeating the same thing in all of them. Thank you.
