### ISSUE TITLE
Use iputils-ping then fallback to ping

### ISSUE THREAD

**Issue by tarkah** [mullvad/mullvadvpn-app#2686]
## Issue report

Operating system: Linux, Solus OS
App version: 2021.3_beta1, built from source

### Issue description

The ping command used here assumes that option `-I` is available:

https://github.com/mullvad/mullvadvpn-app/blob/2d51a1a84f7ca914e6d157df0e2129af569b086f/talpid-core/src/ping_monitor/unix.rs#L90-L91

https://github.com/mullvad/mullvadvpn-app/blob/2d51a1a84f7ca914e6d157df0e2129af569b086f/talpid-core/src/ping_monitor/unix.rs#L105

This fails with the shipped version of ping `ping (GNU inetutils) 1.9.4` for my distro, but works if `iputils` / `iputils-ping` is installed. On my distro, it gets installed as `iputils-ping` and not `ping`. It'd be great if the existence of `iputils-ping` can be checked and used, otherwise fallback to `ping`, for wider support across distros.

Packaging w/ the following patch fixed things on my distro:

```diff
diff --git a/talpid-core/src/ping_monitor/unix.rs b/talpid-core/src/ping_monitor/unix.rs
index 4207f0db0..668da97a3 100644
--- a/talpid-core/src/ping_monitor/unix.rs
+++ b/talpid-core/src/ping_monitor/unix.rs
@@ -102,7 +102,7 @@ fn ping_cmd(ip: Ipv4Addr, timeout_secs: u16, interface: &str) -> duct::Expressio
     let ip = ip.to_string();
     args.push(&ip);
 
-    duct::cmd("ping", args)
+    duct::cmd("iputils-ping", args)
         .stdin_null()
         .stdout_null()
         .unchecked()
```

**Comment by pinkisemils** [comment]
At a risk of exposing a way to run arbitrary binaries as root (but this could be improved by explicitly dropping privileges before running `ping`), the daemon could use an environment variable to get the path to a suitable `ping` binary, falling back to just `ping`.

**Comment by pinkisemils** [comment]
After some further discussion, we'll see if we can just shed the dependency on `ping` entirely, and just send the traffic from the daemon directly.

**Comment by tarkah** [comment]
@pinkisemils Thanks for the response. Feel free to close this if you'd like, unless you'd like to track this against the eventual dropping of `ping` as a dependency.

In the meantime, I'll just continue to use the patch from above within our packaging and all is well.
