### ISSUE TITLE
Mullvad UI is blank since 2021.2 on Ubuntu

### ISSUE THREAD

**Issue by Strandbummler** [mullvad/mullvadvpn-app#2713]
## Issue report

Operating system: Ubuntu 20.04.2 LTS (running in a VM)

App version: 2021.2 and 2021.3

### Issue description

After installing the most recent version the app UI is blank/white and i can't interact with it. As soon as i reinstall 2020.7 everything is back to normal.

![mullvad-vpn-ui-error](https://user-images.githubusercontent.com/1776019/116751273-1262fb80-aa04-11eb-83ea-0c478953988f.png)

**Comment by raksooo** [comment]
Could you try starting the app by running
```
/opt/Mullvad\ VPN/mullvad-vpn --disable-gpu
```
and let me know if this makes the app display properly.

**Comment by Strandbummler** [comment]
That worked!

**Comment by raksooo** [comment]
Awesome!
