### ISSUE TITLE
[Android Feature Request] Allow users to use Public DNS Servers while using the Custom DNS server feature

### ISSUE THREAD

**Issue by Jpersh27** [mullvad/mullvadvpn-app#2716]
• Hello @faern @jvff and @axti I have a new feature request for the Android application of Mullvad. I understand that currently only local DNS servers work and public DNS servers like the following ones I listed down below don't- 

• Examples include: AdGuard DNS, Mullvad DNS Ad-blocking version, Mullvad DNS without Ad-blocking, Alternate DNS, or NextDNS. 

•Everytime I try enter a public DNS server I get the following pop-up inside the application- ![IMG_20210503_024938.jpg](https://user-images.githubusercontent.com/77606699/116849254-6d3f5300-abbc-11eb-95ae-870a661c35b5.jpg)
![IMG_20210503_025202.jpg](https://user-images.githubusercontent.com/77606699/116849351-952eb680-abbc-11eb-80a6-caabfe2eb010.jpg)
![IMG_20210503_025131.jpg](https://user-images.githubusercontent.com/77606699/116849361-995ad400-abbc-11eb-91bd-9f67574004cd.jpg)
![IMG_20210503_025100.jpg](https://user-images.githubusercontent.com/77606699/116849369-9cee5b00-abbc-11eb-9828-ad0710861aee.jpg)

**Comment by faern** [comment]
You can add a public DNS IP in the app now. But the warning is hardcoded and will go away in the next release. Please see this blog post: https://mullvad.net/en/blog/2021/4/15/support-custom-dns-servers-launched/
