### ISSUE TITLE
[Windows] Failing to start tunnel after system downtime

### ISSUE THREAD

**Issue by pointydev** [mullvad/mullvadvpn-app#2760]
## Issue report

Operating system: Windows 10 21382 (Insider Dev Channel)
App version: 2021.3

### Issue description

After cold booting/restarting/resuming from sleep (and in some cases, locking/unlocking), the Mullvad app fails to connect unless I start a stock Wireguard app connection first and then connect via the Mullvad app while connected. After contacting support via in-app reporting (`6dd2b649-17b6-4751-8ba5-7a9a8ecc355c`) ~~and subsequently replying after a single restart fixed it once~~, the issue persisted after following their troubleshooting steps. 

App is currently configured to use `Any tunnel protocol with OpenVPN over port 443 over TCP and WireGuard over any port over IPv4 or IPv6 in city lon, gb using provider(s) 31173`, however the issue continues without these constraints. Curiously, the tunnel [doesn't appear](https://mullvad.is-serious.business/5JYS5wZ.png) in Windows' network connections when connecting.

Sidenote, after attempting to connect via OpenVPN only (and failing), I receive [this error](https://mullvad.is-serious.business/2rfHaEJ.png) in app, even though I only have 1 other active connection right now (Android).

Thanks,
Elliott

**Comment by dlon** [comment]
This fits the description of a bug that was introduced in recent Windows dev builds and fixed/worked around in Wintun 0.10.4. If you don't want to wait for the next app release, you could just download the most recent version of [Wintun](https://www.wintun.net/) and replace `wintun.dll` in `C:\Program Files\Mullvad VPN\resources`. The Mullvad VPN service must be stopped before doing so.

**Comment by pointydev** [comment]
> download the most recent version of [Wintun](https://www.wintun.net/) and replace `wintun.dll` in `C:\Program Files\Mullvad VPN\resources`.

This workaround seems to fix the issue (using Wintun 0.11), thanks for your help.
