### ISSUE TITLE
[Feature Request] Adblock-DNS: Easylist not good enough, needs slight improvements

### ISSUE THREAD

**Issue by duckblur** [mullvad/mullvadvpn-app#2774]
As someone used to Blokada I was very happy with your adblock via DNS announcement yesterday. I'm wondering why you just chose two Easylists. 

**Don't get me wrong**, I realize you don't want to block too much as your first line of defense  (I do use uBlock origin on desktop). 

With Mullvad's very own DNS, I still get too many ads, so I'm now back on AdguardDNS.

If you just added one more list, or went with something like Energized Blu (default in Blokada), your adblock feature would be pretty much perfect (including the benefit of no DNS leaks of course).

For comparison: dnsforge.de and https://dismail.de/info.html#dns publish the lists used for their own anti ads & tracker DNS (although they may be overdoing IMHO).

Thanks for reading!

**Comment by faern** [comment]
Please raise this concern with support@mullvad.net and not on this issue tracker. Even if you can use the ad blocking DNS in the app the service is a server side service and not something the app controls.

**Comment by duckblur** [comment]
Yeah, I see why you react this way. Thing is, your blog post talks about making adblock a dedicated **button** in the app, similar to cleanweb in Surfshark and others. Of course the blocking is never done by the app, it's just a faster way to change DNS.

**"Until we release an on/off button in our app, test this."**
