### ISSUE TITLE
Feature request: Designate other subnets in same network as "local"

### ISSUE THREAD

**Issue by NateTheSage** [mullvad/mullvadvpn-app#2776]
## Feature request!

Operating system: Windows 10 Enterprise LTSC

App version: 2021.3

### Feature description

Hey all! Just want to say thanks for making such a great VPN. I had only one minor feature request for the client across all versions: The ability to designate other subnets as being "local" so that traffic may flow to them and not be blocked because it does not inhabit the same subnet.

This would be helpful for those (like I) who have multiple VLANs segregating traffic in their home network, as there are some resources I cannot reach because they're not on the same subnet, and I can't change them to be on the same subnet because that will break many other things in my setup.

For example, I have a PC on 10.1.10.2, and a server on 10.1.100.2 that services email. I cannot reach this server with the VPN on and "Local Network Sharing" on, but I can reach my printer at 10.1.10.4 just fine. They are both behind the same router, just on a different subnet for firewalling.

It's a minor annoyance if anything, but I would really like to see this feature!

**Comment by pinkisemils** [comment]
Do you have routes to your specific subnets? If you do not have a specific route to your smaller subnet, the traffic will just not reach those subnets. Allowing [LAN traffic](https://github.com/mullvad/mullvadvpn-app/blob/2eb6eb02ea3a00b4b23d4ecacd37bafee9bb6060/talpid-core/src/firewall/mod.rs#L36-L43) will make our firewall not block traffic going to your subnets, but unless you've configured routes to your subnets, traffic will probably be routed through our tunnel.

**Comment by faern** [comment]
It sounds like you are in the same situation as what I'm replying to here: https://github.com/mullvad/mullvadvpn-app/issues/2674#issuecomment-821223285. Please see that comment and set up routes to your local networks, that's not in scope for the app. Please re-open the issue if I have misunderstood your problem.
