### ISSUE TITLE
Add ability to enable Split Mode Tunneling for Android Auto

### ISSUE THREAD

**Issue by dpaoliello** [mullvad/mullvadvpn-app#2777]
## Issue report

Operating system: Android 10

App version: 2021.1

### Issue description

Recently the Android app was changed to filter the list of Split Mode Tunneling apps to those with the INTERNET permission, however Android Auto needs Split Mode Tunneling enabled to work wirelessly (even with Local Sharing enabled).

I would like to be able to enable Split Mode Tunneling for Android Auto: either by hardcoding an exemption for it so that it is displayed on the Split Mode Tunneling list despite not having the INTERNET permission (this seems like the simplest to do, but may be fragile and annoying to maintain long term), or by having some way to disable filtering by INTERNET permission (seems like the better option, but will require UI changes).

**Comment by pinkisemils** [comment]
Could you be a bit more specific? I don't believe this is an issue with split tunelling, as ideally Android Auto should work without splitting, you'd only have to allow LAN traffic. I'll see if I can get an android auto test kit or something.

**Comment by dpaoliello** [comment]
> Could you be a bit more specific? I don't believe this is an issue with split tunelling, as ideally Android Auto should work without splitting, you'd only have to allow LAN traffic. I'll see if I can get an android auto test kit or something.

Enabling local sharing doesn't seem to help. If I have Mullvad connected, then Android Auto complains that it can't connect (and suggests disabling VPN). If I disconnect Mullvad OR allow split tunneling for Android Auto, then it works fine.

> EDIT: I can't find much info about this, but this support [thread](https://support.google.com/androidauto/thread/78142922/vpn-breaks-wireless-android-auto?hl=en) seems to suggest that this could be an issue with Android itself. Have you tried using the standalone wireguard app?

Standalone app has the same issue. Given that thread and the error screen that pops up (which specifically asks to disable any VPNs), it definitely seems like a known issue in Android.

> I wonder if Android auto uses the 10.0.0.0/8, which might interfere with ours. Does wired Android Auto work? Would be great to deduce exactly what traffic Android Auto is trying to send.

Wired Android Auto works fine.

For what it's worth, when I connect to my AAWireless device it appears to be handing out 10.42.1.0/24 addresses.

It looks like Google does have a way to test Android Auto using a desktop as the head unit (https://android-developers.googleblog.com/2015/08/announcing-android-auto-desktop-head.html), but I'm not sure if that supports connecting wirelessly. You may also be able to glean some info from the AAWireless project (https://github.com/Snirpo/aawireless/tree/develop) or use it with the desktop head unit for testing.

**Comment by pinkisemils** [comment]
Maybe the only practical solution is to _permanently_ split Android Auto, but before we understand what does that imply traffic wise, I'll not recommend that. I do not know if apps launched through Android Auto will then also leak traffic. I'll try and do some testing first to see what leaks and what doesn't. We do appreciate the report though :slightly_smiling_face:.

**Comment by dpaoliello** [comment]
As a workaround, can you please add an option to disable filtering of the Split Mode tunneling list? Currently I'm using an old version of the app in order to be able to enable it for Android Auto...

**Comment by pinkisemils** [comment]
That's definitely something we could try doing in the short term, yes.

**Comment by dpaoliello** [comment]
@pinkisemils Update: I've done some experiments, and it's not the INTERNET permission that causes Android Auto to be filtered out, instead it's the `isLaunchable` check. It'd be great to have an option to "show system apps" that disables the `isLaunchable` check.

**Comment by albin-mullvad** [comment]
We now have a beta build that should fix this issue. You can either grab it [here](https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2022.1-beta2) or wait until it rolls out on Google Play and F-Droid.

**Comment by dpaoliello** [comment]
> We now have a beta build that should fix this issue. You can either grab it [here](https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2022.1-beta2) or wait until it rolls out on Google Play and F-Droid.

Yep, I built my own version with the fix a while ago and can confirm that it's working (I can get Android Auto appearing in the list, and enabling it to bypass VPN gets wireless Android Auto working).

I just installed the APK from GitHub and that appears to be working as well.
