### ISSUE TITLE
[iOS 15] iOS app cannot connect after updating to iOS 15

### ISSUE THREAD

**Issue by tylerwolf35** [mullvad/mullvadvpn-app#2796]
#Issue report

Operating system: iOS 15.0

App version: 2021.2

#Issue description

After updating to the developer beta of iOS 15, the Mullvad app can no longer connect. When I try to connect the app gets stuck on "Creating secure connection".

**Comment by pinkisemils** [comment]
This is a known issue with wireguard-go, and it we're looking into resolving it.

**Comment by pronebird** [comment]
We have a fix and we will be releasing an update soon.

**Comment by faern** [comment]
This has been fixed and a new version has been pushed to TestFlight. If you want to test our fix before it hits stable you can get it via this link: https://testflight.apple.com/join/gOpklnGw.

I'm closing the issue since we have resolved it. Please re-open if you still have iOS 15 issues.
