### ISSUE TITLE
Add license file?

### ISSUE THREAD

**Issue by reimertz** [mullvad/mullvadvpn-app#28]
I can see that you have it defined in ‘package.json’ but might be a good idea to include an actual license file now when you have open-sourced this project. 😄

**Comment by faern** [comment]
Is this one good enough? :)
https://github.com/mullvad/mullvadvpn-app/blob/master/COPYING.md

**Comment by faern** [comment]
Might be an idea to rename it to LICENSE though.

**Comment by nblackburn** [comment]
@faern In a GPL project which is what this is, either `LICENSE` or `COPYING` is accepted so there is no issue here.

**Comment by reimertz** [comment]
derpy. Looked around for `LICENSE` and had no clue about `COPYING`. :D

**Comment by pronebird** [comment]
There is a link to the license file on Github at the very top above the source code. Just click on it and it will automatically take you to COPYING file.

**Comment by faern** [comment]
I'm closing this issue as we do have a license file.
