### ISSUE TITLE
Error 0x5 on install of 2021.4

### ISSUE THREAD

**Issue by anon97945** [mullvad/mullvadvpn-app#2823]
## Issue report

Operating system: Windows 10 64Bit
App version: 2021.4

### Issue description

Can't install Version 2021.4 getting error 0x5 on install.

**Comment by mvd-ows** [comment]
Anything interesting logged in `c:\programdata\mullvad vpn\install.log`?

Can you attach the file here?

**Comment by anon97945** [comment]
> 
> 
> Anything interesting logged in `c:\programdata\mullvad vpn\install.log`?
> 
> Can you attach the file here?

There is no install.log in `C:\Program Files\Mullvad VPN\install.log`

the installer just tells me "error on installing driver: 0x5" or some kind of this.

**Comment by mvd-ows** [comment]
#1 You're looking in the wrong folder. Copy and paste the path I gave you.

#2 Can you screenshot the error message and attach it here?

**Comment by anon97945** [comment]
I got it fixed, it was because of an old Mullvad Split Tunneling driver. I had an unofficial beta build with split tunneling. Got it from the Support. Due to this the 2021.4 had no permissions to uninstall the old Split Tunneling Device. So i went into device manager and deleted it with all the drivers. Installation done. Maybe it needs some fixes with how to handle "outdated" split tunneling devices.

**Comment by mvd-ows** [comment]
Yep, that's the correct fix given the situation you found yourself in. There's already extensive logic in place to handle upgrading and even downgrading of the driver. I'll remind Support to pass on the advice to use a virtual machine for running test builds.
