### ISSUE TITLE
[Feature Request] Minimize to tray hides taskbar icon

### ISSUE THREAD

**Issue by lem503** [mullvad/mullvadvpn-app#283]
Currently it is not possible to hide the taskbar icon in Win10, meaning that tray icon and taskbar icon are always visible. It would be great if we could minimize to tray completely by hiding the taskbar icon when we minimize the app.

Mullvad VPN App version 2018.2.beta1

**Comment by pronebird** [comment]
Hi,

It's a known issue. We've already patched that but I don't think it's been released yet.

Cheers,
Andrej

**Comment by lem503** [comment]
Awesome! Looking forward to the next release.
