### ISSUE TITLE
[Feature Request] Configurable SOCKS proxy for bypass

### ISSUE THREAD

**Issue by sin-ack** [mullvad/mullvadvpn-app#2847]
## Issue report

Operating system: Gentoo Linux 17.1

App version: 2021.3

### Issue description

I would like to have an option in the Mullvad application where you would be able to define a SOCKS proxy on a given port on localhost, and all data sent through that proxy would bypass Mullvad. My usecase is that I would like to keep using Mullvad with Firefox, however I would like to exclude certain websites from using the VPN. I can use FoxyProxy to specify using a certain SOCKS proxy for certain websites, so if Mullvad provided a SOCKS proxy for bypassing the tunnel, then I would be able to do this. If there is a possible workaround I can apply here, that would work as well. Right now, I have to start a separate browser in order to bypass Mullvad for certain websites, which isn't ideal.

**Comment by pinkisemils** [comment]
You can run your own SOCKS proxy via `mullvad-exclude`, and then configure FoxyProxy to use it.

**Comment by sin-ack** [comment]
Oh, thank you for that. I will try this.

**Comment by faern** [comment]
Using our existing split tunneling to exclude your own SOCKS proxy seems like the correct solution here. I don't think we want to bundle a SOCKS proxy with the app for this pretty special use case. I'm going to close this.

**Comment by sunknudsen** [comment]
@faern This feature would be amazing to bypass signup restrictions… just tried creating account on Totanota and signup was refused because of Mullvad IP. Using Firefox containers, one could create a container that bypassed kill switch.
