### ISSUE TITLE
Request: Official BSD Support?

### ISSUE THREAD

**Issue by rail5** [mullvad/mullvadvpn-app#2888]
After struggling for hours in a vain attempt to compile the 2021.4 release on FreeBSD, I'm compelled to ask: would you consider official BSD support?

**Comment by faern** [comment]
I'm sorry, but we are probably not going to add BSD support. It would be a lot of work to make it work there. We need a new firewall integration module and integration with routing tables and DNS etc. It's quite a lot of missing code I'm afraid.

I suggest you run vanilla WireGuard or OpenVPN against our servers. You will then of course miss the features in our app with regards to leak protection and automatic server selection etc. But that's probably the best you can do at the moment.
