### ISSUE TITLE
some chicago servers (QUADRANET) are improperly identified by speedtest.net

### ISSUE THREAD

**Issue by lordcyb3r** [mullvad/mullvadvpn-app#2890]
some chicago servers (QUADRANET) are improperly identified by speedtest.net. closest servers always show up as LA. Probably an issue on quadranet's side

See bellow:

https://i.imgur.com/4Mv6WcG.png

**Comment by faern** [comment]
This is not directly app related. Please report any server issues to support@mullvad.net. Thank you.
