### ISSUE TITLE
Bridging problem of network adapter on WSL2

### ISSUE THREAD

**Issue by johnjohnk2** [mullvad/mullvadvpn-app#2894]
## Issue report

Operating system:  WSL2 on W10

App version: 2021.4

### Issue description

Wsl looses connection after starting mullvad vpn, might not be updating wsl network adapter leaving it without connectivity

![image](https://user-images.githubusercontent.com/36307676/128085481-f841d766-c2b9-4c80-be5f-551929a079a5.png)

**Comment by mvd-ows** [comment]
Hi, can you please describe your configuration.

Single WSL2 client using single NIC in bridged mode? Any specific settings?

What are the steps to reproduce the issue?

**Comment by johnjohnk2** [comment]
Hi @mvd-ows, 
Sorry for the delay, I was outside office. 
I am on W10 pro. Not any specific config, just windows terminal launching Arch WSL installed in the classic way....
I am in single NIC and NAT mode ...

![image](https://user-images.githubusercontent.com/36307676/130694012-057857f4-2d9c-4616-8e14-5f771d5e6fb4.png)

![image](https://user-images.githubusercontent.com/36307676/130694181-7b833951-6879-4ccc-8766-fea84f08c7ae.png)

**Comment by johnjohnk2** [comment]
A friend made a test with Debian on WSL2 and installed windscribe and he does not loose connecxion on Debian. So it seems a problem specific to Mullvad or perhaps Arch configuration. I don't have any clue.

**Comment by pinkisemils** [comment]
Have you enabled _Local network sharing_ in the app's settings?

**Comment by johnjohnk2** [comment]
Nop and that was the issue ! Thanks a lot @pinkisemils !
