### ISSUE TITLE
Mullvad daemon service not found on boot

### ISSUE THREAD

**Issue by linuxosd** [mullvad/mullvadvpn-app#2896]
## Issue report

Operating system: openSUSE Tumbleweed

App version: 2021.4

### Issue description

Application installs successfully, and then:

sudo systemctl enable mullvad-daemon.service
sudo systemctl start mullvad-daemon.service

I can then connect successfully.

Problem is on reboot the mullvad-daemon.service does not start and is not found:

sudo systemctl status mullvad-daemon.service
Unit mullvad-daemon.service could not be found.

So I try to start it:
sudo systemctl start mullvad-daemon.service
Failed to start mullvad-daemon.service: Unit mullvad-daemon.service not found.

Service not found as noted above.

So I had to enable it first:
sudo systemctl enable mullvad-daemon.service

Then start it to finally get it working:
sudo systemctl start mullvad-daemon.service 

The systemd service should be saved as enabled and start on boot but it isn't saving and isn't starting.

**Comment by linuxosd** [comment]
I was able to solve the issue by stopping the mullvad-daemon.service and disabling it:

sudo systemctl stop mullvad-daemon.service

sudo systemctl disable mullvad-daemon.service

and then

sudo cp /opt/Mullvad\ VPN/resources/mullvad-daemon.service /etc/systemd/system/mullvad-daemon.service

Then enable and start the service again.

sudo systemctl enable mullvad-daemon.service
sudo systemctl start mullvad-daemon.service

**Comment by faern** [comment]
Our installer should already copy our `mullvad-daemon.service` to `/etc/systemd/system/`. But also, we don't support Suse, so we have not tried it extensively.

**Comment by linuxosd** [comment]
I can confirm that the mullvad-daemon.service has to be copied manually on openSUSE Tumbleweed with:

sudo cp /opt/Mullvad\ VPN/resources/mullvad-daemon.service /etc/systemd/system/mullvad-daemon.service

That is the only way to get it working.

**Comment by Extarys** [comment]
Mine was copied but wouldn't start, I changed the folder in /opt to remove the space, deleted and recreated the symlinks and it works - the GUI doesn't want to show up though haha I'm still investigating.

```
cat /usr/lib/os-release
NAME="openSUSE Tumbleweed"
# VERSION="20210923"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20210923"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20210923"
```
