### ISSUE TITLE
Can't exclude Prime Video via Split tunneling on Nvidia Shield

### ISSUE THREAD

**Issue by p1r473** [mullvad/mullvadvpn-app#2973]
## Issue report

Operating system: Android 9 (Nvidia Shield)

App version: 2021.1

### Issue description

Can't exclude Prime Video app from Mullvad via Split Tunneling. It doesn't show up in the app list on Nvidia Shield (It does show up on my phone though just fine- Pixel 4 Android 10). Other apps, like Netflix, do show up on the list.
![image](https://user-images.githubusercontent.com/9235633/133940168-649cf566-34e6-457a-8509-5abd4d70b374.png)
![image](https://user-images.githubusercontent.com/9235633/133939944-668241bb-b4b1-4b69-9f3d-a1261a043a82.png)

**Comment by pinkisemils** [comment]
We'll look into this.

**Comment by vnnegt** [comment]
> We'll look into this.

probably an obvious answer, but have you had a chance to look into this?

i noticed that both the ESPN and Fox Sports apps are failing to show up in the list as well

thanks

**Comment by joaommartins** [comment]
Any updates on releasing a new version for Android with the merged fix?

**Comment by albin-mullvad** [comment]
There is now a beta build available that fixes this issue (verified to work on a Shield running Android 11). You can either grab it from GitHub or wait until it rolls out on F-Droid and Google Play.

https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2022.1-beta2

**Comment by albin-mullvad** [comment]
Closing as the previously mentioned fix was released as stable a long time ago: https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2022.1
