### ISSUE TITLE
error[E0658]: half-open range patterns are unstable / error[E0658]: exclusive range pattern syntax is experimental

### ISSUE THREAD

**Issue by lordcyb3r** [mullvad/mullvadvpn-app#2987]
Output from git:

```
 Compiling talpid-openvpn-plugin v2021.4.0-dev-2d1170 (Z:\repos\mullvadvpn-app\talpid-openvpn-plugin)
error[E0658]: half-open range patterns are unstable
   --> talpid-core\src\tunnel\wireguard\wireguard_go.rs:331:9
    |
331 |         0.. => Ok(()),
    |         ^^^
    |
    = note: see issue #67264 <https://github.com/rust-lang/rust/issues/67264> for more information

error[E0658]: exclusive range pattern syntax is experimental
   --> talpid-core\src\tunnel\wireguard\wireguard_go.rs:331:9
    |
331 |         0.. => Ok(()),
    |         ^^^
    |
    = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `talpid-core`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
/z/repos/mullvadvpn-app /z/repos/mullvadvpn-app
Restoring version metadata files...
/z/repos/mullvadvpn-app
```

**Comment by workingjubilee** [comment]
You almost certainly are using an older compiler. Please use https://rustup.rs and run `rustup update`.

**Comment by lordcyb3r** [comment]
> You almost certainly are using an older compiler. Please use https://rustup.rs and run `rustup update`.

I am on the latest nightly branch as of the first posting

**Comment by lordcyb3r** [comment]
imma try the command regardless tho, if it works, I am ok with being wrong

**Comment by faern** [comment]
Is this still an issue? The nightly builds works for us here.

**Comment by lordcyb3r** [comment]
I am currently clean installing nightly. I think i forgot to uninstall my old toolchains. I will report back with my findings

**Comment by lordcyb3r** [comment]
no its complaining about stable not being installed 
`error: toolchain 'stable-x86_64-pc-windows-msvc' is not installed`

**Comment by lordcyb3r** [comment]
Seems to work but i have to go through each sh file and change every instance of stable to nightly. Might want to consider updating the scripts to accept stable, beta, and nightly by default. after i did the change manually, the build succeeded.

**Comment by faern** [comment]
The app is supposed to be built on stable. The code is written to work on latest stable. There is no good reason to build it on nightly. It compiles on stable for us. Are you having issues building the app on latest stable Rust (1.55.0)?
