### ISSUE TITLE
Mullvad does not work under Fedora 35 and Ubuntu 21.10

### ISSUE THREAD

**Issue by strykenKN** [mullvad/mullvadvpn-app#3004]
Fedora 35 and Ubuntu 21.10 installed today.
However, the GUI cannot be started.
The problem is that Mullvad GUI uses an outdated Proton and both versions have Proton 15. 
There seem to be solutions here, but they do not work. 

Operating system: Fedora 35/ Ubuntu 21.10

Mullvad has not released an update for months and is not doing anything at the moment. Mullvad "SHOULD" have known that their app causes immense problems under newer Linuxes and do not change anything. Support knows, but unfortunately no answer. Instead they are hopping around London.

cd /opt/Mullvad VPN
./mullvad-gui                                                                                                                     
[2021-10-03 02:10:15.795][debug] Chromium sandbox is enabled
[2021--10-03 02:10:16.798][info] Running version 2021.4
Gtk-Message: 02:10:16.113: Failed to load module "appmenu-gtk-module"
Gtk-Message: 02:10:16.114: Failed to load module "appmenu-gtk-module"
[2021-10-28 02:10:16.349][info] Detected locale: de-DE
[2021-10-03 02:10:16.395][info] Connected to the daemon
[2021-10-03 02:10:16.571][error] Failed to load index file: ERR_FAILED (-2) loading 'file:///opt/Mullvad VPN/resources/app.asar/build/src/renderer/index.html'

if someone has a simple solution for Fedora, step by step, to solve the problem, I would be very grateful! And I really mean step by step and not just something written quickly. Not everyone is as tech-savvy as others might be! Also think of users who can't do everything!

It's nice when you have Mullvad VPN, paid for it and can't use it and Mullvad still can't manage to bring out a new version and they know that in Oct. of this year Ubuntu and Fedora will bring out new versions. But the main thing is to collect money. Sorry, but I am just pissed off! So, I paid and I can't use Mullvad! I don't find that funny. And I'm not going to fiddle around with the system now.

**Comment by jacksongoode** [comment]
Can similarly confirm this.

**Comment by pizzadude** [comment]
Workaround for now.

Copy "/opt/Mullvad VPN/mullvad-vpn" to "/opt/Mullvad VPN/mullvad-vpn.bak"

Edit "/opt/Mullvad VPN/mullvad-vpn" and replace it with the following (you need to use a text editor with root permissions):

```
#!/usr/bin/env bash
set -eu

UNPRIVILEGED_USERNS_PATH="/proc/sys/kernel/unprivileged_userns_clone"
if [ -e $UNPRIVILEGED_USERNS_PATH ] && grep -q 0 $UNPRIVILEGED_USERNS_PATH; then
    SANDBOX_FLAG="--no-sandbox"
else
    SANDBOX_FLAG=""
fi

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
exec "$SCRIPT_DIR/mullvad-gui" --no-sandbox "$@"
```

Make sure it is executable ( sudo chmod +x "/opt/Mullvad VPN/mullvad-vpn" ) in the terminal.

**Comment by strykenKN** [comment]
Hello thanks for your help, but unfortunately that all does not work also not the script, there does nothing at all with me and Mullvad can also not start in the console.

**Comment by strykenKN** [comment]
Hello,

just received a reply from Mullvad to test the DEV version, but unfortunately also only problems. The GUI starts but the interface remains white. After that Mullvad, also can not be started. 

https://releases.mullvad.net/builds/2021.4-dev-26ca38/

**Comment by KnugiHK** [comment]
Does this works for you?
```shell
$ /opt/Mullvad VPN/mullvad-gui --no-sandbox &
```
Please do this in version 2021.4.

**Comment by KnugiHK** [comment]
> 
> 
> Hello thanks for your help, but unfortunately that all does not work also not the script, there does nothing at all with me and Mullvad can also not start in the console.

Does this works for you?
```shell
$ /opt/Mullvad\ VPN/mullvad-gui --no-sandbox &
```
Please do this in version 2021.4.

**Comment by strykenKN** [comment]
Hello,

I was able to fix it now. I permanently forgot to change it via gdit. Changed it now via gedit and now it works. Thanks for your help.

**Comment by raksooo** [comment]
This will be solved in the next beta-version. More information can be found in https://github.com/mullvad/mullvadvpn-app/issues/2992. I'll close this since it's a duplicate.
