### ISSUE TITLE
[Feature Request] [Linux] Allow quiting Mullvad application from system tray icon

### ISSUE THREAD

**Issue by gotmax23** [mullvad/mullvadvpn-app#3050]
## Issue report

Operating system: Linux (Fedora 34 with the Mullvad rpm package, specifically)

App version: 2021.04

### Issue description

Could you please consider adding the ability to quit the Mullvad app from the system tray (i.e. add a `quit` option to the tray applet's menu)? Closing the app window results in the app minimizing to the system tray, yet the only way to close it is by relaunching the app and clicking through a menu. Implementing this feature would improve the user experience and mirror the behavior of other apps that run in the background and have a system tray applet.

Thanks,
Maxwell

**Comment by YaBoiBurner** [comment]
At least for me, since I'm also wanting to be able to do this, I have two reasons.

First, the desktop app is an electron app, so it uses a decent amount of memory. If the VPN didn't disconnect when I quit the app, I probably would just use it when the VPN was misbehaving.

Second, for some reason clicking the upper left corner of my screen opens up the desktop app. I have no idea how or why this happens, and I don't even know if it's related to Mullvad or if it's an electron thing or a KDE thing or a Wayland thing or some incomprehensible interaction between a few of those things (Though I think it's a KDE thing). I just know that it's kinda annoying.

**Comment by gotmax23** [comment]
Hi everybody,

> What's the reason you want to quit the app? Compared to just disconnect and let it sit running in the background.

I agree with the other commenters about the memory usage issues. Also, I don't like having tray applets cluttering my system tray when I don't need them.

> We don't want to make it too easy to quit the app. Because it's a security risk of sorts. Quitting the app disconnects the VPN, and that could be very bad, depending on the situation.

There is already a `disconnect` button in the tray applet, anyways. If you really wanted, you could add logic to hide the `quit` button when the VPN is connected, but I'm not sure the extra complexity is worth it.

Thanks,
Maxwell

**Comment by TwonkyHardware** [comment]
I can provide another couple of reasons to support this request.

The first is that on my system (Ubuntu 18.04), the Mullvad GUI often doesn't open properly when I select "Open Mullvad VPN" from the system tray menu.  This means I don't have access to the GUI menu from which to quit the program, so I have to `kill -9` by process ID whenever I want to close the program.  I'm filing a separate issue for the GUI problem, but the ability to quit the program from the context menu would save me a lot of hassle when dealing with this, and I was going to suggest this very thing in that issue.

The second is that deliberately making it more difficult for your user to do what they want to do is terrible UX and disrespectful to the user.  This is Linux.  You're supposed to trust the user to know what they want to do.  If you must, Maxwell's suggestion to only show the "Quit" option once the VPN is disconnected is a good idea and a fine compromise.

**Comment by raksooo** [comment]
This has now been implemented and will hopefully be part of the next release.
