### ISSUE TITLE
DPKG Error when installing 2021.5 over 2021.4

### ISSUE THREAD

**Issue by jonpolak** [mullvad/mullvadvpn-app#3064]
## Issue report

Operating system: 
Linux. Ubuntu Mate 21.10 (5.13 kernel)

App version: 2021.5_amd64.deb

### Issue description
When trying to install 2021.5 over 2021.4 we get this error:
`dpkg: error: unable to read filedescriptor flags for <package status and progress file descriptor>: Bad file descriptor`

**Comment by faern** [comment]
Can you try downloading the installer again? And/or try verifying the deb file with its GPG signature? Just to rule out the possibility that the file you got is corrupt.

**Comment by jonpolak** [comment]
I did check it with GPG at the time. I ran Gdebi from the command line
(instead of Gdebi GUI) a few days later and it worked without a hitch.
(same file)

**Comment by faern** [comment]
Hmm. We have not tried with the GUI. If it works with the CLI tool it sounds like a bug with their GUI.
