### ISSUE TITLE
[feature request] Display block url when Block adds

### ISSUE THREAD

**Issue by CruiseMan** [mullvad/mullvadvpn-app#3095]
Would be interesting to see block urls, thank you

**Comment by faern** [comment]
Could you please elaborate on what you mean? First of all, the ad/tracker blocking built into our app is DNS based. So it will prevent you from talking to certain **domains**, not certain **URLs**. Second: The blocking is implemented server-side. So our DNS resolvers on the VPN servers do the blocking of certain bad domains, not the app. So the app currently has no knowledge of what blocked domains your computer is trying to look up.

**Comment by CruiseMan** [comment]
> Could you please elaborate on what you mean? First of all, the ad/tracker blocking built into our app is DNS based. So it will prevent you from talking to certain **domains**, not certain **URLs**. Second: The blocking is implemented server-side. So our DNS resolvers on the VPN servers do the blocking of certain bad domains, not the app. So the app currently has no knowledge of what blocked domains your computer is trying to look up.

Ohh ok, I thought you run DNS server inside the app, and blocking is client side. Currently I'm running pinhole locally and use custom dns to block domains (ads, etc). And ideally I would like to get rid off pinhole in afore of Mullvad but still want to have flexibility to monitor blocked url and add custom domains/URL's. And having local DNS(build-in in Mullvad would also speed up dns response). And another benefit I think would be less traffic on your infrastructure (AKA more decentralized). If I live in Australia and connected to US ip, dns response could be up to 200-300ms.
Another option for me is to use Lockdown app for Mac, so I can still enjoy Mullvad vpn and be able to see blocked url (https://github.com/confirmedcode/Lockdown-Mac/issues/22)

**Comment by faern** [comment]
We are experimenting with having a local DNS resolver run by us to be able to do a bunch of stuff. But it's probably pretty far in the future before we offer custom domain filtering client side.

I'm going to close this issue as it's not possible in the current state.
