### ISSUE TITLE
[ Issue/Question ] Wireguard triple-hop - Way more Captchas than double-hop or single-hop

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/mullvadvpn-app#3106]
## Issue report

Operating system: macOS Catalina, version 10.15.7

App version: 2021.5

### Issue description

_I was hesitating between contacting the service support or posting here, sorry in advance if this ticket should not here._

This ticket is not **really** an issue, anything blocking at least, but recently I have been using your triple-hop, with Wireguard:

1. For double-hopping
  https://mullvad.net/en/help/cli-command-wg/#multihopping

2. For triple-hopping > `macOS - Safari / Chrome / Edge / Brave`
  https://mullvad.net/en/help/socks5-proxy/

Everything seems configured correctly, I can see `SOCKS through WireGuard` on https://mullvad.net/en/check .

However, and that's the point of this ticket, each time I login to some website I now have to deal with Captchas <ins>**way way more often**</ins>, and also most of the time I have to answer 3-5 challenges (one answer is not enough).

Compared to when I am using only double-hop, or no hop at all (single-hop?), I barely see any Captchas, and when I do, one good answer is enough most of the time.

You say using SOCKS5 should, in principle, reduce the number of Captchas: (okay it's not exact science but still)
https://mullvad.net/en/help/socks5-proxy/#captchas

> ### Reduced CAPTCHAs
> Another benefit is a reduction in the amount of CAPTCHAs you will experience. Many websites and services require this identification when they detect traffic that originates from a VPN server. The proxy makes this detection more difficult.

I am fine to just use double or single-hop, but I was wondering is it something expected? Are websites more likely to detect bots (and therefore show a Captcha) when browsing with your SOCKS5 proxy (or more simply "a proxy") whereas you say this should not be the case?

Thanks for your help! :v:

**Comment by faern** [comment]
I don't think the number of hops affect the level of captchas at all. It's all in what source IP you come from when you connect to the various services that give you captchas. So I'd say that for the specific socks5 proxy you are using there is a high level of captchas probably. That IP has probably been misused by someone or similar. Try connecting through another server so you get another exit IP.

If that does not help, please contact support@mullvad.net. They are better suited to answer questions like this. I hope you are able to sort this out :)

**Comment by MrChocolatine** [comment]
> I don't think the number of hops affect the level of captchas at all

Indeed, that's not what I meant to say, more like "why am I getting more Captchas when using your SOCKS5 proxy?". Sorry if it was not clear.

> Try connecting through another server so you get another exit IP.

You mean the exit service/second hop? I will try.

Thanks for your time @faern .
