### ISSUE TITLE
Feature request: make it clearer when you've changed settings away from defaults

### ISSUE THREAD

**Issue by matiaskorhonen** [mullvad/mullvadvpn-app#3109]
## Issue report

Operating system: macOS

App version: 2021.5

### Issue description

It would be nice if the connection screen of the app made it more clear when you've fiddled around with the settings in such a way that it could have a severe performance impact.

A little while ago I fiddled around with the fireguard settings while trying to workaround some port blocks on a wifi network, forgot, and then was baffled by the poor connection speeds I was getting until today.

Here's a rough mockup of the sort of thing I had in mind:

![Mock-up of the Mullvad connection screen](https://user-images.githubusercontent.com/43314/141320987-5ffaf6ba-37e4-411e-b17c-962e8d5832bb.png)

In my imagination if no settings have been modified the view would look as it does now.

**Comment by faern** [comment]
It sounds very noisy to just repeat all settings[1] in the main view. It's going to get clobbered up very fast. What if you have the VPN protocol set to automatic (the default) but you have customized a lot of WireGuard *and* OpenVPN settings? Should we then list all those customized settings but in some way communicate that it might use either protocol? To me it sounds like a lot of duplication of what the settings view is already showing you.

Could another solution be to somehow show in the settings view what the default value for each setting is?

[1]: Changed settings, but anyway. That's probably a few settings for most users.

**Comment by MarkusPettersson98** [comment]
Hello!

Something akin to your suggestion has actually been implemented as of the [2024.6 release](https://github.com/mullvad/mullvadvpn-app/blob/main/CHANGELOG.md#20246-beta1---2024-09-26)! 🎉 

![bild](https://github.com/user-attachments/assets/19161a2d-8dd5-45ca-a25b-a3538dee0075)

We call it "Feature indicators", and it displays a summary of the settings that are relevant for a given connection.
