### ISSUE TITLE
Amazon Prime Video not displayed on the split tunneling screen

### ISSUE THREAD

**Issue by wanam** [mullvad/mullvadvpn-app#3121]
## Issue report

Operating system: AndroidTV 9 (MiBox S)

App version: 2021.1

### Issue description

I try to whitelist Prime Video app on my TV box, when I go to split tunneling screen to whitelist the app, I can see and check many other apps (Netflix...) but Prime Video app is not listed.

**Comment by wanam** [comment]
I though it may be related to the fact Prime Video is a system app bundled on this box, but Netflix is also and can be whitelisted with no issues.

**Comment by albin-mullvad** [comment]
Looks like a duplicate of:  #2973

See my comment here:  https://github.com/mullvad/mullvadvpn-app/issues/2973#issuecomment-954671619

**Comment by wanam** [comment]
Indeed it is a duplicate.
Closing this one.
