### ISSUE TITLE
Upgrade to 2021.6 breaks everything

### ISSUE THREAD

**Issue by TwonkyHardware** [mullvad/mullvadvpn-app#3123]
## Issue report

Operating system: Ubuntu 18.04, Cinnamon DE

App version: 2021.5, 2021.6-beta, 2021.6

### Issue description

I was using the 2021.6 beta as part of an attempt to diagnose [this issue](https://github.com/mullvad/mullvadvpn-app/issues/3068).  After receiving a desktop notification that the 2021.6 release upgrade was available, I downloaded and installed it (all while the 2021.6 beta version was active and connected).

After installing the release version of 2021.6, I tried starting Mullvad.  The GUI opened and stuck on "Connecting to Mullvad system service..." indefinitely.

Assuming there was a bug in the 2021.6 release, I reinstalled 2021.5.  After starting Mullvad, the GUI again opened and stuck on "Connecting to Mullvad system service..." indefinitely.

I reinstalled the 2021.6 beta, which had been working fine just minutes before.  After starting Mullvad, the GUI again opened and stuck on "Connecting to Mullvad system service..." indefinitely.

At this point, when I closed Mullvad completely, I had no internet connection at all (I assume this is the built-in killswitch).  So, I purged Mullvad with `$ sudo apt-get purge mullvad-vpn` so that I could access the Internet and look for solutions.

Finding none, I tried re-installing the latest release, 2021.6, in case the purge had removed the problem.  It did not; after starting Mullvad, the GUI again opened and stuck on "Connecting to Mullvad system service..." indefinitely.

I purged the 2021.6 version and installed the 2021.5 version, which I know functioned on my machine.  After starting Mullvad, the GUI continues to open and get stuck on "Connecting to Mullvad system service..." indefinitely.  However, I find that with the app closed, I do have internet service, allowing me to make this post.

What do I do?

**Edit**
I successfully sent a problem report (referencing this issue).

**Comment by faern** [comment]
The relevant part of the logs you sent seems to be:

```
[2021-11-18 11:27:54.143][mullvad_daemon][ERROR] Error: Unable to initialize daemon
Caused by: Unable to initialize split tunneling
Caused by: Unable to initialize net_cls cgroup instance
Caused by: EBUSY: Device or resource busy
```

So it fails to initialize `cgroup` it needs for split tunneling. Have you tried just rebooting your computer?

**Comment by TwonkyHardware** [comment]
I was finally able to reboot, and that did fix the problem.  What's the relationship between rebooting and initializing a `cgroup`?

**Comment by faern** [comment]
I have no idea. Sometimes computers act very strange. And we have not seen this specific error from anyone else. Please re-open the issue if it happens again. Since you don't experience the issue any longer I'm going to close this for now, since now no one has it :D
