### ISSUE TITLE
Allow "Always require VPN", bur keep internet on manual disconnect

### ISSUE THREAD

**Issue by bep** [mullvad/mullvadvpn-app#3128]
![image](https://user-images.githubusercontent.com/394382/142646218-5f4a9a94-cf90-4869-8c89-ff112188b042.png)

With the above setting enabled, the internet connection is lost when I manually disconnect, which is not what I want/expect.

It would be useful if I could have this "kill switch" work only for unexpected failures (as in: The Mullvad process was killed/shutdown). I understand that this may be a breaking change / a different thing, so I would not mind another button in the UI.

**Comment by dlon** [comment]
There's no switch for this, but it is already how Mullvad works. If your connection is lost or if the Mullvad daemon dies while the app is connected, your internet will be blocked until the app has reconnected (unless you manually disconnect). More details can be found here if you're interested: https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md.
