### ISSUE TITLE
Bug: The Japanese expiration date is not displayed correctly.

### ISSUE THREAD

**Issue by carbongreat13** [mullvad/mullvadvpn-app#3131]
## Issue report

Operating system: Arch Linux

App version: 2021.6
### Issue description
"残り1日 残り2日。(One day left. Two days left.)"  but the correct number is "残り2日.(2 days left.)" is correct.
![Mullvad-eng](https://user-images.githubusercontent.com/94222513/142728351-334928b4-9caa-4c40-a084-a477097b02d0.png)
![Mullvad-jpn](https://user-images.githubusercontent.com/94222513/142728354-de67deb5-6e7c-4d01-bd5d-460002105481.png)
![Mullvad-jpn-edit](https://user-images.githubusercontent.com/94222513/142728505-c5443e77-fbda-490d-8e39-15de6f0562fa.png)

**Comment by raksooo** [comment]
Thanks for reporting this! I'll bring it up with our translators.

**Comment by raksooo** [comment]
Thanks for reporting! We've brought this to our translators attention and it will be fixed in the next version.
