### ISSUE TITLE
[Feature Request] Filter by server ownership

### ISSUE THREAD

**Issue by sindastra** [mullvad/mullvadvpn-app#3136]
If you look at the [Mullvad website](https://mullvad.net/en/servers/), you can filter by server ownership (owned or rented).

The Mullvad App on desktop allows to filter by provider. It would be nice if, in addition to filter by provider, we could filter by ownership, and for example, only use servers at are "owned".

Of course the idea would be that once the filter is enabled, not only would it hide the undesired servers from the list, but also if we choose a country from the list, it should pick a server from that country at random (like currently), but only from the filtered ones (for example "owned").

**Comment by faern** [comment]
Thank you for the feature request. This has been an idea internally for a long time as well. But it has not gotten enough attention/requests to make it worth implementing. We'll see what we can do about that, but now we have a tracking issue for it at least!

**Comment by sindastra** [comment]
It seems this has been resolved with commit 49103bd72286abd57be1f0f4f59a2b2ee77bd404
