### ISSUE TITLE
[Feature Request] Always require vpn per app

### ISSUE THREAD

**Issue by AMTitan** [mullvad/mullvadvpn-app#3153]
I was wondering because you have an always require vpn would there be any way that you can do a always require vpn on a per app basis? If I did this on firefox and had a weather widget say I did the requirement on firefox if I get disconnected for any reason firefox will not get any internet until it gets reconnected but the weather widget would just go to normal internet. This might be hard to implement but you can try and rework the split tunneling to do this exact thing.

**Comment by faern** [comment]
Always require VPN is *not* the same as a kill switch. Even with always require VPN off the app will prevent all network leaks on accidental disconnects until a new tunnel is up and running. Always require VPN is only for blocking internet when you intentionally disable the VPN. You can read more here: https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md#kill-switch

Maybe you already knew the above? Maybe that's exactly what you meant. That if you intentionally disconnect Mullvad you want Firefox to be kept offline until you connect again, but you want to have the weather widget work all the time? Can't you just use split tunneling on your weather widget and have it always use the normal internet? Or is it important that it uses the tunnel when one is connected?
