### ISSUE TITLE
Any browser needs 10x the amount of time to open when connected to VPN

### ISSUE THREAD

**Issue by Anchor5178** [mullvad/mullvadvpn-app#3156]
## Issue report

Operating system: elementaryOS 6 Odin

App version: 2021.6

### Issue description

When connected to VPN any browser (Librewolf, Firefox, Epiphany) needs more than 10 seconds to open. Other applications work just fine. Executing "sudo apt update" also takes more than 10 seconds to do anything. Changing ANY setting does not change this behaviour, nor the protocol nor a custom DNS server etc etc. After disconnecting from VPN everything works just fine and browser applications open just fine.

I was already experiencing this issue months ago on an old elementaryOS 6 install and reported it by E-Mail within the program. The support could not fix my issue and told me to use wireguard directly instead of the MullvadVPN Application which did fix the issue. I completely reinstalled my OS and setup MullvadVPN on this fresh install of elementaryOS 6. Same problem again.

When connected:
```
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 6 received, 0% packet loss, time 5008ms
rtt min/avg/max/mdev = 16.480/17.283/18.290/0.603 ms
--- google.com ping statistics ---
7 packets transmitted, 7 received, 0% packet loss, time 6009ms
rtt min/avg/max/mdev = 21.955/23.814/25.353/1.034 ms
```
My webbrowser works fine when it is already started and VPN is running. I can use it completely normal, only the startup is heavily delayed.
CPU is completely normal when starting browser or doing "sudo apt update" in terminal when connected.

**Comment by faern** [comment]
We are not really supporting Elementary OS with our app. That's probably why they recommended you to use the vanilla WireGuard app. I have not heard about this before, so I suspect we will have a hard time to reproduce it. But if we can reproduce it we might be able to figure out why this is happening. Thank you for reporting it.

**Comment by faern** [comment]
I'm closing this as both stale and not supported. We have not heard more people report about this so it does not seem like a common problem.
