### ISSUE TITLE
Add --help option

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#3161]
Currently, if you run mullvad-vpn `--help` from the command line, it will launch the desktop app.
I suggest implementing the `--help` option. This option is not specified in POSIX, but is required in GNU.

**Comment by pronebird** [comment]
If you want to manage the tunnel or settings, you can use `mullvad` CLI instead which supports `--help`. `mullvad-vpn` is a GUI app and you're not supposed to use it as a command line tool.

**Comment by faern** [comment]
We can surely add a `--help` option to our GUI wrapper script at `/opt/Mullvad VPN/mullvad-vpn` that informs the user that they are probably looking for the CLI which is just called `mullvad`. It can also tell the user what actual flags our GUI supports, because there are some.
