### ISSUE TITLE
Ability to block Google and Facebook

### ISSUE THREAD

**Issue by askew07** [mullvad/mullvadvpn-app#3169]
## Issue report

Operating system: `Fedora Linux 35 (Workstation Edition)`

App version: `2021.6`

### Issue description

I had been a long-term customer of another VPN service; hang on, do not ban me :). Truth be told, I am transitioning from _that_ VPN service to Mullvad, and I am completely in love with this project. Even more, I am in love with the fact that this is a (mostly) Rust project!.

Besides the ability to block Ads and Trackers, my former VPN service had the ability to block both **Google** AND **Facebook**. I think, they are using these block lists:

https://github.com/nickspaargaren/no-google
https://github.com/jmdugan/blocklists/blob/master/corporations/facebook/all

Having the ability to go into the Internet jungle knowing that **Google** and **Facebook** traffic is _blocked_ at the DNS level, is a wonderful experience. Sure, you will not access Instagram, WhatsApp, Google search, Facebook, YouTube, etc... but that's exactly the point: the two biggest companies tracking us right now, are blocked at the DNS level.

### Feature Request
 Please consider adding options to block **Google** and **Facebook**, in all platforms. So we end with toogles like these in **Preferences**:

- Block ads
- Block trackers
- Block Google
- Block Facebook

I would be an even happier Mullvad customer if you can add these options.

Congratulations for the excellent work in this project.

**Comment by askew07** [comment]
BTW, I forgot to mention that I am aware that I can accomplish this by `Mullvad custom DNS` + `NextDNS` (on which I can select `No-Google`, `No-Facebook` block lists), but then I will have to trust in _two_ companies: Mullvad AND NextDNS.

I will _much_ prefer to have to trust in only one: my VPN service.

**Comment by faern** [comment]
The current block ads + block trackers support is hosted server side. So to get VPN server side support for this type of blocking you would have to talk to support@mullvad.net. But given how not flexible it would be to have a huge amount of various block lists server side I don't think that will happen.

Regarding client side DNS blocking: It's an idea we are exploring, but it's not in the near roadmap. It's a pretty large feature. We might add it. But it's not going to happen any time soon I'm afraid.

**Comment by jjpinom** [comment]
I think the Mullvad + NextDNS is the option right now.
