### ISSUE TITLE
[Feature Request] Allow Custom Configs on Mullvad Apps

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#3175]
I hope Mullvad consider this.

Please add a feature wherein we can load our own custom .ovpn or .conf files on Mullvad apps. 

As of currently, Mullvad doesn't offer Dedicated IP, thus having a way to import and use custom configs with Mullvad apps would be nice.

**Comment by faern** [comment]
What problem is it you are trying to solve exactly? What's your use case? I'm not sure I understand what it is that you are trying to do.

From the extension `.ovpn` it sounds like you want to load custom OpenVPN config files? This will likely not happen, since the way we run OpenVPN is pretty important for it to work in tandem with our daemon that controls it. If you want a custom OpenVPN configuration we suggest you run vanilla OpenVPN.

**Comment by MrChocolatine** [comment]
@8227846265 , if you haven't noticed there are guides on their website to configure OpenVPN for Mullvad:
https://mullvad.net/en/help/search/?q=openvpn

**Comment by 8227846265** [comment]
@faern  - I see, I have some `.ovpn` configs on VPN servers on countries that Mullvad doesn't officially support that I want to run with Mullvad app instead of other VPN apps (e.g. vanilla OpenVPN)

Since due to that I find that Mullvad has the best VPN app in Windows, primarily with the `Connect on Boot` feature. 

I have tried the vanilla WireGuard and OpenVPN, the other service provider's VPN application.
A. The vanilla apps were hit-and-miss and there's still disconnected state after signing in your computer
B. While the other service providers' application has to wait for their app to load on startup before connecting.

It's awful if you have Kill Switch enabled. Every reboot causes ≤1 minute disconnected state 

Nothing really beats Mullvad in terms of connecting to the VPN as fast as possible upon reboot of your computer. The first 1 second, your computer successfully logged in. You're already connected, which I really find amazing.

However, there are some servers I would prefer available, but I have heard the stance of Mullvad on geolocated regions, so I won't ever see the countries that I wish to have VPN connected to.

**Comment by faern** [comment]
I'm glad you like our VPN client :blush: 

You can connect to custom OpenVPN servers with our app on desktop via the CLI. You can't load custom config files. But you can tell the app all the parameters it needs to connect to a VPN server that is not ours. Fire up a console and explore the relevant parts of the CLI with:
```
$ mullvad relay set custom openvpn --help
```

**Comment by 8227846265** [comment]
Noted, will try this. :)
