### ISSUE TITLE
Feature request: Custom server lists (multiple locations in `mullvad relay set location`?)

### ISSUE THREAD

**Issue by Mikaela** [mullvad/mullvadvpn-app#3180]
## Issue report

Operating system: Fedora release 35 (Thirty Five)
App version: 2021.6

### Issue description

Currently `mullvad relay set location` takes either a country-code or `any`. I would like to configure multiple country codes and have Mullvad pick from them in style of `any` e.g. `mullvad relay set location se,no,ee,de,nl,fr` in case there was trouble connecting to a single configured country.

I was also thinking of allowing wider locations than individual countries like `mullvad relay set location europe`, but that could land to same country as the user is in unintentionally, it's not as fine-tuned and  I read in https://github.com/mullvad/mullvadvpn-app/issues/1542#issuecomment-599475104 that so wide options are discouraged.

**Comment by faern** [comment]
Hi. This is a feature we track internally under the name "Custom lists" or "custom server lists". I thought we had a github issue for it. But I can't find any at the moment. Yes we plan on eventually support allowing the user to create their own location lists that can contain any subset of countries and servers. So it's a more flexible solution to what you suggest.

This is in the backlog, but I have no ETA for it. Some vague design discussions has taken place so far.

**Comment by ynuwenhof** [comment]
Any ETA on this feature yet?

**Comment by faern** [comment]
Not really. A lot of other features has taken precedence. But it's still in the backlog. We know it's a wanted feature, so we'll eventually get there.

**Comment by hulthe** [comment]
Custom Lists was shipped with 2023.6
