### ISSUE TITLE
CLI command / API to dynamically rotate VPN targets from scripts [question]

### ISSUE THREAD

**Issue by boulderob** [mullvad/mullvadvpn-app#3181]
## Issue report

Operating system:  MacOS 11.2.3

App version: 2021.6

### Issue description

Question: 

I believe a site that I download from is throttling / sometimes blocking??? me on a mullvad vpn address I use for access to that country.  This never happened for the last 2 years but they must have changed their back end.  It's the only site I have any issues with regarding mullvad vpn IPs.

Is there a way to run mullvad from the cli from within my own scripts in a manner that would allow me to periodically/randomly switch the VPN target into the country.  I don't see this documented anywhere but I would like to be able to *DYNAMICALLY rotate* the connections.  Hopefully you have a stock cli subcommand that might do this or better yet an API that that allows me to fetch, change and login to VPN targets automagically?

Thanks

**Comment by faern** [comment]
We should probably document it better. But yes, we have a CLI for our app and it is mentioned in the [first paragraph in the readme](https://github.com/mullvad/mullvadvpn-app/#mullvad-vpn-desktop-and-mobile-app) in this repository.

When you install this app you also get the CLI command `mullvad`. You can issue `mullvad reconnect` to make it just reconnect using the same connection parameters. You can also set a new location with `mullvad relay set location ...`. Explore the CLI with the `--help` flags to the various subcommands and I think you will find what you need.

Please leave any feedback you have on the usability of the CLI.

**Comment by faern** [comment]
I'm closing this since the question has been answered.

**Comment by boulderob** [comment]
@faern Sorry for coming back so late on this.  Thanks for the info on the cli.

More specifically though is there a way from the cli to automate the process of listing all the FRENCH (or any other ctry) current live vpn servers?...   I couldn't find this in the cli options.

Going in and manually copying and pasting individual servers from your GUI tool isn't really automation.  Not only is manually copy and paste tedious and prone to errors but if you update your servers, i have no idea of and will miss new additions.

My use case is to simply and automatically from code pull a list of your servers in said country i'm interested and try them randomly until i find one that works for a given link I'm interested in viewing.  Or simply rotate them randomly during regular use to prevent getting the ip blocked.

Thanks

**Comment by faern** [comment]
I agree that it could be useful to add some filters to `mullvad relay list`. For example `--location <country> [<city>]` and/or `--provider <provider>`. PRs welcome if you want to add this functionality to the CLI.
