### ISSUE TITLE
Can you upload your git commit signing key to keys.openpgp.org?

### ISSUE THREAD

**Issue by carbongreat13** [mullvad/mullvadvpn-app#3185]
Traditional PGP keyservers are vulnerable.
Could you please upload your commit signing key to a secure keyserver, [keys.openpgp.org](https://keys.openpgp.org/)?
Specifically, these are the two PGP keys.
- EA0A77BF9E115615FC3BD8BC7653B940E494FE87
- 8339C7D2942EB854E3F27CE5AEE9DECFD582E984

**Comment by faern** [comment]
Both those keys are available on our open source page: https://mullvad.net/en/help/open-source/

That should be more reliable than a key server since you fetch the keys via TLS directly from us rather than a public key server that anyone can post keys to.

**Comment by faern** [comment]
I will close this. Our keys are available over https. We might push to keyservers later, but we have an internal key-revamp project that we want to finish first.
