### ISSUE TITLE
Wont start on ubuntu 20.04

### ISSUE THREAD

**Issue by thiagomen001** [mullvad/mullvadvpn-app#3188]
Hello,
I installed "elementary os 6 - Based on ubuntu 20.04" a few days ago and mullvad worked very well.
But without any change on my environment (update, new install) I can't start the gui anymore. It displays and closes instantly.

Any idea ?

**Comment by raksooo** [comment]
Our support team would be able to help you with this issue. You can reach them by either emailing support@mullvad.net or by reporting the problem with the `mullvad-report-problem` CLI tool. Sending a problem report has the benefit of app logs being included which helps when trying to figure out what's wrong. This can be done by running the following in a terminal:
```
mullvad-problem-report collect -o <path>
mullvad-problem-report send -e <email> -m <message> -r <path>
```
`<path>` needs to be the same path in both commands, e.g. `/tmp/mullvad-app.log`
Email and message are optional but our support team wont be able to reply without an email.

If you want to look into it yourself you can have a look if there are any errors in `~/.config/Mullvad\ VPN/logs/frontend-{main, renderer}.log`? You could try running the app from the terminal with either `/opt/Mullvad\ VPN/mullvad-vpn --no-sandbox` or `/opt/Mullvad\ VPN/mullvad-vpn --disable-gpu`.
