### ISSUE TITLE
[Feature-Request] Cli version for Modem/router like Nextdns do

### ISSUE THREAD

**Issue by BirdInFire** [mullvad/mullvadvpn-app#3206]
Hello,
I would like to ask you to have a Cli version of the app like nextdns do (see this release to see what i mean buy version (arm etc) : https://github.com/nextdns/nextdns/releases) for linux based nerwork Router/Firewall to install, UDM, UDM Pro.

Because many of us are "forced" to actually use an app on each computer, when we have a Firewall / Router (UDM-PRO) who actually have the CPU power to output our connexion with VPN but the constructor does not provide VPN client connexion to external Server (like your).

I really hope to see your app into (in my case) UDM pro, to actually use a VPN server (mean country) by VLAN or other thing like that directly at network level.

I don't have cited pfsence (because i do not know if they have an implmentation of openvpn/wireguard or not), and DD-WRT have an implementation of OpenVpn, i ask here to support (like the UDM pro) the Firewall who don't have support for openvpn or wireguard at all.

UDM can do it but we must modify the os by ssh and it cannot be undone easily (where in a script like nextdns's one) one line install / config / delete it.

So even if it don't work we can remove it as fast a we have actually installed it (and it mean a lot for it admin (be fast)).

Hope to see it one day.

**Comment by faern** [comment]
This app likely won't be supporting routers any time soon. I'm not saying Mullvad won't support it, but this app won't. For non app related issues I would recommend you to contact support@mullvad.net.

I asked support. It's not likely that we will support the Unifi lineup as they are not at all designed for this. They wipe the VPN config on every reboot. So it's not really worth it / not a recommended type of usage.

We have a draft for a guide on how to get Mullvad working on their Edgerouter, but it's not published yet. If that is of interest to you I recommend that you contact support and ask for it :)
