### ISSUE TITLE
[BUG] DNS server not matching when using Custom DNS (NextDNS)

### ISSUE THREAD

**Issue by askew07** [mullvad/mullvadvpn-app#3244]
## Issue report

Operating system: Fedora Workstation 35 | MacOS | iOS

App version: 2021.6

### Issue description
When using Custom DNS (e.g.: NextDNS), and moving between locations, dnsleaktest.com report that the DNS servers are actually leaking.

#### Steps to reproduce it
1. Assuming you have NextDNS account with a configuration, set the IPv6 servers (endpoints) shown in NextDNS _Setup_ tab in Mullvad.
1.1 In Mullvad app, go to _Preferences_ and disable *Block ads* and *Block trackers*.
1.2 Go to _Advanced_ > _Use custom DNS server_ and add the two IPv6 servers shown in *Setup* tab in NextDNS.
2. With Mullvad set to use Custom DNS (NextDNS) server, move to a desired location (let's say Canada) and try dnsleaktest.com. Run *Standard test* to check the DNS servers being hit. They should be servers in Canada.
3. Move to another location (let's say USA), and run again dnsleaktest.com. Run *Standard test* and see how the DNS servers are STILL the previous location (Canada): they have not updated when I moved between countries, but instead keep using the previous location.

#### Notes
Above bug happens in Linux, MacOS and iOS. Does not matter between which countries you switch; Mullvad will always leak by using the previous selected location (tested in dnsleaktest.com)

This is a *high-priority* bug.

**Comment by faern** [comment]
Have you verified the DNS requests are actually *leaking* (= being sent outside the VPN tunnel)? I have not tried NextDNS here, yet, but I would assume that the DNS requests are going inside the tunnel and NextDNS are caching which DNS server to use, and they don't realize you moved between countries that fast.

As long as the DNS requests are actually being sent inside the tunnel, we don't have a leak. Then which actual DNS server NextDNS decides to talk to, that's up to them and not in scope for what our app is responsible for.

**Comment by askew07** [comment]
Ok, sorry @faern , I think I have made a mistake: you are right, the request is being sent _inside_ the tunnel, so there is no leak (issue title updated). What I meant, is that when moving from locations in Mullvad, the NextDNS servers do *not* seems to update, in order to reflect the new location.

But if this is out of the Mullvad scope, I understand.

The very weird thing (and this is probably on Mullvad side), is that when switching locations in Mullvad with a Custom DNS (being NextDNS), testing in dnsleaktest.com, it almost always defaults to *Brussels, Belgium* (?), and this hostname is NOT dns.nextdns.io as it consistently is when using NextDNS as Custom DNS: this _might_ be, Mullvad app fault (please verify).

Example:

I am connected to Switzerland right now (using CustomDNS, NextDNS), and dnsleaktest.com correctly reports the DNS server being in Switzerland (and hostname is: dns.nextdns.io, which is correct when using NextDNS). And just switched to Canada, and dnsleaktest.com reports that now my DNS server is on "Brussels, Belgium", and hostname is empty (ISP: M247 Ltd), which might suggest that Mullvad app is using its own DNS and not the assigned Custom DNS.

Can someone in Mullvad team double-check / verify this?

Appreciated.

**Comment by askew07** [comment]
Even more weird; check the DNS servers reported now (I was before in UK, then moved to NC, USA).

![image](https://user-images.githubusercontent.com/95476521/148756167-103f63e3-09d8-4b37-a217-716ec9078065.png)

**Comment by askew07** [comment]
Hi again,

Confirming that this seems to be a problem on NextDNS side, since I switched Custom DNS servers in Mullvad app to Cloudflare (1.1.1.1, 1.0.0.1), and Cloudflare is accurate when resolving servers according to VPN location, when switching.

Sorry about the confusion.
