### ISSUE TITLE
mullvad-cli panics when "relay location" is set to "any".

### ISSUE THREAD

**Issue by OliverRoss** [mullvad/mullvadvpn-app#3264]
## Issue report

Operating system: Arch Linux, up to date

App version: mullvad-cli 2021.6

### Issue description

When calling `mullvad relay get` without any relay restrictions set, the app panics with the following output:

```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidArgument("missing relay location")', mullvad-cli/src/cmds/relay.rs:587:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace```

### Background info

After using `mullvad factory-reset` there was seemingly a constraint to use swedish servers (the default?).
I removed that constraint with `mullvad relay set location any`. Afterwards the issue came up.

**Comment by faern** [comment]
Thanks for the report. This was fixed in #3166. So current main branch does not have this issue and the next release will work as expected.
