### ISSUE TITLE
Suggestion - Improve User experience when Split Tunnel fails to find executable and Mullvad Service doesn't start

### ISSUE THREAD

**Issue by Ezelmannen** [mullvad/mullvadvpn-app#3265]
Operating system: Windows 10 Home 21H2 
App version: 2021.6

I use the Split Tunnel function to be able to view Netflix through a specific instance of Firefox Portable outside of Mullvad VPN.
The executable for Firefox Portable is stored on a Veracrypt-encrypted drive which doesn't decrypt when I boot the machine unless I actively tell it to (by pointing to it in VeraCrypt and entering the password).
I also have the option "Always require VPN" active.

If my computer reboots, for whatever reason (if I tells it too, if it crashes or if Windows Update decided to do it by its own mind), I end up in a rebooted state where I have no access to Internet at all.
It seems this has to do with the Mullvad Service doesn't start (even after several retries in services.msc) and the Mullvad Application just keeps looking for the service.

In this state I CAN NOT in the Mullvad Application tell it to Turn Off the "Always require VPN"-function.

I have found that the culprit here seems to be that the Split Tunnel Firefox Portable Executable isn't found since I hadn't activated my VeraCrypt drive yet.
I saw this when looking at the application log:

> [2022-01-13 19:51:25.888][mullvad_daemon::version][INFO] Starting mullvad-daemon - 2021.6 2021-11-17
> [2022-01-13 19:51:25.888][mullvad_daemon][INFO] Logging to C:\ProgramData\Mullvad VPN
> [2022-01-13 19:51:25.890][mullvad_daemon::system_service][INFO] Service started.
> [2022-01-13 19:51:25.890][mullvad_daemon::system_service][DEBUG] Update service status: StartPending, checkpoint: 1, wait_hint: 1s
> [2022-01-13 19:51:25.891][mullvad_daemon][INFO] Management interface listening on //./pipe/Mullvad VPN
> [2022-01-13 19:51:25.892][mullvad_daemon::settings][INFO] Loading settings from C:\WINDOWS\system32\config\systemprofile\AppData\Local\Mullvad VPN\settings.json
> [2022-01-13 19:51:25.893][mullvad_daemon][INFO] Loaded cached target state "Unsecured" from C:\ProgramData\Mullvad VPN\cache\target-start-state.json
> [2022-01-13 19:51:25.894][mullvad_rpc::address_cache][DEBUG] Loading API addresses from "C:\\ProgramData\\Mullvad VPN\\cache\\api-ip-address.txt"
> [2022-01-13 19:51:25.894][mullvad_rpc::address_cache][DEBUG] Using API address: [REDACTED]:444
> [2022-01-13 19:51:25.910][talpid_core::offline::imp][INFO] Initial connectivity: Connected
> [2022-01-13 19:51:25.910][talpid_core::split_tunnel::imp::driver][WARN] Error: Skipping path with non-existent drive letter
> Caused by: The system cannot find the file specified. (os error 2)
> Path: U:\Tools\Net\FLOSS\FirefoxPortable_ONLY_FOR_NETFLIX_WITH_MULLVAD_SPLIT_TUNNEL\FirefoxPortable.exe
> [2022-01-13 19:51:25.910][talpid_core::split_tunnel::imp::driver][DEBUG] Excluded device paths:
> [2022-01-13 19:51:25.924][talpid_core::split_tunnel::imp][DEBUG] Stopping split tunnel event thread
> [2022-01-13 19:51:25.924][mullvad_daemon::system_service][ERROR] Error: Unable to initialize daemon
> Caused by: Tunnel state machine error
> Caused by: Failed to initialize split tunneling
> Caused by: Failed to set list of excluded applications
> Caused by: The parameter is incorrect. (os error 87)
> [2022-01-13 19:51:25.924][mullvad_daemon::system_service][DEBUG] Update service status: Stopped, checkpoint: 0, wait_hint: 0ns
> [2022-01-13 19:51:25.925][talpid_core::split_tunnel::imp::path_monitor][DEBUG] Shutting down reparse point monitor
> [2022-01-13 19:51:25.925][mullvad_daemon::management_interface][INFO] Management interface shut down
> [2022-01-13 19:51:25.925][mullvad_daemon][DEBUG] Process exiting with code 0
> 

Suggestions:
- A more User friendly fail state when Split Tunnel Executable isn't found on startup. Perhaps a message stating it, or even allowing Mullvad Service to start, but with a disclaimer about the Split Tunnel not working.

- At the very least, a way to turn of Split Tunnel when in this state. If the drive with the Split Tunnel Executable is really lost, then I have no other option to get things working than to fully remove Mullvad from my system I guess.

- Make it possible to Turn Off 'Always require VPN' even if Mullvad Service fails. _(Should maybe be its own Suggestion)_

**Comment by dlon** [comment]
The main issue here is that the Mullvad service ends up sending an invalid config to the split tunnel device if none of the excluded paths reside on real volumes/drives. This has been fixed, and the problem will be gone in 2021.7.

It is still the case that these processes will not be excluded if the drive arrives after the split tunneling config is set, though. The ideal solution to that problem involves monitoring volume changes, but we're still not sure if that is something that should be done.

**Comment by dlon** [comment]
This will be fully fixed by #3322.
