### ISSUE TITLE
[--optimize] flag is not recognized {Minor Issue}

### ISSUE THREAD

**Issue by lordcyb3r** [mullvad/mullvadvpn-app#3274]
## Issue report

Operating system: Windows 11 Enterprise

App version: 2021.6-dev-8e12f7

### Issue description

When building the [--optimize] flag is not recognized. Building without flags works as intended.

**Comment by faern** [comment]
In what way do you mean it is not recognized? Could you please be more specific? Does the build script exit with an error? Is `cargo build` invoked without `--release`?

**Comment by lordcyb3r** [comment]
its when you pass the command `./build.sh [--optimize]`

**Comment by faern** [comment]
The correct format is `./build.sh --optimize`. The brackets is a pretty standard way of signaling that an argument is optional. I'll close this then as I think this was just a misunderstanding of how to use it. Please re-open if this is still an issue.
