### ISSUE TITLE
Suggestion - add a "random" server selection option.

### ISSUE THREAD

**Issue by Corfucinas** [mullvad/mullvadvpn-app#3278]
Has it been previously consider to boot the app and make it select a random server that is available?

I think it can be interesting in order to avoid patterns in which users longer on the same servers, thus, same IPs

**Comment by faern** [comment]
Every time you connect the VPN it picks a random server in the geographical location you have selected. So if you have selected a country it will pick a random server in that country. Is that not what you want?

With our CLI you can configure it to use ANY server anywhere. This is currently not exposed in the GUI since we don't think this is what most people want as it can give really bad speeds and latency if it randomly selects a server too far away. But if you want to try it, start a terminal/console and run: `mullvad relay set location any`

**Comment by Corfucinas** [comment]
I didn't know if the CLI option, that seems a reasonable feature.

However, I think that introducing a `random` or `shuffle` feature to the GUI can be useful as well. I believe users will be willing to sacrifice a bit of performance to have an increased possibility of not reusing the same servers constantly due to laziness or default preferences.

Taking into consideration what you said, the user can predefine a set of serves and this feature rotate the selection, or be open to any server

What do you think?

**Comment by faern** [comment]
> the user can predefine a set of serves and this feature rotate the selection

This is what selecting a country or a city already does. A server is selected randomly within your selected location. And usually have multiple servers in every location. However, we currently have no way of selecting servers at random in multiple, but a limited set of countries.

I think what you want is really just what #3180 talks about, is that correct?

**Comment by Corfucinas** [comment]
Correct

I was under the assumption that selecting a location will use the same IP address (users select a server, rather than a location than then balances the traffic between a servers in that location).

Adding a random feature will extend this towards the location, and in turn this will be applied to the selection process normally.

**Comment by faern** [comment]
> I was under the assumption that selecting a location will use the same IP address

No. All our servers have *multiple* exit IPs. And basically all locations (cities/countries) have multiple servers. So if you select a city or country you will exit through different IPs different times you connect the VPN. In a city with few servers the number of IPs is of course smaller than cities with many servers etc.

**Comment by Corfucinas** [comment]
I think this can be closed, adding just a random city option will incorporate this feature into it
