### ISSUE TITLE
arch linux enable always require vpn sometimes failed to connect when start computer

### ISSUE THREAD

**Issue by flyxyz123** [mullvad/mullvadvpn-app#3287]
## Issue report

Operating system: arch linux\
`uname -a`: `Linux xyzstudio 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux`

App version: 2021.6\
installed from aur package mullvad-vpn-bin: <https://aur.archlinux.org/packages/mullvad-vpn-bin/>

networkmanager version: 1.34.0-1

### Issue description

Arch linux enable always require vpn sometimes failed to connect when start computer. The `mullvad status listen` command will show it is trying to connecting and disconnecting in a very fast speed. This happened to me more than twice a week. A workaround I discovered is to open mullvad-vpn gui and disable "always require vpn" , then quit gui, then open the gui back again and connect again, now it is connected.

In preference I enable launch app on start-up, auto-connect, local network sharing, notification. In advanced I enable enable ipv6, always require vpn, openvpn only. In the past I use default settings for openvpn settings; now I use tcp, port 443, bridge mode off; both settings have this bug. I attached log file generated with `mullvad-problem-report collect --output report.log` below. 

[report.log](https://github.com/mullvad/mullvadvpn-app/files/7921699/report.log)

**Comment by dlon** [comment]
I think what is happening is that your time and date are completely off and cannot be synchronized because you have enabled always require VPN. This causes all certificates to be considered expired. I don't think that this can be considered a bug.

I would try to make sure that the time is set correctly in the first place. You could also try use WireGuard instead of OpenVPN. You can use it over TCP if you need to.

**Comment by flyxyz123** [comment]
> I think what is happening is that your time and date are completely off and cannot be synchronized because you have enabled always require VPN. This causes all certificates to be considered expired. I don't think that this can be considered a bug.
> 
> I would try to make sure that the time is set correctly in the first place. You could also use WireGuard instead of OpenVPN. There's a TCP option if you need that.

Thank you so much for the help. I was using `timedatectl set-ntp true` for syncing the time. I followed the instruction on arch wiki <https://wiki.archlinux.org/title/Systemd-timesyncd#Usage>. Do you think `timedatectl` causes this issue? I don't know too much about networking. But I'm guessing maybe `timedatectl` try to make a poll to sync time with remote server but failed due to I enable always require VPN but the VPN is not connected. And the VPN is not connected because time is not synchronized. Thus create a dead loop.

According to arch wiki, it says `timedatectl` implements SNTP instead of NTP. Should I try a NTP implementation for syncing the time?

**Comment by pinkisemils** [comment]
You can try excluding `ntp` from the tunnel by changing it's systemd unit to execute the respective daemon via `mullvad-exclude`. But this might not always work because connecting and disconnecting from a tunnel would still break a connection if there was one.

**Comment by flyxyz123** [comment]
> You can try excluding `ntp` from the tunnel by changing it's systemd unit to execute the respective daemon via `mullvad-exclude`. But this might not always work because connecting and disconnecting from a tunnel would still break a connection if there was one.

Thank you. I just switched to `chrony`. I'll try to manually adjust system clock next time this issue appear to see if it works. If it works, I'll try your suggestion of using `mullvad-exclude` in the `chronyd` systemd unit. For now, I will close this issue.
