### ISSUE TITLE
Mullvad app does not generate a new Wireguard key automatically 

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#3290]
## Issue report

Operating system: Windows 10

App version: 2021.6

## Issue description

Wireguard public key is not automatically regenerated. 

I was managing my Wireguard keys and I accidentally deleted them all. On this premise, the Mullvad app could no longer connect to the internet, which was expected.

On the other hand, the application did not generate a new key automatically. I had to go to the settings and create a key manually.

Lay users may have difficulty doing this process.

**Comment by faern** [comment]
The key regeneration currently only happens once per week. Yes, this is not the best user experience. We are working on an overhaul to the device + key relationship overall, so this will be fixed. Thanks for the report.

**Comment by hulthe** [comment]
This issue is fixed on newer versions.
