### ISSUE TITLE
Please point me in the right direction as to how I could find VPN endpoints that work with Amazon Prime?

### ISSUE THREAD

**Issue by firepacket** [mullvad/mullvadvpn-app#3292]
I am a software developer, and I am willing to create an app (multiplatform if possible) but windows for sure, a way to check your servers for Amazon Prime Access.

Do you have any APIs that would allow me to do command line connects and HTTPS requests? I can handle the rest, I just want to be able to cycle through all active Mullvad servers Wireguard and OVPN, connects, and check a webpage.

Does anyone have a direction for this?

I would be happy to integrate it with your website backend via PostBacks so your website could have updated information for all your visitors too.

Or is it a lost cause? Does Amazon have all your IPs?

Please help. I want to watch Prime. Do I need to look elsewhere? Thank you..

**Comment by faern** [comment]
You can use our CLI to script the connecting and disconnecting of the app towards different servers. See our CLI guide for some basics: https://mullvad.net/en/help/how-use-mullvad-cli/. Or just execute `mullvad --help` and start navigating down through the subcommands.

Basically what  you want is probably `mullvad list` to get all servers (There is an issue here on adding a flag to make it easier to parse: #2268). Then you probably want `mullvad relay set hostname <hostname>` to change server. And `mullvad connect --wait` to connect to it.

I highly doubt that we want any Amazon specific features on our website. We are also not very likely to bring in third party integrations. But that's not my area really. If you want to, you can contact support@mullvad.net.

**Comment by firepacket** [comment]
> You can use our CLI to script the connecting and disconnecting of the app towards different servers. See our CLI guide for some basics: https://mullvad.net/en/help/how-use-mullvad-cli/. Or just execute `mullvad --help` and start navigating down through the subcommands.
> 
> Basically what you want is probably `mullvad list` to get all servers (There is an issue here on adding a flag to make it easier to parse: #2268). Then you probably want `mullvad relay set hostname <hostname>` to change server. And `mullvad connect --wait` to connect to it.

That's great, exactly what I was looking for!

> I highly doubt that we want any Amazon specific features on our website. We are also not very likely to bring in third party integrations. But that's not my area really. If you want to, you can contact [support@mullvad.net](mailto:support@mullvad.net).

You're right. Makes sense, it would be tacky and bring too much heat.

**Comment by cole-h** [comment]
FWIW, I've opened https://github.com/mullvad/mullvadvpn-app/pull/3304 which should make it easier for you to parse out the hostname of the server you want to test out.

**Comment by firepacket** [comment]
Awesome!
