### ISSUE TITLE
Add runit service file

### ISSUE THREAD

**Issue by carbongreat13** [mullvad/mullvadvpn-app#3306]
## Issue report

Operating system: Gentoo Linux
App version: 2021.6

### Issue description
Could you please add a service file for [runit](http://smarden.org/runit/)?
At the moment we only have a service file for [systemd](https://github.com/mullvad/mullvadvpn-app/blob/master/dist-assets/linux/mullvad-daemon.service) and a [script for traditional Init](https://github.com/mullvad/mullvadvpn-app/blob/master/dist-assets/linux/mullvad-daemon.conf).

**Comment by pinkisemils** [comment]
We currently have no plans of supporting any other init system, as such we don't plan on adding a runit service file. In fact, the upstart config file is a bit of technical debt that we'll remove, as it isn't used by anything and as such, it isn't maintained.

**Comment by carbongreat13** [comment]
How about I write a service file and make a pull request?
