### ISSUE TITLE
Add CSV/JSON output option for relay list

### ISSUE THREAD

**Issue by sxdjt** [mullvad/mullvadvpn-app#3324]
It would be great if we were able to get the results of `mullvad relay list` as CSV and/or JSON output.  It would support scripting connections much easier.

Something like:

$ `mullvad relay list --output csv`

Country,City,Lat,Long,server,IP4,IP6,Tunnel,Hosting
se,got,57.70887,11.97456,se-got-001,185.213.154.131,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-002,185.213.154.132,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-003,185.213.154.133,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-004,185.213.154.134,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-005,185.213.154.135,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-006,185.213.154.136,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-007,185.213.154.137,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-008,185.213.154.138,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-009,185.213.154.139,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-010,185.213.154.140,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-011,185.213.154.141,,OpenVPN,31173
se,got,57.70887,11.97456,se-got-012,185.213.154.142,,OpenVPN,31173
se,got,57.70887,11.97456,se3-wireguard,185.213.154.66,2a03:1b20:5:f011:31::a03f,WireGuard,31173
se,got,57.70887,11.97456,se5-wireguard,185.213.154.67,2a03:1b20:5:f011::a05f,WireGuard,31173
se,got,57.70887,11.97456,se9-wireguard,185.213.154.68,2a03:1b20:5:f011::a09f,WireGuard,31173

or...

$ ``mullvad` relay list --output json`

{
   "se": [
      {
         "City": "got",
         "Lat": 57.70887,
         "Long": 11.97456,
         "server": "se-got-001",
         "IP4": "185.213.154.131",
         "IP6": "",
         "Tunnel": "OpenVPN",
         "Hosting": 31173
      },
...etc.

**Comment by MrChocolatine** [comment]
For a JSON output this might help:
https://github.com/mullvad/mullvadvpn-app/pull/3304#issuecomment-1025462698

**Comment by MarkusPettersson98** [comment]
I'll close this issue by referring to the answer given in https://github.com/mullvad/mullvadvpn-app/issues/2268#issuecomment-1025459443. Please let me know if this does not satisfy your needs.
