### ISSUE TITLE
Suggestion - Get a server in San Francisco to be able to download from archive.org

### ISSUE THREAD

**Issue by heldiho53** [mullvad/mullvadvpn-app#3327]
Hi, love your services. Archive.org is very slow as long as you're not in San Francisco were their servers are, unfortunately you don't have any San Fran servers. I'm using a competitor vpn for that purpose alone, if you would implement a San Fran server, I wouldn't need a second vpn service.

**Comment by faern** [comment]
This Github repository is about our app, not our service in general or infrastructure. Please reach out to support@mullvad.net for requests like these. Thank you.
