### ISSUE TITLE
[Suggestion] Add Handshake Domain Support

### ISSUE THREAD

**Issue by banmark** [mullvad/mullvadvpn-app#3335]
Currently Mullvad doesn't seem to resolve the handshake domains correctly when I change the DNS servers maybe in the future there could be a toggle to automatically resolve the Handshake Domains.

**Comment by faern** [comment]
When you change the DNS servers to what? Our app has no knowledge of Handshake Domains and likely never will. Our relays also operate regular DNS resolvers, so not their either. But if this is a question about how our VPN servers resolve things you should direct your question to support@mullvad.net.

Please note that our VPN servers intercept and hijack all DNS requests sent inside the tunnel if you have created your VPN tunnel via our online config generator. This is to prevent accidental DNS leaks. DNS requests sent inside tunnels from our own apps however does not do this. So if you use our app and set a Custom DNS, it should do name resolution to the DNS server you specify.

**Comment by faern** [comment]
Nope. I'm going to close this as it is very unlikely that we will support Handshake Domains. Unless it becomes a very common and widely accepted system for domains.
