### ISSUE TITLE
almost all Mullvad servers extremely slow!

### ISSUE THREAD

**Issue by strykenKN** [mullvad/mullvadvpn-app#3336]
Hello,

what is going on with you again ? Page this afternoon your servers are spinning! No matter which one you take, they are extremely slow and I hardly get a page on. With a friend who also has Mullvad, exactly the same. Your servers are extremely slow today! It hardly goes anything. I pay money and I expect that the servers are also fast, there is a snail faster than your servers!

**Comment by faern** [comment]
Please take anything not directly app related with support@mullvad.net.

Are you connecting to Germany or England via Vodafone? They are known to be troublesome at the moment sadly. The issue is with our server providers, ops is working on it!

**Comment by faern** [comment]
The peering issue at those hosting providers has been fixed. I hope this solves your issue.
