### ISSUE TITLE
Google Play In App Purchase

### ISSUE THREAD

**Issue by zajimumaaa** [mullvad/mullvadvpn-app#3338]
Is there any reason why Android app don't have In App Purchase? it's really convinient to pay using Google Play IAP. I notice that iOS App have IAP, why it's not available on Android?

**Comment by faern** [comment]
It's just not implemented yet. It's in our backlog. So it should hopefully arrive, eventually.

**Comment by barokvanzieks** [comment]
any updates on this?

**Comment by barokvanzieks** [comment]
been a year xD

**Comment by Pururun** [comment]
This has been added in this PR: https://github.com/mullvad/mullvadvpn-app/pull/5125
Will be available in the next release.
