### ISSUE TITLE
Unable to add custom OpenVPN arguments in Mac app

### ISSUE THREAD

**Issue by gdmachado** [mullvad/mullvadvpn-app#334]
I'm testing Mullvad on Mac, and I wanted to be able to customize some of the options documented [here](https://mullvad.net/en/guides/mullvad-client-advanced-options/), which are available in the Windows/Linux builds (more specifically, `custom_ovpn_args`).

The reason for this is that I wanted to use Mullvad on Mac under a Multihop config, however I could not find how to configure that with the Mac app.

I found the `settings.json` file under `/Users/<user>/Library/Application Support/mullvad-daemon`, but I'm not sure this is the correct way, and since it's different than the `settings.ini` file in Windows, I don't really know how to declare custom ovpn args that way.

**Comment by faern** [comment]
The new mac app does not yet have feature parity with the old python client. One thing that is currently not possible is to specify custom OpenVPN arguments. To either add this, or to support multihop in some other way, is in the backlog. So the app will get there, but this is currently not possible.

It is not recommended to try to manually make changes to the `settings.json` file. Everything in that file is configurable from the GUI or the CLI of the app.

Thank you for your feedback. I hope we can support your use case in a while.

**Comment by gdmachado** [comment]
That's awesome to hear that this is in the backlog. I imagine most of the userbase comes from linux, but since I also develop in Mac it would be nice to have.

As a temporary workaround, do you see any sort of security issue in using the "old" Mullvad client in https://mullvad.net/media/client/Mullvad-67.dmg under MacOS 10.13 (since I believe this is possible under this older version)?

**Comment by faern** [comment]
If you want multihop/bridges I recommend you follow the guides on our website. For any further support please contact support@mullvad.net

**Comment by faern** [comment]
The app has built in bridge support, which essentially means multihop. Please see this guide: https://mullvad.net/en/help/how-use-bridge-mode/

It's still not possible to add custom OpenVPN argument and we don't really plan on doing so since it's easy to mess things up.

Closing this issue now since the multihop part of it is resolved. Here is another (yet open) issue that talks about custom OpenVPN arguments, for a different reason #1471
