### ISSUE TITLE
Windows: RPC address file cannot be retrieved

### ISSUE THREAD

**Issue by Lorentzen1337** [mullvad/mullvadvpn-app#336]
Hi!
I'm having problems logging in although I am pretty sure the problem is regarding to the following loop I get in the frontend.log:

> [2018-07-30 23:14:57.123][debug] Waiting for RPC address file: "C:\ProgramData\Mullvad VPN\.mullvad_rpc_address"
> [2018-07-30 23:14:57.324][debug] Read RPC connection info ws://127.0.0.1:49683
> [2018-07-30 23:14:57.325][info] Connecting to websocket ws://127.0.0.1:49683
> [2018-07-30 23:15:02.028][info] The websocket connection closed with code: 1006
> [2018-07-30 23:15:02.028][debug] Lost connection to daemon: Abnormal closure

This repeats itself every time I start the app even without trying to log in.
I am rocking an old 12 digit account but still I do not think the log in part itself is the problem.
Latest beta2 version is being used.

**Comment by pronebird** [comment]
Hi, 

Could you please open Settings from Login screen, click "Report a problem" and send us a report with anonymized logs?

**Comment by Lorentzen1337** [comment]
Done 👍

**Comment by Lorentzen1337** [comment]
Fixed when installing latest beta3 version.
