### ISSUE TITLE
Feature request: Show connection info upon hovering over the system tray icon

### ISSUE THREAD

**Issue by onchov** [mullvad/mullvadvpn-app#3368]
## Issue report

Operating system: all desktop (Windows & Linux)

App version: 2021.6

### Issue description

Steps to reproduce:
1. Connect to any VPN location in Mullvad so the system tray icon is displayed as a locked padlock.
2. Hover mouse pointer over the system tray icon.

Existing result:
A label is displayed with the text 'Mullvad VPN' or something similar.

Expected result:
A label is displayed with the connection info (Mullvad VPN, location, server name, elapsed time etc).

Reasoning:
Currently, to access the connection information, one needs to actually open the app. Simply  hovering over the system tray icon would be a convenient way to check it at a glance.

**Comment by raksooo** [comment]
This sounds like a good idea to me. I've added it to our internal backlog.

**Comment by raksooo** [comment]
@onchov It's now been implemented in the PR linked above and will be part of the next app release.

**Comment by onchov** [comment]
Thanks!
