### ISSUE TITLE
Map animation looks terrible on macOS

### ISSUE THREAD

**Issue by matiaskorhonen** [mullvad/mullvadvpn-app#3387]
## Issue report

Operating system: macOS 12.2.1

App version: 2021.6

### Issue description

The map animation on connection looks terrible because of the low FPS, possibly due to the animation not getting hardware accelerated. It's hard to say what exactly is causing the poor performance without properly debugging the app. This has been the case on macOS as long as I've been using Mullvad.

https://user-images.githubusercontent.com/43314/155852220-4d57c3d3-f4f1-474a-bed9-8f4d5503c883.mp4

**Comment by raksooo** [comment]
Thanks for reporting this. We are aware of this problem and plan to fix it pretty soon.

**Comment by aexvir** [comment]
still happening on 2022.2 😕

**Comment by sebastianbuzar** [comment]
Almost 8 months later it's still present on 2022.4 :(

https://user-images.githubusercontent.com/115063598/193995386-9c561ea0-8429-4bb4-bb26-d143ef2228d6.mp4

**Comment by au-ganymede** [comment]
> Thanks for reporting this. We are aware of this problem and plan to fix it pretty soon.

Almost 8 months later it's still present on 2022.4 :-(


https://user-images.githubusercontent.com/115064696/193996840-41ada35c-d1fb-4505-a186-7e2a71b33589.mp4

**Comment by soast** [comment]
And on 2022.5 unfortunately.

Was searching for ways to disable the animation and stumbled upon this issue. 
Maybe if it's not easy to fix, maybe just disable it for mac? It's all about perception, especially for pedantic mac users (like myself), this implicitly tells me the Mullvad app is a resource hog (while it may not be, it feels that way because of this animation for me). Maybe it's an exaggeration but as you can see from the issue and +1's we're not alone in this :)

**Comment by sebastianbuzar** [comment]
> Thanks for reporting this. We are aware of this problem and plan to fix it pretty soon.

@raksooo Any update on this issue?

**Comment by au-ganymede** [comment]
> Thanks for reporting this. We are aware of this problem and plan to fix it pretty soon.
@raksooo Any update on this issue?

**Comment by raksooo** [comment]
@au-ganymede No update yet unfortunately. We'll make sure to provide an update here when this has been fixed/improved.

**Comment by olmoh** [comment]
We released a new version of the map in version [2024.1](https://github.com/mullvad/mullvadvpn-app/blob/main/CHANGELOG.md#changed-7), it should now be more performant and look a bit better. If you are still experiencing problems with the map please add a new issue.
