### ISSUE TITLE
[Suggestion-Android] Add Full Sensor Rotation

### ISSUE THREAD

**Issue by RockyJE** [mullvad/mullvadvpn-app#3395]
Android 11
Mullvad v2022.1 (22010099)

Please add to your app 'allow all screen rotations' or 'follow device rotation' (**screenOrientation="fullSensor"**, from what I understand). This should allow all screen rotations/follow device rotation. I currently have to use 3C Toolbox's Rotate>Sensor orientation to make this possible.

Because of a physical limitation I have to use my tablet 'upside down', which requires an app to rotate 180° for it to be easily usable. Unfortunately, there is not yet an accessibility setting for Android to override an apps' inability to rotate all four ways, so it is up to app developers to correct this oversight.

**Comment by albin-mullvad** [comment]
Thanks for the suggestion, I've added this to our backlog.

The change might require more work than just updating the manifest due to how [configuration changes are handled in Android](https://developer.android.com/guide/topics/resources/runtime-changes), but we'll definitively look into this.

**Comment by Rawa** [comment]
This has now been merge to main, it should be in the next upcoming release.

Thanks for reporting!

**Comment by albin-mullvad** [comment]
Here's a link to the first beta for the upcoming release that includes support for this: https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2024.1-beta1
