### ISSUE TITLE
Feature request: App not properly marking network as down when in airplane mode

### ISSUE THREAD

**Issue by Pauler221** [mullvad/mullvadvpn-app#3408]
When Always-on VPN is enabled but the phone is in airplane mode or WiFi and cellular data are both turned  off (when theres no network connection) the mullvad app doesn't mark the network as down hence other apps and services report the inability to resolve host.

**Comment by albin-mullvad** [comment]
Thanks for reaching out! Can you share an example or documentation of this?

**Comment by Pauler221** [comment]
A New OS update seems to have fixed this issue.
