### ISSUE TITLE
Missing app from split tunneling

### ISSUE THREAD

**Issue by adrianmihalko** [mullvad/mullvadvpn-app#3416]
## Issue report

Operating system: Android TV

App version: 2021.1

### Issue description

I installed HBO Max and it is missing from the app list in Split Tunneling menu. All other installed apps are here.

**Comment by faern** [comment]
Thanks for reporting this. Could you please specify what version of Android you are running? Can you please try to upgrade our app to `2022.1` and see if the issue persists?

**Comment by adrianmihalko** [comment]
Upgrading resolved the issue.
