### ISSUE TITLE
Re-support for Windows 8.1

### ISSUE THREAD

**Issue by carbongreat13** [mullvad/mullvadvpn-app#3417]
## Issue report

Operating system: Windows Embedded 8.1 Industry Pro
App version: 2021.6

### Issue description
Could you please support Windows 8.1 again?
Support by Microsoft is still ongoing.
If possible, I would like Mullvad to support it until [July 11, 2023](https://docs.microsoft.com/en-us/lifecycle/products/windows-embedded-81-industry).

**Comment by faern** [comment]
* Mainstream support for Windows 8 has already ended. It's currently only on extended support (for about a year more).
* Very few of our users are using Windows 8.
* Windows 8 uses the old way of signing binaries, and share a lot of the more legacy APIs with Windows 7. Windows 10+ became a bit more technically coherent.

All of these arguments put together makes it not very practical or defendable to keep supporting Windows 8. Windows 8 users can still keep using version `2021.6` of our app or switch to vanilla WireGuard or OpenVPN. Windows 8 users can still keep on using our service until it's completely unsupported by Microsoft, and even longer (not advisable), but just not with the latest versions of our app.
