### ISSUE TITLE
[ Feature Request ] Add Device Labels on WireGuard Keys Page

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#3494]
Hi, I would like to suggest adding device labels on the WireGuard keys found at https://mullvad.net/en/account/#/ports

It's been an issue if you have more than 5 devices and all of them have Mullvad and you want to troubleshoot something that requires uninstalling devices.

The problem here is that the user may forget which slot of the WireGuard key that uninstall device contains, they may also forget to manually check which WireGuard key the app uses before uninstalling.

Hence, you'll have to do a guessing game which WireGuard key to remove to re-seat the WireGuard key of the uninstalled device upon reinstallation.

If the user guess wrong and removed the WireGuard Key of a different but active device. That device will have its connection cut unless manually investigated by the user.

A more extreme example but something that could happen is that the user is forced to remove all WireGuard keys and regenerate them all per device manually.

= = =

With a Device Label, the user won't accidentally remove the WireGuard key of another active device when they want to delete a WireGuard Key.

**Comment by faern** [comment]
> Hi, I would like to suggest adding device labels on the WireGuard keys found at https://mullvad.net/en/account/#/ports

This is actually in the making! It has already been merged to our main development git branch. See #3375.

What it does is to give each Mullvad WireGuard key a random two word name. This name is then displayed in the app and will soon be displayed on the website as well. This should help you correlate apps with their corresponding keys on the website. If you uninstall the app without remembering your device name this is of course of less help, but then at least you have an easier time to check your other active devices and compare their names with the keys on the website. Please mind that during uninstall the key **should** be removed from our website (but not on mobile), see below.

> The problem here is that the user may forget which slot of the WireGuard key that uninstall device contains, they may also forget to manually check which WireGuard key the app uses before uninstalling.

This depends on your platform. But for most platforms uninstalling the app should remove the key from your account, so you don't need to do it manually. However this does not work if you don't have any working internet during uninstall of course. It also does not work on mobile (Android + iOS) where we are not allowed to execute any cleanup code before the app is simply removed. To mitigate the issue I recommend logging out of the app before uninstalling it. That way the key should be removed from our service.

**Comment by 8227846265** [comment]
> This is actually in the making! It has already been merged to our main development git branch. See #3375.

This is great. Looking forward to the release.

> To mitigate the issue I recommend logging out of the app before uninstalling it. That way the key should be removed from our service.

This is noted. I'll do this next time I uninstall Mullvad on a device.
