### ISSUE TITLE
Restore DNS Settings on Disconnect (Windows) (Feature request)

### ISSUE THREAD

**Issue by olback** [mullvad/mullvadvpn-app#352]
Instead of setting your DNS to the default setting on disconnect, use the previous configuration. I'd love if your settings were restored after being disconnected. So the primary DNS server after disconnect should be `192.168.0.202`.

Here are a few screenshots showing that the DNS settings are different before and after being connected
Before connecting:
![m1](https://user-images.githubusercontent.com/8039145/43870310-2d5d1324-9b77-11e8-910b-02ed43b56afe.PNG)
Connected:
![m2](https://user-images.githubusercontent.com/8039145/43870319-37eb634a-9b77-11e8-986f-098956776cf4.PNG)
Disconnected:
![m3](https://user-images.githubusercontent.com/8039145/43870330-3d97aa1a-9b77-11e8-9d29-cf7878b58d85.PNG)

OS: Windows 10 1803

**Comment by mvd-ows** [comment]
This is a known limitation in the current app. It will be corrected in a coming version.

Please note that if you have a static IP configured, the DNS servers will be restored correctly.

**Comment by mvd-ows** [comment]
This issue is fixed in `2018.4-beta2`. Release notes and installer available on the releases page: https://github.com/mullvad/mullvadvpn-app/releases
