### ISSUE TITLE
Icelandic translation

### ISSUE THREAD

**Issue by Trendyne** [mullvad/mullvadvpn-app#3532]
I'd like to help translate the app to Icelandic but I can't find the crowdin. [gui/locales/README.md](https://github.com/mullvad/mullvadvpn-app/blob/584a4f31cb64a4b02f81a2bade1fa99eeb4d98ca/gui/locales/README.md) doesn't list the crowdin. Since the API endpoint is https://api.crowdin.com/api/project/mullvad-app it should be https://crowdin.com/project/mullvad-app but that's a 404 for me. If it's hidden, my crowdin is strikeCunny2245

Thanks

**Comment by raksooo** [comment]
Thanks for wanting to help! We currently outsource the translations to a company specialized in translating. Unfortunately adding third party translators to this process would be a bit to complicated. It would, as for all our translations, have to be proofread by another translator and it would have to be maintained in the future.

The instructions in `gui/locales/README.md` are intended for us at Mullvad when developing the app and require permission to the crowdin project.

Unfortunately we don't plan to add Icelandic currently.

But thanks for reaching out! We really appreciate your interest in helping!

**Comment by xerta555** [comment]
@raksooo I suppose that the situation of the translations managment haven't been changed?
I ask because i would like to improve the French translation as it's actually incomplete.

I use regulary Crowding, OneSky, Transifex & Co to translate other projet(s).
Bref, let me know if Mullvad team let users participating to the translations.

**Comment by faern** [comment]
We can now accept third party translation suggestions! There is a google docs spreadsheet where users can suggest improvements. Please see our new section in the contribution guidelines! https://github.com/mullvad/mullvadvpn-app/blob/master/CONTRIBUTING.md

However, please note that we can't accept completely new languages at the moment. Only improvements to existing translations.

**Comment by xerta555** [comment]
@faern Nice news, but why the translations managing for Mullvad apps are so complex/difficult ?

**Comment by xerta555** [comment]
> Since we are a company behind this open source project, the company's reputation is on stake if we release apps containing very bad texts. So we have to take all translations via a paid for service, so we can hold someone accountable for the localization. And Mullvad pays for the translations and proofreading. So we don't want a huge set of languages to pay for that we don't think we have enough users using. If you were to add language X then we have to pay for the proofreading up front, but we also need to pay for all future translation and proofreading of new strings that are added to the app for this language X. As such, we only want to add languages where we think we have enough users to justify it.

> It's really the same as the argument for not accepting all third party code contributions: Because it comes with the cost of maintaining that code and feature indefinitely.

I understand.
It's always complicated to have open source code available to the public for an application that you have to pay to use.
