### ISSUE TITLE
[ Feature Request ] Mullvad SmartDNS

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#3558]
Hello, I would like to suggest a potential new function of Mullvad. This is similar to Windscribe's Control D (https://controld.com/teleport)

Wherein:

- Mullvad can provide a web dashboard on (https://mullvad.net/en/account/#/) where user can redirect/block certain domain while connected on Mullvad VPN+DNS.

**Use Case:**

- There are domains that blocks Mullvad VPN IP Addresses and connecting to different VPN server just to unblock these few websites is detrimental to user experience as moving away from the closest server to you may cause higher latency and/or lower internet speed.
- With this function. The user is able to unblock any domain blocked while connected to the closest Mullvad VPN server to the user and get the best user experience.
- In order for this to function properly. User must be connected to both Mullvad VPN and DNS server.

**For Example:**

- example.com is blocking Mullvad X VPN Server IP Address. To unblock it and for user to get access to example.com
- They visit https://mullvad.net/en/account/#/ and visit the page for controlling domain redirect/block.
- They put example.com to load on Mullvad Y Proxy DNS Server IP Address.
- User clear cache or close/re-open the browser to reset the browser DNS cache and visit example.com once more
- User can now visit example.com without being blocked.

**Comment by faern** [comment]
Thanks for the suggestion. This is much more of an infrastructure feature request than an app feature request. This repository is only about our app specifically. Please feel free to suggest things related to the Mullvad VPN service in general directly to our support at support@mullvad.net.
