### ISSUE TITLE
[Suggestion] Account security

### ISSUE THREAD

**Issue by 4orsak3n** [mullvad/mullvadvpn-app#3561]
Something I've always wondered about when logging into your Mullvad account from desktop or application is the fact that anyone can use the same account number to effectively log into it, without any proof that you're the owner of the "account".

A suggestion I thought would benefit Mullvads account security, would be to ask to add a password for the first login to the newly paid account number. And thereafter asking for said password to be entered in order to access the VPN.

Not sure if this has already been suggested or if there's already something similar in place, just a thought! Love the service and have been part of it for years now, thanks!

**Comment by MrChocolatine** [comment]
You may want to read:
https://mullvad.net/en/blog/2017/6/20/mullvads-account-numbers-get-longer-and-safer/

PS: I am not from Mullvad's team, just a happy customer.

**Comment by faern** [comment]
> the fact that anyone can use the same account number to effectively log into it, without any proof that you're the owner of the "account".

Knowing the account number is the proof that you are the owner. Don't let others get hold of your account number. It basically is your Mullvad password.

We know that Mullvad accounts look a bit weird compared to most other account management. But it's well tried and has worked for many years. If you keep your account number safe there should not be any issues really.

**Comment by thepwrtank18** [comment]
If they wanted an extreme, unneeded amount of security, they could send a .txt or .bin file that is just a giant account number.

**Comment by inson1** [comment]
@thepwrtank18 Longer would be better. But it doesnt have to be in file. At least 30-35 would be extreme without any file needed. 

Even my passwords are longer than 16 characters and they have email/username + they include numbers, uppercase and lowercase letters and special symbols.
