### ISSUE TITLE
Chromium based apps to crash on Fedora 36 KDE

### ISSUE THREAD

**Issue by alastortenebris** [mullvad/mullvadvpn-app#3575]
## Issue report

Operating system: Fedora 36 KDE

App version: 2022.1

### Issue description

When running the Mullvad desktop GUI, all apps that use Chrome (Steam, Discord, Element, etc) crash and no longer show up, including the Mullvad app itself.

The following is the stderr output that the Chrome apps output.
`[13502:13502:0511/111425.761076:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
[13542:13542:0511/111425.777004:ERROR:gpu_init.cc(446)] Passthrough is not supported, GL is egl, ANGLE is 
[13542:13542:0511/111425.781323:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
`

**Comment by faern** [comment]
Do you happen to have an Nvidia GPU? Nvidia + Linux != instant love. And we have tried our app under Fedora 36, it has worked fine for us. But we don't test the app on Nvidia machines. Try running the app without the sandbox and see if that helps, since the error seems to be sandbox related.

```
/opt/Mullvad\ VPN/mullvad-vpn --no-sandbox
```

**Comment by alastortenebris** [comment]
> Do you happen to have an Nvidia GPU? Nvidia + Linux != instant love. And we have tried our app under Fedora 36, it has worked fine for us. But we don't test the app on Nvidia machines. Try running the app without the sandbox and see if that helps, since the error seems to be sandbox related.
> 
> ```
> /opt/Mullvad\ VPN/mullvad-vpn --no-sandbox
> ```

I have AMD switchable graphics (Vega Integrated/Polaris Dedicated).

Running that command causes the same issue as before.

**Comment by faern** [comment]
Do you have another desktop environment installed on your machine? If so, could you try logging in to that one and see if our frontend can start? For example Gnome, xfce or something else.

**Comment by raksooo** [comment]
@alastortenebris Could you try this development build to see if it behaves differently. One change that could affect this issue is that we've upgraded from Electron 16 to 18. https://releases.mullvad.net/builds/2022.1-dev-61c0bc/MullvadVPN-2022.1-dev-61c0bc_x86_64.rpm.

Note that this is a development build that is only intended for testing. It's more likely to contain bugs and hasn't gone through the same testing and validation process as our stable releases.

**Comment by alastortenebris** [comment]
After further tests, other apps cause this same issue, so I think this issue is not a Mullvad app issue, so I will close this bug.
