### ISSUE TITLE
Windows beta app permissions/security problem (2018.2-beta3)

### ISSUE THREAD

**Issue by s0ftwhere** [mullvad/mullvadvpn-app#358]
Hello guys,

I just tried the latest beta. Great work :)

I have the following problem. When I try to install it I get an error:

"Windows cannot access the specified device, path or file. You may not have the appropriate permissions to access the item." 

I have tried installing it a few times and I couldn't. Basically I had to disable my antivirus in order for this message to disappear.

Additionally, Windows itself blocks the app as untrusted and asks me to allow it.

Is there a way for this to be fixed?

**Comment by faern** [comment]
The installer for the beta release you are trying is not signed. For the stable release we will sign it with a proper certificate. That will at least make windows itself not ask you questions, not sure if it also silences your antivirus.

**Comment by faern** [comment]
Thanks for reporting this though! Please contact us again if you have similar problems with the stable 2018.2 release later when that comes out. Glad you like the software :)
