### ISSUE TITLE
iOS Feature Request: Change port and add malware dns server to wireguard configuration generator

### ISSUE THREAD

**Issue by Dynasty-Dev** [mullvad/mullvadvpn-app#3582]
Hello, I recently discovered the mullvad vpn was blocked on a public network I use frequently. I had to use the wireguard app in order to change the port since the iOS Mullvad App doesn't have this option. The only port that worked was 123 (ntp). It would be great if you could implement a way to change the port used in the official ios app. Another thing I noticied is that theres no malware dns server on the configuration generator for mullvad. I only see option for ads, tracking or ads and tracking. Not sure if malware is intergrated into tracking but on the official clients for both mobile and desktop I see tracking, ads and malware so Id assume not. Also as I said, the only port which could unblock mullvad from the public network was 123 but the wireguard configuration generator doesn't let you choose port 123 and some others so i Had to manually do it in the wireguard ios app. That works but it would be convenient if you could set it in the generator.

**Comment by faern** [comment]
This is closely related to #2430, but just a different platform. Yes, we are working on adding the WireGuard port selection option to all platforms. Going to leave this open, so people can follow it and get notified when it's merged.

**Comment by buggmagnet** [comment]
Custom WireGuard port selection has been there for quite a while now on iOS, closing this issue.
Users can also either use a Custom DNS server (only if it's a public facing IP, [there's a long standing issue regarding LAN IPs for DNS](https://github.com/mullvad/mullvadvpn-app/issues/6594)), or trust Mullvad anti Malware DNS server.

Do feel free to open a bug report if our DNS server doesn't block some Malware that you would like to see blocked though.

Thank you for your support !
