### ISSUE TITLE
Mullvad Manjaro

### ISSUE THREAD

**Issue by laripette** [mullvad/mullvadvpn-app#3588]
I saw that there is a deb and rpm version but, could you also make a version for manjaro ?

**Comment by faern** [comment]
We don't support Manjaro and currently don't intend to. We have received so many issue reports from Manjaro users, so we know the app works quite bad there. If we supply an official build it looks like we support the distribution. Given that we don't test the app for Manjaro we don't want to make it look like we give any security or functionality guarantees there.
