### ISSUE TITLE
2022.2-beta1 returning error: mullvad-vpn

### ISSUE THREAD

**Issue by Disrooting** [mullvad/mullvadvpn-app#3595]
## Issue report

Operating system: <!-- Name AND version of operating system: **MX Linux**

App version: <!-- Version of the Mullvad VPN app you are running.: **2022.2-beta1**

### Issue description

Downloaded the latest beta using the command:

wget --content-disposition https://mullvad.net/download/app/deb/latest-beta/

then started installing it using:

sudo apt install -y ./MullvadVPN-2022.2-beta1_amd64.deb

upon installing, i received an error while processing: mullvad-vpn

tried purging the old mullvad version i had and it got removed then restarted the computer and started the install, but i kept getting the same error.

**Comment by faern** [comment]
We don't support or test the app on MX Linux. Could you maybe supply a more verbose log of the install error?

Maybe you can look at our installer scripts and try to figure out what goes wrong? PRs welcome (if they don't complicate stuff too much for platforms we actually do support). https://github.com/mullvad/mullvadvpn-app/tree/master/dist-assets/linux

**Comment by faern** [comment]
>  System has not been booted with systemd as init system (PID 1). Can't operate.

Clearly you don't use systemd. This is our only supported init system at the moment. As stated above, PRs welcome if they don't mess too much with our supported systems. And even if merged, we won't be performing any stability or security testing of MX linux internally.
