### ISSUE TITLE
Add Port 123 as a valid WireGuard port

### ISSUE THREAD

**Issue by AAraonWPaul** [mullvad/mullvadvpn-app#3600]
In the mullvad app please add port 123 as 53 and wireguard port doesn't work. It is a common port that usually works. It would be great if you add it along 53 and wireguard port. Please also add the ability to add the port in the wireguard configuration generator. Right now port 123 is not allowed on the site but I manually edited the file and its working fine.

**Comment by faern** [comment]
Port 123 is not in the currently allowed range on the servers. So we would need to get that added by the server team first. I can ask them. After that is done you could enable it with our CLI using this command:
```
mullvad relay set tunnel wireguard --port 123
```

Yes, we are working on adding the ability to set any port in the GUI just as you already can in the CLI. This is related to #2430 and #3582

**Comment by faern** [comment]
Not really yet. We are working on adding this port to the list of allowed wg ports in the API still.

**Comment by faern** [comment]
I'm going to close this.

* The requested port is now usable in the app via the CLI
* We have ongoing work to allow specifying custom ports in the GUI. This will happen and this issue does not need to be open for that specifically
* The static config generator does not support this port yet. But you can easily manually edit your static configs to use port 123. And also, website issues is not tracked in this issue tracker.
