### ISSUE TITLE
Automatic tunnel protocal always choosing openvpn

### ISSUE THREAD

**Issue by Dynasty-Dev** [mullvad/mullvadvpn-app#3601]
Operating System: Windows 10/11

Whenever tunnel protocol is set to automatic it seems like mullvad always chooses openvpn. Not only does it happen to me I've seen a couple of people say this and I looked up some youtube reviews and it seems like they have openvpn as well since the server name doesn't have wireguard

**Comment by faern** [comment]
Yes, this is how it currently works on Windows. We will move over to having WireGuard be the default protocol (with fallback to OpenVPN) on Windows in just a few releases. Then all three desktop platforms will work the same. But currently OpenVPN (with no fallback to WireGuard) is how it works on Windows. If you want to use WireGuard you have to select that under the advanced settings.
