### ISSUE TITLE
[Feature Request - Android] Filter by Provider on Server List

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#3606]
Hello, please add the `Filter by Provider` feature that is available on Mullvad Desktop App to the `Mullvad Android App`.

There are servers that have 10 Gbps on the country that I usually connect in, and I like it to cycle to each of the 10 Gbps servers instead of alternating between the 10 Gbps and 1 Gbps servers on the `Android` app for a more consistent connection experience.

**Comment by 8227846265** [comment]
Please disregard, the title edits. :)

**Comment by faern** [comment]
This is in the backlog. But we must first finish the device concept and a few other stuff before we can get to this on Android :)

Also, are you actually experiencing worse performance on the 1 gbit servers in practice? A phone usually does not need extreme bandwidth. I don't have the bandwidth usage graphs in front of me, but I doubt the 1 gbit servers are fully loaded.

**Comment by 8227846265** [comment]
@faern - My issue is actually related to peering. The 10 Gbps server provider has better peering than the 1 Gbps server provider with my ISP and 3rd party DNS.

**Comment by albin-mullvad** [comment]
We've now released a beta with the `Filter by Provider` functionality, so please try it out and let us know what you think!

Beta release: https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2024.1-beta1
