### ISSUE TITLE
Doesn't install on Fire Stick 4K

### ISSUE THREAD

**Issue by Spaxly** [mullvad/mullvadvpn-app#3616]
Operating system: Fire OS For Fire Stick 4K
Version of App: Trying to install Latest Release

I am unable to install Mullvad VPN on my Fire Stick 4K. I am updated and have no updates available at the moment. The error I receive when trying to install is `There was a problem parsing this package`. I have tried to download with Downloader which is the go-to way for me to install APK's. Any help on this?

**Comment by Spaxly** [comment]
> Sadly the Fire Stick is using a too old Android version as its base most of the time. If you are able to install Fire OS 7 or 8 it might work better! Our app only works on Android 8+, but Fire OS <7 uses older Android than that.

Is there any other way to use Mullvad VPN on Fire OS 6?

**Comment by faern** [comment]
I suggest you ask our support directly on support@mullvad.net. Our app won't work on it. Thank you
