### ISSUE TITLE
prebuild.sh violates POSIX

### ISSUE THREAD

**Issue by carbongreat13** [mullvad/mullvadvpn-app#3617]
### Issue description
[The sheban of prebuild.sh](https://github.com/mullvad/mullvadvpn-app/blob/13f1ec7a6135c33bb60e39641de61657b6c7ba6a/ios/prebuild.sh#L1) is for POSIX sh.

However, [line 13](https://github.com/mullvad/mullvadvpn-app/blob/13f1ec7a6135c33bb60e39641de61657b6c7ba6a/ios/prebuild.sh#L13) violates POSIX. This can be checked with [checkbashisms](https://packages.qa.debian.org/d/devscripts.html).
The script must be modified to be POSIX compliant.

**Comment by faern** [comment]
> The script must be modified to be POSIX compliant.

Can you please explain why you feel like the script must be posix compliant?

What shebang would you suggest to use if we were to not change the posix compliance?

**Comment by carbongreat13** [comment]
> Can you please explain why you feel like the script must be posix compliant?

I'm not sure if the shebang is `#!/bin/sh` so. That's all. `#!/bin/sh` and the script must be POSIX compliant.

> What shebang would you suggest to use if we were to not change the posix compliance?

`#!/bin/bash`
