### ISSUE TITLE
minor spelling error in format.rs

### ISSUE THREAD

**Issue by Le-Kat** [mullvad/mullvadvpn-app#3620]
## Issue report

Operating system: Arch Linux 5.17.9-arch1-1

App version: 2022.1

### Issue description

Line 156 of file [mullvad-cli/src/format.rs](https://github.com/mullvad/mullvadvpn-app/blob/master/mullvad-cli/src/format.rs#L156) has a spelling error that reads:

> Deamon cannot block traffic from flowing, non-local traffic will leak

when I believe it's meant to say "Daemon" instead of "Deamon".

**Comment by Le-Kat** [comment]
Ok I tried doing a pull request and idk if I formatted it properly.

**Comment by faern** [comment]
Thanks. We'll look into it. I see you closed your PR, but we can easily fix the spelling internaly.
