### ISSUE TITLE
Missing JNI directory. (Build time error)

### ISSUE THREAD

**Issue by V-Mohammad-taqi** [mullvad/mullvadvpn-app#3641]
Missing JNI directory:

> Task :app:ensureJniDirectoryExist FAILED
Execution failed for task ':app:ensureJniDirectoryExist'.
> Missing JNI directory: F:\mullvadvpn-app\android\app\build/extraJni

I directly open the android directory in android studio and got this error...

**Comment by pinkisemils** [comment]
This would be fixed by invoking `build-apk.sh --dev-build` script once.

**Comment by albin-mullvad** [comment]
As mentioned by @pinkisemils, it's necessary to build the Rust daemon before a proper APK can be built. This is mentioned in the [documentation](https://github.com/mullvad/mullvadvpn-app#android-1), however it can hopefully be simplified in the future.
