### ISSUE TITLE
net_cls interfering with lxd

### ISSUE THREAD

**Issue by Miosame** [mullvad/mullvadvpn-app#3651]
## Issue report

Operating system: Arch Linux (5.18.3-zen1-1-zen)

App version: 2022.2-beta2

### Issue description

mullvad automatically mounts what I assume is a v1 cgroup for net_cls, causing lxd to not be able to start containers as it now thinks it's an unsupported/broken cgroup host, unmounting net_cls makes mullvad-exclude (obviously) not work with `No net_cls controller`

reading #1893 supposedly there's some device setting you can do, to mount net_cls elsewhere? but I could not find such setting anywhere in the beta app, what's the solution to avoid having it break lxd?

**Comment by faern** [comment]
Pleas see #3660. We have added more documentation on this now.

**Comment by Miosame** [comment]
@faern thanks! though would you be able to hint at where I should mount it to, so it doesn't interfere with v2?

**Comment by pinkisemils** [comment]
Technically any directory will work - any reasonable consumer of the old controller should be able to find it anywhere. If you believe our daemon will be the only user of the old controller, it'd be reasonable to mount it in `/sys/fs/net-cls-v1`, but Fedora mounts the V1 controller under the V2 cgroup - `/sys/fs/cgroup/net_cls`, and debian does the same.

**Comment by pinkisemils** [comment]
Yes.

**Comment by Miosame** [comment]
I guess you can't use LXD/LXC together with mullvad-exclude then, that's unfortunate, is there any workarounds for this to still be able to keep using both?

**Comment by Miosame** [comment]
oh wow I wasn't aware it can _literally_ be mounted anywhere, will try that shortly, thanks!

**Comment by Miosame** [comment]
that worked, thanks so much!

**Comment by paride** [comment]
Given that AIUI the mountpoint is arbitrary,  can't the default be changed so that it doesn't interfere with LXD?

**Comment by kkremitzki** [comment]
If I may, I don't think documentation is the proper fix for this issue. I am an Incus user who just installed the Mullvad VPN app, and I was surprised to notice that after a reboot my Incus containers stopped working, but the VMs still functioned as expected. I had to investigate this mysterious behavior and then manually implement a fix, so in a sense, it's not really fixed, its brokenness is merely documented.

**Comment by bmullan** [comment]
**_This Mullvad BUG affects users of both LXD and Incus hypervisor systems._**

Is anyone at Mullvad looking into fixing this BUG ?  Simply closing it is not the right way to handle it
and the bug has now been in existence for several years without being addressed?
