### ISSUE TITLE
[macOS] Use a black and white icon in the menu bar

### ISSUE THREAD

**Issue by rakleed** [mullvad/mullvadvpn-app#3657]
## Issue report

Operating system: macOS 12.4

App version: 2022.1

### Issue description

Use a black and white icon in the menu bar, as this is recommended in [HIG](https://developer.apple.com/design/human-interface-guidelines/components/system-experiences/the-menu-bar), and is also how all other applications are done.

![image](https://user-images.githubusercontent.com/19418601/173460541-8de7198a-6233-41dd-b9b4-6b9a2db03ac7.png)

**Comment by faern** [comment]
This is already supported. Just go to: Settings (cogwheel) -> Preferences -> Monochromatic tray icon.

**Comment by rakleed** [comment]
@faern could you make this the default behavior for a macOS app?

**Comment by faern** [comment]
I'll forward that request to the designers and frontend developers. Thanks for the suggestion.
