### ISSUE TITLE
Conflicts when having more than one TAP-Win32 adapter

### ISSUE THREAD

**Issue by davidacampos** [mullvad/mullvadvpn-app#367]
When using other VPNs, like tinc (https://tinc-vpn.org/), that also make use of TAP-Win32 adapters, the new Mullvad client is never connecting, and when uninstalling it removes ALL instances of the adapter, even the ones not added by the installer.

The old client also had some issues (like replacing the info of a previously existing adapter, when installing the client) BUT in general you were able to connect, you would just needed to have in mind that the "Mullvad TAP-Win32" adapter was going to be the 1st one (the one that got installed first, subsequent adapters were ignored). I'm not sure how the then client decides "which" adapter to use, because it seems it's not using the right one...

**Comment by faern** [comment]
Thank you for reporting this. We will look into not removing adapters not created by us.

**Comment by mvd-ows** [comment]
Please provide the necessary steps to reproduce this issue. Our uninstaller does not contain any code to remove adapters.

**Comment by davidacampos** [comment]
I no longer have access to that machine to try to reproduce it myself, but the steps were:

1- Install Tinc
2- Add the adapter from Tinc's folder (the adapter is not added automatically during Tinc's installation)
3- Install Mullvad client
4- Uninstall Mullvad client

**Comment by mvd-ows** [comment]
OK, thanks.

As I mentioned previously, the uninstaller for the new app doesn't remove any adapters. However, the uninstaller for the old client does remove adapters.

When you install the new app, it creates a new TAP adapter named `Mullvad` and uses this for all its tunneling needs. 

Feel free to open a new issue if you have other concerns.
