### ISSUE TITLE
Feature request: Custom naming of wireguard keys

### ISSUE THREAD

**Issue by jeth318** [mullvad/mullvadvpn-app#3673]
### Issue description

I appreciated the newly added feature that brought the automatic naming of wireguard keys. However, it would be even better to have to possibility to add a custom name to each key.

Regards / J

**Comment by faern** [comment]
Please see the last section in our blog post about these names. Unfortunately we can't do that because our goal to not store user data. A custom name is user data

https://mullvad.net/en/blog/2022/6/13/introducing-names-for-easier-device-management/
