### ISSUE TITLE
Link view "Advanced" to view "Preferences"

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/mullvadvpn-app#3690]
## Issue report

Operating system: macOS Monterey v12.4

App version: 2022.1

### Issue description

Tiny suggestion to make the desktop app even more usable:
would it be possible to make any text, that refers to another part of the app, clickable so we can reach that other part directly without navigating ourselves please?

So far, I noticed this would only apply to the section `Use a custom DNS server` in the `Advanced` view:

<table>
<tr>
  <th>Clicking on the text "under Preferences" ...
  <th>...would bring us directly to the "Preferences" view
<tr>
	<td><img width="432" alt="01 advanced" src="https://user-images.githubusercontent.com/47531779/175143916-49455ea2-63fd-4621-b002-f357ff293c03.png">
	<td><img width="432" alt="02 preferences" src="https://user-images.githubusercontent.com/47531779/175143933-dca885d2-d6ca-4600-b425-0cb4a9ea5a7d.png">
</table>

Thank you.

**Comment by faern** [comment]
Hi, thanks for the suggestion. I think this is a good suggestion in general! Just wanting to let you know that we are currently working on reorganizing the navigation overall. So this might be way less of an issue soon anyway. We are planning on getting rid of "Preferences" and "Advanced" and instead have the tree main categories "Interface settings", "VPN tunnel settings" and "Support" where we will sort stuff under a bit differently than today.

**Comment by MrChocolatine** [comment]
Wonderful, in that case feel free to close this issue :) .
