### ISSUE TITLE
Application not starts (Windows 10)

### ISSUE THREAD

**Issue by Iowerth** [mullvad/mullvadvpn-app#3694]
## Issue report

Operating system: Windows 10 ver. 1909
App version: 2022.2

### Issue description
When launch Mullvad VPN.exe then only mullvad-daemon.exe appears in Task Manager but no icon in system tray. Accordingly it is impossible to use Mullvad. After restarting PC it may be fixed or not randomly.

**Comment by faern** [comment]
By the way. You should probably update your operating system with the latest patches from Microsoft. Windows 10 version 1909 is very old, and [reached end of support back in May 2021](https://docs.microsoft.com/en-us/lifecycle/announcements/windows-10-1909-end-of-servicing). I strongly advise you to run the automatic update built into Windows.

**Comment by Iowerth** [comment]
> Please send a problem report to us using the app. Click settings -> report a problem. Then we'll get some app logs that will help us debug the issue. Please reference this github issue in the problem report message. Thank you

How can I send you logs while app not starts? There are not today's files in folder \AppData\Local\Mullvad VPN\logs\

**Comment by faern** [comment]
I thought you said it was sometimes randomly working? If it is, you can send the report when it works.. But if you don't have any files at `~\AppData\Local\Mullvad VPN\logs\` then it will likely not help, since there are no logs. What if you try starting it from a console?

* Open `cmd.exe`
* Run `"C:\Program Files\Mullvad VPN\Mullvad VPN.exe"

What output do you get?

**Comment by faern** [comment]
That looks correct. Are you sure there is no tray icon with a lock in your system tray? Check in the drawer that you expand with the arrow. Our tray icon is not the Mullvad logo, but rather a padlock :lock:, look for that.

But you should also run Windows update, seriously :)

**Comment by faern** [comment]
Then maybe the shortcuts in your start menu are broken/pointing at the wrong files? Check where they link to and/or try reinstalling the app maybe?

**Comment by Iowerth** [comment]
Don't worry, you have already helped a lot with method when start app from cmd. I will use it when it will be needed.
Seems smth wrong with my OS.
