### ISSUE TITLE
Compilation of mullvad-vpn-cli 2022.2-1 fails on Arch Linux

### ISSUE THREAD

**Issue by JulianOestreich90** [mullvad/mullvadvpn-app#3697]
I'm trying to build aur/mullvad-vpn-cli  2022.2-1 on Arch Linux with yay. I always run into errors while the compilation. I tried deleting my cache folders and run a clean build but i always run into errors like in the screenshot:

![mullvad_compile](https://user-images.githubusercontent.com/19915127/175341009-892175c9-5e9b-4c84-8e3d-0e7fd376c0ea.png)

**Comment by pinkisemils** [comment]
You should update your rust compiler, as of [1.58](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#captured-identifiers-in-format-strings) format strings can refer to variables in the callers scope.
