### ISSUE TITLE
Android request : Add automatic connect on system startup 

### ISSUE THREAD

**Issue by lucafont2** [mullvad/mullvadvpn-app#3699]
## Issue report

Operating system: MIUI 12.0.3 Android 10

App version: 2022.1

### Issue description

Right now the app does not have an option to enable automatic connection on Android restart. This is concerning because after my battery ran out, i did not notice the app was not running for a while after the restart. 
If the feature is already present then is not working on my device

**Comment by MrChocolatine** [comment]
_I have Android 12 so I am not sure my answer will help you but I hope it will._

The only time I noticed Mullvad was not running after a restart was when I disabled this setting:
Android settings > Network and Internet > VPN > Cogwheel on Mullvad VPN > Always-on VPN

Apparently Android 10 should have this option as well:
- https://support.google.com/work/android/answer/9213914 > See section "Always-on VPN"
- https://support.google.com/android/answer/9089766#always-on_VPN

Also, in Mullvad you have the setting "Auto-connect (Auto connect when the app launches)":
Mullvad settings > Preferences > Auto-connect

**Comment by lucafont2** [comment]
> _Simple customer here._ _I have Android 12 but I hope my answer will still be helpful._
> 
> The only time I noticed Mullvad was not running after a restart was when I disabled this setting: Android settings > Network and Internet > VPN > Cogwheel on Mullvad VPN > Always-on VPN
> 
> Apparently Android 10 should have this option as well:
> 
> * https://support.google.com/work/android/answer/9213914 > See section "Always-on VPN"
> * https://support.google.com/android/answer/9089766#always-on_VPN
> 
> Also, in Mullvad you have the setting "Auto-connect when the app launches": Mullvad settings > Preferences > Auto-connect

Thanks, this fixed the issue. I already had the "automatically turn on" option simply the app was not in the system startup.

But I don't know if this workaround is viable also for old android users.

**Comment by faern** [comment]
As pointed out above, you should enable the system setting *Always-on VPN* for having the app automatically start. Please see these instructions in our Android guide: https://mullvad.net/en/help/using-mullvad-vpn-on-android/#connect-automatically
