### ISSUE TITLE
iOS/iPadOS unreliable connections, new information as Beta expires

### ISSUE THREAD

**Issue by narration-sd** [mullvad/mullvadvpn-app#3701]
I've been after this for a long time, and have written you a detailed report of this problem as it stands with the most recent Beta, which disappeared without replacement this morning here.

The report is here: https://github.com/mullvad/mullvadvpn-app/issues/2622#issuecomment-1167772891, and I'm marking it by a new issue to assure that it doesn't get overlooked and lost.

This report has some details that should be very interesting to a responsible person.

II also includes notes on a solution working forward from what you are trying already, which one might feel can make a solid repair.

Also some gentle humor, after directness to purpose, a wink to all those persons on your end :)

I hope you enjoy...

**Comment by faern** [comment]
You can just get the latest version from App Store. We don't have any beta. Well, we had, but it worked fine, so we published it to App Store. It's the exact same version.

**Comment by narration-sd** [comment]
p.s..
- the fresh Windows beta is in, and as expected,, seems to work fine
- just a note, on 'professional' above, except I won't.  You might understand yourself, that I am generationally and of depth, experienced. I am trying to help, in that way many managing directors have partnered me to do. Please try to use that, thanks.

**Comment by faern** [comment]
The TestFlight build expired. Yes. Download the app from the App Store. TestFlight builds always expire after 90 days, that's how TestFlight works. Maybe it would be smoother if we released an app more often than every 90 days, but currently we don't.

Was there any other issue? The only issue I found in your description was that "TestFlight build is gone, what to do?"

**Comment by pronebird** [comment]
@narration-sd Thanks for reminding us of those issues. Right now we only run tests when connecting. We intend to add periodic connection test to determine if the tunnel is functional once connected.  This should perhaps solve some of the issue that you have described.

**Comment by narration-sd** [comment]
It does sound it could get complicated, especially given uncertainties in Apple's approval and release step.

I guess if you wanted to do it, some automation in the packaging step to set the clock, and a sufficient lead time for worst-case 90 days might get you there. 

Another way I've seen people use is to simply release again if time is running out on a beta that's still in progress.

**Comment by narration-sd** [comment]
Just a small thought here, as the 2022.4 release with MTU fix was just installed, and immediately sowed the highest speed ever on the local wifi connection.

So it''s natural to wonder if this wouldn't be an important thing to assure gets into the iOS/iPadOS version -- given Apple APIs let you. I hadn't thought about it, but mismattched MTU could I think cause some amount of the issues I keep seeing...always up-to-date with your betas or releases.

Other than that, hope you are enjoying what looks like a fine summer from photos a friend sends -- a little warm also, it's understood... 🌿

**Comment by faern** [comment]
The iOS version of our app did not have the MTU bug that Linux 2022.3 had. So the same fix is not needed on iOS. That said, we could of course still set a too high MTU in some scenarios indeed. The plan is to add better automatic MTU detection and the possibility to manually set it on all platforms. It's in the backlog.

**Comment by buggmagnet** [comment]
Hello,

I'm closing this as it is a very stale issue at this point. Please re-open a new issue if you still experience a similar with the latest available builds.
