### ISSUE TITLE
Connection failure in new beta

### ISSUE THREAD

**Issue by masadas** [mullvad/mullvadvpn-app#3702]
The message that the dns setup failed is displayed and the connection fail. 
It was tested in wireguard and openvpn
OS is Windows 11.

![화면 캡처 2022-06-28 045703](https://user-images.githubusercontent.com/108301010/176025485-95347962-3c33-4aa1-88ad-862cc3f181b1.png)
.

**Comment by faern** [comment]
Please send a problem report from within the app: Settings (cogwheel) -> Report a problem. That will send redacted logs to us to help us find the issue. Please explain in the problem report message any special setup you might be having.

**Comment by xerta555** [comment]
Exactly same problem.
It's a critical problem.

My logfile: [dc97db88-bfde-46c4-a2c9-7f9c6ff7e0cf.log](https://github.com/mullvad/mullvadvpn-app/files/9003718/dc97db88-bfde-46c4-a2c9-7f9c6ff7e0cf.log)

Need a fix ASAP

**Comment by ianusa** [comment]
Same issue here and rolled back to the official release.

**Comment by faern** [comment]
> Need a fix ASAP

This is a beta. If it does not work well for you, please roll back to the last stable release.

We are looking into this issue. We won't release this app as stable before it has been fixed.

Thanks for the logs.

**Comment by xerta555** [comment]
It is true that the urgency is not totally justified, hoping that a solution is quickly found.

**Comment by xerta555** [comment]
I test it in 2-3 hours.

**Comment by masadas** [comment]
It seems to be working fine.
Thank you.

**Comment by faern** [comment]
I'm glad to hear that the new beta seems to fix the issue! I will close this issue then.
