### ISSUE TITLE
question about  Update mullvad in f-droid

### ISSUE THREAD

**Issue by winterwolf45** [mullvad/mullvadvpn-app#3714]
Hi thanks for created this project 

I need to know why mullvad android client isn't update into f-droid ?
( sorry because of I need use openvpn client mullvad alternative wireguard into app mullvad and it's just possible with version 2022.2 but in f-droid it's version is 2022.1)

**Comment by pinkisemils** [comment]
As of the 1st of July 2022, `2022.1` is the latest Android version.
