### ISSUE TITLE
Unable to verify GPG of Mac OS app

### ISSUE THREAD

**Issue by pavelgrib** [mullvad/mullvadvpn-app#3723]
## Issue report

Operating system: Mac OS 12.3.1 on M1 Silicon

App version: MullvadVPN-2022.2

### Issue description

I decided to follow the steps to [verify signatures](https://mullvad.net/en/help/verifying-signatures/) after downloading the  Mac OS installation bundle.  I brew-installed gnupg, then added the Mullvad code signing key and set the trust to 5.  When I try to verify the .asc file for the 2022.2 package, I get this:
```
$ gpg --verify MullvadVPN-2022.2.pkg.asc
gpg: no signed data
gpg: can't hash datafile: No data
```

Am I doing something wrong or is there an issue with the keys?  Thanks.

**Comment by faern** [comment]
Is the file `MullvadVPN-2022.2.pkg` placed in the same directory? Try explicitly specify the file that is signed, instead of having gpg guess it: `gpg --verify MullvadVPN-2022.2.pkg.asc MullvadVPN-2022.2.pkg`

**Comment by pavelgrib** [comment]
Ugh, thank you very much, I re-downloaded the pkg file and pointed gpg to it.
