### ISSUE TITLE
Add option to disable split tunneling in the daemon through a CLI flag

### ISSUE THREAD

**Issue by GGG-KILLER** [mullvad/mullvadvpn-app#3737]
## Issue report

Operating system: NixOS 22.11

App version: 2022.1

### Issue description
I'm trying to run mullvad inside a container with wireguard and `systemd-nspawn`, however, because of split tunneling attempting to use cgroups, I've been unable to use it since split tunneling was introduced.

An option to disable split tunneling in the daemon would be very helpful since I haven't been able to find a way to make the mullvad app work inside systemd-nspawn containers.

**Comment by GGG-KILLER** [comment]
In the end I've just stopped using the mullvad app and switched to raw wireguard.

**Comment by MarkusPettersson98** [comment]
Okay, that's understandable. I don't see us investigating this if we don't receive more reports about it, so I'll close this issue for now. If you or anyone else want to, we can always re-open it in the future.
