### ISSUE TITLE
App spams notifications on Windows 11

### ISSUE THREAD

**Issue by ggtylerr** [mullvad/mullvadvpn-app#3754]
## Issue report

Operating system: Windows 11 Home

App version: 2022.4

### Issue description

Whenever the app is connecting / reconnecting, it spams the notifications: 
![image](https://user-images.githubusercontent.com/28498877/179409078-c330ca19-86f9-4d6e-ad8f-4e0f1adf106c.png)

**Comment by raksooo** [comment]
Thanks for reporting this. It should remove the previous notifications when a new one is shown. I'll add this to our backlog and update here when we investigate/fix it.

**Comment by QLaughable** [comment]
This bug recently started appearing for me on 2023.3 - worth noting that I have notifications turned off, setting seems to be ignored now

**Comment by faern** [comment]
@QLaughable Version 2023.3 has a bug that inverts the logic for notifications. We have important and less important notifications. And the notification setting should only disable the less important ones. But the logic was flipped. So currently you only see the unimportant notifications and not the important ones. This has been fixed and we are working on pushing a new beta soon.

**Comment by raksooo** [comment]
@maritz We've fixed that and will include it in the next version as well. In the meanwhile you can quit and restart the app when this happens.

**Comment by raksooo** [comment]
We've now released a beta that should fix the issues mentioned in here. Please try it out and let us know if these issues persist: https://mullvad.net/download/beta. I'll close this issue but if you're still having issues we'll reopen it.
