### ISSUE TITLE
Have a plan for Inverse Split Tunneling ?

### ISSUE THREAD

**Issue by donut88** [mullvad/mullvadvpn-app#3760]
## Issue report

Operating system: windows10

App version: MullvadVPN-2022.3-beta2.exe

### Issue description

I want Inverse Split Tunneling(Protect only selected devices or applications. Everything else flows outside the VPN.)
Do you have any plans for this ?

**Comment by raksooo** [comment]
Thanks for your feedback. There's another issue discussing this: https://github.com/mullvad/mullvadvpn-app/issues/2808. I'll close this since it's a duplicate.
