### ISSUE TITLE
mullvad-daemon fails to delete the wg-mullvad interface after disconnecting

### ISSUE THREAD

**Issue by amoebaguy** [mullvad/mullvadvpn-app#3768]
## Issue report

Operating system: Fedora Linux 36, Kernel 5.19.0-0.rc7.53.fc37.x86_64
App version: 2022.3-beta2

### Issue description

mullvad-daemon fails to delete the wg-mullvad interface after disconnecting due to receiving a netlink error on kernel 5.19.x. This is because of a bug in the [rust netlink library](https://github.com/little-dude/netlink) used here https://github.com/mullvad/mullvadvpn-app/blob/baa4802b2e31b55133b3e8fc4ad5058a8ffd0496/talpid-core/Cargo.toml#L59

It got fixed and merged recently: https://github.com/little-dude/netlink/pull/274.

Podman/netavark had to deal with the same issue https://github.com/containers/netavark/issues/345.

**Comment by pinkisemils** [comment]
Thanks for the report, we'll try to update the dependency ASAP.

**Comment by amoebaguy** [comment]
> Thanks for the report, we'll try to update the dependency ASAP.

I built master with https://github.com/mullvad/mullvadvpn-app/pull/3775 applied and gave it a test. It unfortunately still fails to remove the interface after a disconnect on 5.19.0-rc7.

```log
mullvad-daemon[22467]: [mullvad_daemon][DEBUG] Target state Secured => Unsecured
mullvad-daemon[22467]: [talpid_core::dns][INFO] Resetting DNS
mullvad-daemon[22467]: [talpid_core::routing::imp::imp][DEBUG] Clearing routes
mullvad-daemon[22467]: [mullvad_daemon][DEBUG] New tunnel state: Disconnecting(Nothing)
mullvad-daemon[22467]: [talpid_core::tunnel::wireguard::wireguard_kernel::netlink_tunnel][ERROR] Failed to remove WireGuard device: Failed to delete device
mullvad-daemon[22467]: [talpid_core::tunnel::wireguard][ERROR] Error: Failed to stop tunnel
mullvad-daemon[22467]: Caused by: Failed to start wireguard tunnel
mullvad-daemon[22467]: [talpid_core::tunnel_state_machine::connecting_state][DEBUG] Tunnel monitor exited with block reason: None
mullvad-daemon[22467]: [talpid_core::firewall][INFO] Resetting firewall policy
mullvad-daemon[22467]: [talpid_core::firewall::imp][DEBUG] Removing table and chain from netfilter
mullvad-daemon[22467]: [mullvad_daemon][DEBUG] New tunnel state: Disconnected
mullvad-daemon[22467]: [mullvad_daemon::management_interface][DEBUG] get_current_location
```

**Comment by amoebaguy** [comment]
I was going to debug this issue a little more and noticed https://github.com/mullvad/mullvadvpn-app/pull/3775 was marked as merged into master but I couldn't find the actual changes in master or any reference to the PR commit. Was this somehow reverted?

**Comment by pinkisemils** [comment]
It was reverted, yes. I can replicate that the updated netlink crates still fail to remove the device. I'll see about fixing that.
