### ISSUE TITLE
Question: Imgur only blocked on some of my devices

### ISSUE THREAD

**Issue by goodboi69691** [mullvad/mullvadvpn-app#3814]
This isn't an issue per say but with the desktop vpn, imgur.com is blocked, but not when connected to mobile vpn the Imgur app works fine. Why?

**Comment by Evernow** [comment]
You just happen to be assigned a different IP address on the different device.

**Comment by faern** [comment]
Yeah, this is probably due to exiting via different servers/IPs. And imgur might block one, but not the other. Try changing between a few servers on the device where imgur is blocked and see if it helps.
