### ISSUE TITLE
New graphical user interface GUI

### ISSUE THREAD

**Issue by Pantyhose-X** [mullvad/mullvadvpn-app#3815]
Suggestion graphical user interface GUI usr https://github.com/dioxuslabs/dioxus
Introducing [Dioxus](https://github.com/dioxuslabs/dioxus): a React-like library for building fast, portable, and beautiful user interfaces with Rust. Runs on the web, desktop, mobile, and more.

Implement 100% rust language client

**Comment by faern** [comment]
Thank you for the recommendation. We will eventually evaluate possible UI frameworks to rewrite the frontend in. I can't give any time estimate for when this will happen. But we are collecting a list of possible alternatives. I have now added this library to that list.

I'm going to close this issue as it's not really tracking anything, it's more of a suggestion.
