### ISSUE TITLE
iOS app requires 12 digit account number to log in, account number is 10 digits long

### ISSUE THREAD

**Issue by rafalstapinski** [mullvad/mullvadvpn-app#3816]
## Issue report

Operating system:  iOS 16

App version:  2022.2

### Issue description

The ability to log in on the iOS app is only enabled once you type in a minimum of 12 digits. Unfortunately my account number is 10 digits long. The minimum input length to enable the "Log In" option should be lowered to 10.

**Comment by faern** [comment]
Hi! Thank you for being a long time customer :) We moved to 16 digits many years ago. This was to increase the security and make it harder to guess/brute force an account. You should probably generate a new account then. If you have a lot of time on your account you can contact support@mullvad.net and they will help you move the time over to a new account.

We want to increase the number of digits required for the login button to be enabled, not lower it :p we are just waiting for the remaining few old accounts to expire/be migrated.

**Comment by rafalstapinski** [comment]
Thanks for the response - justification totally makes sense. I'll migrate my account over!
