### ISSUE TITLE
Your privacy might be at risk with this unsupported app version

### ISSUE THREAD

**Issue by lordcyb3r** [mullvad/mullvadvpn-app#3819]
## Issue report

Operating system: windows 11

App version: Mullvad 2022.3-beta3-dev-4a1b73

### Issue description

Just need some clarification on this message that the add shows after building the latest dev build and installing.

"Your privacy might be at risk with this unsupported app version".

Is this something to worry about or is it just related to the fact that this is a dev build?

Thanks in advance!

**Comment by faern** [comment]
This is just because it's a dev build. We cant guarantee the security or stability of development builds
