### ISSUE TITLE
macos 13 beta causes immediate freeze

### ISSUE THREAD

**Issue by pozm** [mullvad/mullvadvpn-app#3824]
## Issue report

Operating system: MacOS 13.0 beta (22a5311f)

App version: 2022.3

### Issue description

Open opening the app just stops responding, the only way to make it close is to forcefully kill it.
i think one of the new macos updates caused such to happen since this issue is brand new.

https://user-images.githubusercontent.com/44528100/183723114-d67556eb-483c-4ea8-b7b2-ea119e4f0341.mov

**Comment by faern** [comment]
Thanks for reporting this! We have tried macOS 13 and it works for us. So we need to figure out what's different on your machine. Could you try to run the app's frontend from a terminal, to capture the output (I can provide more detailed instructions later if you don't know how to do it).

.. And also send a problem report, please. Even if the frontend does not start, you can collect and send a problem report with these two commands if you open the terminal:

```
mullvad-problem-report collect --output mullvad-report.log
mullvad-problem-report send --report mullvad-report.log
```

**Comment by pozm** [comment]
Sorry for not sending a problem report, i was unaware you were able to from within the terminal, since your guide specifies to do so through the gui. I have now sent the report.

as for terminal output when running it:

```
Mullvad VPN.app/Contents/MacOS🔒 took 16s
❯ ./Mullvad\ VPN
[2022-08-10 11:53:15.579][verbose] Chromium sandbox is enabled
[2022-08-10 11:53:15.583][info] Running version 2022.3-beta3
[2022-08-10 11:53:15.628][info] Detected locale: en-GB
[2022-08-10 11:53:15.644][info] Connected to the daemon
objc[33919]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x234b82e50) and /Applications/Mullvad VPN.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x109cd13c8). One of the two will be used. Which one is undefined.
Error returned: <dictionary: 0x1fc6375b0> { count = 1, transaction: 0, voucher = 0x0, contents =
	"XPCErrorDescription" => <string: 0x1fc637748> { length = 18, contents = "Connection invalid" }
}
[2022-08-10 11:53:15.925][info] Skip autoconnect because GUI setting is disabled
```

**Comment by raksooo** [comment]
@pozm Could you try running the app with `--disable-gpu`?

**Comment by pozm** [comment]
The output has changed, but it still hangs.
```
❯ ./Mullvad\ VPN --disable-gpu
[2022-08-10 14:20:39.220][verbose] Chromium sandbox is enabled
[2022-08-10 14:20:39.226][info] Running version 2022.3-beta3
[2022-08-10 14:20:39.344][info] Detected locale: en-GB
[2022-08-10 14:20:39.361][info] Connected to the daemon
objc[34759]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x234b82e50) and /Applications/Mullvad VPN.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x109bf93c8). One of the two will be used. Which one is undefined.
```

**Comment by raksooo** [comment]
@pozm Okay, thanks. Are you using an x86 or arm mac?

**Comment by pozm** [comment]
I am using arm.

**Comment by raksooo** [comment]
I just tested running the app on macOS 13 beta 5 (22a5321d) on an M1 Mac mini and both 2022.2 and 2022.3-beta3 runs fine for me. Could you update to macOS 13 beta 5 to see if it makes any difference? Did you run previous betas? Did it work on them?

**Comment by pozm** [comment]
Yep updating to the latest has fixed the issue for me. i ran all betas and only broke after 2rd one i think, very odd that you weren't able to replicate though.

**Comment by raksooo** [comment]
I don't think we've tried running the app on 22a5311f so it might be that that's the only beta with the problem. Great that it works now, hopefully it continues to work throughout all betas 🤞 Thanks for taking your time to try our suggestions!

**Comment by MrChocolatine** [comment]
Completely unrelated but friendly comment for @pozm :
when you record your screen you can enable an option to show your mouse clicks (while we understand you try to do that in your initial video) :v: .

![recording options](https://user-images.githubusercontent.com/47531779/184118645-c625c0ad-6070-4992-bc0e-a009ef7d8273.png)
