### ISSUE TITLE
Android APP not asking for VPN permission and just fails.

### ISSUE THREAD

**Issue by logan2k** [mullvad/mullvadvpn-app#3826]
-->

## Issue report

Operating system: <Android 9>

App version: <2022.1>

### Issue description

<
![bug](https://user-images.githubusercontent.com/79699834/183931562-e32245e2-d044-4dbd-9570-06973c8fa797.png)

As the picture shown, this is what I see immediately after click connect, it didn't even ask.
>

**Comment by logan2k** [comment]
Solved.
There cannot be an "always-on VPN" enabled for other APPs.

**Comment by faern** [comment]
Ah, yes! That's true. We aim to detect that and show a better error message. Great you were able to fix it!
