### ISSUE TITLE
Unable to communicate from a device running mullvad to devices on a statically routed subnet with local network sharing enabled

### ISSUE THREAD

**Issue by K4LCIFER** [mullvad/mullvadvpn-app#3827]
## Issue report

Operating system: Arch Linux

App version: 2022.2

### Issue description
Say you have the following network:
![image](https://user-images.githubusercontent.com/7829231/184073755-b79282ad-4d2b-4137-891e-0181db7d06ce.png)
Router A has a static route to the network of Router B, and vice versa. If Device A has Mullvad VPN running (with local network sharing enabled), it is unable to communicate to Device B, and vice versa. communication works as expected with Mullvad VPN disabled.

**Comment by faern** [comment]
You need to set up the correct routes **on Device A**. My guess is that device A only has a special route for `192.168.0.1/24` saying it's the local LAN and has no gateway. Similarly you need to add a route **to device A** to network `192.168.1.1/24` and say it's accessible via router A. If this is not there all traffic to `192.168.1.1/24` is routed via the default route, which the VPN picks up and sends in the encrypted tunnel.

Our app can't magically know what LAN networks are available behind routers etc. You need to either make router A advertise the `192.168.1.1/24` network via DHCP, or statically set that route up on device A.

**Comment by kubrickfr** [comment]
I have the same "problem" (as explained by @faern it's normal and expected), and whenever I need to access devices on "network B", I just manually add the route to the network via my router.
In your case you would need to do

`sudo ip r add 192.168.1.0/24 via 192.168.0.1`

And mullvad will leave that traffic alone if you have local network sharing enabled.

you can add these (normally useless) routes to you NetworkManager configuration too.

**Comment by faern** [comment]
I'm closing this as I think we have provided the answer to the original question.

**Comment by 05nelsonm** [comment]
Ran into this issue, too.

 - Option 1: Add static routes to device that is using Mullvad App
   ![image](https://user-images.githubusercontent.com/44778092/204904220-8aa1f677-67ca-4c6e-927b-fc7cb37f063d.png)

 - Option 2: Add static routes to the interface (LAN) via [rfc3442](https://www.rfc-editor.org/rfc/rfc3442.html)
     - Create the string value (click image below to go to calculator):
       [![image](https://user-images.githubusercontent.com/44778092/204904718-6312ab30-5c29-486f-8617-db28a563fe1c.png)](https://www.medo64.com/2018/01/configuring-classless-static-route-option/)
     - Add option 121 to interface (for example, in OPNsense)
       ![image](https://user-images.githubusercontent.com/44778092/204905474-076ac7f1-7fae-4e4a-91a0-6970c771d722.png)

After you've applied the settings, disconnect and then connect again and you should be good to go.

For my LAN I went with Option 2, but for a machine that I have on my guest network I went with Option 1 as to not broadcast my setup unnecessarily.
