### ISSUE TITLE
Where does the Mullvad app store its session data on Linux?

### ISSUE THREAD

**Issue by tommytran732** [mullvad/mullvadvpn-app#3838]
Hi,

I want to ask where the app store its session data on Linux? I am running into a problem where if I install Mullvad in a Qubes TemplateVM and log into it using an AppVM, the login is gone after a reboot. This means that I need to add a bind dir for where mullvad saves the session data to make it persistent, but I cannot seem to figure out where it is yet.

**Comment by tommytran732** [comment]
nvm, I realized it is in `/etc/mullvad-vpn`. Don't know why i only looked in `/opt/` xd

**Comment by tommytran732** [comment]
I gotta reopen this because after making /etc/mullvad=vpn persistent, it still does not remember the login. I am sure I am missing something else, but I am not sure what right now.

**Comment by faern** [comment]
The system service stores settings in `/etc/mullvad-vpn`, yes. And some cache in `/var/cache/mullvad-vpn/`, but that should not be relevant to remembering the login. The current login is in `/etc/mullvad-vpn/device.json`

Check the logs of `mullvad-vpn` to try to figure out if something went wrong after starting again. Check the contents of `/etc/mullvad-vpn/device.json` before and after reboot. If logged in, the first key in the object should be `"logged_in"` containing an `account_token` value.

**Comment by faern** [comment]
Any update on this? I'll close it since the original question has been answered. Please re-open with a specific issue or request if this is still a problem.

**Comment by tommytran732** [comment]
Yeah, sorry I forgot to close it. Turns out it was user error on my part.
