### ISSUE TITLE
App stuck "connecting to daemon"

### ISSUE THREAD

**Issue by KSundstrom** [mullvad/mullvadvpn-app#387]
I have version 2018.2 of the app installed, and if I choose "Run Mullvad VPN" right at the end of the installation, it seems to work fine, but whenever I thereafter have closed the app and try to run it again, it seems to be stuck "connecting to daemon" in the tray; if I click on the red lock icon in the tray, this is all it ever says (neither does anything generally happen when I click the cogwheel). Killing the process tree and restarting has no effect. I have tried uninstalling and installing several times. From support I got a nightly build of the app which was supposed to perhaps fix this problem, but it seems to behave the same.

**Comment by faern** [comment]
Thank you for helping us identify the issue. But please continue iterating this issue with the Mullvad support. Sending a problem report from the nightly build you got would likely help us find the source of this problem.

**Comment by KSundstrom** [comment]
Thank you, I'll try to install the nightly build again and see what I can do.
