### ISSUE TITLE
Client keeps "Connecting to daemon..."

### ISSUE THREAD

**Issue by superDuperCyberTechno** [mullvad/mullvadvpn-app#391]
Resinstalling the client will make it work again temporarily. 

Closing the client and opening it again will make the client "Connecting to daemon..." again, indefinitely.

This is for version 2018.2

**Comment by faern** [comment]
We prefer to take such support cases via support@mullvad.net. You can just send a problem report from within the app directly to automatically attach the log files and some information about what OS you are running.

**Comment by darkwebdev** [comment]
@superDuperCyberTechno man have you managed to solve the problem?

**Comment by superDuperCyberTechno** [comment]
Kinda. A total reinstall of Windows 10 made it work...

**Comment by faern** [comment]
We solved one very common problem causing it to get stuck in that view when we released `2018.3`. So please upgrade to the latest version of this app if you are still experiencing this issue. Closing since `2018.3` should solve it.
