### ISSUE TITLE
Split tunneling no longer working for multiple instances of programs

### ISSUE THREAD

**Issue by RedCard1nal** [mullvad/mullvadvpn-app#3921]
Operating system: Windows 11

App version: Discovered issue on 2022.3, but it persists on 2022.4 and 2022.2

### Issue description

Today I found that split tunneling was no longer working for certain programs, specifically programs that I run in multiple instances. I run multiple instances of both qbittorrent and firefox and found that only one of each program instacces would obey my split tunneling rules. Typically I run Firefox #1 outside of the tunnel and Firefox #2 inside. Both qbittorrent #1 and #2 are inside the tunnel. Now, firefox #2 will not be tunneled and qbittorrent #2 will not use the vpn tunnel.

I did some troubleshooting with firefox #2 and found that if I open the program while Mullvad is active with split tunneling turned on, then it won't be tunneled. I can check my ip with speedtest and even the mullvad connection checker says I'm not using mullvad even though I am. If I disconnect and reconnect from the vpn then it will start being tunneled, and once I close and reopen again it leaves the tunnel.

Also, if I disable split tunneling completely then connect to the vpn I can get both qbittorrent #1 and #2 to use the vpn.

I'm at a loss for what's going on because I did not update Mullvad client before noticing this issue. Once I found the problem I tried upgrading and downgrading from 2022.3 and it persists.

**Comment by dlon** [comment]
Thanks for the report. Could you clarify what you mean by "multiple instances"? How do you run your different instances exactly?

**Comment by faern** [comment]
@RedCard1nal When you do end up in this weird state where one instance of qbittorrent is leaking (:scream:) and both firefox instances are also outside the tunnel. Then try opening the console/terminal (`cmd.exe`) and run the following commands and give us the output: `mullvad split-tunnel pid list` and `mullvad split-tunnel app list`. This will give us information about what processes our app is currently actually splitting out from the tunnel.

And regarding qbittorrent. As a temporary workaround to stop it from leaking: You can bind it to the VPN network interface to force it out through the VPN tunnel. Go to the advanced settings I believe and find "network interface" and select the Mullvad interface.

**Comment by faern** [comment]
Ping @RedCard1nal. This sounds like a pretty bad leak from our app? So if you can still reproduce it (we can't) then we'd love some more info.

**Comment by LinuxOnTheDesktop** [comment]
Original reporter: are the numbers following the hashes really meant to link to bug reports?

Here are some bug reports that it really would make some sense to compare (well, _prima facie_ at least): 

- #2877;
- #3624;
- #3899.

**Comment by hulthe** [comment]
@RedCard1nal are you still experiencing this issue?
