### ISSUE TITLE
[Feature Request] Add themed icon support for Android 13

### ISSUE THREAD

**Issue by owenwastaken** [mullvad/mullvadvpn-app#3935]
## Issue report

Operating system: Android 13

App version: 2022.1

### Issue description

Add support for Android 13's Material You themed icons. This would require reusing the monochrome icon already being used in the notification tray for an adaptive icon. Here is some more information about Adaptive Icons.

[https://developer.android.com/develop/ui/views/launch/icon_design_adaptive](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive)

**Comment by faern** [comment]
Thanks for the request. We are already aware of the new icon type and have discussed it internally. It will be added in a few releases.
