### ISSUE TITLE
Suggestion for a small but somewhat significant interface change: change 'secure connection' to 'secured connection'

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [mullvad/mullvadvpn-app#3938]
## Issue report

Operating system: Windows 10, but probably cross-platform

App version: 2022.4

### Issue description

Seeing the following gives one to think, initially, that one's connection is not yet secure.

![image](https://user-images.githubusercontent.com/47056543/190639562-bbaf1e7a-320a-49a8-81d2-a10602e0587e.png)

For, one sees there something that looks like _an offer_ to secure one's connection. After all, at another time one can see the following - which _is_ an offer to secure one's connection.

![image](https://user-images.githubusercontent.com/47056543/190639734-8c871c8c-1482-4d40-abfb-50102e6542fd.png)

The problem is that 'secure' in 'secure connection' can be read as a verb/imperative, whereas it is meant as an adjective.

_Proposed solution_: change the text 'secure connection' (in the first image) either to 'secured connection' or to 'connection is secure' or to 'connection secured'.

**Comment by faern** [comment]
This has been the source of multiple internal discussions over the years. And the text has changed back and fourth a number of times in the actual app. About a year ago we finally settled on the combination *Secure connection* and *Unsecured connection*. We think these are correct and we are not going to open this can of worms again. Yes, there might be people thinking there are better ways to write it. But there are also many people who think the current way is the best. Not everyone can be happy :P
