### ISSUE TITLE
Help Wanted: mullvad-daemon Breaks Public-Facing Services

### ISSUE THREAD

**Issue by 3NdR1m** [mullvad/mullvadvpn-app#3941]
Ubuntu 22.04.1 LTS x86_64
mullvad 2022.4

Pretty much stock Ubuntu 22 (installed 4 days ago)
Nginx binds to 80,443/tcp
sshd binds to 22/tcp
enp6s0’s inet is 10.0.0.2/24
uwf is active and allows 22,80,443/tcp From Anywhere
10.0.0.1 is in a WAN and forwards 22,80,443/tcp to 10.0.0.2

Everything works fine while Mullvad is disconnected, but once it’s on, inbound connection from WAN are filtered (I’ve allowed LAN through configuration).

I know this tool provides PID-based tunnel splitting for specific applications, but I need a solution that’ll survive throughout application and system restarts. I’m taking suggestions.

Thanks.

**Comment by pinkisemils** [comment]
Plain `mullvad-exclude` execution wouldn't work as it only marks the outgoing traffic to be routed outside of the tunnel.  For running internet aware services, you should check out the [advanced split tunneling guide](https://mullvad.net/en/help/split-tunneling-with-linux-advanced/).

**Comment by 3NdR1m** [comment]
It works! Thanks very much!
