### ISSUE TITLE
(iOS) Add WireGuard Over TCP option

### ISSUE THREAD

**Issue by Dynasty-Dev** [mullvad/mullvadvpn-app#3953]
Hello, I recently saw a blog from a year ago about Mullvad adding WireGuard over TCP to a few servers and so I contacted them asking if theyve expanded it to all servers and they responded saying they indeed have. So I am wondering if you could add an option for this on iOS since shadowsocks with openvpn isn’t available? It really useful for accessing on public networks as all WireGuard UDP ports are easily blocked and openvpn tcp 443 is as well.

**Comment by Dynasty-Dev** [comment]
Also the iOS TestFlight is full, anyway you can free up a spot 😁

**Comment by faern** [comment]
> Also the iOS TestFlight is full, anyway you can free up a spot grin

Our public external TestFlight group does not have any user limit. But we are also not currently running any TestFlight. There is no build there to test right now.

I really don't understand the way Apple designed this. So TestFlight builds expire after 90 days. If you have not uploaded any new version in that time that means that the app does not exist on TestFlight any longer. We don't release a new app every 90 days in general, which means we most of the time don't have any TestFlight app out.

**Comment by falchion10** [comment]
Any updates to Wireguard TCP on iOS? It’s been more than half a year…

**Comment by pinkisemils** [comment]
It will not be a part of the upcoming stable release, but we are looking to work on it straight after.

**Comment by falchion10** [comment]
Has this option been added yet?

**Comment by falchion10** [comment]
Wanted to follow up and see if it was ever added. If it was someone can probably close this issue.

**Comment by buggmagnet** [comment]
We have had WireGuard over TCP since our 2023.8 release for iOS, we can now close this issue.
