### ISSUE TITLE
"out" ip address not showing up

### ISSUE THREAD

**Issue by korason7117** [mullvad/mullvadvpn-app#3959]
Archlinux KDE Wayland 5.24.5
Mullvad 2022.4

Is this normal behavior? When trying to get an output of my current vpn ip address by doing the following command returns this unusual output: 
``` 
$ mullvad status -l
Connected to us-sjc-wg-301 in San Jose, CA, USA
Location data unavailable
```
By trying a connection check on: https://mullvad.net/en/check/
![2022_09_25_20_41_32](https://user-images.githubusercontent.com/63473694/192183714-3f4c8a36-8195-4b33-bd21-3d990464759f.png)

Or trying to view the "out" ip address in Mullvad app:
![2022_09_25_20_43_37](https://user-images.githubusercontent.com/63473694/192183872-a00ae764-1b27-4be7-8867-3c0becd2f848.png)

**Comment by faern** [comment]
We had some temporary issues with the connectivity check API. It should be fine now. I'm closing. Please reopen if you are still having this problem.

**Comment by MahdiNazemi** [comment]
I'm experiencing the same problem with the Mullvad client on macOS. I sometimes get to see the "Out" IP(s) and sometimes don't.

**Comment by raksooo** [comment]
@MahdiNazemi We're aware that the "Out IP" sometimes isn't shown in the GUI. We have that issue in our backlog and will look into it.

**Comment by Pencilcaseman** [comment]
I'm still having the same issue on MacOS. I can't be certain, but it feels like an issue with lockdown mode and/or having it always connected. 

When the laptop sleeps for a sufficiently long time, it disconnects from the internet. Upon waking it again, it reconnects, and Mullvad attempts to form another connection. The client GUI shows an `In` connection but no `Out` connection, and I cannot send or receive any data through the network.

The only fix I've found is disabling Lockdown Mode and disconnecting the VPN for a few seconds. 
After that, it tends to connect quickly and shows both the input and output IP addresses.

App Version: 2024.5
MacOS Version: Sequoia 15.0

I hope this information is useful in some way :D
