### ISSUE TITLE
java.net.SocketException: Permission denied: connect

### ISSUE THREAD

**Issue by lordcyb3r** [mullvad/mullvadvpn-app#3990]
## Issue report

Operating system: Windows 11

App version: 2022.4-dev-215f4e 

### Issue description
I am trying to run a signum blockchain node with port forwarding and dynamic dns outside of mullvad. when i split tunnel the node binary and all of its java binaries i get this error from the node debug console "java.net.SocketException: Permission denied: connect" and am unable to get any sort of connection.

Removing the split tunnel works fine and allows the node to sync, however it is unreachable by others trying to access it.

At this point I am working with both Mullvad and the Signum teams to figure out which side the problem lies on. I believe I have narrowed the culprit down to javaw.exe. adding that one to the split tunnel immediately causes the error codes.

The ports the node relies on are 3123, and 3125. the ddns being broadcasted resolves to my public IP to those ports.

**Comment by lordcyb3r** [comment]
just as an addon, here is their software/repo that I am running into issues with https://github.com/signum-network/signum-node

**Comment by dlon** [comment]
Some Java apps use IPv4-mapped IPv6 addresses, as we've seen [before](https://github.com/mullvad/mullvadvpn-app/issues/2972). This could be another example of that. As is mentioned in that issue, it's not possible to rewrite such connections, so this isn't something we can fix right now.
