### ISSUE TITLE
mullvad blocks ICMP on forwarded port breaking a number of services

### ISSUE THREAD

**Issue by Xephobia** [mullvad/mullvadvpn-app#4004]
Operating system: arch linux 5.19.7

App version: 2022.4

Hi, while trying to debug why port forwarding wouldnt work with my torrent client, even with the ports forwarded, i've discovered that ICMP is blocked on the ports that are forwarded.
Here's an example of a blocked packet (listening with netcat and pinging using mullvad's port check) :
![image](https://user-images.githubusercontent.com/28755060/194394878-c15a142e-f653-4031-b66d-74d28d2d0898.png)

**Comment by faern** [comment]
Thanks for reporting this. However, the issue is not related to the app. Can you please send this concern to support@mullvad.net and they can probably give you a better reply/fix the issue.

**Comment by faern** [comment]
Maybe I spoke too soon! I'll look into this a bit more.
