### ISSUE TITLE
SSH can't connect while Mullvad is on

### ISSUE THREAD

**Issue by ShockedCoder** [mullvad/mullvadvpn-app#4012]
## Issue report

Operating system: Manjaro Linux 

App version: 2022.04 

### Issue description

I can't connect to my PC through SSH and I have the "allow local connections" turned on, but it still won't work.

**Comment by ShockedCoder** [comment]
Forgot to mention, but I also tried using the nft rules from #2097 and it didn't work.

**Comment by faern** [comment]
Did you adapt the rules to your setup (IP, port etc)? What if you add a `counter` to the rules? Can you see them trigger on incoming packets with `nft list ruleset`?

**Comment by pinkisemils** [comment]
Have you tried following the [advanced split tunneling guide](https://mullvad.net/en/help/split-tunneling-with-linux-advanced/#allow-incoming)? Are you even trying to connect to your computer over the internet or just LAN? Does it work if you disconnect from the tunnel?

**Comment by pinkisemils** [comment]
I just want to make one last comment on the topic of running SSH -

> I tried both over and under(LAN) the internet and it only worked when I turned off Mullvad

This is pretty weird as when LAN traffic is allowed, incoming connections from a LAN should be allowed regardless of whether the client is connected to a tunnel or not, *if LAN traffic is allowed*.

**Comment by ShockedCoder** [comment]
> *if LAN traffic is allowed*. 

It is, and it only somewhat works. When I have it on the only thing that changes is that I can access LAN webserver, but other than that nothing else LAN works.
