### ISSUE TITLE
[Feature Request] VPN forcing for the WiFi Android hotspot

### ISSUE THREAD

**Issue by git70** [mullvad/mullvadvpn-app#4016]
Is it possible to implement network traffic directing by VPN for devices connected to the Android device via the WiFi hotspot?
This is very disturbing behavior now that hotspot connections are leaking into a cellular ISP.
The user trusts "Killswitch" and "Always on VPN", but suddenly it turns out that there is an exception.
I have no even notification or warning, I discovered it by accident.
There are use scenarios in oppressive countries where such behavior can have catastrophic effects...

Edit:
https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md
"...The main purpose of the app is to allow the user to make all network/internet traffic to and from the device travel via an encrypted VPN tunnel..."
Even here you can be misled and understand "All Network/Internet Traffic" as literally **ALL**

**Comment by nanometer5088** [comment]
It is out of their control. Android has limitations on VPN apps, and some traffic is leaked on a regular Android phone.

Look at their official blog post: https://mullvad.net/en/blog/2022/10/10/android-leaks-connectivity-check-traffic/

**Comment by faern** [comment]
I agree that we should update our documentation around this! Sorry for being unclear. It is true that the app (and no other VPN app) can automatically tunnel tethered devices.

However, you can install a socks proxy app on your Android device and configure your other devices to use it. When you connect to the Android device's WiFi you can configure it to use the proxy on the port you have configured. The tethered device can then go via the VPN tunnel (since the traffic from the socks proxy app will go through the tunnel)

@sabercodic You have done this. Maybe you have better instructions to provide?

**Comment by faern** [comment]
We should of course improve our documentation! But I must also say that if the consequences of not using a VPN is so high, I'd recommend checking your connection before doing anything online: https://mullvad.net/check/

**Comment by thestinger** [comment]
> Although @thestinger was a bit nervous when I called the hotspot behavior "leakage" (everyone has the right to define the word "leakage", and I had **no bad intentions**) and this matter has a [low priority in their system](https://github.com/GrapheneOS/os-issue-tracker/issues/30), it is the only hope for me and similar people are repairing this behavior / leakage in GrapheneOS (I have no illusions that Big G will fix it).

@git70 You were spreading misinformation on our issue tracker and if you're now moving that here you're going to be banned.

**Comment by alfredonodo** [comment]
> > For average users, using lineage OS and its forks such as /e/ OS or iodè OS, as they have, as of android 12+, an option in the operating system settings: Allow clients to use VPNs
> 
> The LineageOS feature implements this very incorrectly and has major leaks. It's far worse doing this than following the intended approach of per-profile VPNs which implies not routing entirely separate devices through the Owner user VPN. It's not how it's designed to work and is not good for privacy compared to a per-device VPN route. The correct way to implement it for tethered devices would be a per-device route which requires a different kind of VPN integration than what per-profile VPN apps provide.
> 
> Everything you've referenced is improperly implemented and bad for privacy due to leaks and routing traffic which shouldn't go through the Owner user through it. That is not a good thing, and is a cross-device leak within how the Android VPN model is meant to work.

Do you have any references for your claims? Because according to my tests I see no leaks using solutions 1) and 2).

**Comment by alfredonodo** [comment]
> It worked as intended before, but you want to use an implementation of routing some of the traffic via the Owner user VPN which still bypasses it when it goes down,

If the VPN installed on the Android device is configured with "kill switch" and goes down, according to my tests with Android 13 and 14 there is no traffic and therefore no leaks.

>Strongly recommend running a VPN on each tethered device if you care about privacy. There can theoretically be a good implementation of tethered VPN support but it's hard to see how that can be integrated with VPN apps with the existing API since they don't have an API for stream isolation.

Of course.

>Android allows DNS queries from the system resolver to leak to the network provided DNS servers when a VPN app goes down due to a race condition.

I could not verify this with my tests. Do you have any other reference with tests?

**Comment by alfredonodo** [comment]
> > If the VPN installed on the Android device is configured with "kill switch" and goes down, according to my tests with Android 13 and 14 there is no traffic and therefore no leaks.
> 
> It definitely leaks, significantly beyond how much Android 13 and 14 usually leak.

OK, I will continue with further tests. However, I cannot confirm your claims at the moment. For my background, if I see claims that are not supported by evidence, they are just words. I will keep you updated.

**Comment by alfredonodo** [comment]
> It very clearly has leaks from basic testing. Suggest asking the lead DivestOS developer about it.

If you are referring to the DNS leak a due to this [bug](https://mullvad.net/en/blog/2024/5/3/dns-traffic-can-leak-outside-the-vpn-tunnel-on-android), I agree. However, I could not find any other type of leak.

**Comment by alfredonodo** [comment]
> There are at least around 7 kinds of leaks in standard Android 14 without taking into account this VPN tethering, and we've fixed 4/7 with pending fixes for 3 more less serious ones

Interesting. Can you give some references?

**Comment by alfredonodo** [comment]
> Remember that every time you ask for evidence of very old facts, it distracts a person from their real work.
> Further conversation is unproductive and uneconomical.
> No offense.

I disagree, no offence. Making claims without providing any evidence is neither scientific nor desirable.
If the tests do not confirm the claims, then we are not talking facts, but words.

**Comment by alfredonodo** [comment]
> We do not want to add new problems or new misdesigned features. Private DNS is misdesigned and the VPN tethering in LineageOS has a similar flawed approach regardless of the implementation issues people have found in it, it cannot actually be right.

I am not sure if I understood correctly. Did you contact them?

> Tests confirm what has been said.

Well, I need to do further tests, as I can only confirm DNS leaks.

**Comment by alfredonodo** [comment]
> > I disagree, no offence. Making claims without providing any evidence is neither scientific nor desirable. If the tests do not confirm the claims, then we are not talking facts, but words.
> 
> Rather the other way around: You don't trust the programmer's claims? Show proof that he's telling lies. Do you expect @thestinger to paste here a piece of code he created? This is OSS = look at the source yourself.
> 
> When I buy dark bread at the bakery around the corner, I trust the baker until I find Coca-Cola inside myself

Actually, I do not trust any opinion, only facts. Please read carefully, I am not saying anyone is a liar, but that I have not been able to reproduce what is stated. Maybe it is my fault, maybe not. Who knows?
Once again, without proof every statement is just words.

**Comment by CULTofBEETROOT** [comment]
> > > I disagree, no offence. Making claims without providing any evidence is neither scientific nor desirable. If the tests do not confirm the claims, then we are not talking facts, but words.
> > 
> > 
> > Rather the other way around: You don't trust the programmer's claims? Show proof that he's telling lies. Do you expect [@thestinger](https://github.com/thestinger) to paste here a piece of code he created? This is OSS = look at the source yourself.
> > When I buy dark bread at the bakery around the corner, I trust the baker until I find Coca-Cola inside myself
> 
> Actually, I do not trust any opinion, only facts. Please read carefully, I am not saying anyone is a liar, but that I have not been able to reproduce what is stated. Maybe it is my fault, maybe not. Who knows? Once again, without proof every statement is just words.

Keep all informed of your progress Alfredonodo, your question is so legitimate that some intimidators are scared and racing time.
