### ISSUE TITLE
[Feature Request] Add an option for tray menu to quit the App without opening the window

### ISSUE THREAD

**Issue by PeterDaveHello** [mullvad/mullvadvpn-app#4021]
## Issue report

Operating system: Linux Mint 20.3

App version: 2022.4

### Issue description

Currently there are only `Open Mullvad VPN` and `Connect`/`Reconnect`/`Disconnect` options. Would be great if there's an option `Quit App`, just like the one in the app `Settings`

![image](https://user-images.githubusercontent.com/3691490/195078096-b3486fa7-d29d-49cf-a837-b1c6059f9d76.png)

**Comment by raksooo** [comment]
Thanks for the feedback. We've gotten a few requests for this and have now added it to our backlog.
