### ISSUE TITLE
[Feature Request] Add language option on mobile app

### ISSUE THREAD

**Issue by PeterDaveHello** [mullvad/mullvadvpn-app#4025]
## Issue report

Operating system: Android 13 & iOS 16

App version: 2022.1 on Android & 2022.2 on iOS

### Issue description

There is no Language option in mobile apps:

| iOS | Linux Mint |
| --- | ------ |
| ![image](https://user-images.githubusercontent.com/3691490/195110191-482b38c1-76a3-4c88-80a1-f309fb57bfa3.png) | ![image](https://user-images.githubusercontent.com/3691490/195110016-3d089e44-2ee1-4e8c-81ad-c217c1accf1d.png) |

**Comment by faern** [comment]
The iOS app is not yet translated at all. That will happen, but not yet clear when.
The Android app is translated and uses the same language as the phone itself. Is there any particular reason why you want to use our app in a different language compared to your phone's language? Of course, if we don't have your preferred language, it will fall back to English, maybe you know one of the other languages better?

**Comment by PeterDaveHello** [comment]
With all due respect and being honest, I'd prefer to just use English, because the translation quality is usually not good enough 😆

**Comment by faern** [comment]
So why do you request the feature to be able to change language? From your screenshots, it looks like you already have the app in English everywhere.

**Comment by PeterDaveHello** [comment]
@faern The screenshot is just an example, actually the language on my Android phone is different. If the language option exists for the Desktop, shouldn't we also have it on Mobile App 😆

**Comment by pronebird** [comment]
On iOS usually the UI language is picked up from the system preferences. You should be able to override UI language in the system "Settings" app via "Mullvad VPN" -> "Preferred language". However it does not appear there yet because we do not have the app translated into any other language. Hope that makes sense.

**Comment by PeterDaveHello** [comment]
No problem is iOS doesn't have translation yet, but would really to have an option an Android though!

**Comment by Rawa** [comment]
Closing this issue, since we've added [Per-app language preferences](https://developer.android.com/guide/topics/resources/app-languages) support on Android. 

A user can now set the language of the app through the App Info -> Language.
