### ISSUE TITLE
Building Mullvad for Raspberry OS

### ISSUE THREAD

**Issue by texasmouse** [mullvad/mullvadvpn-app#4043]
## Issue report

Operating system: Raspberry OS 5.10.103-v7l+ #1529 (Rpi 4B w/ 4GB)

App version: 2022.5-beta2-dev-e552d9

### Issue description

Wanting to get Mullvad running on a new installation of Raspberry OS.  I was able to get pretty far in the build process, and am unable to get past an error:

`error: could not find native static library `wg`, perhaps an -L flag is missing?
error: could not compile `talpid-core` due to previous error `

From a previous issue, it looked like I may not have libwg.a, but I do have it in ~/mullvadvpn-app/build/lib/armv7l-unknown-linux-gnu.  I many have a bad PATH somewhere.  If it helps, here is my build process so far:

PREP SYSTEM
1. Update 'go' to the latest version (at least 1.16.2)
          http://go.dev/do/
          get the go.1.19.1.Linux-armv6l.tar.gz file (ARM v6 not ARM64)
          pull it down to the system and tar -xvf into /usr/local
2. Add new version of go to $PATH in ~/.profile
 	  vi ~/.profile
          last line of file:  $PATH=/usr/local/go/bin:$PATH
3. logout and log back in for path to update
4. cargo install --git https://github.com/volta-cli/volta && volta setup
5. sudo apt install gcc libdbus-1-dev
6. sudo apt install rpm
7. sudo curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          Proceed with installation (default)
8.  logout and log back in for path to update
9. Update Nodejs:
          curl -fsSL https://deb.nodesource.com/setup_current.x | sudo bash
          sudo apt-get install -y nodejs
10. git clone https://github.com/grpc/grpc-node.git && cd grpc-node/packages/grpc-js && npm
11. npm install @grpc/grpc-js
12. sudo apt install -y protobuf-compiler

BUILD MULLVAD
** Seems like I am building a lot of executables I already have installed.  Not sure if that is right. **

1. git clone https//github.com/mullvad/mullvadvpn-app.git
2. cd mullvadvpn-app/
3. git submodule update --init
4. cd dist-assets/binaries/
5. git submodule update --init --recursive
6. Edit the OpenSSL Makefile to disable 128-bit Integers on build
          cd into mullvadvpn-app/dist-assets/binaries
          Vi Makefile
          About 8 lines down, change 'enable-ec_nistp...' to 'no-ec_nistp...'
8. build libwg.a
          cd mullvadvpn-app/wireguard
          ./build-wireguard-go.sh 
9.  wireguard will not compile as its looking for a system to support i64, not i32.  Need to change that… Hope this actually works because a comment says otherwise.
	cd back to mullvadvpn-app/talpid-core/src/tunnel/wireguard/wireguard_kernel
	vi parser.rs
		about 25 lines up from the bottom, change these lines:
			tv_sec: NativeEndian::read_i64(buffer),
			tv_nsec: NativeEndian::read_i64(buffer),
		to
			tv_sec: NativeEndian::read_i32(buffer),
			tv_nsec: NativeEndian::read_i32(buffer),
10.  cd back to root mullvadvpn-app directory
11.  ./build.sh --optimize

Near the end of the process, boom… error.

Any insight is appreciated.

**Comment by faern** [comment]
Just in case you didn't know: We have already built installers for ARM64: https://github.com/mullvad/mullvadvpn-app/releases/download/2022.5-beta2/MullvadVPN-2022.5-beta2_arm64.deb

Do you really need/want to build everything from scratch? You are supposed to clone our binaries repo and there you get a lot of the C dependencies already built for you.

You do not need to manually run `build-wireguard-go.sh` if you also run `build.sh`. The latter invokes the former for you.

**Comment by faern** [comment]
> Operating system: Raspberry OS 5.10.103-v7l+ https://github.com/mullvad/mullvadvpn-app/pull/1529 (Rpi 4B w/ 4GB)

I think you have a 32 bit OS. Our app is only written with 64 bit in mind. You have a Raspberry Pi 4B, which has a 64 bit CPU. If you want to run Mullvad I recommend you to reinstall the 64 bit version of Raspberry OS.

**Comment by texasmouse** [comment]
I had a feeling this was ultimately a PEBCAK error.  I don’t want to build anything from scratch.  Since I unknowingly installed the 32-bit OS, I couldn’t get a lot of things to work and assumed I had to build from scratch.  Thank you for setting me straight!!
