### ISSUE TITLE
[Feature Request] Mullvad tray icon indicating that an update is available

### ISSUE THREAD

**Issue by BajrangB** [mullvad/mullvadvpn-app#4048]
Operating system: Windows 10

App version: 2022.5

It would be great if the Mullvad app tray icon could change to show that an update is available without having to click and open the app, irrespective of the notification settings within the app. Thank you!

**Comment by bit-blit** [comment]
Would like something like this on macOS as well.

**Comment by faern** [comment]
We don't have many pixels to work with here. But maybe it can somehow show there is some alert/message in general available, update or other.

**Comment by BajrangB** [comment]
> 

In general, I agree, but given the importance of VPN security, I think an update for the VPN app must be indicated to the user even if the user has disabled desktop notifications in the app or the OS in general. Personally, I set up auto-start & auto-connect for the VPN and then forget about it. If notifications are disabled, then the only way I'll know about an update is if I open the VPN interface, which may delay the application of an important security fix. Cheers & thank you for considering the request!

**Comment by faern** [comment]
Two responses to that:
1. If you regard the VPN as such critical software on your machine, maybe you shouldn't disable notifications?
2. We have two levels of update notifications. Regular update notifications can be disabled with the notification setting. But upgrading between such versions are *usually* not important for security. However, if we detect a security threat towards a version of our app, we mark it as unsupported and the app yells at you much louder. And this notification cannot be disabled.

**Comment by BajrangB** [comment]
In general, I prefer to keep most notifications disabled. When dealing with multiple devices, it can get overwhelming. 

Since it is mentioned in the app interface that critical notifications cannot be disabled, I presumed app updates will be included in critical notifications and hence, by turning off notifications I would only be disabling connected / disconnected messages etc. Clearly, I was wrong. Thank you for clarifying. I still think an update available indication or including them in critical notifications can be helpful.

**Comment by faern** [comment]
As stated earlier, we do issue critical notifications for important upgrades. But the point of disabling notifications is to get rid of less important notifications. And upgrading between two app versions with no security improvements is not critical.

**Comment by BajrangB** [comment]
Not trying to make this a big deal, but maybe there can be an option, _just for updates_, between critical / non-critical notifications, and let the user decide? Updates may not be security related, but nevertheless can contain new options, important bug fixes, system stability improvements etc., that the user may otherwise miss from receiving as soon as possible because they have their notifications turned off. A visual indicator on the tray icon or a notification can mitigate this issue. Also, since they are not issued frequently, notifications for app updates should not be a disturbance.

Personally, I would be glad to receive them, because I regard updates for internet facing applications as important. @bit-blit also requested this feature on this thread, so there may be more users out there who welcome this feature. Just a suggestion in favor of your application's user-friendliness. Thank you for considering. Cheers!
