### ISSUE TITLE
Cycle through chosen list of servers

### ISSUE THREAD

**Issue by 34candos** [mullvad/mullvadvpn-app#4056]
## Issue report

Operating system: N/A

App version: N/A

### Issue description

VPNs provide privacy by letting users connect through their servers. However, it may not be ideal to always connect from the same single server and it is not convenient to always think about switching servers in the app.

So a useful feature would be to let users choose not just one single server but several (from several cities/countries); the app would then randomly cycle through the list of selected servers and change each time the VPN connects (on startup or wake, for instance).

**Comment by pinkisemils** [comment]
If you select a city or a country, it will already cycle through them. As for being able to select multiple countries - I believe #1226 is a somewhat similar issue. We believe this is a nice feature to have, but we have not currently scheduled it.

**Comment by 34candos** [comment]
That's good, but it's evidently not as flexible. There may be servers you don't want to connect to within the same city/country (say, rented - and not owned - servers). Selecting several countries would be good too, but still missing the full customisation that would come in handy.

**Comment by faern** [comment]
This is going to be solved by custom/favorites lists, as tracked in #3180. I'm going to close this as a duplicate.
