### ISSUE TITLE
[Feature request] Wireguard UDP-over-TCP for Android client

### ISSUE THREAD

**Issue by Cubxity** [mullvad/mullvadvpn-app#4057]
## Issue report

Operating system: Android 12

App version: 2022.1

### Issue description

Mullvad's Android client currently lacks the Wireguard UDP-over-TCP obfuscation feature that the desktop client supports. When running on a restricted network, Mullvad is unable to establish a Wireguard connection over UDP.

Furthermore, the Android client doesn't support any other forms for obfuscation/circumvention, such as OpenVPN over TCP or OpenVPN w/bridge. As such, I believe it is a good idea to implement a form of obfuscation for the Android client.

**Comment by faern** [comment]
Hi, this is definitely in the backlog. All platforms will eventually get WireGuard over TCP.

**Comment by Cubxity** [comment]
Is this limited by the frontend, or is it limited by the backend used by the Android client?

**Comment by faern** [comment]
The rust code in `mullvad-daemon` already supports this. Some more backend work might be needed. But the biggest change here is implementing the UI components and connecting the correct signals to `mullvad-daemon`.

**Comment by albin-mullvad** [comment]
Implemented and merged in #4644!
