### ISSUE TITLE
Minor cosmetic issue: Loading icon on taskbar looks ugly, I think it should be yellow instead of green-red.

### ISSUE THREAD

**Issue by aqualemon22** [mullvad/mullvadvpn-app#4087]
## Issue report

Operating system: Windows 10, the one with the taskbar you know.

App version: It doesn't really matter, this icon is used in all versions as far as I know. Plus you'll judge me for not updating for a long time.

### Issue description

While the client is trying to connect, it will display this icon on the taskbar: https://github.com/mullvad/mullvadvpn-app/blob/master/gui/assets/images/menubar%20icons/win32/lock-10.ico

This looks very ugly to my eyes, a red dot inside green. It would be more aesthetically pleasing and better convey the meaning of the icon if it was the red unlocked lock icon, except yellow. So copy the red unconnected icon, change the hue to yellow, rename to lock-10.ico and replace. Possibly the easiest fix this repository has ever seen. If you have a better idea than yellow lock, just do it. Anything but red dot inside green.

I already emailed the support team about this think you can make the patch before they even see my e-mail?

Sorry to all the Bangladeshis out there.

**Comment by aqualemon22** [comment]
It would be rude if you closed my request without even considering it for a minute :( It doesn't even take 5 minutes to fix. Add it to your backlog, or the next version, or however this works but do it please

**Comment by aqualemon22** [comment]
You can fix it while waiting for your coffee, isn't that a nice way to save time?

**Comment by aqualemon22** [comment]
I couldn't sleep all night because of this. It's 4 PM now. Time passes fast when you're sleep deprived.

**Comment by aqualemon22** [comment]
I have obtained a screenshot of the problem:
![image](https://user-images.githubusercontent.com/116496889/197394939-20c0a57d-c365-49d3-b8f2-5e1c46bc9af1.png)

**Comment by aqualemon22** [comment]
It kinda looks yellow if you unfocus your eyes! That's not the right solution though. I can unfocus my vision manually, I don't think everybody can do it.

**Comment by aqualemon22** [comment]
People say on Reddit that pets can speak and understand English. I was up all night trying to force my cat into speaking. He just pretended to be a cat. Didn't give up. What are some good interrogation techniques?

**Comment by aqualemon22** [comment]
Perhaps in an alternate universe, the resources of the entire world is being used to fix this problem. Here, it's just me. Just me, on a GitHub issue thread that nobody reads. I can compile the client myself change the icon no problem, I can fix the issue for myself, but I won't do it. It's not fair. Everybody will have YELLOW LOCK. Not just me!

**Comment by aqualemon22** [comment]
I want to talk face-to-face to the person responsible for the red-in-green lock icon

**Comment by aqualemon22** [comment]
I am controlling myself. I will not have YELLOW LOCK until everybody else has it.

**Comment by aqualemon22** [comment]
Can we call the patch the "Golden Lock" update? Sounds kinda cool!

**Comment by aqualemon22** [comment]
I agree. That is the greatest idea I have come up with this year.

**Comment by aqualemon22** [comment]
I will stop updating the thread, I will wait until the bug is fixed.

**Comment by aqualemon22** [comment]
Just because I talk too much doesn't mean I'm schizophrenic.

**Comment by aqualemon22** [comment]
Cats rarely talk, but they have serious behavioral problems.

**Comment by aqualemon22** [comment]
They will try to hunt animals that don't exist, even though they have food. They have hallucinations about killing others.

**Comment by aqualemon22** [comment]
AKA called "Playing". Those nerf guns aren't so innocent. What's going on inside your head when you "play" with them?

**Comment by aqualemon22** [comment]
Foam or Lead. Killing is fun.

**Comment by aqualemon22** [comment]
Why are there "toy guns" huh?? GUNS AREN'T TOYS!

**Comment by aqualemon22** [comment]
Killing is an instinct. You can't judge someone who killed another, just for fun. Cats do it all the time, to mice.

**Comment by aqualemon22** [comment]
What really is going on inside a child's head when he is playing with a nerf gun?????????????????????? HAVE YOU EVER THOUGHT HUH?

**Comment by aqualemon22** [comment]
Why are guns fun? They're fun in games.

**Comment by aqualemon22** [comment]
They shouldn't be fun because we use them to kill our own species.

**Comment by aqualemon22** [comment]
Children may look innocent, but they want to MURDER.

**Comment by aqualemon22** [comment]
What is the origin of soccer? Have you ever thought?

**Comment by aqualemon22** [comment]
What makes soccer fun? Maybe the "throwing an object to another person at high velocity" aspect?

**Comment by aqualemon22** [comment]
These thoughts will only leave my head when you implement the Golden Lock patch.

**Comment by aqualemon22** [comment]
Ursula is a very minor character in GTA V, but I think her dialogue is the most meaningful.

**Comment by aqualemon22** [comment]
You need to hook up with her to get %100 achievement. It's a "Miscellaneous" task.

**Comment by aqualemon22** [comment]
It's only been an hour since I posted this issue, but it already has 28 comments! That's got to be some kind of record. The community is really invested in discussing this issue.

**Comment by aqualemon22** [comment]
Haha. Sorry for the unsettling monologue, I'm sleep deprived and kind of bored. But still unsettling that killing is fun. That's not right.

**Comment by aqualemon22** [comment]
Killing shouldn't be fun. I mean it isn't, I've never killed anything in my life.

**Comment by aqualemon22** [comment]
I think cats are psychopaths. But they're too cute for us to care

**Comment by aqualemon22** [comment]
Don't delete my comments because they're "irrelevant". All of my questions are pertinent to the issue.

**Comment by aqualemon22** [comment]
Signing off now.

**Comment by aqualemon22** [comment]
how do you delete all comments quickly

**Comment by aqualemon22** [comment]
gotta do it manually i guess

**Comment by aqualemon22** [comment]
huh what did i do????? i swear this thread had 35 comments at one point

**Comment by faern** [comment]
We support monochromatic icons. So each state needs to have a different shape, not just different colors.

**Comment by faern** [comment]
If you do not like the colors, I suggest you enable the monochromatic mode in the settings.

**Comment by aqualemon22** [comment]
fine whatever i'll have to compile it myself and change the lock

**Comment by aqualemon22** [comment]
.
