### ISSUE TITLE
No OpenVPN plugin found

### ISSUE THREAD

**Issue by jeffbowen** [mullvad/mullvadvpn-app#41]
I'm unable to actually connect to the VPN server after getting everything built and running. When I hit "Secure my connection", I get the following errors in mullvad-daemon's logs.

    ...
    [2018-01-20 14:25:24.300][talpid_core::tunnel][WARN] Did not find a bundled version of OpenVPN, will rely on the PATH instead
    [2018-01-20 14:25:24.300][mullvad_daemon][ERROR] Error: Failed to start tunnel
    Caused by: Tunnel monitor error: Unable to start tunnel monitor
    Caused by: No OpenVPN plugin found
    ...

It seems it can't find the OpenVPN plugin? It looks like OpenVPN is bundled with the mullvadvpn-app repo but maybe it's not getting built/linked properly? Maybe this just requires adding some undocumented step to the README?

**Comment by pronebird** [comment]
Good one. Seems like we missed that one too!

If you run the app in development mode then you need to place the `openvpn` binary under `target/debug/openvpn-binaries`.

Open the Terminal, change to the folder with the cloned `mullvadvpn-app` repository and run the following commands:

```
mkdir -p target/debug/openvpn-binaries
cp client-binaries/mac/include/openvpn target/debug/openvpn-binaries 
```

**Comment by faern** [comment]
Either that or have the `openvpn` binary on your `PATH`.
But yes, we need to improve documentation on this!

**Comment by faern** [comment]
Looks like it's missing the plugin, not OpenVPN itself. It should try to find it at the same place where the daemon binary is located. Don't you have the plugin shared library under `target/debug/`? The name of it would depend on the platform, `libtalpid_openvpn_plugin.dylib` if you are on macOS.
If that is missing you have probably not built the `talpid-openvpn-plugin` crate?

**Comment by jeffbowen** [comment]
The closest thing to `libtalpid_openvpn_plugin.dylib` I can find is `target/debug/deps/libtalpid_openvpn_plugin.dylib.dSYM/`. There's nothing related to the plugin directly under `target/debug`. Does that mean it hasn't built?

Followed @pronebird's steps but am still getting the `No OpenVPN plugin found` error.

**Comment by faern** [comment]
@jeffbowen You need to have that shared library, yes. What happens if you go to the plugin crate and built that one specifically? Does the file show up then?
```bash
cd talpid-openvpn-plugin/
cargo build
```

Also, what version of Rust are you using? I can't remember the exact differences here and there, but try on latest stable and/or nightly and see if that makes a difference.

**Comment by jeffbowen** [comment]
There we go. After

    cd talpid-openvpn-plugin/
    cargo build
    cd ..
    cargo build

the `No OpenVPN plugin found` error is gone. It will now actually attempt to connect. It still fails to actually connect but that's okay as it unblocks me on #42 as the menu bar icon will go through its animation cycle.

Also FWIW, I'm using `rustc 1.23.0 (766bd11c8 2018-01-01)`. Installed it via rustup.rs as you suggested in the README.

**Comment by pronebird** [comment]
@faern was this fixed?

**Comment by faern** [comment]
I don't know. Ask @jeffbowen. But given how old this is and no one said anything in a long time I think we can close this. It can be re-opened if people are still having trouble.

**Comment by jeffbowen** [comment]
Yeah, I haven't messed with it in over a year so not sure either way. Makes sense to me to close for now.
