### ISSUE TITLE
Notification Problems macOS 13/macOS 12

### ISSUE THREAD

**Issue by bit-blit** [mullvad/mullvadvpn-app#4100]
Operating system: macOS 13.x Ventura/12.x Monterey
App version: 2022.5

When setting up Notifications on macOS 13/macOS 12, Mullvad does not respect the preference setting for how the notifications are displayed. I have mine set to ALERTS, which should stay on the desktop until manually dismissed. Mullvad however, will only send a notification using BANNERS which come onto the screen and after a few seconds dismiss itself (no user interaction required). I am finding that they only stay on for such a short period of time that I am having trouble reading them (which is why I set it to ALERTS so they will stay until manually dismissed). I feel Mullvad should respect the notification preference setting and display the notifications as the user has chosen - I have mine set to ALERTS, but am only getting BANNERS.

If you need further info, do not hesitate to ask.

Best Regards,

**Comment by raksooo** [comment]
Thanks for the feedback. I've recently improved the notifications a lot and this should be resolved, although it has not been released yet. What we did previously was to automatically remove the alert notifications after 4 seconds making them look like banner notifications. We've now changed the default type to banner (it will respect your previous choice when upgrading) and we never remove notifications that are still relevant so they will end up in the notification center.

These improvements have been merged and will be part of a future release.
