### ISSUE TITLE
Frontend does not autostart on login on Fedora KDE

### ISSUE THREAD

**Issue by alastortenebris** [mullvad/mullvadvpn-app#4103]
## Issue report

Operating system: Fedora 36 KDE

App version: 2022.5
### Issue description

When the frontend is set to autostart on login, it doesn't; however, the daemon still runs and VPN still connects.

**Comment by raksooo** [comment]
Could you check if the app is running but not visible:
```sh
ps aux |  grep mullvad-gui
```

**Comment by pizzadude** [comment]
sounds like this https://github.com/mullvad/mullvadvpn-app/issues/2904

**Comment by alastortenebris** [comment]
Unfortunately, I'm currently using Fedora Kinoite, so I can't actually edit `/usr/share/applications`

That being said, wouldn't it be easier if the folder didn't have a space in the first place?

**Comment by alastortenebris** [comment]
I did not mean to hit that.

**Comment by faern** [comment]
It would be easier if some desktop environments did not have broken .desktop file parsing :joy:

**Comment by MrChocolatine** [comment]
Also related to:
- https://github.com/mullvad/mullvadvpn-app/issues/3836
- Which brings here https://github.com/mullvad/mullvadvpn-app/issues/3488#issuecomment-1091638793

**Comment by pizzadude** [comment]
@alastortenebris 
`Unfortunately, I'm currently using Fedora Kinoite, so I can't actually edit /usr/share/applications`

copy /usr/share/applications/mullvad-vpn.desktop to ~/.config/autostart and edit it
or copy it to ~/.local/share/applications, edit it there, and symlink it to ~/.config/autostart

**Comment by alastortenebris** [comment]
Looks like the issue has been fixed on Fedora 37.

**Comment by raksooo** [comment]
Great to hear! Hopefully this is the case for everyone who've had this issue.

**Comment by lotth** [comment]
I have Fedora 37, updated from Fedora 36, and the issue from [Mullvad GUI is not launched at system start-up [workaround found] #2904](https://github.com/mullvad/mullvadvpn-app/issues/2904) still present.
