### ISSUE TITLE
Can't install/update mullvad to 2022.5

### ISSUE THREAD

**Issue by yallxe** [mullvad/mullvadvpn-app#4129]
## Issue report

Operating system: Windows 10

App version: 2022.5

### Issue description

I was trying to update Mullvad on my computer to the latest version, but faced an issue during an installation process.
![image](https://user-images.githubusercontent.com/82591945/200170960-066f8434-7095-41d6-8f16-e4ca5bfc0a21.png)

**Comment by pinkisemils** [comment]
This should be fixed as of #4136.
