### ISSUE TITLE
Reset modified settings

### ISSUE THREAD

**Issue by amirrh6** [mullvad/mullvadvpn-app#4132]
## Issue report

Operating system: Linux Mint 21

App version: 2022.5

### Issue description

I followed the instructions on https://mullvad.net/en/help/shadowsocks-with-v2ray/#using-linux to set a bridge via 'mullvad' CLI and configure 'mullvad-exclude'. It did not work for me, so I want to revert the original settings of both 'mullvad' and 'mullvad-exclude'. How can I do this?

**Comment by pinkisemils** [comment]
To revert the client back, you should just need to run `mullvad bridge set auto` and `mullvad relay set tunnel-protocol any`. Be sure to set a known good location too.

`mullvad-exclude` isn't affected by any settings and will continue working as intended.

**Comment by amirrh6** [comment]
Thank you @pinkisemils !
`mullvad relay set tunnel-protocol` worked but `mullvad bridge set auto` didn't:
![image](https://user-images.githubusercontent.com/65363030/200885167-5b742a95-9408-4bc8-82ec-cc85320b84b1.png)
