### ISSUE TITLE
Post-quantum secure multihop

### ISSUE THREAD

**Issue by jorik392** [mullvad/mullvadvpn-app#4133]
### Issue description

Post-quantum secure support has expanded but it is not possible to use it in multihop yet. Please add this feature.

**Comment by faern** [comment]
Yes, this is in the backlog. But it's just an experimental feature so far. We will fix it eventually, before we classify it as stable.

**Comment by jackloomen** [comment]
Would it be possible to get a standalone binary for the key exchange? The WG PSK can then be manually manged or via scripts.

**Comment by faern** [comment]
We currently don't provide one. But the protocol is public, and you can pretty easily build one yourself from https://github.com/mullvad/mullvadvpn-app/blob/master/talpid-tunnel-config-client/examples/psk-exchange.rs

**Comment by jackloomen** [comment]
> We currently don't provide one. But the protocol is public, and you can pretty easily build one yourself from https://github.com/mullvad/mullvadvpn-app/blob/master/talpid-tunnel-config-client/examples/psk-exchange.rs

That was helpful. But there appears to not be a function for printing PSK's properly.
```
private key: ......
psk: PresharedKey([102, 48, 95, .... ]
```

**Comment by faern** [comment]
> edit: It also seems like redoing the PQC PSK procedure while connected to a PQ-Peer does not work for some reason.

Yes, changing the PSK while using the PSK does not make sense. That will create a race condition where the server will start using the new PSK as soon as it's able to compute it. This will break the current tunnel (as the client now has the wrong PSK) and the response to the gRPC request will not even make it back to the client most of the time (based on timing)

**Comment by MrChocolatine** [comment]
@jorik392 , looks like it's coming in the next stable release `2023.3`!

https://github.com/mullvad/mullvadvpn-app/releases/tag/2023.3-beta1

**Comment by faern** [comment]
Yes. That's true. It's fixed for the upcoming release and is part of the current beta. So I'm closing this as done.
