### ISSUE TITLE
Unclear Kill Switch documentation

### ISSUE THREAD

**Issue by rozab** [mullvad/mullvadvpn-app#4141]
## Issue report

Operating system: Windows 10

App version: 2022.5

### Issue description

Related issue: #3430

It isn't clear that the Kill Switch feature cannot be turned off. It is listed in the settings, with a toggle button next to it, and both of these things indicate to the user that it's a *setting* that can be *set*. The toggle is greyed out, but there is no indication as to why.

![image](https://user-images.githubusercontent.com/35606180/201412788-519955ce-6795-4004-aff2-9fe77fa12d3b.png)

The lengthy info text also does not mention this:

![image](https://user-images.githubusercontent.com/35606180/201412857-ae62246d-52b8-4022-a0eb-57a4d64edbe9.png)

Perhaps this is the intended meaning of 'built-in feature', but it's not how I'd interpret that. Mullvad has a gambling blocker built-in, but that doesn't mean it can't be disabled. Maybe this could be replaced with 'always-on feature'?

I found this doc page in the previous issue, and while it does explain how the kill switch cannot be disabled, it is confusing to read since it was written before that dummy setting was added.

https://github.com/mullvad/mullvadvpn-app/blob/master/docs/security.md#kill-switch

> There is no setting for it. 

> The app avoids the term "kill switch"

I am deeply thankful for mullvad, thanks for your work on it <3

**Comment by faern** [comment]
Thanks for the feedback. The amount of times we have reworded, renamed, moved and changed the names and info texts around "kill switch" and "lockdown mode" is way too high. There is always someone getting confused about it, no matter what we call it, how we explain it or where we put it. Sorry, but we have tried. I agree with you that we can do a better job of saying "can't be disabled". It was probably in a previous version of the app. But the text has been revised many times as there was always someone saying something is missing in it, and we can't have too much text, as that will also be confusing.
