### ISSUE TITLE
New privacy disclaimer is like cookiewall

### ISSUE THREAD

**Issue by AngryLasagna** [mullvad/mullvadvpn-app#4152]
## Issue report

Android 13

2022.3 Its right in that changelog.
https://github.com/mullvad/mullvadvpn-app/releases/tag/android/2022.3

### Issue description

![Screenshot_20221119-135111](https://user-images.githubusercontent.com/57591331/202852492-ca2e2b98-46a0-4322-b85d-8d8e2b60acc6.png)

This new accept privacy policy screen feels like one of those obnoxious cookiewalls.
Fetching App List -> When it is needed to enable Split Tunneling settings, stays on my device and is not used for anything else then don't tell me about it in a popup please. Don't nag users about a non-issue. Put it in the FAQ or something.
Sending Version Stats -> Tell me once and give me a permanent toggle if I don't like it.  Everyone using an external updating facility does not need the version check. Don't make force me into accepting something optional for the main feature to work.

**Comment by albin-mullvad** [comment]
Sorry for the inconvenience and thank you for sharing this feedback.

The short version is that we had to add this _prominent disclosure_ (more info [here](https://support.google.com/googleplay/android-developer/answer/12564964)) within 7 days to not get taken down from Google Play. We are looking at multiple ways of improving this in future releases.
