### ISSUE TITLE
Weird UI after Sleep

### ISSUE THREAD

**Issue by GibMeMyPacket** [mullvad/mullvadvpn-app#4157]
## Issue report

Operating system: Windows 10

App version: 2022.5

### Issue description

The issue is that usually, when i put the computer to sleep while Mullvad has been connected (via SSH bridge), after that i wake the computer up, Mullvad is not getting connected and acting weird!
It doesn't happen all the time, but i can pretty sure say half the time.
https://i.imgur.com/5mcRMTk.gif
The gif above shows the issue.

To get it fixed, i have to restart or close all processes of Mullvad via Process Hacker by searching Mullvad and selecting all processes in it.

**Comment by faern** [comment]
Please send a problem report from within the app. We will need app logs in order to figure out what went wrong here.

**Comment by nihaals** [comment]
Running `sudo killall mullvad-daemon` fixes it for me (on macOS) whenever it happens, although my UI issues are slightly different (I think it's the same issue though, and it might be because of using a different OS).

**Comment by faern** [comment]
Yeah, the frontend is not responsible for spawning the system service/daemon. That has to be running, otherwise the GUI will just tell you it's waiting for the system service. It just works on macOS because the system automatically brings the daemon up again I guess.

**Comment by nihaals** [comment]
Restarting it through your service manager instead of manually killing the process is probably better too (e.g. `systemd restart mullvad-daemon`), I only started killing the process myself since that's what I originally found that worked and didn't look at the services.

**Comment by HJLBX** [comment]
> The issue is that usually, when i put the computer to sleep while Mullvad has been connected (via SSH bridge), after that i wake the computer up, Mullvad is not getting connected and acting weird! It doesn't happen all the time, but i can pretty sure say half the time. https://i.imgur.com/5mcRMTk.gif The gif above shows the issue.
>
> To get it fixed, i have to restart or close all processes of Mullvad via Process Hacker by searching Mullvad and selecting all processes in it.

I can confirm similar problematic behaviors induced after waking from Sleep on Windows 11 22H2.

The very same issue shown in your linked GIF has occurred multiple times after waking the system from Sleep.
Sometimes Mullvad will not connect at all despite no problem with network access.
Sometimes the taskbar Manage Network Connections will show zero available networks.
Sometimes the taskbar disable\enable Wifi will cause the GUI to freeze and crash.
Sometimes there is a "flood" or "spamming" of Mullvad connection alerts during the waking-from-sleep process - as many as a few hundred.
To fix these issues always requires a system reboot (a network reset does not work).

**Comment by dlon** [comment]
This is probably an issue with S0 low-power sleep (i.e., modern standby). The system service does not get suspended, but the Electron app does. The latter gets flooded with state changes when waking up.

**Comment by HJLBX** [comment]
> ## Issue report
> Operating system: Windows 10
> 
> App version: 2022.5
> 
> ### Issue description
> The issue is that usually, when i put the computer to sleep while Mullvad has been connected (via SSH bridge), after that i wake the computer up, Mullvad is not getting connected and acting weird! It doesn't happen all the time, but i can pretty sure say half the time. https://i.imgur.com/5mcRMTk.gif The gif above shows the issue.
> 
> To get it fixed, i have to restart or close all processes of Mullvad via Process Hacker by searching Mullvad and selecting all processes in it.

![Mullvad](https://user-images.githubusercontent.com/97270395/222049951-477c67df-4825-448d-8bb1-44d335b06f42.png)

**Comment by SleepyAnubis** [comment]
> I can confirm similar problematic behaviors induced after waking from Sleep on Windows 11 22H2. The weird behaviors are independent of the Mullvad VPN configuration. These intermittent behaviors occur with ANY settings configuration.
> 
> The very same issue shown in your linked GIF has occurred multiple times after waking the system from Sleep. Sometimes Mullvad will not connect at all despite no problem with network access. Sometimes the taskbar Manage Network Connections will show zero available networks. Sometimes the taskbar disable\enable Wifi will cause the GUI to freeze and crash. Sometimes there is a "flood" or "spamming" of Mullvad connection alerts during the waking-from-sleep process - as many as a few hundred. To fix these issues always requires a system reboot (a network reset does not work).

Having these same issues, Windows 10 22H2.

I find killing the client and mullvad-daemon then restarting the client does fix it though.  Waking from sleep is definitely the trigger

**Comment by raksooo** [comment]
We've fixed a bunch of issues in our latest beta release. Please try it out and let us know if there are any improvements in regard of these issues: https://mullvad.net/download/beta

**Comment by hulthe** [comment]
Fixed
