### ISSUE TITLE
Connected of `224.0.0.251` and `224.0.0.252` in through svchost.exe.

### ISSUE THREAD

**Issue by Noir16** [mullvad/mullvadvpn-app#4171]
## Issue report

Operating system: Windows 10/11

App version: 2022.05

### Issue description
`224.0.0.251` and `224.0.0.252` server is connected in through System DNS Client(svchost.exe), and is there a way to connect to Mullvad without this connection process?

https://github.com/safing/portmaster/issues/313#issuecomment-1326755100
I through this process, smooth concurrent use with Portmaster is possible. However, the connection speed is reduced. (After connecting, there was no slowdown in network access via VPN.)
I would like technical support to skip this connection process and rely on Portmaster's DNS configuration.

**Comment by dlon** [comment]
We've merged a patch (https://github.com/mullvad/mullvadvpn-app/pull/4047) which will let Portmaster redirect DNS queries back to localhost. You won't have to do anything special for it to work in the next version of the Mullvad app.

I recommend using this workaround in the meantime: https://github.com/mullvad/mullvadvpn-app/issues/4033#issuecomment-1279136368
