### ISSUE TITLE
App is stuck loading

### ISSUE THREAD

**Issue by quinnzbellz** [mullvad/mullvadvpn-app#4180]
## Issue report

Operating system: Android 13

App version: 2022.3

### Issue description

When I open the app, 90% of the time it gets stuck on connecting to system service and it never loads until some random point later on in the day. This is extremely annoying when I'm at school and even reddit is blocked. My solution as of right now is to use the wireguard app on fdroid with it, but this can't keep happening. It's been going on for the last 2 versions of the app, and is extremely frustrating.

**Comment by faern** [comment]
Can you please send a problem report from within the app just after this issue happens? When the app is stuck waiting for the system service, or just after it started working again? That way we'll get some application logs to investigate. With the current description we can't debug the issue.

In the problem report description text field, please refer to this Github issue or submit the same text there as you have here. Thank you.
