### ISSUE TITLE
Pop-up window with Uncaught Exception (in ConsoleOutput.write) over other apps at random times

### ISSUE THREAD

**Issue by gavento** [mullvad/mullvadvpn-app#4188]
## Issue report

Operating system: Linux Ubuntu 22.04.01 LTS

App version: 2022.5 (installed from `MullvadVPN-2022.5_amd64.deb`)

### Issue description

Occasionally (sometimes a few times a day, but at least a few times a week) the Mullvad app opens a pop-up window with an `Uncaught Exception` error. This does not seem to interfere with the operation of the app itself (runs fine after closing the pop-up). However, it interrupts my work and is quite annoying (e.g. if it happens in professional calls etc).

Since this is a write error, I have checked free space on my drives and all filesystems have >10GB free, every tmpfs have >2GB.

The error message:

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: write EIO
at afterWriteDispatched (node:internal/stream_base_commons:1 60:1 5)
at writeGeneric (node:internal/stream_base_commons:1 51 B)
at Socket._writeGeneric (node:net:795:11 )
at Socket.=write (node:net:807:8)
at writeOrBuffer (node:internal/streams/writable:389:1 2)
at _write (node:internal/streams/writable:330:1 0)
at Writable.write (node:internal/streams/writable:334:1 0)
at console.value (node:internal/console/constructor:286:1 6)
at console.log (node:internal/console/constructorB60:26)
at ConsoleOutput.write (/opt/Mullvad VPN/resources/app.asar/build/src/shared/logging.js:83:25)
``` 
![image](https://user-images.githubusercontent.com/956446/205362397-6d191a49-8627-4818-ae46-26214e7f0ce3.png)

Note: I have encountered similar pop-ups with Mullvad GUI in 2021 with the same computer (and Ubuntu likely 21.04), and stopped using mullvad shortly after. AFAIK the error was also in `ConsoleOutput.write` but I am not certain of this.

Tail of `logs/frontend-main.log` does not seem to be related (masking the exact times):
```
[...]
[2022-12-02 15:XXX][verbose] GRPC Channel connectivity state changed to 2
[2022-12-02 18:XXX][verbose] GRPC Channel connectivity state changed to 2
[2022-12-02 19:XXX][verbose] GRPC Channel connectivity state changed to 2
```

Tail of `logs/frontend-renderer.log` also seems unrelated (masking the exact times):
```
[...]
[2022-12-02 18:XXX][verbose] Tunnel state: error
[2022-12-02 19:XXX][verbose] Tunnel state: connecting
[2022-12-02 19:XXX][verbose] Tunnel state: connected
```

**Comment by gavento** [comment]
More error pop-up observations:

## 1.

The error popup appears immediately when I click "Support", then "Report a problem", and then "View app logs". When I close the popup, an editor opens with the concatenated log info (as is likely intended). This is reproducible - the error does not re-appear upon clicking "View app logs" again without closing the "Report problem", but does reappear if I close and reopen the "Report problem" view.

The only log record close to the time of the error is one in `logs/frontend-main.log`. No other logs (in `.config/Mullvad VPN` nor in `/var/log/mullvad` contained any records close to the time.

```
[2022-12-03 11:58:30.860][verbose] Problem report was written to /tmp/88ca52c5-0606-4bd1-9ced-c1a9e57024ec.log
```

Note that in the screenshot, the drawing of the window under the error is blocked on the dialogue; but that is very minor and likely not worth fixing (the app redraws on closing the popup).

![image](https://user-images.githubusercontent.com/956446/205437573-41ecfeae-a345-4a4f-8f4f-5738bd47ef18.png)

## 2.
One of those popups coincided with this log record in `logs/frontend-main.log`. No other logs (in `.config/Mullvad VPN` nor in `/var/log/mullvad` contained any records close to the time.

```
[2022-12-03 11:54:41.123][verbose] GRPC Channel connectivity state changed to 2
```

**Comment by raksooo** [comment]
Thanks for reporting and for all the information. We have this issue in our backlog and I will hopefully start working on it pretty soon. I'm not able to reproduce it myself but this information will definitely help me tackle it.

**Comment by raksooo** [comment]
@gavento What output do you get if you run `mullvad-problem-report collect --output problemreport.txt`? What is the exit code? The command combines all the application logs to one file and saves it as the provided filename and is run when you press "View app logs" in the app.

If you run the app from the terminal (`/opt/Mullvad\ VPN/mullvad-vpn`), is there any difference in that output compared to the contents of the log (`~/.config/Mullvad\ VPN/logs/frontend-main.log`) around the time of the error?

**Comment by gavento** [comment]
Ends without error (exit code 0):
```
gavento@computer:~$ mullvad-problem-report collect --output problemreport.txt; echo $?
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/openvpn.old.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/openvpn.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/shadowsocks.old.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/shadowsocks.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/old-install-daemon.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/early-boot-fw.old.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/early-boot-fw.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/daemon.old.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /var/log/mullvad-vpn/daemon.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /home/gavento/.config/Mullvad VPN/logs/frontend-main.old.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /home/gavento/.config/Mullvad VPN/logs/frontend-renderer.old.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /home/gavento/.config/Mullvad VPN/logs/frontend-main.log
[2022-12-10T07:12:09Z INFO  mullvad_problem_report] Adding /home/gavento/.config/Mullvad VPN/logs/frontend-renderer.log
Problem report written to /home/gavento/problemreport.txt

Send the problem report to support via the send subcommand. See:
 $ mullvad-problem-report send --help
```

NB that re-running it fails as it won't overwrite the file (exit code 1) - though not very likely to be the problem:
```
[...]
Error: Failed to write the problem report to problemreport.txt
Caused by: Permission denied (os error 13)
```

Re running the app from the terminal: will try that and report back.

**Comment by gavento** [comment]
I tried running the app from the console for ~5 days and got no error popups - that is unusual (though not impossible, given the variance in errors?)

However, when I force-closed the terminal window (not the Mullvad app), I get the error window twice (a second one appears after I close the first error, and after I close the second one, the app closes). 
**This is reproducible:**
- start the app from a console with `/opt/Mullvad\ VPN/mullvad-gui`
- close the console window without terminating the program first

The logfiles again do not contain any records related to the errors, e.g. `frontend-main.log` only has the following for that time. VPN itself keeps running.
```
[... messages from earlier ...]
[2022-12-16 14:44:03.013][info] before-quit received
[2022-12-16 14:44:03.015][info] Quit initiated
[2022-12-16 14:44:03.016][info] Unsubscribed from the daemon events
[2022-12-16 14:44:03.020][verbose] GRPC Channel connectivity state changed to 4
```

Both those errors are exactly the same:
<img src="https://user-images.githubusercontent.com/956446/208110826-b25d156c-88b7-435b-8d09-298b1ccbf382.png" width="47%"><img src="https://user-images.githubusercontent.com/956446/208110858-d7187127-8829-4464-b37c-d55adcac2459.png" width="47%">

**Comment by raksooo** [comment]
Thanks for the info! I'll look into it!

**Comment by emilmelnikov** [comment]
I'm experiencing a similar issue on macOS 13.4.1 (22F82):
<img width="512" alt="Screenshot 2023-06-27 at 09 41 36" src="https://github.com/mullvad/mullvadvpn-app/assets/1649961/d7f909b2-13d1-44ee-9c61-c4ac4d09ab56">

The error itself is not that bad, but the fact that the popup window blocks everything else is very unfortunate: you can't even stop/restart Mullvad, or do anything else from GUI.

It would be very nice to somehow make this window non-modal, if possible.

**Comment by ipslfn** [comment]
![mullvad 3](https://github.com/mullvad/mullvadvpn-app/assets/67012312/71c1a6c2-118e-4c71-9438-25b8304a6ead)
![mullvad](https://github.com/mullvad/mullvadvpn-app/assets/67012312/cb708d8e-579f-437f-bbf3-d66c11afbe75)
![mullvad 2](https://github.com/mullvad/mullvadvpn-app/assets/67012312/f4b40107-4e2b-4c86-a8eb-542fc8c84a64)
[problemreport.txt](https://github.com/mullvad/mullvadvpn-app/files/12423816/problemreport.txt)

I'm getting a similar issue, no luck through the CLI.

**Comment by faern** [comment]
Your `mullvad-daemon` system service is not running. That's why neither the CLI nor the GUI can talk to it. Fix that first. We indeed seem to have a bug in the GUI also, but that's unrelated to your non-running Mullvad system service. Open `services.msc` and right click "Mullvad VPN Service" and click start.

**Comment by brentmohan** [comment]
Also getting the "Error: 14 UNAVAILABLE: Connection dropped". Same as the two people above me

Tried reinstalling Mullvad, resetting network configuration, restarting the Mullvad VPN services (it was running already), turning off firewalls, and some more measures, with no success.
For every Mullvad command in CLI I'm getting "RPC Failed" errors. 

![image](https://github.com/mullvad/mullvadvpn-app/assets/148244795/362c46c0-b2bd-4972-85d3-3f679a889dc2)

![image](https://github.com/mullvad/mullvadvpn-app/assets/148244795/1b9b0106-cad9-46a4-859a-0d2b55a7af0f)

Would love to hear how to resolve this

**Comment by brentmohan** [comment]
Still dealing with this issue. No fix?

**Comment by shriramters** [comment]
idk why this is closed, the issue is still there on 2024.4

**Comment by wtechgo** [comment]
I have this issue only when I run `mullvad.desktop`, which points to a script that works normally when executed from the terminal.

Here's the script in case that would matter.

```
#!/bin/bash

is-mullvad-connected() {
  [[ "$(mullvad status | grep "Connected to")" ]] && echo "true" && return
  mullvad status >&2
  echo "false"
}

[ "$(pgrep -f "/usr/lib/firefox")" ] && echo Firefox is running, abort && sleep 3 && exit
[ "$(pgrep Telegram)" ] && echo Telegram is running, abort && sleep 3 && exit

mullvad-vpn &

sleep 5
mullvad connect
sleep 7

[ "$(is-mullvad-connected)" = "false" ] && 
  echo "retrying Mullvad connect..." &&
  mullvad connect && sleep 4

[ "$(is-mullvad-connected)" = "false" ] && 
  echo "Mullvad could not connect, abort" && exit

firefox -P crypto &

```

And the `.desktop` entry.

```
[Desktop Entry]
Exec=/home/user/.local/bin/the_script.sh
Name=the_script
Terminal=true
Type=Application
```

If anybody knows how I can fix this, let me know because it's bugging me way more than it should lol.

**Comment by nsirolli** [comment]
I have also this issue.

App version: 2025.4
OS: Arch
DE: sway 1.10

**Comment by waltmck** [comment]
I think that this issue should be reopened as I can consistently reproduce this problem on two separate machines (both running Linux). I have been running the VPN in headless mode to avoid dealing with the buggy GUI but it is a pain to manually quit and restart the daemon whenever I need to change settings with the GUI.

Please let me know what information you need to resolve the problem.

EDIT: Here is the precise error message.

![Image](https://github.com/user-attachments/assets/ad9bc867-ddf2-4d50-a5dd-4afce8c53b22)

**Comment by nsirolli** [comment]
I could not explain why, but after launching mullvad-gui using a systemd unit (following the [Arch wiki](https://wiki.archlinux.org/title/Sway#Manage_Sway-specific_daemons_with_systemd)) the popup window with the error message never showed up again.
