### ISSUE TITLE
[Feature request] Split tunneling excludes websites

### ISSUE THREAD

**Issue by fabriziobagala** [mullvad/mullvadvpn-app#4204]
## Issue report

Operating system: macOS Ventura 13.0.1
App version: 2022.5

### Issue description

When split tunneling will be implemented on macOS, and in any case on other operating systems as well, it would be useful to be able to exclude websites from VPN use.

**Comment by faern** [comment]
We are not currently planning on extending the split tunneling functionality to work on a per domain or per URL basis. It would either require us to intercept and handle all DNS queries, or integrate into the webbrowser (would only work for browsing split tunneling). You can already do this manually, but it's very cumbersome. You can run your own local socks5 proxy that you apply split tunneling to (on the platforms that support it) and then run the container plugin on firefox and configure individual socks5 proxies per container. And in that way have some containers go outside the VPN tunnel.

I'm closing this as it's not really planned. For macOS split tunneling feature request see #3039 (yes, I know it's your own issue post)
