### ISSUE TITLE
Mullvad-daemon (without VPN active) on macOS Ventura disrupts iCloud Private Relay 

### ISSUE THREAD

**Issue by aniqueta** [mullvad/mullvadvpn-app#4215]
## Issue report

Operating system: macOS 13.1 (Ventura)

App version: 2022.5

### Issue description

Upon upgrading from macOS 12.6.1 (Monterey) to macOS 13.1 (Ventura), I found that iCloud Private Relay would no longer activate. The error messages were that system settings prevented this. This was surprising, since the same system settings were active prior to the upgrade. 

Through process of elimination of removing various network settings, I found that when mullvad-daemon is running in the background, even without being connected to a Mullvad VPN, iCloud Private Relay cannot activate. Disabling the LaunchDaemon or completely uninstalling Mullvad (and then restarting) resolves this. Reinstalling Mullvad recreates the issue, and again, just disabling the LaunchDaemon and restarting resolves the issue. 

I suspect this is not entirely a Mullvad issue, but rather a bug from Apple in macOS Ventura, given there were no issues previously in Monterey. Additionally, when iCloud Private Relay is unable to activate, the new System Settings app hangs when navigating to the iCloud and iCloud Private Relay settings. It's also strange that this is even an issue when Mullvad VPN isn't active, not listed as a VPN in System Settings (e.g., after a fresh reinstall), and just the daemon waiting in the background. (Of course, iCloud Private Relay will not be available when a VPN is active, but in this case, even having the app installed and the daemon waiting in the background is apparently a problem.)

I do not know if there is a workaround Mullvad can explore here and/or if Mullvad can bring the bug to Apple's attention. Thanks.

**Comment by Timolution** [comment]
Same issue here. Just updated from Monterey 12.6.2 to Ventura 13.1, and encountered exact same problem with same workaround ‘solution’.

**Comment by ermonas** [comment]
Can reproduce. No issues in 13.0, but as soon as I updated to 13.1, iCloud Private Relay stopped working altogether until I uninstalled Mullvad.

**Comment by pinkisemils** [comment]
This might be related to #2401, and it's currently being worked on. However, I can't promise anything there.

**Comment by aniqueta** [comment]
Thanks for looking into this. This remains an issue in 2023.1 and macOS Ventura 13.2. Out of curiosity, what exactly is mullvad-daemon doing that requires it to be running at all times, even when Mullvad isn't active?

**Comment by faern** [comment]
It technically does not need to run when the user does not want to use Mullvad (except if they are in lockdown mode, then our daemon still needs to run and keep the firewall in a blocking state). However, it would be much harder to architect the app in such a way that it did not run when not needed and still provide the same security guarantees.

For example, the daemon should start asap on boot, so that if you have `auto-connect` enabled, it should protect the user as early in the boot process as possible.

Starting and stopping the system service requires root access, so the GUI cannot do it. As a result the app GUI can't just start and stop the daemon as it see fit. The easiest is to just let it run in the background all the time, being ready for interaction from the Mullvad command line interface or GUI.

**Comment by Jo-SR11** [comment]
Bypassing the Mullvad client and using the wireguard app fixes this, albeit partially—being able to run private relay with the mullvad app would be the ideal solution. If the wireguard app is able to coexist with private relay, then mullvad should be able to shouldn't it?

**Comment by cityrolr** [comment]
On the newest Mullvad versions (2023.3 & 2023.4), this issue seems fixed to me. Apple Privacy Relay only gets disconnected when connecting to Mullvad, and when disconnecting, Privacy Relay is on again.

**Comment by raksooo** [comment]
@cityrolr Great to hear! We've made changes in 2023.4 which we believe fixes this so I'll close the issue. Please write here if this is still an issue and we'll open it again.

**Comment by conmulligan** [comment]
This was previously resolved for me, but after updating to `2024.6` it was regressed on macOS `15.0.1`.
