### ISSUE TITLE
Resize UI issue

### ISSUE THREAD

**Issue by nouser32** [mullvad/mullvadvpn-app#4217]
## Issue report

Operating system:  Windows 11

App version: 2022.5

### Issue description

The desktop app has issue that auto resize when changing to external screen(changing GPU to the external one ),that deny to get full access to app features until quit it and open it again 
![image](https://user-images.githubusercontent.com/120561776/207568382-49af44a6-1c43-44b9-b467-bbe5e206780d.png)

**Comment by raksooo** [comment]
@nouser32  Would you like to test a dev-build that might have fixed this? Dev-builds haven't gone through our internal testing and we can't guarantee the security of them.

https://releases.mullvad.net/builds/2022.5-dev-45f5f6/

If the window still ends up with the incorrect size, does it reset if you press the tray icon? Or hide it and reopen?

More info can be found in: https://github.com/mullvad/mullvadvpn-app/issues/3120
