### ISSUE TITLE
VPN app tries to access credentials store on Linux

### ISSUE THREAD

**Issue by Mart-Bogdan** [mullvad/mullvadvpn-app#4229]
## Issue report

Operating system: Manjaro Linux, kernel: 5.15.81-1-MANJARO. KDE: 5.26.4

App version: 2022.5

### Issue description

As soon as I disconnect VPN or switch location, system prompts me to unlock my password manager, KWallet, currently.
And it doesn't provide app name, as some apps, like Chrome does. 

![image](https://user-images.githubusercontent.com/775038/208249235-fbbf29db-5cd5-41dc-ac60-f31991b34765.png)

**Comment by pinkisemils** [comment]
It would be great if you were to send us a problem report so we can read the logs. 

I don't believe it would be our application that is reading from the wallet. Does this happen if you use the CLI too? You can try that out via `mullvad reconnect` or `mullvad disconnect`.

**Comment by faern** [comment]
Thanks for reporting. We have seen this once in the past, but was unable to identify the source for it. Our app is not reading anything from the user wallet for sure. Most likely a bug in `kded5` or other related services. We also don't really support Manjaro, and given that so few hit this issue we are not likely to dig deep into it right now.

**Comment by Mart-Bogdan** [comment]
I haven't tryed cli version. Hm. need to try I guess. 

I don't sure how to track what process is accessign it actually. Didn't see anything in list of open processes. Perhaps something is reacting on network change. 

P.S. I don't think it's completely Manjaro related. I'll try it on another distro next year (HA HA). And would try to get more info.

THat's just me enabled wallet to ask every time, which is not enabled by default.

**Comment by HanM23** [comment]
> Thanks for reporting. We have seen this once in the past, but was unable to identify the source for it. Our app is not reading anything from the user wallet for sure. Most likely a bug in `kded5` or other related services. We also don't really support Manjaro, and given that so few hit this issue we are not likely to dig deep into it right now.

Thanks for your input, btw, may i ask you if there is any plan to support Arch based distros ? Or is there any reason to not support them ?
Regards

**Comment by HanM23** [comment]
Not a sane OS ? I use Mullvad on Manjaro for 1 year now without any issue.
Maybe you are not sane either, and you surely lost one customer, i do not like your mentality.

**Comment by MrChocolatine** [comment]
> Not a sane OS ? I use Mullvad on Manjaro for 1 year now without any issue. Maybe you are not sane either, and you surely lost one customer, i do not like your mentality.

What a sensitivity... I don't see anything mean.

**Comment by aidzmtsk** [comment]
> Not a sane OS ? I use Mullvad on Manjaro for 1 year now without any issue. Maybe you are not sane either, and you surely lost one customer, i do not like your mentality.

Yeah, I get this issue is old, but just want to point [this](https://manjarno.snorlax.sh/) out
