### ISSUE TITLE
[Feature request] Obfuscated servers

### ISSUE THREAD

**Issue by fabriziobagala** [mullvad/mullvadvpn-app#4245]
## Issue report

Operating system: macOS Ventura 13.1

App version: 2022.5

### Issue description

Obfuscated servers are specialized VPN servers that hide the fact that you’re using a VPN to reroute your traffic.

**Comment by faern** [comment]
We already support this on macOS (and all desktop OSes). Currently only with OpenVPN, but it will come to WireGuard as well. Go to Settings -> VPN Settings -> Set "Tunnel Protocol" to OpenVPN and go to OpenVPN settings -> Enable bridge mode.

Now your connection will use Shadowsocks and go via one of our bridge servers. When you open the location selection you will now see two tabs, entry and exit, that decide the first hop (bridge) and second hop (OpenVPN)

We are working on extending this support, to use various obfuscation protocols and use our bridge servers for WireGuard also. But that's for later. I'm closing this as rudimentary support is already here. This can be re-opened if you write a more specific feature request and it's about something we currently don't have.

**Comment by MrChocolatine** [comment]
> We already support this on macOS (and all desktop OSes). Currently only with OpenVPN, but it will come to WireGuard as well. Go to Settings -> VPN Settings -> Set "Tunnel Protocol" to OpenVPN and go to OpenVPN settings -> Enable bridge mode.
> 
> Now your connection will use Shadowsocks and go via one of our bridge servers. When you open the location selection you will now see two tabs, entry and exit, that decide the first hop (bridge) and second hop (OpenVPN)
> 
> We are working on extending this support, to use various obfuscation protocols and use our bridge servers for WireGuard also. But that's for later. I'm closing this as rudimentary support is already here. This can be re-opened if you write a more specific feature request and it's about something we currently don't have.

With WireGuard enabled, is the `Obfuscation` setting diffent? (Settings > VPN settings > WireGuard settings > Obfuscation)

**Comment by faern** [comment]
Ah yeah. So when we use the word "obfuscation" we usually mean hiding the VPN traffic in some obfuscation protocol. This means we count putting WireGuard traffic in a TCP connection as obfuscation. But the traffic is still going directly to the VPN server, not via any bridge.

A bridge is a special type of server. They are not VPN servers in the sense that they don't host OpenVPN or WireGuard on them. They only host a bunch of obfuscation services to allow users to reach our VPN servers through them.

OP used the term "obfuscation server" which I interpreted as "bridge server" and answered accordingly. We do support "obfuscation" with WireGuard (Wireguard over TCP), but we don't yet support going via bridge servers with WireGuard.
