### ISSUE TITLE
Quitting via ⌘Q doesn't disconnect VPN

### ISSUE THREAD

**Issue by rosszurowski** [mullvad/mullvadvpn-app#4250]
## Issue report

Operating system: macOS Ventura 13.1
App version: 2022.5

### Issue description

Previously, quitting the Mullvad menu bar app with ⌘Q would disconnect the VPN. However, as of recently, the VPN silently stays active. This has tripped me up a few times: usually I find out because I discover my internet speeds are 1/3 of what they should be because my packets are going across the Atlantic.

It seems like this was changed as part of the 2022.5 release, judging by the [2022.5 version release notes](https://github.com/mullvad/mullvadvpn-app/releases/tag/2022.5):

> Stay connected when desktop app is killed or crashes. The only situation where the app now
disconnects on quit is when the user presses the quit button.

I'm flagging this as a bug because it seems like pressing the "quit" button in the app _does_ in fact disconnect the tunnel, but using ⌘Q _doesn't_. This seems like it might have been an oversight, since both actions are the user explicitly telling Mullvad to close. Using shortcuts for menu bar apps isn't terribly common so maybe it was forgotten in testing?

### Screen recording

Here's a quick screen recording demonstrating what I mean. First I quit the app using the "quit" button and the tunnel is disconnected. Then I use ⌘Q but the tunnel stays active.

https://user-images.githubusercontent.com/303731/210167686-cd5c7751-1895-45c8-b16d-6c4d2d6f99c3.mp4

**Comment by faern** [comment]
> Using shortcuts for menu bar apps isn't terribly common so maybe it was forgotten in testing?

You are correct. We will most likely disable the hotkey completely. It does not make sense to have cmd-q quit Mullvad when we are not the currently active application according to macOS. Our app's name is not written in the top left next to the apple menu.

**Comment by rosszurowski** [comment]
Disabling the hotkey would be an improvement because folks like me wouldn't use it any more and run into an unexpected behaviour.

That said, I think I misspoke when I said it "isn't terribly common." What I meant is that it's _not commonly known_ that menu bar apps support keyboard shortcuts. It _is_ common for menu bar apps to support shortcuts while they have focus. Some examples off the top of my head:

- 1Password (use Ctrl+Click to access their menu)
- Fantastical
- CleanShot X
- Raycast
- Docker
- Loom
- Tailscale

I'd encourage you to keep the ⌘Q shortcut around, unless it's causing issues.

**Comment by faern** [comment]
We don't want users to accidentally disconnect. So having cmd-q quit & disconnect without any warning dialogue would be a bit dangerous. We will still opt for removing the shortcut and we'll see what people think about that.
