### ISSUE TITLE
Tray icon dimension in Tint2 on Linux

### ISSUE THREAD

**Issue by niels0n** [mullvad/mullvadvpn-app#4280]
## Issue report

Operating system: Arch Linux

App version: 2022.5

### Issue description

Hi, is it possible to scale the icon in tray on Tint2?

As you can see in the screenshot it is smaller than the others and I can't find a way to resize it.

Any help would be gratly appreciated.

![ArchLabs_2023-01-16-05_141x31](https://user-images.githubusercontent.com/47432766/212764488-edfec0b9-61ae-4e81-89ab-a6ea2568fdbf.png)

**Comment by raksooo** [comment]
Thanks for reporting this issue! Tray icons on Linux is a bit tricky (especially in combination with the Electron APIs) and we've previously had issues that the icon is too large in some window managers and too small in others. Unfortunately this would be a bit complicated and very time consuming to solve for all setups, so we won't change anything unless this becomes a big problem in more common setups.

**Comment by niels0n** [comment]
Okay, thanks for the reply!
