### ISSUE TITLE
Automatically check server load before connecting

### ISSUE THREAD

**Issue by robd003** [mullvad/mullvadvpn-app#4281]
### Issue description

It would be great if the app would query mullvad first to see which servers in the geographic location you selected were the least utilized and then picked one of them instead of just selecting a server at random. I've had times where I connect to a server that is under heavy load and I have to disconnect / reconnect until I get one that has available bandwidth.

**Comment by faern** [comment]
Hi. Server load is not an issue for your connection. We do not publish server load anywhere publicly available. But I can assure you our servers network or CPU load is not a bottleneck. Our servers have significant spare capacity.

If you experience a slow tunnel to a specific server it's much more likely that you (your ISP) has bad peering to that specific server (or its data center), or that that this specific connection is getting throttled by some party between you and the server.

We won't implement this for the same reason we won't implement a "fastest server" location selection option. See my previous answer to that here: https://github.com/mullvad/mullvadvpn-app/issues/1925#issuecomment-759405550.
