### ISSUE TITLE
2018.2 client does not connect under LMDE2

### ISSUE THREAD

**Issue by gstor2018** [mullvad/mullvadvpn-app#429]
I am using Linux Mint Debian Edition version 2 (based on Debian 8/Jessie), and the 2018.2 client fails to install; package installer reports that all dependencies are met, but then "Failed to install package 'MullvadVPN-2018.2_amd64.deb'" and the following:

```
Unpacking mullvad-vpn (2018.2.0) ...
Setting up mullvad-vpn (2018.2.0) ...
Created symlink from /etc/systemd/system/multi-user.target.wants/mullvad-daemon.service to /etc/systemd/system/mullvad-daemon.service.
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package mullvad-vpn (--install):
 subprocess installed post-installation script returned error exit status 1
Processing triggers for gnome-menus (3.13.3-6) ...
Processing triggers for desktop-file-utils (0.22-1) ...
Processing triggers for mime-support (3.58) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
```
However, the Mullvad VPN application shows up in the Menu after the above. If I launch it, it reports  "Connecting to daemon..." and doesn't do anything else. The old version (67) connects properly.

**Comment by faern** [comment]
Debian 8 has reached end of life (EOL). This issue has also been inactive for very long. Closing.
