### ISSUE TITLE
Yarn is not working

### ISSUE THREAD

**Issue by Myzel394** [mullvad/mullvadvpn-app#4290]
## Issue report

Operating system: Fedora 37 (Linux)

App version: 2022.5

### Issue description

When I try to install a dependency using yarn (e.g. `yarn install react`) I always get this error when I'm connected to Mullvad:

```bash
error An unexpected error occurred: "https://registry.npmjs.org/react: connect ECONNREFUSED 2606:4700::6810:1323:443".
info If you think this is a bug, please open a bug report with the information provided in "/home/nintendogs/super-secret-project/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

[Already tried out this answer](https://stackoverflow.com/a/45877279/9878135), but the error persists

**Comment by pinkisemils** [comment]
Does this happen even if you reconnect? I currently cannot reproduce this, but it might be due to IPv6. You could also try disabling IPv6 and see if that solves the issue.

**Comment by Myzel394** [comment]
I tried several servers, but none worked (trie rented, owned and different countries). Strangely though `curl https://registry.npmjs.org/react` seems to work, as I'm getting a huge response back. I don't know `nc` but when I run `nc registry.npmjs.org 443`, there is nothing shown in the console.  What do you mean by "disabling IPv6"?

**Comment by MrChocolatine** [comment]
@Myzel394 , I think he meant deactivating it in the VPN settings:

![vpn ipv6](https://user-images.githubusercontent.com/47531779/213185048-6165f424-41b0-4ee5-abce-8a9f9909e2fb.png)

**Comment by Myzel394** [comment]
@MrChocolatine I already had it deactivated but **activating** it seems to resolve this issue! :D
