### ISSUE TITLE
Device requirements for OpenVPN

### ISSUE THREAD

**Issue by vrnvorona** [mullvad/mullvadvpn-app#4311]
## Issue report

Operating system: MacOS

App version: 2022.5

### Issue description

After upgrading from 2022.1 to 2022.5 I lost ability to use OpenVPN without registering wireguard device (i had 5 locked on other devices, and used openvpn on mac because it doesn't use wireguard key limit).

**Comment by pinkisemils** [comment]
This is working as designed, as there should only ever be 5 logged in apps per one account at any one point in time.
