### ISSUE TITLE
Hang at connecting when internet is bad

### ISSUE THREAD

**Issue by logan2k** [mullvad/mullvadvpn-app#4328]
## Issue report

Operating system: <Debian 11>

App version: <2022.5>

### Issue description

If Internet or Mullvad server is not easy to reach, the GUI will only show "connecting" and "blocking internet" without server name, and cannot change server location. Can exit GUI, but seems the real stucking process is the daemon, have to kill it and wait for timeout.
This problem is only on 2022.5, not older versions.

**Comment by faern** [comment]
Can you please send a problem report, so we get the app logs from when it ended up in this state? You can send them from the GUI if you open settings -> Support -> Report a problem. Please explain the issue or link to this issue. And please specify the time when the issue happened, so we can correlate that with the timestamps in the logs.

**Comment by pinkisemils** [comment]
Have you tried the latest beta? This might already be fixed.
