### ISSUE TITLE
Limit access to control mullvad-daemon to certain users/groups

### ISSUE THREAD

**Issue by emerajid** [mullvad/mullvadvpn-app#4355]
OS: Debian GNU/Linux 11 (bullseye)
App version: 2022.5

Hi. I want to be able to manage permissions. Currently I use handmade openVPN setup because no one but root can control it, so users without access to privileges are forced to use VPN. But many servers are wireguard and combining openVPN and wireguard is kind of PITA. With mullvadVPN I can connect as one user and then effortlessly disconnect as another. Can this somehow be managed so that only authorized users can speak to mullvad-daemon?

**Comment by faern** [comment]
You can restrict which group has access to the `mullvad-daemon` management interface with the environment variable `MULLVAD_MANAGEMENT_SOCKET_GROUP`. Please see the documentation in the readme: https://github.com/mullvad/mullvadvpn-app/#environment-variables-used-by-the-service

**Comment by emerajid** [comment]
@faern
Thank you, I was reading inattentively.
