### ISSUE TITLE
VPN configuration on macOS

### ISSUE THREAD

**Issue by fabriziobagala** [mullvad/mullvadvpn-app#4370]
## Issue report

Operating system: macOS 13.2.1
App version: 2022.5
Chip: Apple M2

### Issue description

More than reporting an issue, this is a clarification of how Mullvad VPN works.

I have noticed that several VPN apps create a VPN configuration on macOS, while Mullvad VPN does not. How come this does not happen? Is this a mismanagement of the VPN or an alternative method? Services that add VPN configuration directly into the operating system give the impression that they integrate seamlessly into the operating system.

Example:

![immagine](https://user-images.githubusercontent.com/62190484/219850349-2a07bbe6-c42a-4bd4-b67a-de31a142b37f.png)

![immagine](https://user-images.githubusercontent.com/62190484/219850088-57ab8f13-11d8-421d-b850-6427e260d640.png)

**Comment by pinkisemils** [comment]
The listed applications use the packet tunnel NetworkExtension API, which is somewhat cumbersome. It would necessitate significant changes that would only benefit macOS. This of course isn't without it's downsides, but one significant benefit is that the communication between our tunnel and the firewall code is a lot clearer and robust. Our experience with the packet tunnel on iOS seems to indicate it isn't as robust as one would prefer.
