### ISSUE TITLE
Two factor authetication when signing in

### ISSUE THREAD

**Issue by d4f5409d** [mullvad/mullvadvpn-app#4383]
Please provide an option to have a secondary factor when logging in in every app and on the website, if someone gets/sees our private account number so we can protect our accounts.

**Comment by faern** [comment]
This is not really related to the app, but rather to the service in general. I would highly recommend that you contact support@mullvad.net with this feature request.

In general, treat your account number as a password, don't show it to others. We previously showed the account number in various places in the app and website. But we have now started masking it out like a password everywhere, so this should be less of an issue now.
