### ISSUE TITLE
[Feature request] Obfuscation in the mobile app

### ISSUE THREAD

**Issue by dizelgerda** [mullvad/mullvadvpn-app#4417]
## Issue report

Operating system: IOS 16.3.1

App version: 2022.2

### Issue description

Hello! The iOS app is very lacking in obfuscation. In countries such as China or Russia, this function is very necessary.

Thank you for your work. I hope that this feature will appear in the near future.

**Comment by faern** [comment]
We know this is a wanted feature and it's in the backlog.

**Comment by buggmagnet** [comment]
Hello,

Since this issue was opened, we added UDP over TCP obfuscation for WireGuard in iOS. I'm closing this issue, but please do re-open an issue if this doesn't work in your situation so we can get feedback on what to focus on in order to unblock our users.

Thank you for your support !
