### ISSUE TITLE
[Question] DDNS with mullvad

### ISSUE THREAD

**Issue by rhayart** [mullvad/mullvadvpn-app#4429]
Hi,

I'm using the mullvad app on a linux computer.
It's probably a noob question, but i cannot find an answer about this.

I have an nginx web server running on that computer.
I added a new port forwarding and listen to this port on my nginx conf.

I can reach my website using the OUTSIDE_RELAY_IP:FORWARDED_PORT
But i would like to use a dynamic DNS (DDNS) for it.

I'm using duckdns.org, so i have MY_DOMAIN.duckdns.org set to the OUTSIDE_RELAY_IP, but with this setup
i can't reach the web server.

Is there a solution to this ?

Thanks in advance.

**Comment by faern** [comment]
Does the name resolution work? If you run `dig MY_DOMAIN.duckdns.org` does it actually return `OUTSIDE_RELAY_IP`?

Did you configure nginx to listen to `MY_DOMAIN.duckdns.org`? If it does get a request that does not match your config it won't respond correctly.

**Comment by faern** [comment]
This question is not app related. If you have further inquiries on the same topic, please send that to support@mullvad.net, thank you :)

**Comment by rhayart** [comment]
Yes it ping to the `OUTSIDE_RELAY_IP` and nginx it setup for `MY_DOMAIN.duckdns.org` 
Without the VPN set, i can reach the domain.

Oh sorry, ok, i will send this to the support then.
Thanks.
