### ISSUE TITLE
[Tip] Annual third-party audits

### ISSUE THREAD

**Issue by fabriziobagala** [mullvad/mullvadvpn-app#4433]
## Issue report

Operating system: macOS 13.2.1
App version: 2023.2

### Issue description

Possibility to have available the annual reports of third-party audits (performed, for example, by Cure53) on the infrastructure and apps, and on the no-log policy. Currently, a lot of time passes between audits. Third-party audits increase customers' confidence in the service.

**Comment by faern** [comment]
You can find all our audits under the audit tag in our blog: https://mullvad.net/en/blog/tag/audits/. And for the app specifically, all audits are available in https://github.com/mullvad/mullvadvpn-app/tree/main/audits.

Our last app audit was during October 2022. I don't agree that's a long time ago. We perform app audits every second year. So the next one is scheduled for 2024. We don't see any value in having them more often. Performing an audit takes time from the development team. Time we could use to improve the app. And given how good results we have had in the audits that we already performed, it feels like a bit of waste to do them more often.
