### ISSUE TITLE
Add Bitcoin/Lightning ⚡ Payment Method to Reduce Payment Friction [Feature Request][UX]

### ISSUE THREAD

**Issue by alltheseas** [mullvad/mullvadvpn-app#4435]
Operating system: Initially web (mullvad.net), and later suggest adding directly to iOS, Android apps.

App version: -

## User Story

As a Mullvad user or prospective user who would like to quickly top up my account using sats, I would like the capability to pay via Bitcoin's Layer 2 Lightning Network, so that I can reduce my payment friction, AND instantly receive a confirmation of my BTC payment via LN to Mullvad.

### Acceptance Criteria ###
1. Mullvad user has a way to pay via Lightning (⚡ ) on mullvad, and this is visible under payment methods. Mockup: 
![LN Mockup Mullvad](https://user-images.githubusercontent.com/64376233/224405141-1409f7ed-a49a-4539-b82d-dc72c873e846.png)

2. Implementation suggestion: utilize one-time Bolt11 invoice generated for customer specified amount (see FOSS [BTCPayServer](https://github.com/btcpayserver) implementation. BTCPayServer is used by lightning.store)
3. Amount specific (see 2.) LN invoice address is displayed and copy-able to clipboard (copy functionality)
4. QR code is automagically generated, which contains LN invoice address (see 3.; see [lightning.store](https://lightning.store/) pay with LN example below)
5. Open in wallet option leads to system default BTC/LN wallet, and automagically transposes LN invoice via copy paste
6. User receives feedback visual "Payment Received" confirmation (e.g. via modal or other method)  as soon as LN⚡ payment is received.

<img width="661" alt="Screenshot 2023-03-10 at 12 58 01 PM" src="https://user-images.githubusercontent.com/64376233/224402962-2f68775d-df24-4f0d-a93d-d8720b9db51e.png">

**Comment by Skyman21m** [comment]
Yep as a regular Mullvad user paying it Bitcoin, this feature would be greatly appreciated indeed. I know many Bitcoiners who also use Mullvad and who'd pay via Lightning if it was unabled. It's faster, much more private for the sender if done in a non custodial way, and it should not be to difficult to figure it out for the MullVad IT team.

**Comment by faern** [comment]
Supporting Lightning as a payment option is in the backlog for the team managing payment methods. But I can't give any ETA for when that might be available. Probably not very soon. For all non-app related questions and feature requests, please contact support@mullvad.net.

The app does not integrate any payment options. Except redeeming vouchers, and on iOS we have in-app purchases. We currently have no plan to integrate more payment options in the app. Mostly because we think it's fairly easy to do on the website. But also because Apple/Google will not allow us to have other payment methods than their own.

**Comment by neorrk** [comment]
Supporting Lighting is super important for times like this:
![image](https://user-images.githubusercontent.com/58256328/236879811-35a233b7-adfb-4719-b447-5234869d04ac.png)

**Comment by Redsandro** [comment]
@pinkisemils closed this as completed on Mar 15, 2023, but I can't find the option to use Lightning. Where can I find the option for Lightning?

**Comment by faern** [comment]
Please see my previous comment about how this is not the issue tracker for payment methods. Please contact support@mullvad.net for anything not app related. https://github.com/mullvad/mullvadvpn-app/issues/4435#issuecomment-1467642117
