### ISSUE TITLE
Desktop app server search 

### ISSUE THREAD

**Issue by skar395** [mullvad/mullvadvpn-app#4485]
## Issue report

Operating system: Arch Linux

App version: 2023.2

### Issue description

I have the app in Italian but the search doesn't work in Italian, the content is searched only by writing in English.
If you search in English with the UI in Italian, the search works correctly

**Comment by dizelgerda** [comment]
I join, the same problem with other languages.

**Comment by raksooo** [comment]
Thanks for reporting! We'll look into this!
