### ISSUE TITLE
Feature request: remove the nag about using betas

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [mullvad/mullvadvpn-app#4510]
## Issue report

Operating system: Windows 10 Pro - 22H2 (2009: 19045)

App version: 2023.2

### Issue description

I tire of seeing this obstructive message:

![image](https://user-images.githubusercontent.com/47056543/229314105-43e2cf12-46a5-4719-93d7-85cb20fa79bb.png)

Yet, there is no way to get rid of the message (save by installing the beta - and even then the relief will be temporary).

I should like there to be a way of disabling those messages. A close button? An option to never see such messages?

**Comment by raksooo** [comment]
If you aren't interested in the beta versions you can opt out of the beta program under Settings > Support > Beta program. Although you can only opt out if you're currently using a stable version.

**Comment by faern** [comment]
Yes. We already have the setting you are asking for. It's just that you are being automatically opted in to betas as soon as you install one. And you can't disable it while using a beta. I'm closing this as done.
