### ISSUE TITLE
App not connecting on Android

### ISSUE THREAD

**Issue by 0verEngineer** [mullvad/mullvadvpn-app#4516]
## Issue report

Operating system: 
Android 13 (GrapheneOS)

App version: 2022.3

### Issue description
- On App start it is Stuck about 30s on "Connecting to mullvad system services"
- Then login loads for 30s and then it failed with the error: "An error occured"
- If i try to use the "Report a Problem"-Feature it loads and then it says "Failed to send"

**Comment by faern** [comment]
Thanks for reporting this. We currently have some issues with our API servers and our app does not handle this as gracefully as one could wish it would. We are working on resolving the server issues. We'll also put some effort into making the in app errors more clear!

**Comment by mollyuser** [comment]
How long will this take? Just bought an account but cannot use it since i cant login into mullvad.

**Comment by 0verEngineer** [comment]
> How long will this take? Just bought an account but cannot use it since i cant login into mullvad. 

I'm not a mullvad developer so i can't answer your question, but in the meantime you can use the Wireguard app, just google how to set it up.

**Comment by faern** [comment]
We of course hope that the API server is back to normal asap. I can't give any detailed estimate. Hoping for later today of course, but could also take another day or so if we are unlucky. Fixing the handling inside the app will be slower since it requires a test and release cycle.

**Comment by faern** [comment]
This has been fixed now. The Android app should hopefully work as normal. The API server has a bit stricter rate limiting than usual, and you might be hit by this. But if you try again a while later it should hopefully let you in!
