### ISSUE TITLE
Increase compatibility with different init systems, in particular sysvinit and runit

### ISSUE THREAD

**Issue by baimafeima** [mullvad/mullvadvpn-app#452]
Do you have any plans to increase compatibility so that it could also be used on operating systems such as **Devuan** and **MX Linux** (both use `sysvinit`) or **Void Linux** (`runit`)?
See: https://mxlinux.org/wiki/system/systemd

> MX Linux ships with systemd present but disabled by default. The MX Linux team strongly urges users to remain with this configuration which uses sysvinit instead.

**Comment by faern** [comment]
We currently have no plans on supporting older or more obscure init systems. But thanks for letting us know about them, we might look into it one day.

**Comment by alec1** [comment]
Another vote for supporting sysvinit.  Thank you!

**Comment by emilnd** [comment]
Hi!
One more vote for this!

Would it be possible to get some kind of a summary of what work would be needed to break out of systemd from Mullvad?

**Comment by bobemoe** [comment]
Yep, another vote for this.

There are many privacy/security and even stability concerns with systemd and you may find that your target user base (privacy conscious users) may be deliberately opting not to use systemd.

Linux is about freedom and choice, but systemd is eroding this. By dropping support for everything else you are facilitating this erosion. Please help keep linux freedom and allow us to choose what software we run.

Other init systems may be old but they aren't obscure. They are tried and tested and still in use.

I suspect it's the init.d script that is missing to start the daemon, replaced by systemd's .service file. I have written my own init.d scrips for other applications.  I haven't check if this is the case on mullvad yet.

Thanks :)

**Comment by bobemoe** [comment]
So i'm not sure what the benefit of the mullvad app is but it works fine with openvpn on non-systemd linux https://mullvad.net/en/help/linux-openvpn-installation/ i'm happy now :)

**Comment by faern** [comment]
We are probably not going to do this. We hear from extremely few people who use these init systems. And if you do use them you can probably create your own service definition and make it start.
