### ISSUE TITLE
Feature Request - Option to Exclude RDP Port from Mullvand

### ISSUE THREAD

**Issue by tgwaste** [mullvad/mullvadvpn-app#4533]
The port forwarding solution for RDP is just bad.  The moment the VPN needs to reconnect you are locked out of your server again because the IP changes.  There needs to be a way to just be able to use Mullvand without it effecting RDP in any way.  When the VPN locks YOU out, thats a little to secure.

**Comment by pinkisemils** [comment]
You can use a forwarded port and have RDP listen on that port - this way you'd be able to accept incoming connections from the currently connected Mullvad's exit IP. 
Secondly, I don't believe it's possible to do this without 3rd party software on Windows, but on macOS you this might be possible by adding your own anchors to `pf` with rules to accept the specific traffic you want to allow. On Linux, you can follow our [advanced split tunneling guide](https://mullvad.net/it/help/split-tunneling-with-linux-advanced/),
