### ISSUE TITLE
2023.3 rpm installation fails due to file conflicts with another Electron app

### ISSUE THREAD

**Issue by vashirov** [mullvad/mullvadvpn-app#4534]
## Issue report

Operating system: Fedora 38

App version: 2023.3

### Issue description

`mullvad-vpn-2023.3-1.x86_64` rpm installation fails with the following message:
```
Error: Transaction test error:
  file /usr/lib/.build-id/0d/9fad3f21b1e381cc66b5efcae8f3910ae0edc1 from install of mullvad-vpn-2023.3-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
  file /usr/lib/.build-id/76/9d0269491ca2313fcd15d63059bac67bd8b1b3 from install of mullvad-vpn-2023.3-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
  file /usr/lib/.build-id/c2/dcac7cb6a727685d10d4161a0d14988f12a0fa from install of mullvad-vpn-2023.3-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
  file /usr/lib/.build-id/cb/dc9db5fec0e6129bddcb0c282be98be4c6966e from install of mullvad-vpn-2023.3-1.x86_64 conflicts with file from package slack-4.29.149-0.1.el8.x86_64
```

This issue is similar to:
https://github.com/bitwarden/clients/issues/3524
https://github.com/jgraph/drawio-desktop/issues/259

I believe it can be fixed by adding `--rpm-rpmbuild-define=_build_id_links none` to the `fpm` options for `rpm` build:
https://github.com/mullvad/mullvadvpn-app/blob/2cc9013dfe0b5336d7b7c3146a5c8702e3007477/gui/tasks/distribution.js#L203-L208

**Comment by intheendtheyweregone** [comment]
Had this same issue when trying to update Mullvad for a relative.. installed fine after adding the `--force` flag when installing. Not sure what, if any, consequences this had, but the "conflicting" applications seemed to work fine after.

`sudo rpm -i --force MullvadVPN-2023.3_x86_64.rpm`

**Comment by pinkisemils** [comment]
Thanks for reporting this, we'll look into this.
