### ISSUE TITLE
Make the Android notification persistant

### ISSUE THREAD

**Issue by Cappuccino093** [mullvad/mullvadvpn-app#4549]
There is a problem and it is that when you use the button to delete all notifications the Mullvad VPN notification got deleted too... It may be useful if there was an option to make it persistent and not deletable from the notification center

**Comment by albin-mullvad** [comment]
Thanks for reporting! Which device and Android version are you using?

**Comment by Cappuccino093** [comment]
Thanks to you!

I have made a mistake, the notification doesn't get deleted with the "Delete all" button, but anyway it can be deletable so I think that shouldn't be happening because I can close the VPN by mistake deleting the notification. Others VPN apps for example, it has the notification persistent and cannot be deleted by any way.

My device is a Galaxy A33 5G, with Android 13 and One UI 5.1.

**Comment by Cappuccino093** [comment]
Oh, I come from NordVPN, the notification is persistent that you are unable to delete it by any way

I think it should be convenient that MullvadVPN had the same behaviour, or an option to make the notification undeletable like Microsoft ToDo lets you turn on or turn off the notification persistent
