### ISSUE TITLE
Mullvad VPN located in Sweden #Privacylaws

### ISSUE THREAD

**Issue by Abyssgrowth** [mullvad/mullvadvpn-app#4550]
Mullvad is located in sweden which is (or atleast was) an active member of the 14-eyes-surveillance-network.
I've already read mullvad's official statement to that.
https://mullvad.net/it/blog/2019/10/18/5-9-or-14-eyes-your-vpn-actually-safe/
https://mullvad.net/en/help/swedish-legislation/
Ultimately i want to ask for a comparison of swedens and switzerlands privacy laws, i'm asking for the major pros and cons of each country in terms of online privacy (browsing the web / using a vpn).

**Comment by pinkisemils** [comment]
This is not related to our client software. Instead of opening a GitHub issue, you may email our support team (support@mullvad.net).
