### ISSUE TITLE
Norwegian typos

### ISSUE THREAD

**Issue by okpersonvern** [mullvad/mullvadvpn-app#4552]
## Issue report

Operating system: Ubuntu 22.04

App version: 2023.3

### Issue description

I noticed two typos in the Norwegian translation.

In the Lockdown warning popup "Innstillingen bil" should be "Innstillingen **vil**".
![Screenshot_20230413_110537](https://user-images.githubusercontent.com/99329251/231712404-2bb26392-0f00-4477-8ee0-74eace90b6f7.png)

In the Lockdown info popup, "Låsmodus" should be "Lås**e**modus".
![Screenshot_20230413_110821](https://user-images.githubusercontent.com/99329251/231712898-b37a0960-f6d3-4d58-90c4-5608ecb8edab.png)

**Comment by raksooo** [comment]
Thanks for reporting! I've notified our translators and it will be fixed in the next version.
