### ISSUE TITLE
Fdroid's version hasn't updated over 5 months.

### ISSUE THREAD

**Issue by Ud4ba** [mullvad/mullvadvpn-app#4555]
Fdroid version seem outdated. Is this known ?

**Comment by MrChocolatine** [comment]
- Latest version available on FDroid `2022.3`:
  https://f-droid.org/en/packages/net.mullvad.mullvadvpn/

- Latest version available here on the official repo `2022.3`:
  https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2022.3

The versions match, FDroid shows the correct version.

Look at the [current PRs](https://github.com/mullvad/mullvadvpn-app/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3AAndroid) and the [merged PRs](https://github.com/mullvad/mullvadvpn-app/pulls?q=is%3Apr+sort%3Aupdated-desc+label%3AAndroid+is%3Aclosed) for Android for what should eventually land in the next version(s).

_PS: I am not part of Mullvad VPN._

**Comment by faern** [comment]
`2022.3` is currently our latest Android app release indeed.
