### ISSUE TITLE
[Feature Request] Dedicated IP address

### ISSUE THREAD

**Issue by fabriziobagala** [mullvad/mullvadvpn-app#4556]
## Issue report

Operating system: macOS 13.3.1
App version: 2023.3

### Issue description

For each individual account, it would be nice to be able to associate a dedicated IP address.

**Comment by faern** [comment]
Hi,

This is not app-related, but rather about our entire service. Such inquiries are best sent to support@mullvad.net.

But we will likely not provide that service. A large point of a VPN service is to put many users behind a single IP, to make it harder to see who does what. A dedicated IP would go completely against that. We do not want to store any information that can tie user traffic to a person. If we had a dedicated IP per account, we would need to store that mapping. If someone asks us "who had IP `x` at point `y` in time, we could technically see which account it was associated with. And if that account was very recently paid for with a non-anonymous we could theoretically derive approximately who is behind that account. Which is not good.

We don't want to store anything anywhere that could tie an account to actual network traffic.
