### ISSUE TITLE
[Feature Request] Split tunnel via networks

### ISSUE THREAD

**Issue by imjuzcy** [mullvad/mullvadvpn-app#4557]
## Issue report

Operating system: Fedora 37

App version: 2023.3

### Issue description

Currently, the split tunnel feature works by excluding programs. 

So if I want to access `1.2.3.4/16` on my browser without going through VPN, I would need to exclude a whole browser. However, with #3921, I can't have the same browser open with another window that I want to go through the VPN. So I have to install a separate browser and exclude that.

In an old split tunnel feature request #781, the second comment describes exactly what this feature request means, but at the end application-based split tunnelling is implemented instead of network-based.

I tried adding additional route manually with `ip route add 1.2.3.4/16 via 192.168.1.1`, but it doesn't work, although the route is added and visible in `ip route`.

**Comment by faern** [comment]
> I tried adding additional route manually with ip route add 1.2.3.4/16 via 192.168.1.1, but it doesn't work, although the route is added and visible in ip route.

That's because our firewall rules block all traffic to the internet not going through the tunnel or not originating from an excluded application. But we have a guide for how to exclude by IP over here: https://mullvad.net/en/help/split-tunneling-with-linux-advanced/#excluding

**Comment by imjuzcy** [comment]
Thanks for that guide. 

One thing I noticed from the guide:

> both IPv4 and IPv6 addresses can be used here

implies that one can just replace the IPv4 given in the example with a IPv6, but it'll not work. Instead, `ip` has to be changed to `ip6` for IPv6 addresses/subnets, e.g.:

```
table inet excludeTraffic {
  chain excludeOutgoing {
    type route hook output priority 0; policy accept;
    ip6 daddr 2a00:1234::/24 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
  }
}
```

That also applies for example given further below, for example for "Named IP sets", IPv6 addresses/subnets have to be defined in a separate block and applied with another line in the rule chain. 

So instread of:
```
define EXCLUDED_IPS = {
    173.239.79.196,
    173.239.79.197,
    17.0.0.0/8,
    2a00:1234::/24
}

table inet excludeTraffic {
  chain excludeOutgoing {
    type route hook output priority 0; policy accept;
    ip daddr $EXCLUDED_IPS ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
  }
}
```
it should be:
```
define EXCLUDED_IPV4S = {
    173.239.79.196,
    173.239.79.197,
    17.0.0.0/8
}

define EXCLUDED_IPV6S = {
    2a00:1234::/24
}

table inet excludeTraffic {
  chain excludeOutgoing {
    type route hook output priority 0; policy accept;
    ip daddr $EXCLUDED_IPV4S ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
    ip6 daddr $EXCLUDED_IPV6S ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
  }
}
```
