### ISSUE TITLE
Fix menu bar app causing unwanted macOS "space" switching

### ISSUE THREAD

**Issue by Phaoast** [mullvad/mullvadvpn-app#4567]
## Issue report

Operating system: macOS Ventura

App version: 2023.3

### Issue description

When interacting with the Mullvad menu bar icon, the current macOS "space" unexpectedly switches to a different one before the menu bar app opens. The expected behavior is for the menu bar app to consistently open in the same space where the icon was clicked, without switching spaces. This issue seems to be specific to the Mullvad menu bar app, as other apps like OneDrive do not exhibit this behavior. Perhaps the issue is related to #4416.

Expected behavior: The menu bar app should open in the current space without any space switching occurring.

Actual behavior: The current space switches to another one, and then the menu bar app opens.

**Comment by raksooo** [comment]
Thank you for reporting this issue. It was fixed recently and will be included in the next release of the app. See this pull request for more info https://github.com/mullvad/mullvadvpn-app/pull/4416.
