### ISSUE TITLE
[Feature request] Mesh VPN feature 

### ISSUE THREAD

**Issue by Victor239** [mullvad/mullvadvpn-app#4570]
If you have multiple devices always connected to Mullvad VPN it limits the usage of software which would otherwise be able to connect via LAN (e.g. Syncthing, KDE Connect, etc).

Having meshnet capabilities would allow devices connected to Mullvad to better communicate with each other instead of being forced to network via WAN, and for LAN-only software it would enable their usage.

Competitor software with mesh VPNs: Tailscale, NordVPN, Tinc, Yggdrasil, Zerotier

**Comment by faern** [comment]
Most of the "competitors" you list are not privacy focused technology in the same sense as we are. What you suggest would open up a huge security and privacy hole. If all devices on one Mullvad account could talk to each other that means anyone who get a hold of your account number now has a direct network connection to all your connected devices. This would be incredibly bad for your security, and could potentially deanonymize you.

We of course expect our users to keep their account numbers secret. But we at the same time have the service design policy that even if you obtain someone else's account number, there should not be anything you can do with it that puts the account holder at risk. That's one of the reasons why you can't even see your past payments when you log in to your account.

This type of feature request is not really an app request, but rather something for the bigger service. So it should be requested from support@mullvad.net and not here. But I can already tell you that this will not happen.

We are not a "create a virtual network for your devices"-style VPN. We are a "create a secure tunnel to the internet"-style VPN ;)

**Comment by colvdv** [comment]
I too would value such a feature. It is literally the only thing stopping me from switching from NordVPN to Mullvad, because I use Meshnet as remote LAN.

If anyone does decide to look into such a feature implement, this may be useful: https://github.com/NordSecurity/libtelio
