### ISSUE TITLE
No relay server matches the current settings

### ISSUE THREAD

**Issue by bugreportmullvad** [mullvad/mullvadvpn-app#4637]
## Issue report
Android 10

App version: 2021.1 (google app store does not let me upgrade)

### Issue description

The list of servers on the android app is changing from time to time.

- when a user of mullvad app on android selects a server, the setting is
saved for next time. next time the app is launched, the same server is used.

- this feature is working well most of the time on my phone

- but sometimes, the android app RECEIVES A DIFFERENT WHOLE LIST OF
SERVERS. It seems to be like there are 2 lists. an old one and a new
one. When the android app receives a different list (for unknown
reason), then the pre-selected server that has been saved in the
settings, becomes invalid (it does not belong in the new list that has just
been received). So the app logic is, in this case, to display an error
message that says : "No relay server matches the current settings". The
error message is pretty clear and describes well what is happening. I
then go to the list of servers to select another server, and it works.

- then the app behaves well and i can start and stop mullvad, relaunch
it and it can work like that for few days or a week, or even more. the
setting is well saved. and the list of available servers does not change
for a while, so all is good.

- but then, out of the blue, one day, the android mullvad app receives
yet another list of servers (it downloads it... i guess) and again, my
currently selected server does NOT BELONG TO THE FRESHLY RETRIEVED LIST.
so the same error is displayed, and I have to reselect the server.

- what I am telling you is that the lists of server that are getting
retrieved by the app, ARE APPARENTLY TWO. there is an older list, and a
newer list.

The older list seems to have, for Amsterdam, this set of servers: nl1
nl2 nl20 nl21 nl22 nl23 nl3 nl4 nl5

The newer list seems to have instead: nl-ams-wg-001 nl-ams-wg-002
nl-ams-wg-003 nl-ams-wg-004 nl-ams-wg-005 nl-ams-wg-006 nl-ams-wg-101
nl-ams-wg-102 nl-ams-wg-103 nl-ams-wg-104 nl-ams-wg-201 nl-ams-wg-202
nl-ams-wg-203

- AND THOSE 2 LISTS ARE ALTERNATING ! one time i get the old one, the
next time (can be few days apart) i get the new one. and then the old
one again, and then the new one again, and then the old one etc.... (the alternation already happened 4 times)

- I am not downloading the list of servers manually. the android app
does it internally. I want to understand
the reason why the list that is obtained by the app, **is not always the
same, but instead, is alternating between an old list and a new list**,
and this issue is repeating itself every few days apart. It seems like there are some cache servers in your infrastructure for the API calls, and that some servers do not have the same list of relays than others.

**Comment by bugreportmullvad** [comment]
i managed to install manually with the APK to version 2022.3. will let you know if the issue persists.

**Comment by albin-mullvad** [comment]
Thanks for reporting. Hopefully this is resolved by using `2022.3` :+1:
