### ISSUE TITLE
Session Hijack 

### ISSUE THREAD

**Issue by Tropical-Smootie** [mullvad/mullvadvpn-app#4639]
## Issue report

Operating system: macOS ventura 13.3.1

App Version: 2023.3

### Issue description

So I Set up my vpn location to Amsterdam, I was was casually browsing the web and about 30  minutes after I decide to check my public ip online and it return Abu Dhabi, United Arab Emirates. I check the  Mullvad App again and it says Amsterdam.
I then reloaded the checkmyip webpage and it still says Abu Dhabi.

I soon reset my VPN Location to some other city and reloaded the webpage and everything was normal.

Was this a Highjack?

anyone else experienced this?

**Comment by paperclip-dayo** [comment]
The website that you used to check your IP address has outdated geoip databases, nothing to worry about here.
Some websites showing a different location than the server you're connected to is normal with VPNs.

**Comment by faern** [comment]
GeoIP databases change constantly as IPs are re-assigned etc. I would recommend you check your connectivity with https://mullvad.net/check. Our own check page should always be up to date with our own IPs and in what cities they are located. It does not hurt to use third party services to verify what your exit *IP* is, but don't trust their city/country information too much.

I'm closing this as I don't think there is anything to work on here really.
