### ISSUE TITLE
[Bug] The Mac application stops opening when you click the icon in the menu bar

### ISSUE THREAD

**Issue by dizelgerda** [mullvad/mullvadvpn-app#4651]
## Issue report

Operating system: macOS 13.3.1 

App version: 2023.3

### Issue description

The bug is back again. Past issue:
https://github.com/mullvad/mullvadvpn-app/issues/4453

**Comment by raksooo** [comment]
The bug was fixed after 2023.3 was released and will be included in 2023.4. We're preparing to release a first beta very soon.

**Comment by dizelgerda** [comment]
Okay, I'm sorry to bother you in that case.

**Comment by raksooo** [comment]
We've now released the beta! You can download it here: https://mullvad.net/en/download/vpn/macos#beta

Please write in #4453 again if you still experience this problem in `2023.4-beta1` and I'll reopen that issue.

**Comment by BEaXt7f97** [comment]
> We've now released the beta! You can download it here: https://mullvad.net/en/download/vpn/macos#beta
> 
> Please write in #4453 again if you still experience this problem in `2023.4-beta1` and I'll reopen that issue.

I am now experiencing this issue, Macbook Pro M3 Pro 16" version 2023.6, fully updated.

I force quit Mullvad, then re-open and for about 30-seconds I can use it in the Menu Bar, then once I click it and move my mouse just 1 pixel, it hides, and makes Mullvad UI unusable.
