### ISSUE TITLE
[Feature request] Add name of the current interface to `mullvad status`

### ISSUE THREAD

**Issue by seguri** [mullvad/mullvadvpn-app#4676]
## Issue report

Operating system: macOS 13.3.1

App version: 2023.3

### Issue description

Please add the name of the current tunneling interface to the output of `mullvad status -v`, e.g. `utun4`.

**Comment by faern** [comment]
This is a pretty neat feature suggestion. Especially on macOS where the tunnel name changes a lot. I'll add it as a suggestion in the backlog

**Comment by MarkusPettersson98** [comment]
This feature was merged in #4726.

Thanks @seguri for the suggestion! :blush:
