### ISSUE TITLE
Management interface error on 2023.3 (Debian 11)

### ISSUE THREAD

**Issue by yslupdates** [mullvad/mullvadvpn-app#4715]
## Issue report

Operating system: Debian 11.7 via Proxmox LXC on Intel 8500T

App version: mullvad 2023.3

### Issue description

Hi I've encountered this issue on 2023.3 for debian 11 (this is a LXC within proxmox)

Installed using these instructions https://mullvad.net/en/help/install-mullvad-app-linux/

```
root@mullvadvpn:~# mullvad status
Error: Management interface error
Caused by: Management RPC server or client error
Caused by: transport error
Caused by: error trying to connect: No such file or directory (os error 2)
Caused by: No such file or directory (os error 2)
root@mullvadvpn:~# mullvad version
Error: Management interface error
Caused by: Management RPC server or client error
Caused by: transport error
Caused by: error trying to connect: No such file or directory (os error 2)
Caused by: No such file or directory (os error 2)
```

I can't proceed further such as logging in because most commands give me this message. I can execute "mullvad" to see all the list of commands no problem

For now I am working to use wireguard as an alternative but I'd like to use this mullvad cli

Edit:
I tried it again and when I was installing the mullvad deb file at the very last line I got this

`N: Download is performed unsandboxed as root as file '/root/MullvadVPN-2023.3_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)`

Would this affect my troubles? Mullvad still launches but still gets errors as above

**Comment by faern** [comment]
The `mullvad-daemon` system service is probably not running. So we have to figure out why. Check the status of the service with `systemctl status mullvad-daemon.service` and paste the output here please. You can also try manually starting it with `sudo systemctl start mullvad-daemon.service`.

Please note that we do not support running in an LXC and it's not something we have tried ourselves. It could be that it fails due to our interaction with cgroups or something.

**Comment by yslupdates** [comment]
> The `mullvad-daemon` system service is probably not running. So we have to figure out why. Check the status of the service with `systemctl status mullvad-daemon.service` and paste the output here please. You can also try manually starting it with `sudo systemctl start mullvad-daemon.service`.
> 
> Please note that we do not support running in an LXC and it's not something we have tried ourselves. It could be that it fails due to our interaction with cgroups or something.

```
root@debian:~# mullvad status
Error: Management interface error
Caused by: Management RPC server or client error
Caused by: transport error
Caused by: error trying to connect: Connection refused (os error 111)
Caused by: Connection refused (os error 111)
root@debian:~# systemctl status mullvad-daemon.service
* mullvad-daemon.service - Mullvad VPN daemon
     Loaded: loaded (/lib/systemd/system/mullvad-daemon.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-05-22 13:15:38 PDT; 38s ago
    Process: 6715 ExecStart=/usr/bin/mullvad-daemon -v --disable-stdout-timestamps (code=exited, status=1/FAILURE)
   Main PID: 6715 (code=exited, status=1/FAILURE)
        CPU: 15ms

May 22 13:15:37 debian systemd[1]: mullvad-daemon.service: Main process exited, code=exited, status=1/FAILURE
May 22 13:15:37 debian systemd[1]: mullvad-daemon.service: Failed with result 'exit-code'.
May 22 13:15:38 debian systemd[1]: mullvad-daemon.service: Scheduled restart job, restart counter is at 6.
May 22 13:15:38 debian systemd[1]: Stopped Mullvad VPN daemon.
May 22 13:15:38 debian systemd[1]: mullvad-daemon.service: Start request repeated too quickly.
May 22 13:15:38 debian systemd[1]: mullvad-daemon.service: Failed with result 'exit-code'.
May 22 13:15:38 debian systemd[1]: Failed to start Mullvad VPN daemon.
```

Looks about right, still unfortunately not working.

Can I you a question on next steps for me?
So I was planning to use mullvad CLI on this debian LXC container. I will try ubuntu LXC next if that makes any difference (doubt it), and then consider running Mullvad directly onto Proxmox OS and feed the connection through to the other non-mullvad apps I use (that will be in LXCs). I am coming from docker-gluetun for using Mullvad but am switching off because of [bandwidth speed concerns](https://github.com/qdm12/gluetun/wiki/Bandwidth-speeds) of running Mullvad (via wireguard) thru a docker container.
Since LXC's don't seem to work, would I experience similar issues if I run mullvad within a debian VM (that's on proxmox)? I don't mind doing a baremetal install if that's the best for speeds, I just wanted to go the proxmox route to try it out.

**Comment by dlon** [comment]
Take a look at `/var/log/mullvad-vpn/daemon.log`. It might tell you why the service refuses to start.

> Since LXC's don't seem to work, would I experience similar issues if I run mullvad within a debian VM (that's on proxmox)?

You can run Mullvad in VMs without any issues. LXCs, maybe not.

> Is wireguard with a mullvad config file supported within an LXC?

I believe that's possible provided that the host kernel has the wireguard module loaded. It will most likely come with that module unless the kernel is several years old.

**Comment by yslupdates** [comment]
> Take a look at `/var/log/mullvad-vpn/daemon.log`. It might tell you why the service refuses to start.
> 
> > Since LXC's don't seem to work, would I experience similar issues if I run mullvad within a debian VM (that's on proxmox)?
> 
> You can run Mullvad in VMs without any issues. LXCs, maybe not.
> 
> > Is wireguard with a mullvad config file supported within an LXC?
> 
> I believe that's possible provided that the host kernel has the wireguard module loaded. It will most likely come with that module unless the kernel is several years old.

Thanks for the reply. I am giving up on Proxmox LXCs and just going to debian or ubuntu server. Thanks for all the help
