### ISSUE TITLE
Add México and Guatemala servers

### ISSUE THREAD

**Issue by Cappuccino093** [mullvad/mullvadvpn-app#4782]
It will be great if you add México and Guatemala servers for VPNs (Specially México)

**Comment by faern** [comment]
Do you mean localization (translate the app)? Or servers in those locations?

**Comment by Cappuccino093** [comment]
> Do you mean localization (translate the app)? Or servers in those locations?

Servers
I edited the request, thanks

**Comment by raksooo** [comment]
This repository and the issue tracker is for the app only. For infrastructure related questions/requests please contact support@mullvad.net.
