### ISSUE TITLE
Improper Mullvad Tray Icon

### ISSUE THREAD

**Issue by moore-bryan** [mullvad/mullvadvpn-app#4798]
Running Mullvad 2023.4-beta1 on my vanilla Fedora 38 install, using Wayland.

The app runs correctly, but the tray icon often shows improperly; that is, rather than the locked and unlocked padlock it will often just show a set of ellipses. This is an intermittent thing, though, as the padlock _sometimes_ shows correctly.
![image](https://github.com/mullvad/mullvadvpn-app/assets/8169342/296a2c1b-ef06-4269-b821-a52d388fafec)

**Comment by raksooo** [comment]
Which desktop environment do you use?

**Comment by raksooo** [comment]
The tray icon is handled by Electron and we've upgraded Electron in 2023.4-beta1 so that could be the cause.

If you're using GNOME. Did you have to install some tray icon gnome shell extension?

**Comment by moore-bryan** [comment]
Sorry, I meant to include this is on GNOME. I never installed a tray icon gnome-shell extension for Mullvad before. I'm just confused at to why it _sometimes_ works; that screams "bug" to me.

**Comment by leodag** [comment]
I'm also seeing this, since upgrading to 2023.4. I'm on GNOME 44.0, using [this extension](https://extensions.gnome.org/extension/615/appindicator-support/). It even stays as '...' after I disconnect, and after I reconnect.

**Comment by moore-bryan** [comment]
Hmm... Interestingly, toggling the "AppIndicator and KStatusNotifierItem Support" extension—which I _completely_ forgot I had installed—from "on" to "off" and back to "on" brings the correct padlock icon back.

**Comment by raksooo** [comment]
In 2017 GNOME stopped supporting tray icons (https://blogs.gnome.org/aday/2017/08/31/status-icons-and-gnome/). The solution since then has been to install gnome shell extensions to continue displaying tray icons. My experience is that they for some reason break quite often and gets fixed, and that some extension works at some point and others work at other times. Some that I know have worked in the past is `AppIndicator and KStatusNotifierItem Support`, `TopIconsFix` and `Tray Icons: Reloaded`. I'm not sure which ones work at the moment but I think you'll get more up to date information about this if you email support@mullvad.net.

**Comment by moore-bryan** [comment]
I think you're on to something and, perhaps, I should try one of the other extensions to show legacy tray icons; I'm currently using what's considered by most to be the gold standard—i.e., AppIndicator and KStatusNotifierItem Support—but maybe one of the other ones will work better.

I already reached out to Mullvad support and the only response was that it might be related to their use of an updated Electron. The odd behavior is that if I toggle the extension from "on" to "off" and back to "on," everything works as expected.

I've tried delaying the start of Mullvad and that did not work; I also can't seem to figure out how, if it's even possible, to delay the start of an extension.

I plan to try one of the other tray icon extensions for GNOME Shell and see if I get any consistent success...

**Comment by moore-bryan** [comment]
The other extensions _generally_ show the padlock correctly, but for several aesthetic reasons they don't cut it for me and it is not consistent enough. At the same time, I've become convinced this is more an issue with the extension(s) for showing tray icons in GNOME 44 than Mullvad itself.
