### ISSUE TITLE
[Feature] DNS Blocking List for Focus

### ISSUE THREAD

**Issue by Overload3910** [mullvad/mullvadvpn-app#4819]
## Feature Request
Operating system: all platforms

Hello there, 
would it be possible to add additional DNS Filter lists for Social Media Sites and Movie Streaming/Online Shopping Platforms? Maybe under the umbrella of a 'Focus' list?

I am confident that anyone who is easily distracted, like me, would very much appreciate a setting like that. 

## Pros
- improved focus for people who are easily distracted 
- no security risk compared to site blocking extensions 

![SCR-20230622-klv](https://github.com/mullvad/mullvadvpn-app/assets/135011493/df616e21-e2d6-4d9f-a3cb-bfffdee23a7d)

Thank you! You guys rock!

**Comment by MarkusPettersson98** [comment]
Hello! We added a social media block list in the 2023.6 release, have you tried it yet? :blush:

We have not looked into a Movie Streaming/Online Shopping Platforms blocklist, but if that is still requested I will keep this issue open for the time being. Please let me know what you think :blush:

**Comment by Overload3910** [comment]
Yes thanks! 

A shopping filter would also be something great.

**Comment by MarkusPettersson98** [comment]
Feel free to open an issue with a feature suggestion for adding a shopping DNS block list if you feel like it :blush:
