### ISSUE TITLE
I saw a question about this VPN in the Steam discussion area of the game TABG

### ISSUE THREAD

**Issue by MZZZ-T** [mullvad/mullvadvpn-app#4824]
Through translation software conversion, there may be Syntax error

![G2U4TU](https://github.com/mullvad/mullvadvpn-app/assets/102852424/6722a98a-5530-414d-980d-7dfb6aa49e39)

https://steamcommunity.com/app/823130/discussions/0/3803901365999054677/

I want to know why "he claims to have some sort of botnet run through the VPN "Mullvad" that is running accounts in each game that will then crash the game."

The game's servers have been being DDOSed by a hacker during this time, I wonder if this might have something to do with this project

**Comment by faern** [comment]
All Mullvad does is change the public facing IP of its users. This question is not directly related to the Mullvad VPN app this repository is about. For non-app related questions about our service I suggest you contact support@mullvad.net.
