### ISSUE TITLE
machine readable list of locations

### ISSUE THREAD

**Issue by 4cq2** [mullvad/mullvadvpn-app#4862]
all I want is a machine readable list of Mullvad locations. I checked here:

https://mullvad.net/servers

but its all HTML. also I found this:

https://github.com/mullvad/mullvadvpn-app/blob/main/gui/locales/relay-locations.pot

but it seems that is not what I am looking for, as it lists India, but Mullvad does not currently offer an India location.

**Comment by 4cq2** [comment]
found it:

<https://mullvad.net/en/servers/__data.json>

**Comment by 4cq2** [comment]
I found this:

<https://mullvad.net/en/servers/__data.json>

but it seems the data is randomly arranged:

~~~
{
   "active": 8,
   "city_code": 5,
   "city_name": 6,
   "country_code": 3,
   "country_name": 4,
   "fqdn": 7,
   "hostname": 2,
   "ipv4_addr_in": 11,
   "ipv6_addr_in": 12,
   "network_port_speed": 13,
   "owned": 9,
   "provider": 10,
   "status_messages": 15,
   "stboot": 8,
   "type": 14
},
"al-tia-ovpn-001",
"al",
"Albania",
"tia",
"Tirana",
"al-tia-ovpn-001.relays.mullvad.net",
true,
false,
"iRegister",
"31.171.154.50",
"2a04:27c0:0:4::a01f",
1,
"openvpn",
~~~

**Comment by 4cq2** [comment]
I found this:

<https://mullvad.net/en/servers/__data.json>

but it seems the data is randomly arranged:

~~~
{
   "active": 8,
   "city_code": 5,
   "city_name": 6,
   "country_code": 3,
   "country_name": 4,
   "fqdn": 7,
   "hostname": 2,
   "ipv4_addr_in": 11,
   "ipv6_addr_in": 12,
   "network_port_speed": 13,
   "owned": 9,
   "provider": 10,
   "status_messages": 15,
   "stboot": 8,
   "type": 14
},
"al-tia-ovpn-001",
"al",
"Albania",
"tia",
"Tirana",
"al-tia-ovpn-001.relays.mullvad.net",
true,
false,
"iRegister",
"31.171.154.50",
"2a04:27c0:0:4::a01f",
1,
"openvpn",
~~~

I figured out a way to split the data into servers, but server entries seem to have no reason about how they are arranged, so I cant seem to filter on the ones that actually include a location name. I also tried checking the Android app, but its using certificate pinning so I cant actually inspect any of the requests. Here is some Go code if it helps anyone:

~~~go
package mullvad

import (
   "encoding/json"
   "io"
)

type server []any

func servers(r io.Reader) ([]server, error) {
   var data struct {
      Data []any
   }
   err := json.NewDecoder(r).Decode(&data)
   if err != nil {
      return nil, err
   }
   var servs []server
   indexes := data.Data[0].([]any)
   for i, low := range indexes {
      low := int(low.(float64))
      high := len(data.Data)-1
      if i+1 < len(indexes) {
         high = int(indexes[i+1].(float64))
      }
      servs = append(servs, data.Data[low:high])
   }
   return servs, nil
}
~~~

**Comment by 4cq2** [comment]
found it:

https://github.com/mullvad/mullvadvpn-app/blob/478d361051081471f27cfdffcc4576628442cb4a/ios/relays-prebuild.sh#L21

**Comment by faern** [comment]
I highly recommend you use our public API instead of our app's API. The app's API can be changed at any point to accommodate what the app needs. The public API is intended for third party consumption.

https://api.mullvad.net/public/documentation/
