### ISSUE TITLE
someone is spoofing mullvad.net

### ISSUE THREAD

**Issue by tillydray** [mullvad/mullvadvpn-app#4868]
## Issue report

Operating system: n/a

App version: n/a

### Issue description

Look at https://mullvadd.com/. Looks to me like a clear spoof.

**Comment by runboy93** [comment]
https://www.virustotal.com/gui/url/db18365dd916a90aeaf974867e511ef1e3696cb7bdac93950844f475fdf22775/summary

**Comment by faern** [comment]
This is not app related, nor is there much we can do about people buying similar domains and hosting bad stuff. But I'll forward this information to our support.
