### ISSUE TITLE
Update to 2023.4 in Debian 10 does not work

### ISSUE THREAD

**Issue by howardlesshippin** [mullvad/mullvadvpn-app#4895]
## Issue report

Operating system: 

App version:

**Comment by howardlesshippin** [comment]
The app is not working for me after the upgrade to 23.4 on MX Linux 19 (Debian 10).  The installation page https://mullvad.net/en/download/vpn/linux says that it is for Debian 10+ but the release page says that support for Debian 10 is "deprecated".  I have not been able to find the earlier version on Github or the Mullvad website.

**Comment by faern** [comment]
Hi! Yeah `2023.4` does drop support for Debian 10. The app needs a newer kernel now. This Github repository does specify that, but we have forgotten to update our download page. I'll ping the web team.

You can find the last working release at https://github.com/mullvad/mullvadvpn-app/releases/tag/2023.3
