### ISSUE TITLE
[Bug] The app's remaining days counter fails to update unless the app is closed from the App Switcher and reopened

### ISSUE THREAD

**Issue by MahdiNazemi** [mullvad/mullvadvpn-app#4909]
## Issue report

Operating system: iOS 16.5.1 (c)

App version: 2023.3

### Issue description

The app's remaining days counter fails to update unless the app is closed from the App Switcher and reopened. For example, mine was stuck at 35 days for a few days. After closing and reopening the app, the number was updated to 31.

**Comment by pinkisemils** [comment]
Thank you for reporting this, we'll see what we can do about this :slightly_smiling_face:

**Comment by buggmagnet** [comment]
This shouldn't be an issue anymore, but please feel free to reopen this ticket if you experience this problem again.
