### ISSUE TITLE
How can I use mullvad split tunneling source code for Windows but for PPTP protocol not Wireguard and OpenVPN ?

### ISSUE THREAD

**Issue by alom4hdi** [mullvad/mullvadvpn-app#4920]
I just wanna know where is the source code of handling applications split tunneling in windows ?

**Comment by faern** [comment]
The kernel driver we wrote to handle split tunneling lives in https://github.com/mullvad/win-split-tunnel. And the integration of that driver into our app lives mostly in this Rust module: https://github.com/mullvad/mullvadvpn-app/tree/main/talpid-core/src/split_tunnel/windows
