### ISSUE TITLE
Ubuntu 23.04 - Graphics Corruption in 2023.5-beta1

### ISSUE THREAD

**Issue by tommodev** [mullvad/mullvadvpn-app#4952]
## Issue report

Howdy, sorry couldn't get to the report issue button due to graphics bork but captured a log.

### Operating system

Neofetch Dump -

```
OS: Ubuntu 23.04 x86_64
Kernel: 6.2.0-26-generic
Resolution: 3840x2160
DE: GNOME 44.3
WM: Mutter
WM Theme: Adwaita
Theme: Yaru-red [GTK2/3]
Icons: Yaru-red [GTK2/3]
CPU: AMD Ryzen 5 2600 (12) @ 3.400GHz
GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X/590
Memory: 5993MiB / 31993MiB
```

### App version

2023.5-beta1 installed via Deb, sourced from GH

### Issue description

Mullvad Desktop is in tray, connection OK, but on opening Gui from systray all graphics within the window (excluding system border) were corrupted. Apologies didn't get screenshot.

Logfile from CLI launch of '/opt/Mullvad VPN/mullvad-gui' attached to issue.
[mullvad-exec-log.txt](https://github.com/mullvad/mullvadvpn-app/files/12239397/mullvad-exec-log.txt)

Log seems pretty upset about shader compilation:

```
...
[13829:0802/185437.071501:ERROR:shared_context_state.cc(81)] Skia shader compilation error
------------------------
// Vertex SKSL
#extension GL_NV_shader_noperspective_interpolation: require
...
Errors:
link failed but did not provide an info log
[13829:0802/185437.075354:ERROR:shared_context_state.cc(81)] Skia shader compilation error
...
```

**Comment by tommodev** [comment]
Can repo. 2 screenshots attached. Downgrading to 2023.4 and visuals are OK, upgrading to 2023.5-beta1 introduces the corruption again.

Otherwise app is "ok" and mullvad connects to server as expected.

![Screenshot from 2023-08-03 07-23-59](https://github.com/mullvad/mullvadvpn-app/assets/79486309/d08fe7c1-1172-4142-827e-16d021299af2)

![Screenshot from 2023-08-03 07-24-54](https://github.com/mullvad/mullvadvpn-app/assets/79486309/6ad88a7a-ed6f-4cca-a96d-b161157cb0b2)

**Comment by tommodev** [comment]
In case it's relevant, running using Ubuntu's default of Wayland, not X11.

**Comment by faern** [comment]
Thank you for finding a workaround. That can surely be very helpful when we dig into this issue.

**Comment by raksooo** [comment]
We've added automatic removal of the GPU cache dir on upgrade so this should be fixed when it's released.
