### ISSUE TITLE
[Feature request] Fully packaged Linux release

### ISSUE THREAD

**Issue by hanniabu** [mullvad/mullvadvpn-app#4960]
## Issue report

Operating system: Ubuntu v22.04

App version: n/a

### Issue description

When installing the Mullvad app on Ubuntu it requires you to connect to the internet in order to install the dependencies. I would like to formally request a fully packed release so the computer doesn't need to be exposed online without VPN. This would also mitigate the same issue with upgrades where you need to connect to the internet without VPN in order to install the dependencies for the update.

**Comment by faern** [comment]
Is accessing the ubuntu repositories a problem for you? Or can you describe the problem you are trying to mitigate more exactly please. Whats the attack vector you are afraid of?

**Comment by hanniabu** [comment]
> Is accessing the ubuntu repositories a problem for you?

Not quite sure what you mean by this

> can you describe the problem you are trying to mitigate

I am trying to avoid connecting to the internet without VPN, but that is not possible with Mullvad at the moment since once you download the .deb file you need to be connected to the internet to install the dependencies before you can run it and use the VPN. If there was a fully packaged version then you could copy over the app via USB, install it, and run it without needing to connect to the internet without VPN.

**Comment by Zylquinal** [comment]
> I am trying to avoid connecting to the internet without VPN, but that is not possible with Mullvad at the moment since once you download the .deb file you need to be connected to the internet to install the dependencies before you can run it and use the VPN.

Use `sudo apt install --no-install-recommends MULLVAD_VPN_DEB_FILE`

You probably encounter the `libappindicator3-1` dependency, and installing without using `--no-install-recommends` would trigger the dependency installation.

**Comment by faern** [comment]
Yes, we indeed have an optional dependency. It did not install by default for me so I did not mention it. If it does for you, the command above can avoid it.

This should solve the original issue and I will close this ticket. On Fedora we do actually have hard dependencies, but that's not what OP is asking about. And most users already have those installed from the beginning anyway.

**Comment by hanniabu** [comment]
Thank you @Zylquinal this addresses my issue
