### ISSUE TITLE
Use Mullvad IP(s) as HTTP Proxy(ies)

### ISSUE THREAD

**Issue by beavue** [mullvad/mullvadvpn-app#4962]
## Issue report

Operating system: Debian 11
App version: 2023.4

### Issue description

Well, I have no issue I was just wondering if it was possible to use Mullvad IPs as HTTP Proxy instead of using socks5 one. 

My friend had done what I am saying now a while ago but I don't know how and he's gone so I can't ask him anyway.

I just want to be able to rotate between all (600+) mullvad servers for scraping purposes.

**Comment by faern** [comment]
This sounds like a question not directly about the app. I suggest you contact support@mullvad.net instead. This repository is about our VPN application, not our infrastructure/service.
