### ISSUE TITLE
States "Connected" despite not being connected to VPN on macOS Sonoma Beta 6

### ISSUE THREAD

**Issue by asharahmed** [mullvad/mullvadvpn-app#5051]
## Issue report

Operating system: macOS 14.0 Sonoma Beta 7

App version: 2023.5-beta1 

### Issue description

Following the release of macOS Sonoma beta 6, the Mullvad VPN app, both stable and beta versions have stopped working, at least on 2 macOS machines running macOS Sonoma beta 6. Setting the configuration of the Mullvad VPN app to use OpenVPN only and enabling the SOCKS5 proxy also does not help. 

My guess is they changed a portion of the networking API?

**Comment by raksooo** [comment]
Thanks for reporting this! We're investigating the issue.

**Comment by magikxx** [comment]
the same here

**Comment by MahdiNazemi** [comment]
I occasionally encounter the same problem on Ventura with a Mullvad version which I have compiled from the source.

**Comment by axiel7** [comment]
FYI the WireGuard app works fine on ventura, you can export the config files on your account settings

**Comment by raksooo** [comment]
Apple has fixed this issue in the second release candidate of macOS 14 (Build 23A344). Let us know if you still have any problems.

**Comment by KTamas** [comment]
@raksooo 2023.05-beta2 same issue on 23A344 unless I turn on local network sharing

**Comment by DavydeVries** [comment]
@raksooo after updating to macOS 14 (Build 23A344) the problem got even worse.
