### ISSUE TITLE
Desktop: permanent split-tunneling like on Android?

### ISSUE THREAD

**Issue by firefoxlover** [mullvad/mullvadvpn-app#5065]
Some examples may be kde connect or other services, where you want to use your local network.

Is there some problem with Linux, that this only works on Android? Some UUID randomization or something?

Because I can always find running apps through their name and get the PID like that.

This would be really great to have!

**Comment by firefoxlover** [comment]
dupe of https://github.com/mullvad/mullvadvpn-app/issues/3044

Is this issue still unfixable?

**Comment by faern** [comment]
Hi. My comment from the issue you linked to is still the best answer to this. https://github.com/mullvad/mullvadvpn-app/issues/3044#issuecomment-947562333

Yes, it's still unfixable in the sense you probably want it to work. You still need to launch a program into a specific cgroup. However, the recommendation to create dedicated `.desktop` files that prepend `mullvad-exclude` to the actual program is still the best way to achieve this. Then, whenever you launch your program via launchers and start menus it will be excluded.
