### ISSUE TITLE
Split tunneling: show all desktop entries

### ISSUE THREAD

**Issue by firefoxlover** [mullvad/mullvadvpn-app#5066]
I have some custom Launchers in the `~/.local/share/applications` dir for for example Firefox binary, Mercury, and other binaries or Appimages.

Currently mullvad-vpn doesnt list these in the GUI app, its a bit weird. This restricts the amount of apps supported.

Flatpaks and system apps work normally.

Fedora 38 KDE (Kinoite)
latest MullvadVPN rpm

**Comment by faern** [comment]
Thanks for reporting this. I agree that this sounds like a bug. We should list user programs.

**Comment by raksooo** [comment]
Thanks for reporting. Those should be included as long as `$HOME` is set for the app. Desktop entries will be filtered out if they don't fulfill the following requirements:
- `type` needs to be `Application`
- `exec` needs to be set
- `noDisplay`, `terminal` and `hidden` can't be `true`
- If they have `notShowIn` or `onlyShowIn` set the current desktop environment need to match what is specified.

**Comment by firefoxlover** [comment]
Thank you! It seems the type was missing, they are showing normally
