### ISSUE TITLE
upgrade test version to stable version

### ISSUE THREAD

**Issue by mohammadRezaeian** [mullvad/mullvadvpn-app#5117]
## Issue report

Operating system: android 12
App version: 2023.6-beta1

### Issue description
Is it possible upgrade test version to Stable version alternative first remove it and installing stable version?

**Comment by albin-mullvad** [comment]
Hi! Can you please elaborate? Upgrading from `2023.6-beta1` to `2023.6` will be possible when `2023.6` has been released if that answers your question.
