### ISSUE TITLE
No tray icon in XFCE 2023.4

### ISSUE THREAD

**Issue by dentaku65** [mullvad/mullvadvpn-app#5139]
Hello,

upgrading from 2023.3 to 2023.4 the tray icon in Xubuntu 22.04 LTS is disappear; here some differences from the previous version taken from indicator log

**2023.3**
```
 $ cat $HOME/.cache/xfce4-indicator-plugin.log
DEBUG      libindicator-plugin       Looking at Module: libayatana-application.so
DEBUG      libindicator-plugin       Loading Module: libayatana-application.so
DEBUG      libindicator-plugin       Load indicator: libayatana-application.so
WARNING    libindicator-plugin       Error opening directory “/usr/share/ayatana/indicators”: No such file or directory
DEBUG      Ayatana-Indicator-Application Connected to Application Indicator Service.
DEBUG      Ayatana-Indicator-Application Request current apps
DEBUG      Ayatana-Indicator-Application Building new application entry: :1.258  with icon: nm-signal-75 at position 0
DEBUG      libindicator-plugin       Entry added for io=libayatana-application.so
DEBUG      Ayatana-Indicator-Application Building new application entry: :1.268  with icon: Mullvad VPN1_2 at position 0
DEBUG      Ayatana-Indicator-Application 	Appending search path: /tmp/.org.chromium.Chromium.0VDSew
DEBUG      libindicator-plugin       Entry added for io=libayatana-application.so
DEBUG      Ayatana-Indicator-Application Building new application entry: :1.276  with icon: blueman-tray at position 0
DEBUG      libindicator-plugin       Entry added for io=libayatana-application.so
DEBUG      Ayatana-Indicator-Application 	Appending search path: /tmp/.org.chromium.Chromium.sdpPkL
```
Note the two entries **/tmp/.org.chromium.Chromium**; the first one is empty, the second one contains the the Mullvad icon displayed on tray indicator 

**2023.4**
```
$ cat $HOME/.cache/xfce4-indicator-plugin.log
DEBUG      libindicator-plugin       Looking at Module: libayatana-application.so
DEBUG      libindicator-plugin       Loading Module: libayatana-application.so
DEBUG      libindicator-plugin       Load indicator: libayatana-application.so
WARNING    libindicator-plugin       Error opening directory “/usr/share/ayatana/indicators”: No such file or directory
DEBUG      Ayatana-Indicator-Application Connected to Application Indicator Service.
DEBUG      Ayatana-Indicator-Application Request current apps
DEBUG      Ayatana-Indicator-Application Building new application entry: :1.340  with icon: nm-signal-75 at position 0
DEBUG      libindicator-plugin       Entry added for io=libayatana-application.so
DEBUG      Ayatana-Indicator-Application Building new application entry: :1.358  with icon: blueman-tray at position 0
DEBUG      libindicator-plugin       Entry added for io=libayatana-application.so
```
On 2023.4  the entries on **/tmp/.org.chromium.Chromium** exist only on one occurrence and it is empty and there is nothing in the log.

Open this even on [reddit](https://www.reddit.com/r/mullvadvpn/comments/16e0qgf/mullvad_20234_no_tray_icon/) 

Den

**Comment by raksooo** [comment]
It should be back in 2023.5-beta1. Please try it out and let us know if it works!

**Comment by dentaku65** [comment]
Hello,
seems fixed with a small workaround. Xfce4 has 3 applet to place tray icons:
```
Indicator Plugin
Status Tray Plugin
Status Notifier Plugin
```
The culprit of this behavior seems, in my case, the Indicator Plugin. Removing this plugin and adding Status Notifier Plugin the applet do not recognized the Mullvad application and the icon is not displayed in tray area; to display the icon you need to open the properties of the plugin and flag the check mark "Menu is primary action"; however in the same property panel under "Know Items"  appears not "Mullvad" but an item called "chrome_icon_status_1" which I suspect is Mullvad itself. Same scenario Status Tray Plugin ut, in tat case, Mullvad in namely in a correct fashion.

//Den

**Comment by dentaku65** [comment]
Ops,
in Mullvad  2023.5 the issue is come back on every tray icon solutions

```
Indicator Plugin
Status Tray Plugin
Status Notifier Plugin
```

**Comment by dentaku65** [comment]
Working on 2023.5 with Status Notifier Plugin 
It is necessary to disable/remove in  Session and Startup -> Application Autostart -> Ayatana Indicator Application in Xfce4 Settings

**Comment by MarkusPettersson98** [comment]
Hello @dentaku65 , good to hear that it is working for you! I will close this issue for now, but please let me know if you think it should be re-opened :blush:
