### ISSUE TITLE
Option Filter Ownership

### ISSUE THREAD

**Issue by mohammadRezaeian** [mullvad/mullvadvpn-app#5155]
## Issue report

Operating system: Android 12
App version: 2023.6-beta2

### Issue description

hi
Please add option Filter Ownership like Desktop version Mullvad
In Switch location

**Comment by albin-mullvad** [comment]
Thanks for the suggestion! We plan to add this, but it's unfortunately a bit down in our backlog.

**Comment by albin-mullvad** [comment]
Small update: we've started to implement this feature!
