### ISSUE TITLE
Mullvad disables Internet when disconnected

### ISSUE THREAD

**Issue by M4ttyFrank** [mullvad/mullvadvpn-app#5156]
## Issue report

Operating system:  Windows 10

App version: Windows 2023.4

### Issue description

Mullvad seems to kill my Internet randomly. If I disconnect Mullvad, I am unable to use my Internet at all and i have to restart every time my pc to have internet again.

After a number of minutes varying between 5 and 10 the windows internet icon switches on as if I had the cable and if I try to change mullvad network or disconnect, the mullvad padlock icon becomes yellow with a red dot in the middle and I no longer have access to Internet.
If I connect to Mullvad only for a few seconds and try to disconnect most of the time it doesn't give me problems and I can use my wifi network again, but if I stay for longer and try to disconnect then everything freezes.

Another error it gives me is that sometimes it randomly disconnects completely and either it gives me the yellow padlock with the red dot in the middle, or it no longer sees any internet connection and I have to restart the PC to solve the problem. It's quite frustrating.

**Comment by pinkisemils** [comment]
Have you sent a problem report?

Have you confirmed that you get no connectivity at all or if DNS is not working? You can verify that by trying to ping a host on the internet using only it's address, by executing the following in a console:
```bat
ping 1.1.1.1
```

**Comment by M4ttyFrank** [comment]
update: i have uninstall AVG antivirus and now i don't have the problem anymore.
