### ISSUE TITLE
2 factor authentication for security 

### ISSUE THREAD

**Issue by Embassy4016** [mullvad/mullvadvpn-app#5174]
## Issue report

Operating system: 

App version: 

### Issue description

I was sharing my account with my ex. But now that we slit up she keeps removing my registered devices and adding hers. It's a constant tug of war where my devices are removed by her, only for me to remove her devices and login to use mullvadvpn on my devices. People should not be using my account without my consent. Right now it's quite easy to do. All they need is my account number. Having a two factor authentication could solve this problem

**Comment by faern** [comment]
You can also solve this by contacting support and having them help you transfer your time to a new account number only known by you. Ultimately this is not an app feature request or bug report, so I will close this. Please contact support@mullvad.net, thank you
