### ISSUE TITLE
DuckDuckGo always shows this error in Firefox

### ISSUE THREAD

**Issue by Baccount** [mullvad/mullvadvpn-app#5193]
## Issue report

Operating system: macOS M1 13.6 (22G120)

App version: Mullvad 2023.5 beta 2

### Issue description

When the vpn is enabled DuckDuckGo always shows this error in Firefox, Safari is not effected. Clearing cache and cookies and restarting the Mac does not fix the issue.
This does Not occur on the stable build of Mullvad 2023.4

https://duckduckgo.com/?t=ffab&q=hkj
![Screenshot 2023-09-25 at 1 10 51 PM](https://github.com/mullvad/mullvadvpn-app/assets/10781882/625f2203-720c-4f29-9e34-7a33719e9235)

**Comment by Baccount** [comment]
Update:
Restarting Firefox after enabling the vpn temperately fixes the issue but it will always require this Non permanent fix.

**Comment by dlon** [comment]
@Baccount Is this still a problem on 2023.5?

**Comment by Baccount** [comment]
I can no longer reproduce this issue on the latest build.
