### ISSUE TITLE
issue in latest release while building

### ISSUE THREAD

**Issue by TheTanmay1** [mullvad/mullvadvpn-app#5218]
## Issue report

Operating system: Using android studio on LInux Mint

App version:   android/2023.6
### Issue description

The project is using an incompatible version (AGP 8.1.0) of the Android Gradle plugin. Latest supported version is AGP 8.0.2

**Comment by Rawa** [comment]
@TheTanmay1 Are you running the latest version of android studio?

**Comment by Rawa** [comment]
Closing, can't reproduce. Probably user is running an old version of Android Studio.

**Comment by TheTanmay1** [comment]
thanks a lot it solved the issue
