### ISSUE TITLE
Mullvad VPN blocks access to internet when display is locked on Android

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#5223]
## Issue report

Operating system: Android version 13

App version: 2023.5

### Issue description

Mullvad VPN blocks access to internet when display is locked. I noticed this on my phone when listening to podcasts on chromeit wouldn't allow the video to further play after 2-5 minutes. I have reproduced this and have determined its not an issue on the video players behalf  nor any other such as youtube music  which I also used to test this.

### Steps to reproduce:
1. Connect to VPN (having always-on or block connections doesn't effect ability to reproduce)
2. Disable and re-enable internet or mobile data
3. Play anything in the background or send yourself an email and notice the video cuts off  if its not already cached and you do not receive the email until toggling VPN on and off even though the internet will function while the screen is on. (Tested using stock OS phone)

Note disconnecting and reconnecting the VPN fixes this issue until you either switch the internet off and on or move between networks.

I'm not sure if this is somehow specific to my device but I have used other VPN services on the same phone and have never had this problem before.

**Comment by issuereporr** [comment]
S20FE, I apologize but I do not feel comfortable sending such detailed logs even though its anonymized.

**Comment by Dimitrigame562dde** [comment]
I have the same issue xD I have an honor 90

**Comment by albin-mullvad** [comment]
@Dimitrigame562dde can you see if it's still a problem on our latest release ([2024.8](https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2024.8))? Thanks!

**Comment by mattcelt** [comment]
Per Rawa's comment, please reopen this issue. It is ongoing on a Samsung S23U (SM918U) running Android 13 w/ OneUI 5.1.

Network access is severed once the lock screen activates regardless of network use.

**Comment by Rawa** [comment]
@mattcelt Please try and disable power saving https://dontkillmyapp.com/samsung#android-13, if this doesn't help create a new issue with app logs.

Mullvad has no logic to kill the tunnel when you shut off the screen, so this is most likely the OS killing the app and not respecting foregroud services.

**Comment by mattcelt** [comment]
Those settings were correct, but I found the following:

Application Data Usage:
· Allow background data usage [On]
· Allow data usage while Data saver is on [Off]

Battery Usage:
· Optimised - Optimise based on your usage of this app. 


I changed the settings to allow data saver use and Unrestricted battery usage. Haven't had a chance to test the new settings yet, but I wanted to capture the troubleshooting process.

**Comment by Rawa** [comment]
Yeah, you probably want the VPN app to be unrestricted when it comes to battery usage. Otherwise the OS might be "clever" and kill it to save battery. Unfortunately, VPN apps are rarely taken into account when developing these power saving features. 😢

**Comment by mattcelt** [comment]
I haven't tested all the features yet, but already the stability of the connection is substantially improved. I recommend adding those settings to the setup/configuration instructions (if they aren't already there and I just missed them...)

**Comment by Rawa** [comment]
> I haven't tested all the features yet, but already the stability of the connection is substantially improved. I recommend adding those settings to the setup/configuration instructions (if they aren't already there and I just missed them...)

If phones properly respect power saving measures this shouldn't be needed, so we should not guide everyone to do this. However, unfortuenately as you can see by looking at https://dontkillmyapp.com/ a lot of manufacturers doesn't fully respect it. I know our support team are recommending users with problems to do this as well, and work has been put better inform users about this with the help of our guides.

**Comment by mattcelt** [comment]
That makes a lot of sense.

My searches online brought me here first, so hopefully this exchange can help others who are having similar issues.

I was able to confirm that changing those settings resolved all of the connection issues I was seeing.

Thank you for all your hard work!
