### ISSUE TITLE
"Social media" DNS content blockers does not activate Use Custom DNS Text

### ISSUE THREAD

**Issue by dylanh12210** [mullvad/mullvadvpn-app#5233]
When checking on a content blocker (I.E: Ads, Malware) it changes the text under "Use custom DNS" to "Disable all content blockers (under VPN settings) to activate this setting."

Turning on the Social Media content blocker does not do this.

**Comment by faern** [comment]
Thanks for reporting this! We'll look into it. Which platform are you using?

**Comment by dylanh12210** [comment]
> Thanks for reporting this! We'll look into it. Which platform are you using?

iOS 17. Sorry I thought I had added it to the tags. Apparently no tags got added though.

**Comment by faern** [comment]
Fixed in #5233
