### ISSUE TITLE
VM connection problem

### ISSUE THREAD

**Issue by TzeKraken** [mullvad/mullvadvpn-app#526]
After installing the 2018.4-beta3 (Host Windows) I am having problems with my VM client (Windows), 
The network connection on my VM client (Windows) is a NAT connection and sharing my host's IP.

Internet connection status: connected
Ping: pakkets send 4, packets received 4

When I launch a browser my internet connection drops every time, when I ping google it sends and receives all packets. Could this be a DNS problem with the mullvad app?

**Comment by faern** [comment]
Please take support requests with support@mullvad.net
