### ISSUE TITLE
Can't verify the signature of MullvadVPN RPM package

### ISSUE THREAD

**Issue by xuzhao9** [mullvad/mullvadvpn-app#5285]
## Issue report

Operating system: openSUSE Tumbleweed

App version: 2023.5

### Issue description

1. Download the rpm file: https://github.com/mullvad/mullvadvpn-app/releases/download/2023.5/MullvadVPN-2023.5_x86_64.rpm
2. Download the rpm asc file: https://github.com/mullvad/mullvadvpn-app/releases/download/2023.5/MullvadVPN-2023.5_x86_64.rpm.asc
3. Run the command `rpm -K MullvadVPN-2023.5_x86_64.rpm`

Output:
```
MullvadVPN-2023.5_x86_64.rpm: digests SIGNATURES NOT OK
```

Note that I have imported and trusted MullvadVPN GPG Key A1198702FC3E0A09A9AE5B75D5A1D4F266DE8DDF

**Comment by faern** [comment]
The signature file at https://github.com/mullvad/mullvadvpn-app/releases/download/2023.5/MullvadVPN-2023.5_x86_64.rpm.asc has nothing with the RPM signature to do. Those are two different signature. The signature in the separate `.asc` file is what GnuPG calls a "detached signature". You can verify it like this:

```
gpg --verify MullvadVPN-2023.5_x86_64.rpm.asc MullvadVPN-2023.5_x86_64.rpm
```

The RPM file also contains an embedded signature, used by the RPM package management system. That's the one `rpm -K` reads and parses. To verify this signature you do not need to download the separate `.asc` file, BUT you need to import our code signing public key *into rpm* with this command: `sudo rpm --import /path/to/mullvad-code-signing.asc`. After that you should be able to do `rpm -K MullvadVPN-2023.5_x86_64.rpm`.

Please see the description provided in the PR where the RPM signatures were added: https://github.com/mullvad/mullvadvpn-app/pull/5208

**Comment by xuzhao9** [comment]
Thanks! I can confirm it works with importing `mullvad-code-signing.asc`.
