### ISSUE TITLE
Latest MullvadVPN app version won't let me connect

### ISSUE THREAD

**Issue by BerserkerBG** [mullvad/mullvadvpn-app#5289]
## Issue report

Operating system: Windows 10 Pro 22H2 (10.0.19045 Build 19045)

App version: 2023.5

### Issue description

When I try to connect to any server using the latest MullvadVPN app, it's giving me this error:
"Blocking Internet. Unable to start tunnel connection. Please send a problem report."

Here is a screenshot:

![image](https://github.com/mullvad/mullvadvpn-app/assets/58362332/b75eec62-1fff-443e-80bd-caecbc4edc9c)

No matter what I did, I could never get this version to connect to any server.

Here are the troubleshoot stepts I did so far:
- I did a Windows Update
- I did a full uninstall of the MullvadVPN app and reinstalled agian multiple times
- I did a sfc scan just in case
- I disabled both my firewall and antivirus
- I uninstalled previous VPN software I had before
- I've reset all of my Windows Services to default.
- I logged out and deleted all of my Mullvad devices

### Alternative Workaround

I used an older version of MullvadVPN app **(2020.7**) and to my surprise, I could finally connect to any server without any issues. I uninstalled this version and went back to the newest one (2023.5) and yet again, I could not connect to any server.

Any clues why older versions work for me, but not the newest?

**Comment by Vladdytine** [comment]
Usually a hard settings in firewall can cause that, if you're using any.

**Comment by NOCx420** [comment]
I'm having the same problem, newest version completely broke connecting for me. OpenVPN just goes round and round in circles and wireguard looks exactly like your screenshot. Tried all fixes and whatnot, but nothing. When trying to connect I get the following output of the daemon in systemctl:
```
mullvad-daemon[42712]: [mullvad_daemon][DEBUG] New tunnel state: Disconnecting(Reconnect)
mullvad-daemon[42712]: [mullvad_daemon][DEBUG] New tunnel state: Error(ErrorState { cause: StartTunnelError, block_failure: None })
mullvad-daemon[42712]: [mullvad_daemon][INFO] Blocking all network connections, reason: Failed to start connection to remote server
mullvad-daemon[42712]: [mullvad_daemon::management_interface][DEBUG] disconnect_tunnel
mullvad-daemon[42712]: [mullvad_daemon][DEBUG] Target state Secured => Unsecured
mullvad-daemon[42712]: [talpid_core::dns][INFO] Resetting DNS
mullvad-daemon[42712]: [talpid_core::firewall][INFO] Resetting firewall policy
mullvad-daemon[42712]: [talpid_core::firewall::imp][DEBUG] Removing table and chain from netfilter
mullvad-daemon[42712]: [mullvad_daemon][DEBUG] New tunnel state: Disconnected
mullvad-daemon[42712]: [mullvad_daemon::management_interface][DEBUG] get_current_location

```

Reinstalled twice, first using the "mullvad-vpn-bin" and then the "mullvad-vpn" AUR package. Seems like I need to downgrade versions until or if this issue is fixed. The mobile application is unaffected for me.

**Comment by Serock3** [comment]
Hello! Are you still experiencing this issue with the latest app version?

**Comment by Cennepal** [comment]
> Hello! Are you still experiencing this issue with the latest app version?

No, I am not. Connecting works now :D

**Comment by Serock3** [comment]
That's great to hear! Sorry for being slow to respond when you provided the logs. I'll go ahead and close the issue since it's solved.
