### ISSUE TITLE
Sudden incompatibility with Docker

### ISSUE THREAD

**Issue by deanvaessen** [mullvad/mullvadvpn-app#529]
Hi,

I hope it's fine posting here, as it's not an issue with the app itself, but rather an issue that it produces in Docker. 

The 2018(.3) version of the app seems to have an incompatibility issue with Docker which the old version of the client does not have. When the new version is active, Docker throws errors about the firewall blocking when trying to share drives to it.

Bottom line is that I cannot run Docker at the same time as the new Mullvad client. The moment I disconnect (or use the old version of the vpn client), everything is just peachy again.

I have found this issue in the Docker repo: https://github.com/docker/for-win/issues/360, as it seems VPNs can throw off the application. But even attempts at changing the subnet address in Docker don't seem to do fix for me. I am posting here in hopes you will be able to recognise what changed between the new and old version of the mullvad client, and can resolve the issue/point me in the right direction.

**Comment by pronebird** [comment]
Hi, 

Did you enable local sharing inside of the app?

**Comment by deanvaessen** [comment]
Thank you! That did it. I feel slightly silly now, but maybe this will help someone else in the future 👍
