### ISSUE TITLE
Mullvad 2018.4 gui window not visible on Ubuntu 14.04

### ISSUE THREAD

**Issue by kkarpieszuk** [mullvad/mullvadvpn-app#531]
Hello,

I just updated Mullvad from 2018.3 to 2018.4 and after that:
- i see red mullvad icon in top ubuntu bar
- when I click it and choose option to show Mullvad, nothing happens. No window visible. 

I went back to blog post and saw infomation that before updating I should remove old version. Maybe this caused the problem. 

So I tried to resolve it, this way:
- removed 2018.4 by:
-- stoping in task manager everything with name related mullvad (mullvad-deamon, few instances with mullvad-vpn)
-- removing mullvad by running `sudo dpkg -r mullvad-vpn`
- reinstalled 2018.3 by `sudo dpkg -i {path to downloaded 2018.3}`
- started mullvad - this time everything works ok, I see the window and it is connecting
- removed 2018.3 the same way I removed 2018.4 described above (stop everything, use dpkg to uninstall mullvad-vpn)
- installed mullvad 2018.4 again with `sudo dpkg -i {path to downloaded 2018.4}`

But I still have the same problem: red icon and no window

Now I am back on 2018.3 but would be great to find a way to have 2018.4 running on Ubuntu 14.04

**Comment by faern** [comment]
This is a mistake on our part. We just upgraded to Electron 3.0 and that causes some issues on certain distros with certain GUI drivers/cards etc. Try adding `--disable-gpu` when starting the GUI:
`/opt/Mullvad\ VPN/mullvad-gui --disable-gpu`
This should hopefully fix it!

**Comment by pronebird** [comment]
A patch for this has landed in 2018.5-beta1. Please give it a try.

**Comment by faern** [comment]
Yes, going to close this now. Should be solved on the master branch and should be in the released beta and soon stable version. Please re-open if the problem persists on the latest version.
