### ISSUE TITLE
[Feature Request] Landscape Mode for Android

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [mullvad/mullvadvpn-app#5350]
## Issue report

Operating system: Android 13

App version: 2023.7

### Issue description

I'd like to suggest the ability to have a landscape mode. For example, sometimes when I'm driving or biking I like to have my phone in landscape mode. But when I switch to Mullvad app, it only has the ability for portrait/vertical mode. IIRC, if I have auto-rotate enabled, switching to the Mullvad app will actually force my phone back into portrait mode too.

That's it. Thanks for the great app!

**Comment by Rawa** [comment]
Hello @tinglycraniumplacidly! Thanks for the feedback.

One of our upcoming projects during this quarter is to migrate over our navigation to Compose, our goal is that along with, or shortly after, the migration we can start to also allow landscape mode. 🤞

**Comment by Rawa** [comment]
This feature has now been merged to main, it should be in the next upcoming release. 

Thanks for reporting!
