### ISSUE TITLE
Mullvad's trust model for software distribution

### ISSUE THREAD

**Issue by mc0e** [mullvad/mullvadvpn-app#5378]
## Issue report

Operating system: Linux, and probably all others.

App version: The Mullvad website, GPG keys and repositories are the issue here.

### Issue description

I think Mullvad needs to lift it's game on how releases are signed and the practices it suggests to users.

Currently:
 - Linux packages are distributed without a proper repository.  
 - Packages are signed, but there is no way to know whether the signing key is good, as the signing key is not signed.
 - Mullvad's instructions on verifying signatures (https://mullvad.net/en/help/verifying-signatures/) display a gross misunderstanding of how the GPG trust model works - No one other than Mullvad should be setting trust level 5 on Mullvad's key.

For a security related product, this is rather underwhelming.  Users are being asked to configure their systems such that any software that is signed by a key that is signed by Mullvad's key will be considered safe.  If Mullvad's key were compromised, the security of any software their users install would be compromised, not just new versions of Mullvad's software.

If nothing else changes, then the page on verifying signatures should be changed.  Instead of saying to give ultimate trust to the Mullvad key, people should sign their copy of the key.  This is a weak solution in that people are signing the key without really knowing if it's correct (and Mullvad should be clear that that's what people are doing).  Still it's much better than telling people to issue commands that give Mullvad ultimate authority to sign other keys.

Far better would be to get your keys signed by people at Debian, Redhat, Canonical et al, and release software through the main repositories.

**Comment by faern** [comment]
I agree we should not be telling users to set the trust level of our key to `5`. That is indeed very wrong.

> Linux packages are distributed without a proper repository.

We are working on that, and that's coming. But I'd say that's unrelated to the rest here.

**Comment by faern** [comment]
Our support team have now updated the signature verification guides. They no longer recommend setting our key to trust level 5. Instead it (optionally) recommends the user to *sign* our key as a way of getting gpg to not print warnings about untrusted keys.

> Linux packages are distributed without a proper repository.

This is now fixed: https://mullvad.net/en/blog/introducing-package-repositories-for-ubuntu-debian-and-fedora

So I'm going to close this now. Feel free to point out if you think there is anything left that is not adequate.
