### ISSUE TITLE
No Tool Tip in macoOS

### ISSUE THREAD

**Issue by bit-blit** [mullvad/mullvadvpn-app#5385]
I'm running the latest version of Mullvad VPN (2023.5) on macOS 14.1 Sonoma

With the latest version of Mullvad - 2023.5 - Has the tool-tip feature been eliminated? When I hover over the lock icon in the toolbar, it no longer gives me a connection status in the form of a tool tip.

Just wondering if this is normal for the newest version and going forward.

Thanks in advance.

**Comment by bit-blit** [comment]
I know this has already been assigned, but I figured I would add this as it may be helpful:

If I hover in the blank space just to the left of the lock icon in the tool bar, the status/tool tip appears. It's like the "trigger" area has been moved one space to the left. Of course some people may have other icons to the left of the Mullvad lock icon, but in my case the lock icon is the left most positioned icon and hovering in the blank space to the left of it will give me the tool-tip/status.

**Comment by Ericmagsllonstrigs** [comment]
I for got Mac passwords

**Comment by raksooo** [comment]
@bit-blit I haven't looked into this yet, but my suspicion is that this was broken in an Electron upgrade. We've upgraded Electron again and I can't reproduce this issue on my computer, although I haven't checked if I have the issue on the old version either. Let's see if the next release of our app fixes this for you.

**Comment by bit-blit** [comment]
OK - No worries, I will wait for the next release and report back. Thanks for your help.

**Comment by bit-blit** [comment]
This problem still persists in the latest 2023.6 release version. Granted, it is a very minor bug and I can live with it, but I thought I should still report back on it. Thanks.

**Comment by alexander-e** [comment]
I'm running the 2023.6 release on macOS 14.2, and for me the tool-tip appears when I hover over the icon in the toolbar.

**Comment by bit-blit** [comment]
> I'm running the 2023.6 release on macOS 14.2, and for me the tool-tip appears when I hover over the icon in the toolbar.

Yes, since updating to macOS 14.2 the problem seems to have been resolved, however, the tool-tip will now show in BOTH positions - both when hovering over the lock icon AND in the blank space to the right of the lock icon. Again, a very minor bug, but I can confirm it is now working when hovering over the lock.

**Comment by alexander-e** [comment]
Isn't this just the blank space that is reserved for each status menu on the menu bar? If you press the icon of the status menu, you will see that it highlights a larger part of the menu bar that (roughly) corresponds to the area where the tooltip appears.

**Comment by bit-blit** [comment]
> Isn't this just the blank space that is reserved for each status menu on the menu bar? If you press the icon of the status menu, you will see that it highlights a larger part of the menu bar that (roughly) corresponds to the area where the tooltip appears.

You are correct - I consider this issue fully resolved. Thank you for your help and comments in clarifying the issue.

**Comment by raksooo** [comment]
Great that Apple solved this!
