### ISSUE TITLE
Back button mis-formatted in Advanced page

### ISSUE THREAD

**Issue by jeffbowen** [mullvad/mullvadvpn-app#54]
Just got beta-9 and the back button to “Settings” is mis-formatted on the Advanced page. macOS 10.13.3. If you'd rather I not report issues on your Github, let me know. ;) Just figured I'd let you know.

![untitled](https://user-images.githubusercontent.com/272795/35770177-0dfd388e-08dc-11e8-865e-ac0bcbd42f68.png)

**Comment by faern** [comment]
Yup, I can reproduce the error. Thanks for letting us know! These types of bug reports are very helpful indeed. We'll look into it and get it fixed before next release.

Ping @anderklander @pronebird

**Comment by anderklander** [comment]
There is a [PR](https://github.com/mullvad/mullvadvpn-app/pull/52) that should fix this!

**Comment by anderklander** [comment]
Merged!
