### ISSUE TITLE
How to connect to Mullvad in restricted WLAN guest network

### ISSUE THREAD

**Issue by baimafeima** [mullvad/mullvadvpn-app#540]
What can I do to be able to connect to Mullvad in a restricted WLAN guest network? It seems that this guest network/hotspot only allows "surfing" and "email". I cannot use any VPN connection and connections with download managers/torrenting and IRC is also blocked. When I use Mullvad in my home WiFi network, everything works well. But this use case (guest network) is actually when I need Mullvad the most.

**Comment by faern** [comment]
That should work. Try going to the advanced settings and select protocol TCP and port 443. If you continue having problems, this type of support is better directed at support@mullvad.net.

The upcoming release of this app (2018.5) will automatically fall back to TCP if UDP seems to be blocked.

**Comment by johnjohnk2** [comment]
Hi @baimafeima I just re open this ticket as I have an issue to connect to irc via thunderbird plugin. I don't know how to create a split tunneling to irc. Thanks for help
