### ISSUE TITLE
Position of Grey Outline seems to be off

### ISSUE THREAD

**Issue by julianschacher** [mullvad/mullvadvpn-app#541]
The position of the grey outline at the top of the Mullvad app seems to be off:

<img width="436" alt="screenshot 2018-10-20 at 20 04 40_mullvad_vpn_app_grey_outline_at_the_top_position_off" src="https://user-images.githubusercontent.com/26492670/47259002-b4084a00-d4a3-11e8-8998-5c3f6bc834af.png">

I'm using the following setup:
- MacBook Pro with macOS Mojave Version 10.14
- Mullvad VPN app version 2018.4

**Comment by julianschacher** [comment]
If you're reading this as a mail: I hit the "Submit New Issue" button / enter key by accident. The issue does now have a description with more information.

**Comment by pronebird** [comment]
Hi,

Thanks for reporting this. We’re aware of this visual defect. It originates from one of our dependencies (Electron) and we’re closely tracking the resolution of this issue.

**Comment by alexandernanberg** [comment]
I think it should be possible to solve this now. https://github.com/electron/electron/issues/13164
Relevant PR that fixed the issue in VSCode https://github.com/Microsoft/vscode/pull/59742

**Comment by pronebird** [comment]
I've addressed this in a5554332247a8aed24561070e71c2af6ffded94c, however we'll have to wait until the relevant fixes are back ported and released with the stable branch. It seems to work fine under the Electron 6 beta.
