### ISSUE TITLE
[Feature Request] Local password protection

### ISSUE THREAD

**Issue by CloreWind** [mullvad/mullvadvpn-app#5422]
### Issue description
Will there is a local password option be added to protect the account information? 

After got mullvad I noticed there is no password on serverside, only a 16 numbers account ID as all certificate. And it will directly show in desktop app. It might cause some problem when using a laptop in public area like company/school, anyone touch the PC could get full access of the account easily. I understand it's for minimal information collection, but add a local password option in app is simple and would not cause any extra issue.

**Comment by faern** [comment]
The app's threat model builds upon trusting the local device where it's running.

I could also argue that if you let people you don't trust use your computer you have no way of trusting that computer any longer. They could install a keylogger and simply steal your Mullvad account number and/or this password you are suggesting at any later point in time.

If you are referring to a multi user computer where the Mullvad app is running as you (the admin) and you have low privilege accounts that other people are using then the answer is: We currently don't support multi user computers very much, that's not our main target audience. However! If you are using Linux or macOS you can actually lock down the management interface of the Mullvad system service and achieve exactly what you want here, but this feature is currently not available on Windows. For this please see the documentation on the `MULLVAD_MANAGEMENT_SOCKET_GROUP` environment variable: https://github.com/mullvad/mullvadvpn-app/#environment-variables-used-by-the-service

**Comment by CloreWind** [comment]
I'm using both windows and macOS, the mac is shared device and I'll try this.
I think mullvad as a public vpn service , not everyone are facing, or preparing to face the danger from purposeful hackers or governments. Keep the account not abused by someone greedy (others who share the device) is also important cause the account recovery of mullvad is only 40days, then the payment log will be deleted.
I know it's just a tiny usage, but sometime useful. it just work like the screen lock of something like Signal.

**Comment by faern** [comment]
In your use case, do you want the "other users" to be able to disconnect and change server, or not be able to interact with the Mullvad system service at all? In other words, what you can already do on macOS? If what we have on macOS/Linux with the management interface permission group is enough for you, we could look into enabling that sort of permission system on Windows. There we use a named pipe for management interface communication, but we could see if we can apply some permission there as well.

**Comment by CloreWind** [comment]
> In your use case, do you want the "other users" to be able to disconnect and change server, or not be able to interact with the Mullvad system service at all? In other words, what you can already do on macOS? If what we have on macOS/Linux with the management interface permission group is enough for you, we could look into enabling that sort of permission system on Windows. There we use a named pipe for management interface communication, but we could see if we can apply some permission there as well.

I'm sorry for not explaining clearly, but you may misunderstanding what I said. In my use case, there is no extra user of the system, only one. Someone may share the PC just temporarily.

The feature what I want to request is a extra step that can make anyone before checking mullvad account number in the app GUI, needs to input a password. The password created by who first set it and it'll encrypt the mullvad account number locally.

**Comment by faern** [comment]
The mullvad system service needs the account number in plain form for multiple things. For example authenticating when connecting over OpenVPN etc. So the `mullvad-daemon.exe` process needs access to the account number in a non-encrypted form. And if your single user (that multiple people share) is an administrator user, nothing stops that user from easily getting the account number from the daemon. If your single user is a non-administrator account a password protection on the management interface can indeed help. This is not a use case we currently support, and are currently not considering, given that multi-user setups is not in our threat model right now.

You might want to consider running Mullvad on your router in order to force all devices on your LAN out via a tunnel and not giving them any access to the VPN setup or config or credentials.

**Comment by CloreWind** [comment]
Understood, thanks.
