### ISSUE TITLE
Getting standalone udp-over-tcp to work on linux using the provided reference implementation

### ISSUE THREAD

**Issue by whostherewhy** [mullvad/mullvadvpn-app#5444]
Trying to get udp-over-tcp working standalone on linux, but no luck.

I modified:
https://github.com/mullvad/mullvadvpn-app/blob/main/tunnel-obfuscation/src/main.rs

as:

```
#[tokio::main]
async fn main() {
    if args().len() != 2 {
        println!("Missing arguments");
    }

    let obfuscator = instantiate_requested(&args().last().unwrap()).await;

    println!("{:?}", obfuscator.endpoint());

    if let Err(err) = obfuscator.run().await {
        println!("obfuscator.run() failed: {err:?}");
    }
}

async fn instantiate_requested(peer: &str) -> Box<dyn Obfuscator> {

    let settings = Udp2TcpSettings {
        peer: peer.parse().unwrap(),
        #[cfg(target_os = "linux")]
        fwmark: None,
    };

    create_obfuscator(&Settings::Udp2Tcp(settings))
        .await
        .expect("Creating obfuscator failed")

}
```

`/path/binary wg.endpoint`

It runs and listens, however when
`wg set wg0 peer xxxxxxx endpoint 127.0.0.1:yyyy`

There is no connectivity. This test was performed on a functioning tunnel (just to to try switching udp to tcp) so everything should be in order

There is no documentation on the subject, could the endpoint port be incorrect? I assumed the tcp port = udp port

**Comment by faern** [comment]
We do not support TCP on the same ports as UDP. If you connect to one of our WireGuard servers with `udp-over-tcp` you need to connect to it on TCP port 5001 or 80. https://github.com/mullvad/mullvadvpn-app/blob/e09558a51ad6f84d375dd00a666cd2f6257e3ead/mullvad-relay-selector/src/lib.rs#L48

**Comment by whostherewhy** [comment]
That worked.

It also seems there was some discussion regarding replacing udp2tcp with fake TCP. If that is still on the slate, would it be possible to add it instead of replacing udp2tcp? Fake TCP will not function within TCP tunnels ex. tor.

**Comment by faern** [comment]
We will not replace it with face TCP. We will add it. Likely on port 443. But this is not decided yet. But yes, we need to keep `udp-over-tcp` because regular non-fake TCP sockets is the only thing you can create on non-rooted phones

**Comment by whostherewhy** [comment]
For some reason udp2tcp is bugged with PQC handshake.
It works for the first handshake, but after some minutes it just drops off.

Restarting the whole handshake & udp2tcp process makes it work again.

Without PQC everything works.

The only wireguard difference in the processes is the two wg commands that set private key and preshared key. this is done while udp2tcp is engaged. And after the operation is completed the tunnel works. But then at some point it stops working. Restarting udp2tcp has no effect, handshake has to be restarted.

**Comment by faern** [comment]
`udp2tcp` indeed only listens for a single incoming connection and then stops listening. That's by design. Both since it keeps the code simpler, and it better guarantees that our own WireGuard connection is the only process utilizing this temporary proxy. We re-create new `udp2tcp` instances whenever we need to re-bind our WireGuard socket, so it works nicely. It was not designed to be used manually. I don't know when or if vanilla WireGuard might rebind its UDP sockets.
