### ISSUE TITLE
Frequency of updates of the DNS Content blockers

### ISSUE THREAD

**Issue by notDavid** [mullvad/mullvadvpn-app#5481]
## Issue report
- Operating system: iOS, macOS
- App version: 2023.5

### Issue description

Hi there, this is more of a question than an issue, but i think it would be good to document this somewhere;

When are fixes / changes released in the [dns blocklists](https://github.com/mullvad/dns-blocklists), active in the Mullvad VPN apps?

Are these updated daily / weekly / etc. ?

Could not find any docs or help on it, including at https://mullvad.net/en/help/dns-over-https-and-dns-over-tls

Thank you!

**Comment by jbjorkang** [comment]
I can answer this, we typically refresh the block lists weekly on Mondays. These get updated on VPN servers within a 24 hour period. This is nothing to do with the app, it is reliant on the VPN servers checking in to pull in the latest updates.

**Comment by jbjorkang** [comment]
I will close this issue as completed. As mentioned in the other related [issue](https://github.com/mullvad/dns-blocklists/issues/123#issuecomment-1825621877) all works as expected.

In the DNS block list repository it already [mentions](https://github.com/mullvad/dns-blocklists) the expected refresh frequency.
