### ISSUE TITLE
just released 2023.6-beta1 locks out internet after reboot, hung on uninstalling

### ISSUE THREAD

**Issue by narration-sd** [mullvad/mullvadvpn-app#5497]
## Issue report

Operating system: Windows 11 latest updates

App version: 2023.6-beta-1

### Locked internet off after reboot, then hung on uninstall

Very simple -- I've had no such trouble before

- downloaded from github after your email
- installed over 2023.5 release, started it manually, looked good
- shutdown machine after a backup, then started it normally. Not a Restart, a Shutdown then an hour later, Start
- no internet. And I think Mullvad said Internet blocked
- checked with phone, etc. Internet is fine, on two different access points
- try Mullvad on either access point. No go.
- try to uninstall, to revert to 2023.5
- uninstaller hangs hard, looks like on removing driver/s
- get Revo and run it. Not sure it did more than remove registry keys; maybe the driver actually was uninstalled
- reinstalled prior released 2023.5
- seems fine with that
- one further point that should not make a difference, but -- is that I run a non-adminstrative user for safety, using password of an admin user when accessing the privileges. This should not bother either normal operation or install/uninstall, as am sure you're aware.

This is a new, clean, very up-to-date machine as I do complex development. I don't feel the machine had anything to do with this.

Hope you can warn against installing until you have a safely fixed version.

**Comment by narration-sd** [comment]
I'm not sure about this now, and will have to give you some more details. Something similar happened when I opened the laptop today, with the prior released version installed.

I checked the settings, and found Lockdown Mode was set. This might be because I had to do that Revo uninstall after your uninstaller hung for the beta -- it removed all/a batcch of your registry keys. But why would Lockdown Mode be the default?

And if the beta were setting it that way, that may be the cause of the hard bug of stopping internet on bootup by it.

Still doesn't explain your uninstaller hanging. From what Revo found to do, it looks like it actually succeeded before hanging.

**Comment by narration-sd** [comment]
Hi Oskar, and thanks for the details. 

I haven't seen this repeat itself, after repairing my settings, and suspect that it did was a combination of this mis-setting by the install, plus a moment when the internet disappeared, perhaps in the middle of Mullvad's sign-on process.  /this unfortunately happens from time to time on my cable modem/access points, which I'm not able to access or adjust (or replace :) ).

I'll let you know if seen again, and that's quite good to understand as far as getting logs to you at Mullvad.

Kind regards,
Clive

**Comment by MarkusPettersson98** [comment]
Hi @narration-sd :blush: 

Sorry for bumping such an old issue, but I just want to check if you have experienced any issues with later app versions? Otherwise, I think I'll go ahead and close this issue

**Comment by narration-sd** [comment]
Takk, Oskar, I haven't -- smooth betas recently, and thank you thoughtfully, for checking....
