### ISSUE TITLE
Show `Entry` tab first when switching locations

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/mullvadvpn-app#5545]
## Issue report

Operating system: macOS

App version: 2023.5

### Issue description

I did not find existing issues with the same suggestion.

When switching location, I would like to see the `Entry` tab first.

Current behaviour:
1. Main view of the app
1. Click the `Switch location` button
1. Content of the `Exit` tab is displayed
1. Click on the `Entry` tab
1. Selection of a **different** server
1. The view switches to the `Exit` tab

Suggested behaviour:
1. Main view of the app
1. Click the `Switch location` button
1. Content of the `Entry` tab is displayed
1. Selection of **any** server
   1. Note: different phrasing as even clicking on the server currently selected would work,
      while in the current behaviour clicking the server currently selected does nothing.
1. The view switches to the `Exit` tab

**Comment by raksooo** [comment]
We'll keep the design as is. Hopefully it's not too inconvenient for your use-case.
