### ISSUE TITLE
Allowed incoming connections are not forwarded to Docker containers

### ISSUE THREAD

**Issue by hollowshiroyuki** [mullvad/mullvadvpn-app#5560]
## Issue report

Operating system: `Linux 5.10.0-26-cloud-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64 GNU/Linux`

App version:
```
Current version       : 2023.6
Is supported          : true
Suggested upgrade     : none
Latest stable version : 2023.6
```

### Issue description

I am using the advanced configuration described here https://mullvad.net/en/help/split-tunneling-with-linux-advanced#allow-incoming to allow incoming traffic to my Debian server. Here's the exact rules :
```
define ALLOWED_PORTS = {
	22,
	80,
	443,
	25565
}

table inet excludeTraffic {
	chain allowIncoming {
		type filter hook input priority -100; policy accept;
		tcp dport $ALLOWED_PORTS ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
	}

	chain allowOutgoing {
		type route hook output priority -100; policy accept;
		tcp sport $ALLOWED_PORTS ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
	}
}
```

Remote SSH works but the others ports don't. When using curl on the server itself using its domain name I receive the response but not when requesting from another device through internet.
I'm pretty sure this is because I am using docker to manage the services listening on these ports, unfortunately I don't have enough networking knowledge to dig further.

I don't really know if this is an issue with the app or docker nft rules or my config file.

Thanks for your help !

**Comment by faern** [comment]
Please contact support@mullvad.net for questions like these. I don't think this is an app bug.

**Comment by CaptainStealthy** [comment]
@hollowshiroyuki Did you ever figure this out? I'm having the same problem, and nothing I try seems to work :(

**Comment by hollowshiroyuki** [comment]
hi @CaptainStealthy,
yes i could find a workaround, however it seems to have some weird side-effects and i wouldn't recommend you to use it (in fact i don't even use it myself until i find the correct solution). i'm not familiar with nftables and the way the workaround works probably introduce some unsafe/undesirable situations
```
table inet mullvad-ts {
	chain prerouting {
		type filter hook prerouting priority -100; policy accept;
		ip daddr <DESTINATION_IP> tcp dport $ALLOWED_PORTS ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
	}
}
```
