### ISSUE TITLE
2023.6 not pushed to RPM repo

### ISSUE THREAD

**Issue by pointydev** [mullvad/mullvadvpn-app#5562]
## Issue report

Operating system: Fedora 39

App version: `2023.6-beta1`

### Issue description

I received a notification in-app (and also via email) that the latest stable release had just released, so I went to `dnf upgrade` in order to update the app, however there was no available upgrade. I checked the [beta](https://repository.mullvad.net/rpm/beta/x86_64/) and [stable](https://repository.mullvad.net/rpm/stable/x86_64/) repos manually, and I can see that the builds haven't been pushed yet. It'd be great if this could be rectified now and for future releases.

Thanks,
Elliott

**Comment by pointydev** [comment]
@raksooo Thanks, I can see the package has been published, however I cannot upgrade easily unless I specify the exact package version, which is technically counted as a downgrade. I'm assuming this is due to the versioning of betas.

![output](https://github.com/mullvad/mullvadvpn-app/assets/22241432/46f539e9-788c-41fb-83b3-1651c490a30b)

**Comment by raksooo** [comment]
Yes this is due to the `-` in `2023.6-beta1`. We've fixed this but unfortunately it wasn't included in this release. In future releases it will work as expected. Sorry for the inconvenience.

**Comment by pointydev** [comment]
> In future releases it will work as expected.

Can confirm that 2024.1-beta1 upgrades as expected, thanks!
