### ISSUE TITLE
Add map to android app

### ISSUE THREAD

**Issue by sjiawjbssj** [mullvad/mullvadvpn-app#5581]
Hi, it would be nice if the map could be added to the android app. Every other version has it.

**Comment by Rawa** [comment]
Thought I'd just add an update on this issue. We've made a push for maps this quarter, and hopefully soon can merge it in to main. We utilize the same underlying map data as on desktop and render our own Map with GL.

Here is a sneak preview:
https://github.com/mullvad/mullvadvpn-app/assets/1526920/b4c7fb09-322e-4733-96de-5fd966f5d401
