### ISSUE TITLE
Always-on-VPN in multiple profiles

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#5586]
## Issue report

Operating system: GrapheneOS ([2023120800](https://grapheneos.org/releases#2023120800)) Android 14 QPR1

App version: 2023.9

### Issue description

I [recently became aware](https://github.com/GrapheneOS/os-issue-tracker/issues/2835) that one apparently can't have Always-on-VPN toggle enabled in multiple Android profiles simultaneously. Eventually, one of them (Owner for me) disconnects. Mullvad Android app then complains that I might have "Always-on-VPN enabled for another app" and GrapheneOS throws up a message of "Disconnected from always-on VPN". I reached out to your Support and received the following reply:

> Disable "Always-on VPN" on one of the profiles, which should resolve the issue. It is only possible to have "Always-on VPN" enabled for an app on one profile at a time. This is an Android limitation.

[According](https://github.com/GrapheneOS/os-issue-tracker/issues/2835#issuecomment-1852313795) to GrapheneOS developers, it is not true and might either constitute an app bug or OS bug.

I'd appreciate it if someone from Mullvad could perhaps chime on the origins of this limitation.

**Comment by albin-mullvad** [comment]
Thanks for reporting! Did this work on previous Graphene/Android versions? Or can you try it out on another device or Graphene/Android version?

**Comment by MrChocolatine** [comment]
I don't have this issue personally.

I am using GrapheneOS on a Pixel 6a.
I have multiple user profiles, but don't use the "Owner" profile.
Each of my user profile have Mullvad VPN installed, and each have Settings > Always-on VPN enabled.
I don't have any issue using Internet when switching profiles.

**Comment by Pururun** [comment]
This might be related to https://github.com/mullvad/mullvadvpn-app/issues/6349

Closing this since the OP deleted their account.
