### ISSUE TITLE
Add full keyboard navigation to the `Selection location` view

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/mullvadvpn-app#5594]
## Issue report

Operating system: all

App version: n/a

### Issue description

I did not find existing issues with the same suggestion.

On the view `Selection location`, whether the `Entry` or the `Exit` tab is active, I would like to be able to fully navigate using my keyboard:

- From the main view of the app, click on `Switch location` button
  - Pressing <kbd>Escape</kbd> would lose the focus from the application/would reduce it in the menubar

- Current view is `Selection location` and focus is currently in the text box

  - Pressing <kbd>Shift</kbd> + <kbd>TAB</kbd> would focus to the selected tab `Exit`
    - Pressing <kbd>◀</kbd> or <kbd>▶</kbd> would focus between the tabs
    - Pressing <kbd>Enter</kbd> would "click" the tab currently focused

      - Here, as an addition, typing on the keyboard would automatically focus & type in the text box.
        Currently, when selecting a tab, we need a second click in the text box to be able to search, a bit annoying

    - Pressing <kbd>TAB</kbd> would focus to the text box (if we have not typed anything yet)

  - Pressing <kbd>TAB</kbd> would focus the location currently active in the list
    - Whether I typed something in the text box or not,
      pressing <kbd>⬇</kbd> would focus the first entry of the list (whether it is filtered or not) and then the next entry
      pressing <kbd>⬆</kbd> would focus the previous entry

    - Pressing <kbd>TAB</kbd> would focus the arrow to expand/collapse the entry,
      and pressing <kbd>Enter</kbd> would "click" the arrow.

    - Same logic for the child entries

This would be a really nice addition to #3382 which has allowed us to go back to the previous view, or to the main view, using different keyboard shortcuts.

**Comment by raksooo** [comment]
Thanks for the suggestion. Better keyboard navigation would indeed be nice! I've added it to our backlog.

**Comment by MrChocolatine** [comment]
> Thanks for the suggestion. Better keyboard navigation would indeed be nice! I've added it to our backlog.

Out of curiosity, do you know when you plan to work on this improvement?

Thank you.

**Comment by raksooo** [comment]
Unfortunately this isn't at the top of our priorities since it's not a commonly requested feature. I suspect there will take quite a long time until we look into this.
