### ISSUE TITLE
Reddit block brazilian servers

### ISSUE THREAD

**Issue by Mummify1867** [mullvad/mullvadvpn-app#5595]
## Issue report

Operating system: Windows 11

App version: 2023.6

### Issue description

Whenever accessing Reddit, the following blocking message is shown. I'm using the br-sao-wg-201 server: [https://ibb.co/hWLftjD](https://ibb.co/hWLftjD)

**Comment by faern** [comment]
Please contact support@mullvad.net with this issue. This is not app related, but rather infrastructure/service related.
