### ISSUE TITLE
[Feature request] Upcoming Turkish government's VPN censorship

### ISSUE THREAD

**Issue by mtunad** [mullvad/mullvadvpn-app#5612]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I am opening up this issue to notify Mullvad Team for the upcoming problems in Turkey. Turkish government is notoriously blocks and follows internet traffic on grounds of surveillance. (Judicial privacy related decisions evaded by government one way or another)

There were many revealings about it. In 2022, BTK-gate news told that Information Technologies and Communications Authority (BTK in Turkish—Turkish FCC) was regularly collecting [traffic logs from ISPs](https://medyascope.tv/2022/07/21/btk-gate-internet-activity-identity-and-personal-data-of-all-users-in-turkey-has-been-collected-by-btk-for-the-past-year-and-a-half/).

There were many similar orders and incidents from Turkish government that can be found by Googling. The latest news about Turkish FCC (BTK) might be telling beforehand what is about to happen in Turkey.

According to respectable journalist Turkish [government ordered](https://t24.com.tr/yazarlar/fusun-sarp-nebil/btk-yine-vpn-kapattirdi,42705) ([google translate](https://t24-com-tr.translate.goog/yazarlar/fusun-sarp-nebil/btk-yine-vpn-kapattirdi,42705?_x_tr_sl=auto&_x_tr_tl=tr&_x_tr_hl=en&_x_tr_pto=wapp)) BTK ordered ISPs to

1) block the given list of VPNs in the news,
2) follow & monitor the alternative access methods
3) report the change in traffic and its amount

Turkish government has already blocked to web sites of Mullvad. However, in recent news, they have started tighten their surveillance practices.

Therefore, what I wish that when Turkish government finds a way to block Mullvad access, I can use Mullvad. I wanted to notify Mullvad Team, whether that can they prepare a solution for mass VPN blocks and evading methods.

After this news, my VPN stability has reduced. I was getting ERR_NAME_NOT_RESOLVED error while surfing through web sites.
<img width="638" alt="image" src="https://github.com/mullvad/mullvadvpn-app/assets/15094113/b469cd60-89c0-43b9-97b9-f0d490252367">

A couple of refresh request is solving the warning, however after I use WireGuard with Obfuscation ON setting, ERR_NAME_NOT_RESOLVED problem disappears. I don't know what it means, as I don't have the technical background of it. The downside of this setting is about ping and connectivity issues in video chats. Would be nice to use Mullvad without obfuscation.

Best regards...

### Alternative solutions

Using obfuscation mode with WireGuard in VPN settings

### Type of feature

- [X] Better privacy/anonymity
- [X] Better at circumventing censorship
- [ ] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [X] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by faern** [comment]
I'm sorry to hear you are being censored. However, this type of feature request does not really belong on this issue tracker. This is a request on improving our service in general, which I suggest you talk to support@mullvad.net about.

This issue does not really include any actionable distinct feature to implement. So I'm going to close this.

> Would be nice to use Mullvad without obfuscation.

Why would that be nice? What's wrong with obfuscation? Obfuscation is a means of hiding that you are using WireGuard or OpenVPN. If your ISP is blocking WireGuard and OpenVPN, you definitely need obfuscation to circumvent their blocks. I don't see why you want to be able to use it without obfuscation.

Our current (only) obfuscation for WireGuard (WireGuard over TCP) is not very high performant, and I guess that is your main problem? Yes, we will work on including more obfuscation methods, that will hopefully perform better.
