### ISSUE TITLE
select  what country to connect to with CLI

### ISSUE THREAD

**Issue by alirezaalavi87** [mullvad/mullvadvpn-app#5618]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Hi.

The CLI app is missing some features. For example you can connect with `mullvad connect` but you cannot specify which server to connect to. These subcommands should be available :
` mullvad connect [country]`
`mullvdad connect [server-name]`

having a CLI is a great feature for a VPN but the CLI should be fully usable by itself.

### Alternative solutions

Only changing the country from gui app is available. and you cannot specify a server from the CLI.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [ ] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by MrChocolatine** [comment]
I am a customer and I can select which country and which server to connect to using the commands provided here:
https://mullvad.net/en/help/how-use-mullvad-cli
https://mullvad.net/en/help/cli-command-wg
https://mullvad.net/en/servers

**Comment by alirezaalavi87** [comment]
@MrChocolatine Oh I see, It is set with the `relay` subcommand. But it would still be easier if we could use  
`mullvad connect [country]`
`mullvdad connect [server-name]`
as  short hand. since it is much more concise

**Comment by faern** [comment]
Changing settings and issuing a state change command (connect/disconnect) are two separate things. We have guides for how to use the CLI as linked above. I feel like `mullvad relay set location <location> && mullvad connect` is sufficiently easy to not warrant a special case `mullvad connect <location>`

The standard use case is not to select what server you want to connect to that often. You set a custom list or a location and then you connect many times over to the same place.

> the CLI should be fully usable by itself.

It is, and this is already important to us! The GUI is *always* a subset of all the features available in the CLI. When we add functionality in the app we expose it in the CLI first and then to the GUI.
