### ISSUE TITLE
Payment BTC

### ISSUE THREAD

**Issue by HotCrypt** [mullvad/mullvadvpn-app#5619]
BTC payment fees too high.

![IMG_5927](https://github.com/mullvad/mullvadvpn-app/assets/108491675/d5851d93-2eda-4785-a841-b5b27ab619e2)

### Alternative solutions

Can you implement BTC payment with Lightning Network? Node LN(D) + btcpay. The fees are extremely low and instantaneous.

Sincerely,

**Comment by faern** [comment]
Sorry, but this feature request is not about the app, rather about the service in general. Please read the issue form description. Contact support@mullvad.net. I'm going to close this as it's not app related.
