### ISSUE TITLE
huge regression in 2023.6, does not connect, GUI is only noise

### ISSUE THREAD

**Issue by firefoxlover** [mullvad/mullvadvpn-app#5620]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Since version 2023.6 on Fedora Kinoite, the app is broken.

I installed the official RPM from the repo, so also automatic updates...

The GUI is just noise, pixels and often black blocks, nothing displayed at all. 

I am currently manually installing the 2023.5 RPM and see if that fixes it. EDIT: yes it does.

I am not sure if I have killswitch enabled, but for some reason the tray icon right click (connect, disconnect, reconnect) dont work either.

So I have no internet access, as mullvad seems to block DNS, after removing the enforced lockdown mode  via CLI at least pinging IPs worked, and also connecting in Firefox to a local IP router worked.

![Screenshot_20231225_154638](https://github.com/mullvad/mullvadvpn-app/assets/78762110/c97e3433-c089-4061-b228-dad6a05221cf)

### Expected Behavior

No GUI glitches, connecting normally

### Steps to Reproduce

Just try it idk. 

Latest RPM,
Fedora Kinoite 39 (based on normal Fedora KDE, firewalld, networkmanager, systemd-resolved)

Non blocked Wifi

Dns in resolved completely vanilla, so when mullvad is disabled captive portals work.

### Operating system version

Fedora 39

### Mullvad VPN app version

worked in 2023.5, broken in 2023.6

**Comment by Jo-Panic** [comment]
Had similar issue with Fedora 39 + Gnome. But for me, the gui seems empty (totally white).

I uninstalled the standalone rpm file then added the Mullvad VPN repository, installed from there and now it works.

**Comment by raksooo** [comment]
@firefoxlover Could you try running the app with `--disable-gpu`?

**Comment by firefoxlover** [comment]
Hi, I will try that.

**Comment by Pobega** [comment]
I'm encountering the same issue, running `/usr/lib/opt/Mullvad\ VPN/mullvad-gui --disable-gpu` works. The client is fully functional.

**Comment by raksooo** [comment]
@Pobega You can copy the desktop file to `~/.local/share/applications` and add the flag there:
```
mkdir -p ~/.local/share/applications
cp /usr/share/applications/mullvad-vpn.desktop ~/.local/share/applications/
```
And then open `~/.local/share/applications/mullvad-vpn.desktop` and add `--disable-gpu` to the `Exec`-line before `%U`, i.e:
```
Exec="/opt/Mullvad VPN/mullvad-vpn" --disable-gpu %U
```

**Comment by Anvil5465** [comment]
the disable gpu flag fixes the issue on Fedora 39 workstation for me. Running the app natively in Wayland using the flags --ozone-platform=wayland --enable-features=WaylandWindowDecorations also appears to fix the issue for me.

**Comment by raksooo** [comment]
You could also try removing `~/.config/Mullvad VPN/GPUCache`.

**Comment by faern** [comment]
If this is indeed the GPU cache issue that we have hit (and fixed) in the past, then removing the cache should solve it. It should also automatically be a solved issues since all our app upgrades *from the next version* will make sure to clear the cache on upgrades.

I'll close this since we suspect it's this issue, which has already been fixed in https://github.com/mullvad/mullvadvpn-app/pull/5068
