### ISSUE TITLE
Split Tunneling not working for Private Networks outside local subnet

### ISSUE THREAD

**Issue by Wyattmin8or246** [mullvad/mullvadvpn-app#5622]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

My PC has a local IP address of 192.168.100.1 and can communicate with devices on the 192.168.100.0/24 subnet with no issue.
When reaching out to a different IP/subnet, such as 192.168.200.254, the connection fails. Once Mullvad is disabled, this works fine.
Local Network Sharing is already enabled and this does not make a difference.
![CurrentBehavior](https://github.com/mullvad/mullvadvpn-app/assets/25379299/564d3f66-c0a4-409a-ba27-7232b7d19578)

### Expected Behavior

Once Mullvad is disabled/disconnected, I am able to reach other private networks with no issues.
From my understanding of the Local Network Sharing description, shouldn't I be able to reach other private networks?
![ExpectedBehavior](https://github.com/mullvad/mullvadvpn-app/assets/25379299/400e4998-e304-46b1-9f18-5edc0333e826)
![LocalNetworkSharingDescription](https://github.com/mullvad/mullvadvpn-app/assets/25379299/e0da685f-77b5-414b-9e73-8169a766a1e3)

### Steps to Reproduce

1. Have Mullvad VPN disabled
2. Attempt to reach another local device outside of your local subnet (ex. anything 10.0.0.0/8 or 172.16.0.0/12 or 192.168.0.0/16) or reach any device that requires you to pass through the Default Gateway of your local subnet.
3. If response in step 2 is successful, enable Mullvad VPN with Local Network Sharing enabled.
4. Try the same connectivity test to that device and see if is is now reachable with the VPN running.

### Operating system version

Windows 11 Pro 22H2 (OS Build 22621.2861)

### Mullvad VPN app version

Reproducible in 2023.5 and 2023.6, unsure of earlier versions

**Comment by faern** [comment]
This works as expected. My guess is that you don't have any routes set up for your other LAN address spaces? See the discussion in this thread: https://github.com/mullvad/mullvadvpn-app/issues/3827. I'm going to close this as a duplicate.
