### ISSUE TITLE
[Feature request] Dynamic port forwarding with Qbittorrent support inside the app

### ISSUE THREAD

**Issue by BrutalCSEjziponken** [mullvad/mullvadvpn-app#5630]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Bring back port forwarding, but make it dynamic (so it uses a random port for each new connection or time based).

THEN build a feature inside the app that automatically updates the new port inside Qbittorrent and maybe other torrent clients via command line. I have seen this very exact thing in different VPN app, so it's 100% possible. I have a GitHub link to an app if someone wants it (not sure if I'm allowed to post it here since it's a fork of a competitors' app). 

This should work on both docker and Windows.

### Alternative solutions

No

### Type of feature

- [ ] Better privacy/anonymity
- [X] Better at circumventing censorship
- [X] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [X] Windows
- [ ] macOS
- [X] Linux

**Comment by faern** [comment]
Hi and thanks for the suggestion. However, having or not having port forwarding is a service level decision and not within the app team. Bringing port forwarding back is not going to be a decision made by the app team at all. I already know that ports won't come back, sorry. But just for the record: you better request such things to support@mullvad.net.

I understand it's technically possible to have port forwarding and various automation built into apps. It's not about that. It's about how to deliver such a service without having it abused in such a way that the service becomes worse for everyone.
