### ISSUE TITLE
[Feature request] Add  a vpn extension in the Mullvad Browser

### ISSUE THREAD

**Issue by easyicetrusty** [mullvad/mullvadvpn-app#5634]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

In the EU using a VPN for the entire system has become a real PAIN. 
Having the option to start the VPN via an extension in the Mullvad Browser (for ex) would be great. This would allow us to use a VPN connection only for certain websites. 
Using 'Split Tunneling' is definitely adding a layer of complexity.  A simpler approach as described above would be preferable to my opinion.  Split Tunneling and System wide proxy, its like oil and water. The idea is to have have Proxy + VPN in the Mullvad Browser and that would be ideal.  A little bit like Brave Browser is offering !! We would avoid installing the VPN App. 

### Alternative solutions

I remove the system wide proxy. 
Add the proxy in the Mullvad Browser
Use the Mullvad App for the VPN. 

### Type of feature

- [X] Better privacy/anonymity
- [X] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by faern** [comment]
It would be a huge effort to adapt our current app to not be a system wide VPN. It's built from the ground up to take control over system DNS, firewall, routing table etc.

What you want sounds like the functionality already existing in our [Mullvad browser plugin](https://mullvad.net/en/download/browser/extension), check it out!

1. Set up vanilla WireGuard with a [Mullvad config](https://mullvad.net/en/account/wireguard-config). This sets up a working WireGuard tunnel on your machine, but you can configure it to not absorb all traffic on your machine
2. Install our firefox extension
3. In the extension set a location and connect proxy. This will make the browser use a SOCKS5 endpoint in the tunnel and it will go through VPN.

However, the above is not in the realm of the app really. If you have further questions I suggest you contact support@mullvad.net.
