### ISSUE TITLE
XWayland is still called when run with Wayland

### ISSUE THREAD

**Issue by nokia8801** [mullvad/mullvadvpn-app#5671]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When running the app natively on Wayland, XWayland is still called as a process during launch and then the process immediately starts sleeping.

### Expected Behavior

XWayland should not be called or triggered as a process at all.

### Steps to Reproduce

1. Install [mullvad-vpn](https://aur.archlinux.org/packages/mullvad-vpn) from the AUR.
2. Run the application with `--ozone-platform=wayland --enable-features=WaylandWindowDecorations` or add the flags to the desktop file.
3. Keep an eye on your system monitor of choice and see the XWayland process pop up. Observe that the process immediately starts sleeping.
4. Confirm with xeyes that the app is natively running on Wayland anyways.

### Operating system version

Arch Linux

### Mullvad VPN app version

2023.6

### Additional Information

GNOME 45.3 on Wayland
Linux 6.6.10
[mullvad-vpn](https://aur.archlinux.org/packages/mullvad-vpn) from the AUR

**Comment by faern** [comment]
Thanks for reporting this. We have very little control over this as it's all in Electron. But I guess we can have a look at if it's possible to avoid. My guess is that this has to be escalated to Electron. Sadly they don't prioritize first class Wayland support very high.

**Comment by nokia8801** [comment]
Thanks for considering it. It could very well be an Electron issue. I can't tell because this is the only Electron app in my system. I like to keep my system as close to Wayland only as possible and I assume a VPN GUI would benefit from the security of Wayland.

Some other native Wayland apps also exhibit this behavior where the XWayland process is called during launch and then it starts sleeping immediately. Some of them have splash screens, which fixes the issue by disabling them. Does the GUI here have a splash screen that I'm perhaps missing cause I'm on GNOME? Although the ones without splash screens also have this problem. But the rest of the native Wayland apps don't have it, with or without splash screens. Just a select few apps where I'll probably make bug reports too.

**Comment by jm355** [comment]
I was able to fix it by editing `/usr/share/applications/mullvad-vpn.desktop` to add `--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --ozone-platform=wayland` to the exec line, like this

```
Exec="/opt/Mullvad VPN/mullvad-vpn" --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --ozone-platform=wayland %U
```

**Comment by nokia8801** [comment]
> I was able to fix it by editing `/usr/share/applications/mullvad-vpn.desktop` to add `--enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --ozone-platform=wayland` to the exec line, like this
> 
> ```
> Exec="/opt/Mullvad VPN/mullvad-vpn" --enable-features=WaylandWindowDecorations --ozone-platform-hint=auto --ozone-platform=wayland %U
> ```

Still calls XWayland for me.

**Comment by nokia8801** [comment]
I have just tested 2024.7 and 2024.8, and the `xwayland` and `mutter-x11-frames` processes are not called during launch anymore. I don't know if any other versions after 2023.6 also fixes the problem, but the latest version does not have it. Most likely something related to Electron upstream. So I'm closing this issue as fixed.

**Comment by MarkusPettersson98** [comment]
Thanks for letting us know! We've not kept that close of an eye on upstream Electron lately, but that is nice to hear :blush:
