### ISSUE TITLE
Account number leaks to clipboard history

### ISSUE THREAD

**Issue by uzantome** [mullvad/mullvadvpn-app#5675]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When going to "Account" and copying the Account number (using the copy button) the account number get saved in the clipboard history

### Expected Behavior

the account number should not get logged in the clipboard history (as with most password managers like for example KeepassXC)

### Steps to Reproduce

1. go to "Account" 
2. copy the Account number (using the copy button)
3. look at clipboard history (KDE)

### Operating system version

- Arch Linux x86_64
- Kernel 6.6.7
- Plasma 5.27.10 (Wayland)
- wl-clipboard 2.2.1

### Mullvad VPN app version

2023.6

**Comment by raksooo** [comment]
Hi, thanks for the suggestion! It would indeed be nice, but unfortunately the Electron APIs we use don't support this. There are probably other ways to accomplish this but it's unfortunately not high enough priority for us.
