### ISSUE TITLE
Create option to allow connecting to one's own servers in addition to Mullvad's 

### ISSUE THREAD

**Issue by baimafeima** [mullvad/mullvadvpn-app#569]
I run several servers (`OpenConnect`, `OpenVPN`, `Wireguard`, etc.) on a VPS at a fixed location. It would be amazing to be able to connect to them via `mullvadvpn-app` and to be able to throw them into a server mix/double hop or to even use them as standalone solutions in case access to the Mullvad network is blocked in regions heavily affected by censorship.

**Comment by pronebird** [comment]
@baimafeima Hi! You can set a custom relay via CLI. The app should handle that gracefully too.

**Comment by faern** [comment]
Please note that the app currently does not support wireguard. Even if the CLI slightly mentions it. It's also not possible to do multi hop or similar currently. But it should work to connect to a custom OpenVPN server as @pronebird points out!

**Comment by baimafeima** [comment]
@pronebird @faern Thank you both for the updates! Much appreciated! As I understand it currently doesn't work with Wireguard (but will be possible in the future?) and OpenConnect. Do you recommend to rather avoid using OpenConnect and thus, haven't implemented such an option? It would be great to have your evaluation regarding their state of crypto.
