### ISSUE TITLE
[Linux] I can't access Twitter or DeepL when I am connected to the Osaka server

### ISSUE THREAD

**Issue by elvis-hrvat** [mullvad/mullvadvpn-app#5706]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

On Linux, when connecting to the Osaka server, I am unable to resolve DNS for twitter.com and deepl.com.
In the Firefox developer console, it shows NS_BINDING_ABORTRD. the same issue occurs in Chromium.
This issue does not occur on Windows.
It also does not occur on servers other than the Osaka server.

### Expected Behavior

DNS resolution is successful.

### Steps to Reproduce

1. Enabling Multihop
2. Set the exit server to the Osaka server. The entry server can be anywhere.
3. Connect to a VPN
4. Open twitter.com or deepl.com in Firefox or Chromium.

### Operating system version

Arch Linux/Debian GNU/Linux 12

### Mullvad VPN app version

2023.6

### Additional Information

This problem reproduces on both Arch Linux and Debian GNU/Linux, but not on Windows.

**Comment by elvis-hrvat** [comment]
I previously emailed Mullvad support, but they did not offer a valid solution. The issue has existed for almost six months now.

**Comment by elvis-hrvat** [comment]
Very important addendum: The DNS servers in the Mullvad app are the default; I have disabled DoH in Firefox.

**Comment by faern** [comment]
I can't reproduce this. I can look up the domain `twitter.com` from all of `jp-osa-wg-001`, `jp-osa-wg-003` and `jp-osa-wg-004` on Fedora Linux. I can also visit both those domains in firefox.

Can you please try disabling multihop and connect directly to the affected server (please specify exactly which server you have issues with, not just the city). Also please perform a separate domain name lookup and provide the output: `dig @10.64.0.1 twitter.com` <- Run this and paste the output please. Try again without the `@10.64.0.1` part also.

**Comment by elvis-hrvat** [comment]
I just tried again and was able to open the Twitter pre-login page. However, I am unable to view the timeline (https://twitter.com/home) after login. Also, the site search (https://twitter.com/search?q=example) is not available.
I can't connect deepl at all.

> Can you please try disabling multihop and connect directly to the affected server (please specify exactly which server you have issues with, not just the city).

This issue is not reproduced when multihop is disabled.
This issue is reproduced on all Osaka servers.

---
`dig @10.64.0.1 twitter.com`
```
; <<>> DiG 9.18.21 <<>> @10.64.0.1 twitter.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 43136
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;twitter.com.			IN	A

;; ANSWER SECTION:
twitter.com.		297	IN	A	104.244.42.193

;; Query time: 103 msec
;; SERVER: 10.64.0.1#53(10.64.0.1) (UDP)
;; WHEN: Sun Feb 04 21:57:38 JST 2024
;; MSG SIZE  rcvd: 56
```
---
`dig twitter.com`
```
; <<>> DiG 9.18.21 <<>> twitter.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 4226
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;twitter.com.			IN	A

;; ANSWER SECTION:
twitter.com.		287	IN	A	104.244.42.193

;; Query time: 109 msec
;; SERVER: 10.64.0.1#53(10.64.0.1) (UDP)
;; WHEN: Sun Feb 04 21:57:48 JST 2024
;; MSG SIZE  rcvd: 56

```

**Comment by dlon** [comment]
@elvis-hrvat It the issue is related to fragmentation, it might help to switch to 2024.1-beta1. This is a guess, though. Can you please tell us whether it makes any difference, if you try it out?

**Comment by dlon** [comment]
Great! Thanks for confirming this.
