### ISSUE TITLE
Support `arm64`

### ISSUE THREAD

**Issue by kolya182** [mullvad/mullvadvpn-app#5716]
Trying to install mullvad on Ubuntu 22 running inside Parallel Desktop on M1 chip.

Unable to install `mullvad-vpn`. package architecture (`amd64`) does not matchsystem (`arm64`).
<img width="875" alt="Screenshot 2024-01-22 at 9 51 24 PM" src="https://github.com/mullvad/mullvadvpn-app/assets/3277207/f7dda83f-e7c5-46d8-bafb-d6946c4b8d0d">

### Operating system version

macOS Sonoma 14.2.1

### Mullvad VPN app version

2023.6

**Comment by faern** [comment]
Which package did you download/how did you install it?

**Comment by kolya182** [comment]
> https://mullvad.net/en/download/vpn/linux#arm
> 
> Just download from there

Thank, that helped. I just was need to scroll down to arm64 build.

**Comment by kolya182** [comment]
> Which package did you download/how did you install it?

I figured out there is a build of mullvad_vpn for arm54, but not for mullvad browser (`Works on all distributions (64 bit only)` is that correct ?

**Comment by faern** [comment]
Glad it saw as simple as downloading the package for the wrong architecture :)  I would recommend using our apt repositories to automatically get the architecture right (and automatic updates in the future!): https://mullvad.net/en/help/install-mullvad-app-linux?q=install+linux

> I figured out there is a build of mullvad_vpn for arm54, but not for mullvad browser (Works on all distributions (64 bit only) is that correct ?

The browser only has x86_64 builds, at least for now. Ping @ruihildt

**Comment by kolya182** [comment]
> Glad it saw as simple as downloading the package for the wrong architecture :) I would recommend using our apt repositories to automatically get the architecture right (and automatic updates in the future!): https://mullvad.net/en/help/install-mullvad-app-linux?q=install+linux
> 
> > I figured out there is a build of mullvad_vpn for arm54, but not for mullvad browser (Works on all distributions (64 bit only) is that correct ?
> 
> The browser only has x86_64 builds, at least for now. Ping @ruihildt

Thanks, best support as always.
@ruihildt 
![Screenshot 2024-01-23 at 1 48 11 PM](https://github.com/mullvad/mullvadvpn-app/assets/3277207/2d84d8d4-642e-4ac0-a09e-e798d1f4b698)

**Comment by ruihildt** [comment]
Thanks for the meme. :D

FYI, this is tracked in https://github.com/mullvad/mullvad-browser/issues/11
