### ISSUE TITLE
Failed To Start Mullvad Service - Error 5

### ISSUE THREAD

**Issue by CodeBlocksCreative** [mullvad/mullvadvpn-app#5719]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Around 75% into install a dialog says 'Failed to start mullvad service error 5' and the installation rolls back (Rollback does not succeed either and requires force quit) 

### Expected Behavior

Mullvad would install

### Steps to Reproduce

Start mullvad install on latest release. 

### Failure Logs

```shell
No logs available this way as install doesnt complete
```

### Operating system version

Windows 11 New Install 

### Mullvad VPN app version

2023.6 or 2024 beta

**Comment by raksooo** [comment]
Thanks for reporting! Unfortunately we can't do much without more information. Our support team has more experience of handling issues like this, please contact them at support@mullvad.net.
