### ISSUE TITLE
[Feature request] Global VPN services IP block concern

### ISSUE THREAD

**Issue by nyakojiru** [mullvad/mullvadvpn-app#5752]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Considering the current situation, not only Mullvad is getting most of the IPs banned from core internet services, and since Mullvad is constantly ahead of other services in privacy, are you guys planning something to counter this? 

### Alternative solutions

I was thinking, from my ignorance as a user, what if there is a pool of constantly new IPs to replace banned ones? Imran got rid of server IPs that have been focused on. I can't think in another solution and I think this is very critical for the future of privacy. 

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [X] Android
- [X] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by faern** [comment]
Thank you for the feedback. This is something we work constantly on in a number of different ways. However, it is not an app related question really, but rather an infrastructure/service related question. My short answer is: Yes, we work on this. But for further inquiries on the topic I suggest you contact support@mullvad.net
