### ISSUE TITLE
[Feature request] Add cli option to start in the system tray

### ISSUE THREAD

**Issue by jacekpoz** [mullvad/mullvadvpn-app#5753]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

It'd be great to have a cli option I could launch the gui client so that it actually doesn't launch the gui at first. Wanna have something like this in my compositor's config:
```
exec-once=mullvad-gui --system-tray
```

### Alternative solutions

Automatically putting the gui on another workspace on launch, later somehow moving it back onto the current one once the command is launched? This is the only thing I could think of.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by raksooo** [comment]
I don't understand what you're asking for. Do you want the app to start but the Window to not open? If that's the case then we already have a setting for it. You can find it in _Settings_ > _User interface settings_ > _Start minimized_.
<img width="325" alt="image" src="https://github.com/mullvad/mullvadvpn-app/assets/3668602/0b2474e2-f629-4f87-950e-02b3b44bde1d">

If you meant something else please try to explain it further, and explain what your use case is for this feature.

**Comment by jacekpoz** [comment]
ah, sorry for missing that! that should work, thank you

**Comment by Hasshu** [comment]
Apologies for the bump, but the latest beta builds seem to be missing the option to start minimized. That's on Fedora Linux 44 with GNOME 50.

<img width="398" height="683" alt="Image" src="https://github.com/user-attachments/assets/44197f1d-fcab-43b5-b026-e15dd7967bde" />
