### ISSUE TITLE
Latency with servers

### ISSUE THREAD

**Issue by artukrap** [mullvad/mullvadvpn-app#576]
It would be cool, to see latency with servers in the server list. So users would have the option to see which server better to pick, depending on their location.

**Comment by faern** [comment]
Latency to server is not the only metric when deciding which server suits you and your location/connection. Thus it could give a false indication. If you actually care about performance and are not happy with just selecting country/city, you are better off trying all servers manually anyway.

Also, pinging all servers would generate a lot of traffic outside the tunnel, and the app tries to stay as quiet as possible to prevent being easy to fingerprint/block/mess with.

We have considered the functionality you are proposing. But for the reasons outlined above we have decided to not implement it. At least for now.

**Comment by artukrap** [comment]
Thanks for detailed answer, then, for now, I will close this issue.
