### ISSUE TITLE
Add Quantum-Secure Tunnels for IOS

### ISSUE THREAD

**Issue by PaulCharlton** [mullvad/mullvadvpn-app#5800]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

the feature for quantum-secure tunnels is available on every platform but IOS.   This issue is a residual subset of issue #4932, and for the sake of separation of concerns, #4932 was compound for both Android and IOS, and should be closed in favor of this feature request as Android has already been implemented.

### Alternative solutions

It has been frustrating that most of my devices are IOS and can not make use of this feature yet

### Type of feature

- [X] Better privacy/anonymity
- [X] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [X] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by PaulCharlton** [comment]
I recommend closing #4932 in favor of this issue as being more specific in scope.

**Comment by PaulCharlton** [comment]
WIP at #5801

**Comment by agnosticlines** [comment]
Hey, is there any update on this? Love the work you're all doing and would love to use the PQ tunnels on my phone

**Comment by BionicBison05** [comment]
This is done now, is it not?

**Comment by MarkusPettersson98** [comment]
Post-Quantum secure tunnels are stable on iOS since [2024.4](https://github.com/mullvad/mullvadvpn-app/blob/main/ios/CHANGELOG.md#added-2) :tada:
