### ISSUE TITLE
Cannot compile for little-endian MIPS

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#5848]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I am trying to cross-compile the Mullvad app for devices with little-endian MIPS architecture (MT7621).
However, the build fails. Is this because the Mullvad app does not support MIPS? Or are my build options wrong?

- The build host is Arch Linux on amd64.
- Build target is mipsle (MT7621). The OS is GNU/Linux, not musl.
- The target option for `cargo` is `mipsel-unknown-linux-gnu`.
- The environment variable `GOARCH` specifies `mipsle`.
---
When I build libwg, it stops with the error `-buildmode=c-archive not supported on linux/mipsle` and `-buildmode=pie not supported on linux/mipsle`.
This is probably an upstream issue (golang/go#59561).

If it is possible to make it possible to build for MIPS by changing the compiler options appropriately, could you please tell me what options I should use?
If it is not possible to build for MIPS with the current Mullvad app, could you please add MIPS support?

I would like to run the Mullvad app on my router.

### Alternative solutions

none

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by raksooo** [comment]
Hi, thanks for reaching out! Unfortunately we don't support MIPS as you mentioned, and I don't think I've heard of anyone within the team trying this out. Closing since MIPS isn't a supported architecture.
