### ISSUE TITLE
[Feature request] Integrate IPinfo's IP to Country ASN data in Mullvad's IP location data.

### ISSUE THREAD

**Issue by abdullahdevrel** [mullvad/mullvadvpn-app#5976]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I would like to request the integration of [IPinfo's IP to Country ASN database](https://ipinfo.io/products/free-ip-database) into Mullvad's [IP location service](https://mullvad.net/en/check): https://mullvad.net/en/check.

Mullvad's IP geolocation data is based on a single provider. Mullvad has built its location on their free and reduced accuracy database. As the current database can often be inaccurate, this presents a critical point on customer reliability. If the current provides inaccurate location data, Mullvad will be presented with two choices. Address customer queries on support and forums or modify the underlying database with their data.

Considering that trust in data could be an issue, I recommend that Mullvad include IPinfo's IP to Country ASN database in their location services. The IPinfo IP to Country ASN database provides full accuracy, and daily updates and does not compromise accuracy. Moreover, the location methodology of the two providers is different. The existing provider uses public record-based location information, while IPinfo uses ping/network-based location data, which is usually more accurate.

The data is available for free and permits commercial usage via attribution (licensed under CC-BY-SA 4.0)

Documentation: https://ipinfo.io/developers/ip-to-country-asn-database

Integrating the database will help Mullvad cite a secondary source to refer to when discussing their server location. The database does not contain city-level information, but country-level information from a secondary database should help users feel reassured that the data is accurate.

![image](https://github.com/mullvad/mullvadvpn-app/assets/111275753/ad6708a3-9e99-4aa0-93cb-9bca539a24b5)

### Alternative solutions

One alternative to this problem is to visit IPinfo.io directly to verify the location information; however, this is not common knowledge to most users.

### Type of feature

- [X] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [X] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by raksooo** [comment]
Hi, thanks for the suggestions! This sounds like something that is better to direct at our support team since this isn't handled by the app itself. Please contact support@mullvadvpn.net.
