### ISSUE TITLE
[Feature request] Internet passthrough on whitelisted wireless networks

### ISSUE THREAD

**Issue by realies** [mullvad/mullvadvpn-app#5985]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Like the WARP app, add a feature to connect directly to the internet on trusted networks that may already be protected.

### Alternative solutions

No alternative solutions.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [X] Other

### Operating System

- [X] Android
- [X] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by raksooo** [comment]
This is a duplicate of https://github.com/mullvad/mullvadvpn-app/issues/1884.
