### ISSUE TITLE
[Feature request] Could you upload your PGP key to keys.openpgp.org?

### ISSUE THREAD

**Issue by elvis-hrvat** [mullvad/mullvadvpn-app#6016]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I would like you to upload the following two PGP keys to [keys.openpgp.org](https://keys.openpgp.org/).
- `8339C7D2942EB854E3F27CE5AEE9DECFD582E984`
- `8339C7D2942EB854E3F27CE5AEE9DECFD582E984`

keys.openpgp.org is a secure keyserver and is also used as the default keyserver for Thunderbird.

### Alternative solutions

none

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by faern** [comment]
You list the same key fingerprint twice. Was that intentional, or what other key did you have in mind?

Also, that is @dlon's code signing key. What use do you have for that in Thunderbird?

But yes, we can get better at uploading our code signing keys to public key servers. But it would be interesting to understand your use case.

**Comment by faern** [comment]
Our code signing key, signing our artifacts are published already:

* https://keys.openpgp.org/search?q=A1198702FC3E0A09A9AE5B75D5A1D4F266DE8DDF
* https://keyserver.ubuntu.com/pks/lookup?search=A1198702FC3E0A09A9AE5B75D5A1D4F266DE8DDF&fingerprint=on&op=index

Individual developer code signing keys, not so much. But you can find all of them here: https://github.com/mullvad/mullvadvpn-app/tree/main/ci/keys

I'm going to close this as it is unclear to me what the point/desired outcome is.
