### ISSUE TITLE
Mullvad 2024.1 on Linux  is very slow if set to use Wireguard

### ISSUE THREAD

**Issue by tajelp** [mullvad/mullvadvpn-app#6017]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

I don't know why and I don't know what info I could provide but the connection is very slow with Wireguard and it used to be good with past releases. Just to let you understand how slow it is, it shows ~12hrs to do an `apt update`. Then I switched to OpenVPN and it worked in ~30 seconds, as expected.

Some info:
app version: `2024.1`

```
$ uname -a
Linux PC 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

VPN settings enabled:
- auto-connect
- local network sharing
- dns content blockers (ads, trackers, malware, gambling)
- kill switch
- lockdown mode
- api access (all on)

### Expected Behavior

Normal connection without slowdowns

### Steps to Reproduce

1. Set Wireguard as connection type
2. Connect with all the settings described above

### Mullvad VPN app version

2024.1

### Additional Information
[24bc4695-6c38-4d6d-84c1-9d9129f21177.log](https://github.com/mullvad/mullvadvpn-app/files/14742251/24bc4695-6c38-4d6d-84c1-9d9129f21177.log)

**Comment by raksooo** [comment]
Hi, unfortunately I can't reproduce this. This could be due to a lot of different reasons. Please contact our support team and they will help you to figure the issue out, support@mullvadvpn.net.

**Comment by TJonCooper** [comment]
I'm also struggling with WireGuard on 2024.1 (Ubuntu 22.04.3 LTS - same kernel as the OP) both in terms of connection speed but also how long it takes to establish a VPN connection to begin with. However it's specific to the quantum-resistant tunnel for me. @tajelp if you switch off quantum resistance, do you still see the same issue?

**Comment by avoo6** [comment]
Same issue here. Slowed connection speed and establishment time on Fedora 37. When Mullvad is downgraded to 2023.6 the issue goes away. The issue exists on both 2024.1 and 2024.2. The connection speed becomes so slow that it is unusable. Quantum resistance and wireguard both on.
