### ISSUE TITLE
how do i undo this command

### ISSUE THREAD

**Issue by Tropical-Smootie** [mullvad/mullvadvpn-app#6031]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mullvad.list

### Expected Behavior

i saw it from one of the guides to install the app on linux but whenever i try to run apt update i get an error and i can never run apt update again

### Steps to Reproduce

how do i undo this command?

### Failure Logs

```shell
you guys should have added on the guide how to undo the the changes made to apt.list when that command doesnt work
```

### Operating system version

linux 

### Mullvad VPN app version

newest

**Comment by raksooo** [comment]
Hi, thanks for the feedback! Yes it would definitely be a good idea to mention how to remove the repository in the guides. Here is one way to remove the repository:
```
# rm /etc/apt/sources.list.d/mullvad.list
```

**Comment by raksooo** [comment]
We also have some troubleshooting instructions in the installation guide that might help you fix the initial issue: https://mullvad.net/en/help/install-mullvad-app-linux
