### ISSUE TITLE
Mullvad's problem is not their app.

### ISSUE THREAD

**Issue by dosenfleisch** [mullvad/mullvadvpn-app#609]
In all the world, there isn't a gui availabe for Linux VPN use that approaches the expert, reliable and simple approach Mullvad has brought to VPN users.  Their "I don't want to know who you are" approach to satisfying a market for VPN users brings with it a big problem.  Most users would need to use a credit card.  The rest send cash, use bitcoin or whatever.  The problem with this, Mullvad decides willy nilly whether they will accept a credit payment based on nothing whatsoever.  Try the service out for a few hours for free.  Decide to try it for a month, and pay them the five euros via credit card.  Then try another six months worth and everything goes well, you try to pay for a year's service.  At this point they suddenly flip out and throw your account into a "bad boy" category in which you don't know if you will have a VPN service or not at the end of the period you've already paid for.

A clear case of scientists and accountants running a company into the ground.

**Comment by pronebird** [comment]
Hi,

I am not sure what exactly went wrong but the it would be the best if you could contact support@mullvad.net if you had some billing issue.

**Comment by dosenfleisch** [comment]
The objective is not to build up a sentiment, but to warn, if not bring some Mullvad folks to their senses.  What happened is exactly as I explained it.  Without specifying any reservations as to amounts or frequency of transactions, Mullvad's folks decide as the spirit moves them, whether they will accept a transaction or not.  Neither my credit card nor my VPN use was an issue.  Their response to my objections, since I know how to run a business better than they do, was to refund my money.  If you can't get them to accept a credit card transaction, why would anyone trust them with any other payment option?   It's a shame.  Their gui and the speed of their servers is truly exceptional.  If their gui is truly open source and available to everyone, all these vpn outfits using a cli interface ought to take full advantage.

**Comment by pronebird** [comment]
I am afraid I have to close this issue because it has nothing to do with the software itself.
