### ISSUE TITLE
Untranslated text in Android app version 2024.1

### ISSUE THREAD

**Issue by FID02** [mullvad/mullvadvpn-app#6121]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

The Mullvad Android app version 2024.1 is missing translations for new texts. Affects Norwegian, Swedish and Danish.
![Screenshot_20240414-141658](https://github.com/mullvad/mullvadvpn-app/assets/99329251/ce01733b-9c5d-4986-a562-ceaa574c1921)
![Screenshot_20240414-141616](https://github.com/mullvad/mullvadvpn-app/assets/99329251/087226f6-b982-4d35-a196-a2edb88d00e5)

### Expected Behavior

Translated text. 

### Steps to Reproduce

Open the app and navigate to the screens shown in the screenshots.

### Android version

14 QPR2 April patch

### Device model

Pixel 8

### Mullvad VPN app version

2024.1

**Comment by albin-mullvad** [comment]
Hey, thanks for reporting! Sometimes this is the case due to our translation cycle that's shared with our desktop app. We'll have a look at these for the upcoming release.

**Comment by albin-mullvad** [comment]
This should be fixed in #6180 which we'll backport to the release branch for `android/2024.2`
