### ISSUE TITLE
Feature Request - Multi-Hop in the Client

### ISSUE THREAD

**Issue by HJLBX** [mullvad/mullvadvpn-app#615]
Multi-hop functionality directly in the Mullvad client app as opposed to the current requirement to manually configure and use a bridge\WireGuard and maintain using the CLI.

The current configuration required to enable multi-hop is over the head of typical users.

This is another play right out of the IVPN client. However, I will be honest with you... while it is nice to have convenient access to multi-hop, very few users would have any practical need for it. Actually, it can slow things down to the point where one doesn't use it.

**Comment by faern** [comment]
This is a planned feature. But we will implement plain single-hop wireguard first so it will take a while. Will close this since it's already on our internal roadmap.

**Comment by fwanky** [comment]
Just wondering if this is actually being developed upon? Would really love it inside of the client.

**Comment by faern** [comment]
You can multi hop with this client app in the latest release. Just use a bridge and that will result in multi hop. You currently can't select bridge location in a simple way, but that is being worked on. This is currently only over OpenVPN.
