### ISSUE TITLE
[Feature Request] machine readable status return from cli

### ISSUE THREAD

**Issue by TimoKramer** [mullvad/mullvadvpn-app#617]
Hi there,

thanks for the new client. I personally prefer to only use the cli and would like to have a status icon in my xfce-gui by calling the mullvad api like `mullvad status`. This works, but I'd prefer a return code to use it in a script. I imagine the usage like so:
```
$> mullvad status
Tunnel status: Connected
Relay: de8
Location: Berlin, Germany
Position: 52.52001°N, 13.40495°W
$> mullvad status quiet; echo $?
$> 0
$> mullvad disconnect
$> mullvad status quiet; echo $?
$> 1
```
I am happy to participate in solving this issue if you think this is a feature you want to have.

Thanks and regards!

**Comment by faern** [comment]
Exiting with a non-zero exit code means there was an error. And being disconnected is not an error, it's just a state. You could get the same result by piping `mullvad status` into `grep "Tunnel status: Connected"` basically.

**Comment by TimoKramer** [comment]
you are right. That's possible as well. I thought it might be a good option.

**Comment by TimoKramer** [comment]
Hi, sorry for reopening. I am usually using this to resolve current status:
`mullvad status 2> /dev/null | head -n 1 | awk '{ print $3}'`
which I expect to return Connected, Disconnected (or sometimes Connecting). But when I am not connected it never returns from the script. I guess it does not return from the position resolution. It would be very good to have a switch not to resolve the position because it seems overengineered for me at this point for this task.

**Comment by faern** [comment]
I'm fixing this in #1091. There I remove the location lookup in `mullvad status` and hide it behind an optional flag, `--location`.

**Comment by TimoKramer** [comment]
thanks!
