### ISSUE TITLE
Firefox/Brave detecting Windows 2024.2 installer as virus/malware

### ISSUE THREAD

**Issue by staffa** [mullvad/mullvadvpn-app#6238]
## Is it a bug?

  [x] I know this is an issue with the app, and contacting Mullvad support is not relevant.

## I have checked if others have reported this already

  [x] I have checked the issue tracker to see if others have reported similar issues.

## Current Behavior

Firefox (125.0.3 64-bit) & Brave (1.65.130, Chromium 124.0.6367.159 Official 64-bit) warn about virus/malware, prompting removal/acceptance on Firefox, block on Brave.
Expected Behavior

No detection, key signing valid.
Steps to Reproduce

    Open Firefox or Brave on Windows 10
    click "Download" on mullvad VPN's download page
    Allow download to complete

## Failure Logs

No response

## Operating system version

Windows 10 22H2

## Mullvad VPN app version

2024.1

## Additional Information

Key signing is valid. No warnings on DuckDuckGo/Edge, no interference from Windows. Windows and malwarebytes scan is fine. Virtus total reports fine but it seems that 2 of the internal files are being flagged by "Jiangmin" as HackTool.ProxyFuse.a ([View under relations](https://www.virustotal.com/gui/file/d17b57268c3776c9e72dc5d1cb56d1eaf5e07003270c4b696b53ba70a8668bf6/relations)). I am unsure if that has anything to do with the browser's flagging it at all. Jiangmin seems to be known for false-positives, so I don't know why major Browsers would 'listen' to it. Other installer .exe files from other sites seem to download just fine as normal.

I've tried it on two computers with same result, regardless of mullvad running.

I've tried it on two computers with same result, regardless of mullvad running. If there's a log somewhere that would be helpful for me to provide, it would be helpful to me if someone explained how to get it :)

I know this is technically not a mullvad app issue, but I thought I would post here just in case there is something in most recent release build that might be related.

**Comment by raksooo** [comment]
Hi, thank you for reporting this and for researching it. We've noticed this as well and are currently looking into fixing it.

**Comment by faern** [comment]
@staffa Sorry for messing with your report. Our linear bot is to blame. I tried restoring your issue content again.

We have reached out to relevant parties and reported this as false positives. We hope the warning will go away soon. If you trust our installer to be safe, feel free to do the same.

**Comment by Joesv** [comment]
For what it's worth: it does not give a malware warning for me anymore as of now on Firefox 125.0.3.

**Comment by staffa** [comment]
@raksooo @faern Indeed, as Joesv reports, it is now downloading as normal through Firefox, and I can report, Brave too :)

I'm not sure why it occurred in the first place, but if anyone has any insight on that, I'd be very interested! 

Anyway, closing. Good work, everyone!

**Comment by faern** [comment]
We detected late last night that the API both browsers use to detect this type of stuff marked the file as clean again. It's probably just an aggregation of a bunch of bad-content-scanners and a few of them might have had a false positive on these files for some reason :shrug: We reported it upstream and it seems to have helped.
