### ISSUE TITLE
Auto-Connect on App start breaks internet when out of time

### ISSUE THREAD

**Issue by duke1102** [mullvad/mullvadvpn-app#624]
Hello!

Just now I ran into a problem when I started the Mullvad app and my account subscription ran out of time. Since the app tries to autoconnect after starting it, it broke the internet connection. Only quitting the app fixed the issue.  

I feel like this needs to get changed and the app should check if there's still an active subscription for the specified account, before trying to connect.

**Comment by faern** [comment]
Which version of the app are you using?

If you are using a recent version it should detect that you are out of time when it tries to establish a tunnel. Then it should end up in the "blocked" state and show a message to you that you have run out of time. Then it's up to you as a user to click "disconnect" if you want to unblock your internet connection.

Either you are using an older version, or this feature has a bug in it.

**Comment by haslam22** [comment]
This issue still exists in the latest version (2018.6).

I just installed the application and logged in to my account. It gives me the "out of time" message and so I go back to the website to buy more time. Unfortunately the app has blocked my internet connection so I can't access anything. I go into the preferences section and there is no option to "unblock" or "disconnect" and keep the app open. Going back to the main page of the app, the only option present there is to quit the application completely.

**Comment by faern** [comment]
If you quit the app it should unlock the normal, unencrypted internet on your computer. Then you should be able to visit our website to buy more time. The next time you start the app it should detect there is now time on the account.

**Comment by faern** [comment]
The UX of this has been improved in the latest beta release now, 2019.2-beta1. There the "out of time" screen will include a button to unblock the internet before bringing the user to the website where they can buy more time.

Closing this. Please open again if this is still a problem. And describe what you are trying to do but can't.
