### ISSUE TITLE
MullvadVPN-2024.3-beta1 raises error with Norton, app is fully blocked from changing servers (Location)

### ISSUE THREAD

**Issue by narration-sd** [mullvad/mullvadvpn-app#6245]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

A hard block to changing Location, even after full reboot, first and every time tried with this Beta. 

I'm attaching a screenshot of what Norton reports. Reverting to current 2024.2, no problems of this kind.

Two more Norton alerts occurred during deinstallation of this Beta, prior to installing current. Didn't check if they were the same cause, though presume so. You need to improve your testing to iinclude Norton, certainly....

![Screenshot 2024-05-11 215920](https://github.com/mullvad/mullvadvpn-app/assets/247945/a60cf094-9a01-4e63-998b-20fa7c7143ca)

### Expected Behavior

Should just work to change Location.

### Steps to Reproduce

1. install the beta
2. try to change Location from whatever it was before

### Failure Logs

```shell
I checked the logs, intending to send them, but de-install Beta apparently cleared them, so there are only logs from fresh re-installed 2024.2. This was a very hard fail, so you should be able to see it as soon as you test with Norton latest.
```

### Operating system version

Windows 11 latest, all updates

### Mullvad VPN app version

2024.3-beta1

**Comment by raksooo** [comment]
Thank you for reporting this. I'm not sure why you're getting this warning. Please try 2024.3 stable that was released a few hours ago and see if it works better.

**Comment by gsture** [comment]
Easy fix: Don't use Norton, it is useless resource hogging application with no real benefits. In contrary to what these company's like Norton and McAfee want you to believe the included windows defender antivirus is really good in protecting your pc without slowing things down or giving you strange issues like this.
