### ISSUE TITLE
[Feature request] Could you upload your PGP key to keys.openpgp.org?

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#6259]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Reopening of #6016 .
I am installing the Mullvad app on Arch Linux using paru.
And I have listed `keyserver hkps://keys.openpgp.org` in `gpg.conf`.
In this environment, could you please upload the PGP key so that we can get the PGP key automatically?

### Alternative solutions

none

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by 5p4r74cu5** [comment]
I second this; I am currently using IVPN on Arch linux because it has an official AUR build, but theres servers suck, and I want to migrate to Mullvad, a little more support regarding Arch would tip alot users like me over to adopting Mullvad.

**Comment by MarkusPettersson98** [comment]
Hello! It seems like this is resolved since https://github.com/mullvad/mullvadvpn-app/issues/6016#issuecomment-2044429471, or am I missing something? Please let me know if you think otherwise :blush:
