### ISSUE TITLE
[Feature request] Pin package list of RPM repo

### ISSUE THREAD

**Issue by SkewedZeppelin** [mullvad/mullvadvpn-app#6270]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

RPM supports limiting what packages a repository is allowed to handle via the `includepkgs` directive.

mullvad.repo should contain this line:
```
includepkgs=mullvad-vpn
```

This prevents any other packages being chosen from the repo if they were to exist.

### Alternative solutions

n/a

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by MarkusPettersson98** [comment]
Thanks a lot for this suggestion @SkewedZeppelin, it will be included in an upcoming release! 💛
