### ISSUE TITLE
Can't update to 2024.3 on focal

### ISSUE THREAD

**Issue by louispotok** [mullvad/mullvadvpn-app#6288]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

I am trying to update Mullvad from 2024.2 to 2024.3 on Ubuntu 20.04, but `sudo apt update` errors with:

```
E: The repository 'https://repository.mullvad.net/deb/stable focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

My sources list looks correct:
```
$ cat /etc/apt/sources.list.d/mullvad.list
deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=amd64] https://repository.mullvad.net/deb/stable focal main
```

I do notice that `focal` is not listed in the `deb/stable/conf/distributions` file or in `deb/stable/dists/`, but from the code in [buildserver-config.sh](https://github.com/mullvad/mullvadvpn-app/blob/9aea68de23c03ae4a0dadef407760031c108ebb7/ci/buildserver-config.sh#L12) it looks like `focal` should still be supported. 

### Expected Behavior

`sudo apt update` finds version 2024.3 for `focal`.

### Steps to Reproduce

1. Using Ubuntu 20.04, follow the installation instructions at https://mullvad.net/en/download/vpn/linux

### Operating system version

Ubuntu 20.04

**Comment by aruku7230** [comment]
Same problem on Ubuntu 20.04.

**Comment by joyofdata** [comment]
Also just ran into a similar/related problem on Linux Mint 21.3 trying to install the application.
```
E: The repository 'https://repository.mullvad.net/deb/stable virginia Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by joyofdata** [comment]
I guess replacing the Linux Mint 21.3 name `virginia` with the name of the underlying Ubuntu version 22.04 `jammy` will do the trick. But `jammy` was also missing last week.
