### ISSUE TITLE
VPN Disconnect Notification

### ISSUE THREAD

**Issue by gsture** [mullvad/mullvadvpn-app#6292]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior
The os randomly says "disconnected from always on VPN" and start blocking connections because the os thinks there is no vpn active. The mullvad app notification still says the vpn is connected. This happens randomly with the vpn in the work profile but then the main profile still works fine or vice versa. If i press the notification / open the mullvad vpn app the vpn seems to reconnect and the notification goes away. 

![VPN_disconnects](https://github.com/mullvad/mullvadvpn-app/assets/31156691/1fe9365c-b13e-438f-adfd-adabc4fe572d)

### Expected Behavior
The vpn should stay connected or reconnect when it's disconnected. It's now like the app is not aware that the vpn is disconnected or the os just thinks the vpn is disconnected while it's not.

### Steps to Reproduce
1. Install mullvad vpn app in main profile and in work profile.
2. When the vpn disconnects abruptly the mullvad app is not aware and won't automatically reconnect.   The os displays "disconnect from always on VPN notification". 

### Android version
Grapheneos 14 (AP1A.240505.005)

### Device model
Pixel 8 and 8a

### Mullvad VPN app version
2024.1/2024.2 beta

### Additional Information
I also reported this to grapheneos but they say it's not an os bug. They say it could be a network error but in case of a network error the vpn should reconnect.

**Comment by MrChocolatine** [comment]
I also use GrapheneOS, but with a Pixel 6a.

I have never had this issue, however I do not use the "work profile" but instead I have many "user profiles".
Maybe that's the cause of your issue? Have you tried with a profile different than the "Owner profile"?

**Comment by gsture** [comment]
> I also use GrapheneOS, but with a Pixel 6a.
> 
> I have never had this issue, however I do not use the "work profile" but instead I have many "user profiles". Maybe that's the cause of your issue? Have you tried with a profile different than the "Owner profile"?

I also never had this issue in the past 3 years on my pixel 5 with the same setup. But now i switched to pixel 8 and also tested this on 8a and with these devices this issue popped up. I am not interested in different user profiles.
