### ISSUE TITLE
Cannot connect to Mullvad using Ubuntu 24.04

### ISSUE THREAD

**Issue by alessandromrc** [mullvad/mullvadvpn-app#6325]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

The app doesn't let me connect to any server provided.

![image](https://github.com/mullvad/mullvadvpn-app/assets/66976091/4535e6b5-66a5-4bb2-a330-4f8bbc29e5b0)

### Expected Behavior

I would think that the app connects me to the server but instead, it just gives me an error.

### Steps to Reproduce

1. Install Mullvad
2. Open Mullvad / Login
3. Try to connect to any server

### Operating system version

Ubuntu 24.04 LTS

### Mullvad VPN app version

2024.3

**Comment by repsorp** [comment]
Hi,
same config here (Ubuntu 24.04, Mullvad 2024.03) and everything works fine

Did you try to uninstall/purge/reinstall Mullvad app ?
`sudo apt purge mullvad-vpn`
https://mullvad.net/en/help/install-mullvad-app-linux

Did you check your VPN settings (auto-connect, kill switch, lockdown mode, Tunnel protocol) ?

**Comment by alessandromrc** [comment]
> Hi, same config here (Ubuntu 24.04, Mullvad 2024.03) and everything works fine
> 
> Did you try to uninstall/purge/reinstall Mullvad app ? `sudo apt purge mullvad-vpn` https://mullvad.net/en/help/install-mullvad-app-linux
> 
> Did you check your VPN settings (auto-connect, kill switch, lockdown mode, Tunnel protocol) ?

Hi,
I've just tried to reinstall Mullvad but nothing has changed, the configuration is the default one...

- Auto-Connect -> Disabled
- Kill Switch  -> Enabled (That cannot be disabled)
- Lockdown Mode -> Disabled
- Tunnel protocol -> Either OpenVPN or Wireguard doesn't work at all.

The problem relies on how Mullvad prevents traffic from leaking using nftables but for some reason, it is not able to do so.

**Comment by repsorp** [comment]
Have you tried contacting them directly from the app ?

**Comment by alessandromrc** [comment]
> Have you tried contacting them directly from the app ?

No, I haven't but I can surely do that.

**Comment by alessandromrc** [comment]
I confirm that the issue is not Ubuntu 24.04 but the broken installation I had of it, everything on Debian is working just fine.
