### ISSUE TITLE
Cant Install VPN

### ISSUE THREAD

**Issue by DiscordDanny** [mullvad/mullvadvpn-app#6440]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

So everytime I try to download, it starts downloading but after quickly opening the downloaded file It tells me that It failed to close and I need to close it manually and retry, I did that and nothing. Same error message, I already tried installing from github and the website but nada. I am downloading the one up to date also, and nada. I'm getting frustrated as I just paid for it and am having issues off the jump.

### Expected Behavior

For it to download?

### Steps to Reproduce

1. ...Download vpn
2. ... Open it.

### Mullvad VPN app version

2024.3

**Comment by DiscordDanny** [comment]
uhhh so yeah idk if i put this in the right place but, Its here. That's my issue

**Comment by Joris914** [comment]
I get this as well, but only when I'm trying to install a newer version. I have to manually uninstall the old version through control panel for the installer to work. Have you checked if you maybe have a botched installation somewhere on your system that you could uninstall?

**Comment by hulthe** [comment]
Hi @DiscordDanny, sorry for the late reply. This sounds like an issue that would be better suited for our support team, as they deal with these sorts of issues all the time: [support@mullvadvpn.net](mailto:support@mullvadvpn.net)

**Comment by hulthe** [comment]
@Joris914 Do you always have issue when installing newer versions of the app?

**Comment by Joris914** [comment]
@hulthe Well, I've only been a customer for a few months, but for the 2 updates during that time I had it both times yes.

**Comment by hulthe** [comment]
@Joris914 If you feel like it, we would appreciate it if you [sent us a bug report](https://mullvad.net/en/help/using-mullvad-vpn-app#support) through the app if it happens to you again. Note that, after failing to update to a newer version, you should open the _old_ version and send the report. That way we should receive all the relevant log files for the failed update attempt.

(Sorry Danny for hijacking your issue, gonna close this now, but feel free to re-open if you find more information about your issue)
