### ISSUE TITLE
Cannot use kill switch and split tunneling together

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [mullvad/mullvadvpn-app#6456]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When Block Connections Without VPN is enabled, the apps selected for split tunneling will not be able to connect to the Internet.

### Expected Behavior

When Block Connections Without VPN is enabled, the apps selected for split tunneling will connect to the Internet without going through the Mullvad server.

### Steps to Reproduce

1. Set any one app as the target of split tunneling
2. Enable Block Connections Without VPN in the Mullvad app from the Android VPN settings

### Android version

14, Stock

### Device model

Pixel 7 Pro

### Mullvad VPN app version

2024.3

### Additional Information

Google VPN works with split tunneling even with Block Connections Without VPN enabled. Therefore, we suspect that this is not an Android specification, but a bug in Mullvad.

**Comment by Pururun** [comment]
I am not sure what Google VPN does to circumvent this, but as far as we know this is a limitation of the VPN implementation on Android.

**Comment by MrChocolatine** [comment]
I feel like I have the exact same issue that I described here:
https://github.com/mullvad/mullvadvpn-app/issues/2877#issuecomment-2408586576

**Comment by albin-mullvad** [comment]
Closing since this is an OS limitation. If anyone can share documentation or other apps than the built-in Google VPN that can achieve this we're happy to re-open the issue.
