### ISSUE TITLE
Api.mullvad.net is blocked, please check your firewal - Fixed

### ISSUE THREAD

**Issue by VladNoToxic** [mullvad/mullvadvpn-app#6462]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Api.mullvad.net is blocked, please check your firewal can be fixed very easily - Russian 

### Alternative solutions

You buy a Canadian proxy, go into the gear.
-Access API -> Add API -> choose remote sooks5 type -> add your proxy and you're done!

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [ ] iOS
- [X] Windows
- [ ] macOS
- [ ] Linux

**Comment by VladNoToxic** [comment]
You're welcome.

**Comment by MarkusPettersson98** [comment]
What exactly is the feature request here? :blush:
