### ISSUE TITLE
Not working on snapdragon x elite

### ISSUE THREAD

**Issue by matotubol** [mullvad/mullvadvpn-app#6466]
### Is it a bug?

- [x] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

when opening the app it says cant connect to the mullvad services

### Expected Behavior

succesuflly launch the app

### Steps to Reproduce

1: open the app
2: get the error

### Operating system version

Windows 11 arm64

### Mullvad VPN app version

2024.3

**Comment by bakahk** [comment]
I have an identical case: the installation runs without any problems, but after starting the application I receive a message that the connection is not possible. Lenovo YOGA Slim 7x Gen 9 14Q8X0 (BIOS: NHCN44WW) Windows 11 ARM (26100.1150) + Windows Update 100%.

**Comment by gdickens** [comment]
Just flagging I faced the same problem in Windows 11 with the Snapdragon X Plus. 

Mullvad installs fine, but it won't connect after entering my credentials. 

I assume it's because it's not currently compatible with the emulation layer on ARM machines.

**Comment by dlon** [comment]
Closing: This is tracked by issue #6102.
