### ISSUE TITLE
Split tunneling doesn't seem to work with qbittorrent

### ISSUE THREAD

**Issue by parthokr** [mullvad/mullvadvpn-app#6534]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Adding [qbittorrent](https://github.com/qbittorrent/qBittorrent) into the split tunnel list doesn't exclude qbittorrent from using Mullvad. Qbittorrent only works when Mullvad is disconnected.

### Expected Behavior

With Mullvad in the connected state, qbittorrent should work provided it is in the split tunnel list.

### Steps to Reproduce

1. Add qbittorrent in split tunnel list of Mullvad MacOS app.
2. Connect to any server via Mullvad.
3. Check tracker status from qbittorrent.

### Operating system version

macOS 15.0

### Mullvad VPN app version

2024.4

**Comment by n1ghthouse** [comment]
Is there any fix for this, what was the solution or if any update that fixed this bug?
