### ISSUE TITLE
Wifi only works when Mullvad is enabled

### ISSUE THREAD

**Issue by IgorGee** [mullvad/mullvadvpn-app#654]
[OS] Windows 10 Home 64 bit  Build 17134

Issue: I cannot access the internet when Mullvad is disconnected.

Attempts at Resolution:
* Quitting mullvad
* Removing Mullvad processes in Task Manager

**Comment by faern** [comment]
For general help with using the app, please contact support@mullvad.net.

For this type of problem I guess they will ask you to go in and set your DNS to automatic. For some Windows computers we fail to restore DNS on disconnect. If that does not help, please contact support. Preferably by sending a problem report from the app so they have some logs that can help them find the problem your are having. Thank you.
