### ISSUE TITLE
Stable builds not pushed to beta RPM repo

### ISSUE THREAD

**Issue by pointydev** [mullvad/mullvadvpn-app#6548]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Unable to upgrade to 2024.4 on Fedora when using the beta RPM repo. This also means the app always shows that it is out of date in the GUI.

### Expected Behavior

To ability to update to the latest stable build when using the beta RPM repo, as was previous behaviour.

### Steps to Reproduce

*(assuming the beta RPM repo is already active and an older version of the app is installed)*
1. `sudo dnf upgrade --refresh mullvad-vpn`

### Operating system version

Fedora 40

### Mullvad VPN app version

2024.4-beta1

### Additional Information

#5562 part 2, electric boogaloo. However, this time I can see the the stable repo has been updated, but the beta repo has not:

![stable](https://github.com/user-attachments/assets/66dbc0dc-2df8-4aa9-a76c-4564a90634cc)
![beta](https://github.com/user-attachments/assets/51a1d6f9-a4a9-4cef-a95b-d7fb284c1189)

> [!NOTE]
> Sidenote, while reviewing the [installation documentation](https://mullvad.net/en/help/install-mullvad-app-linux#fedora), I noticed that one of the instructions is to use `sudo dnf update --refresh` to force an update, despite `upgrade` being used in the sentence before. While `update` is an alias, it'd be nice for them to be consistent. Furthermore, specifying `mullvad-vpn` as the package to be upgraded (as above) may also be good to add to both.

Thanks,
Elliott

**Comment by pointydev** [comment]
While this issue is no longer present due to a newer beta being available, I personally don't want to close this until I see a proper fix implemented (preferably not just "we'll remember").

**Comment by MarkusPettersson98** [comment]
Hi everyone, this should be fixed by https://github.com/mullvad/mullvadvpn-app/pull/6737. I'll close this issue for now, but feel free to reopen if the issue should persist. Thanks for reporting :yellow_heart:

Also @pointydev, I've notified the website team about the inconsistent use of `dnf upgrade` and `dnf update` in the installation documentation :smile:
