### ISSUE TITLE
[Feature request] Selecting the `Entry` and `Exit` list of servers should focus their search input

### ISSUE THREAD

**Issue by MrChocolatine** [mullvad/mullvadvpn-app#6554]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

When selecting the `Entry` and `Exit` list of servers, their search input should be automatically focused.
This would provide a better user experience and a faster search.

### Alternative solutions

None.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [ ] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by Serock3** [comment]
Again, good feedback. It's added to our internal tracker.

**Comment by faern** [comment]
Thank you for a nice improvement suggestion. However, we are going to re-work large parts of the location selection UI, so we will not prioritize doing smaller edits like this for now. Hopefully the new UI, whenever released, will work well for you :)

**Comment by MrChocolatine** [comment]
I know I was told the UI is going to be re-worked, but I could not help myself and wanted to give it a shot, to satisfy my constant curiosity:

https://github.com/mullvad/mullvadvpn-app/pull/6832
