### ISSUE TITLE
Split tunneled apps should retain the system's dns settings

### ISSUE THREAD

**Issue by th3m** [mullvad/mullvadvpn-app#6586]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

A split tunneled app keeps the system's IP but not the dns. Mullvad's app dns settings are used instead.

### Expected Behavior

Expecting when split tunneling an app to retain the dns settings for the app and not use the ones that are set up on mullvad-app.

### Steps to Reproduce

1. Check the dns server on a browser app while securedns settings are off
2. Connect to mullvadvpn while the browser app is split tunneled
3. Check the dns server on the browser app, it is changed to the values set of the mullvadapp

### Operating system version

Windows 11

### Mullvad VPN app version

2024.4

**Comment by Serock3** [comment]
This is known limitation unfortunately and we don't have any plans to address it at the moment. All DNS lookups are made through the same system service which makes it non-trivial to split. You can read more about it here <https://github.com/mullvad/mullvadvpn-app/blob/main/docs/split-tunneling.md>.
