### ISSUE TITLE
[macOS] Unable to toggle "full disk access" for split tunnelling

### ISSUE THREAD

**Issue by FIying-Scotsman** [mullvad/mullvadvpn-app#6606]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

"Full disk access" is requested to allow Split Tunnelling to work but it puts me in a "Mullvad will not have full disk access until it is restarted loop" even though the client is quit. The toggle will then disable itself and any attempts to re-enable it will either show the prompt or it just never enables.

### Expected Behavior

Full disk access should be toggled on.

### Steps to Reproduce

1. As prompted, go to Settings -> Privacy & Security -> Full Disk access
2. Toggle the option with the app open or closed - the toggle will fail to work.
3. Apps allowed through the split tunnel fail to work until Mullvad is disconnected manually.

### Failure Logs

Log is spammed with:
`[2024-08-12 22:09:11.783][talpid_core::split_tunnel::imp::tun][ERROR] Failed to forward to tun device: Message too long (os error 40)
`

and a few lines stating:
`[2024-08-12 22:26:55.972][talpid_core::split_tunnel::imp::tun][ERROR] Failed to forward to tun device: Device not configured (os error 6)
`

After attempting to enable disk access and/or using split tunnelling.

### Operating system version

14.6.1

### Mullvad VPN app version

2024.4

### Additional Information

Local network sharing & VPN killswitch are enabled.

Appears the daemon is blocking the setting from being enabled as killing the app (even after it has quit) shows the daemon is still running which is likely causing macOS to refuse to acknowledge the app has been killed. 

Uninstalling and reinstalling didn't fix it either, nor did a restart (when the app was quit from start up).

**Comment by rzero1** [comment]
I had the same issue. I resolved it by removing Mullvad from the Full Disk Access list with the "minus sign," then re-adding it and toggling it on. This was all done without Mullvad running.

**Comment by FIying-Scotsman** [comment]
> I had the same issue. I resolved it by removing Mullvad from the Full Disk Access list with the "minus sign," then re-adding it and toggling it on. This was all done without Mullvad running.

That seems to have fixed it - thanks. Doesn't appear split tunnelling is working as Stocks still reports it's not connected to the internet (turning off the VPN then makes it work. Verified it's in the "excluded apps" section in the UI) but that's a different problem to this issue.

**Comment by gitternand** [comment]
> I had the same issue. I resolved it by removing Mullvad from the Full Disk Access list with the "minus sign," then re-adding it and toggling it on. This was all done without Mullvad running.

Sadly the issue still persits as of now and on Tahoe you can't remove an app from Full Disk Access anymore (no more minus sign in the settings).

So as of now, there seems to be no solution and split tunneling is not possible on macOS, right?

**Comment by rzero1** [comment]
> > I had the same issue. I resolved it by removing Mullvad from the Full Disk Access list with the "minus sign," then re-adding it and toggling it on. This was all done without Mullvad running.
> 
> Sadly the issue still persits as of now and on Tahoe you can't remove an app from Full Disk Access anymore (no more minus sign in the settings).
> 
> So as of now, there seems to be no solution and split tunneling is not possible on macOS, right?

There is still the minus sign in the settings on Tahoe.
