### ISSUE TITLE
[Feature request] Distribute the MullvadVPN android app through the Accrescent app store.

### ISSUE THREAD

**Issue by mileswentdown** [mullvad/mullvadvpn-app#6658]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I suggest that the MullvadVPN android app should be distributed through the Accrescent app store.
As an android-like operating system user (GrapheneOS) I recognise that the current secure installation options for android apps are quite limited, and as such distributing MullvadVPN through the Accresent app store will provide a reliable and secure way to install the VPN without TOFU and/or using Google Play store.
Also, again, as a GrapheneOS user, it would be extremely convinient to have a way of securely installing MullvadVPN almost right after startup.

### Alternative solutions

I am currently updating (and have installed) MullvadVPN via directly fetching it from Github with Obtanium and verifying it with AppVerifier (which is, again, available through the Accresent app store). This approach is less advantegous than the method I am suggesting due to the current method of signature verification via AppVerifier not being as strong as the one inherently present in the installation process via Acressent.

### Type of feature

- [X] Better privacy/anonymity
- [X] Better at circumventing censorship
- [ ] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by MrChocolatine** [comment]
> I have checked this issue tracker to see if others have reported similar issues.

Just searching the word `Accrescent` shows the request is already tracked in #5606 .

**Comment by mileswentdown** [comment]
> > I have checked this issue tracker to see if others have reported similar issues.
> 
> You searched for the word `Accrescent` and you did not see #5606 already exists?

I am really really really sorry, that is weird, I will now close the issue.
