### ISSUE TITLE
cant mount local network smb share 

### ISSUE THREAD

**Issue by Xyz00777** [mullvad/mullvadvpn-app#6692]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

when i enable "local network sharing" and want to connect to an SMB share then its not working

### Expected Behavior

it should work

### Steps to Reproduce

1. enable local network share and vpn connection
2. try to connect to SMB

### Operating system version

Windows 11

### Mullvad VPN app version

2024.4

### Additional Information

Im aware of issue https://github.com/mullvad/mullvadvpn-app/issues/5493 but its not even working in the local network what should be work :/

**Comment by hulthe** [comment]
Sounds like it could be an issue with DNS, as DNS requests are not covered by local network sharing. Could you try connecting to the SMB share using its IP address?

If this didn't help you, I recommend contacting support. They can help you troubleshoot: [support@mullvadvpn.net](mailto:support@mullvadvpn.net)

Also, here are some links that may or may not be helpful:
https://mullvad.net/en/help/using-mullvad-vpn-app#localnetworksharing
https://mullvad.net/en/help/faq#29
