### ISSUE TITLE
Kubuntu 24.04 GUI not working

### ISSUE THREAD

**Issue by BenderBRod** [mullvad/mullvadvpn-app#6714]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

The VPN connects after boot but th GUI doesnt work at all after upgrading from 22.04 to 24.04
Also the little icon isnt showing in the taskbar. When i open the app, it shows loading for a second in the taskbar, then disappears

### Expected Behavior

The GUI should work like on 22.04

### Steps to Reproduce

1. ...Upgrade to 24.04
2. ...Boot

### Failure Logs

```shell
The log is too long, i put it into the additional informations.
```

### Operating system version

Kubuntu 24.04.1

### Mullvad VPN app version

Latest: 2024.4 (Worked on Kubuntu 22.04.4)

### Additional Information

Before creating this i searched to fix it myself but everything i could find was outdated and for different OS.
I was not connected to the vpn while creating the log
Im not a linux pro so if you need addictional information, please tell me how to get that

[mullvad-report.log](https://github.com/user-attachments/files/16825295/mullvad-report.log)

**Comment by hulthe** [comment]
Hi, you could be experiencing the same problem as #6128, could you try running `sudo dpkg-reconfigure mullvad-vpn` from the terminal?

If that doesn't work, try reinstalling the app

**Comment by BenderBRod** [comment]
Oh wow, that did work.
How did i not find that.
Thanks alot!
