### ISSUE TITLE
Umbrel apps very slow to load when Mullvad is activated

### ISSUE THREAD

**Issue by anthony-robin** [mullvad/mullvadvpn-app#6715]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When Mullvad VPN is turned on, access to my local server (Umbrel) is very slow. It seems that the first connection long a lot and the next one is quicker but after a while it is slow again.

### Expected Behavior

I expect no slow page loading when accessing http://umbrel.local related apps from my device

### Steps to Reproduce

It needs an Umbrel working on the same network to be reproductible so might no be doable for you guys (https://umbrel.com)

1. Install any app from Umbrel App Store
2. Launch Mullvad VPN and connect to any location
3. Access one of the app from your browser (in my case Brave but Firefox slow as well): http://umbrel.local
4. See that it takes around 10 seconds to load the page

### Failure Logs

```shell
/
```

### Operating system version

Ubuntu 24.04

### Mullvad VPN app version

2024.5-beta1

### Additional Information

When the VPN is turned off or not started, local URLs on Umbrel are loading immediately. 

Might also be related to https://github.com/mullvad/mullvadvpn-app/issues/4085 but in my case I experienced it with Umbrel self hosted server URLs.

Here is a screenshot of a part of my configuration (local network enabled):
![Capture d’écran du 2024-09-01 17-17-49](https://github.com/user-attachments/assets/eb70e50e-7fa0-4ee5-ac08-ea22e8a5d673)

Thank you for helping me figuring out how I can speed local pages loading :)

**Comment by lasermind** [comment]
Instead of umbrel.local, have you tried using the IP directly? Does it speed up things again?

**Comment by anthony-robin** [comment]
Good suggestion, I tried replacing `umbrel.local` by `192.168.X.X` and it loads immediately, very fast !

What can explain the difference of time between accessing domain name and local IP within Mullvad ? Is there a configuration to modify in Ubuntu ? Or is there a way to tell Mullvad to ignore a specific domain or IP ?

Thank you :)

**Comment by lasermind** [comment]
I once had the same effect on a different machine; not with Mullvad, but in general. I simply became used to calling the IP directly.

I have no real explanation for this, only a guess. Umbrel advertises this domain in your network. Mullvad probably re-routes the requests to resolve the domain to an IP address. This is quirky. Maybe there’s a fix, but I don’t know it.

If you’re on Windows, what you could try is [editing your `hosts` file](https://www.howtogeek.com/784196/how-to-edit-the-hosts-file-on-windows-10-or-11/). Add this line to it:

```
192.168.X.Y umbrel.local
```

This way, you can tell Windows directly how to resolve the domain, without the need to search for it somewhere in your network.

**Comment by anthony-robin** [comment]
I'm on Ubuntu and adding my local IP to `/etc/hosts` did the job ! All apps are now loading instantly !

Thank you very much for your help :pray:
