### ISSUE TITLE
Fedora repo missing 2024.5

### ISSUE THREAD

**Issue by grrrrr** [mullvad/mullvadvpn-app#6732]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

The fedora repo does not have the latest release, 2024.5

```
$ sudo dnf update
Mullvad VPN                                                                                                                                                                                                   1.0 kB/s | 3.6 kB     00:03    
Errors during downloading metadata for repository 'mullvad-stable':
  - Status code: 404 for https://repository.mullvad.net/rpm/stable/x86_64/repodata/ecc94f20fc23124c316d193a77c2f32faaba7a54cac26fd288b88c9cbf13184c-primary.xml.gz (IP: 45.149.104.1)
Error: Failed to download metadata for repo 'mullvad-stable': Yum repo downloading error: Downloading error(s): repodata/ecc94f20fc23124c316d193a77c2f32faaba7a54cac26fd288b88c9cbf13184c-primary.xml.gz - Cannot download, all mirrors were already tried without success
Ignoring repositories: mullvad-stable
```

### Expected Behavior

 `dnf update` updates mullvad desktop app to 2024.5

### Steps to Reproduce

1. sudo dnf update
2. observe update failing

### Operating system version

Fedora 40

**Comment by raksooo** [comment]
`dnf` only fetches updates from repos every 24 hours at most unless you run it with the `--refresh` flag. Try running `dnf update --refresh`. I'll close this but if you still experience issues please let us know and we'll reopen.

**Comment by aidandenlinger** [comment]
I tried with `dnf update --refresh`, getting the same error and no metadata for 2024.5:

```bash
❯ sudo dnf update --refresh
[sudo] password for user:
...
Mullvad VPN                                   2.3 kB/s | 3.0 kB     00:01
Mullvad VPN                                    43  B/s | 146  B     00:03
Errors during downloading metadata for repository 'mullvad-stable':
  - Status code: 404 for https://repository.mullvad.net/rpm/stable/x86_64/repodata/d2d595515823b70d903a527ad92e974eb06fc0708628c81a21fa50c8c5cb54de-primary.xml.gz (IP: 45.149.104.1)
Error: Failed to download metadata for repo 'mullvad-stable': Yum repo downloading error: Downloading error(s): repodata/d2d595515823b70d903a527ad92e974eb06fc0708628c81a21fa50c8c5cb54de-primary.xml.gz - Cannot download, all mirrors were already tried without success
...
Ignoring repositories: mullvad-stable
```

Dnf then shows no update for mullvad-vpn. I think the repo itself is having issues since it's a 404 error?

Trying to run `dnf install mullvad-vpn`:
```


This seems to be the same problem as #6740 too.

**Comment by RobertoAssumpcao** [comment]
I did the sudo dnf update --refresh and sudo dnf install mullvad-vpn but the error continued, I also tried the sudo dnf clear all and finally I tried to remove and now I'm trying to install but the same error.

**Comment by RobertoAssumpcao** [comment]
I tried again and did the installation, the repository seems to have responded.
