### ISSUE TITLE
GUI does not open when Mullvad for macOS is built from the source

### ISSUE THREAD

**Issue by MahdiNazemi** [mullvad/mullvadvpn-app#6742]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Since the 2024.3 version, the GUI does not open when the desktop app is built from the source. I compiled on a machine and installed the app on two different machines, and they both exhibit this behavior.

### Expected Behavior

The GUI should open when a user clicks on the menu bar icon.

### Steps to Reproduce

1. (Optional) Remove all Mullvad-related files form Application Support and other folders 
2. Follow the build instructions to build the app.
3. Install the app.
4. Click on the menu bar icon.

### Operating system version

macOS 14.6.1

### Mullvad VPN app version

2024.5

I am curious if anyone else has experienced this issue or can provide pointers about where to look to debug the issue.

**Comment by raksooo** [comment]
Thanks for reporting! It should work no matter where the app was built. Did you use the `build.sh` script to build it? Did you see any errors while building? Are there any errors in the logs from when it happens?

**Comment by dlon** [comment]
The problem is likely that `nseventmonitor` is missing under `node_modules`.
