### ISSUE TITLE
Mullvad VPN Debian repo (2024.5): `apt update` > File has unexpected size (901 != 904).

### ISSUE THREAD

**Issue by lasermind** [mullvad/mullvadvpn-app#6754]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

With apt update, an error is thrown about "File has unexpected size (901 != 904)."

![mullvad-unexpectedfilesize](https://github.com/user-attachments/assets/e510425f-3a18-41d4-a5d0-d2cef98428a5)

Somehow Debian (?) thinks the file `Packages.gz` is 904 bytes in size and created on 2024-09-04. But checking the repo in the browser, the file is 901 bytes in size and created on 2024-09-05.

### Expected Behavior

I expected it to work, this means a usable package list is obtained, with no error.

### Steps to Reproduce

1. Add the Mullvad keyring, like described in the docs
2. Add the Mullvad repo, like desribed in the docs

![mullvad-debianinstallinstructions](https://github.com/user-attachments/assets/59ca0ae3-a95e-43ee-9ac8-0f58541d859a)

3. Do `apt update` > see the error

### Failure Logs

```shell
Get:5 https://repository.mullvad.net/deb/stable bookworm InRelease [2,547 B]  
Get:6 https://repository.mullvad.net/deb/stable bookworm/main amd64 Packages [904 B]
Err:6 https://repository.mullvad.net/deb/stable bookworm/main amd64 Packages
  File has unexpected size (901 != 904). Mirror sync in progress? [IP: 45.149.104.1 443]
  Hashes of expected file:
   - Filesize:904 [weak]
   - SHA256:1a67dfbaed20f9fe27c23a21d7505e1c8ba3b38650e4ba5ff43f28557be3606a
   - SHA1:9c0a8ef9a44bed5951f59ecc76aeb066c830106a [weak]
   - MD5Sum:e8c49bfe078ba09eb437db5322d22e39 [weak]
  Release file created at: Wed, 04 Sep 2024 12:32:45 +0000
Fetched 2,547 B in 1s (2,380 B/s)
Reading package lists... Done
E: Failed to fetch https://repository.mullvad.net/deb/stable/dists/bookworm/main/binary-amd64/Packages.gz  File has unexpected size (901 != 904). Mirror sync in progress? [IP: 45.149.104.1 443]
   Hashes of expected file:
    - Filesize:904 [weak]
    - SHA256:1a67dfbaed20f9fe27c23a21d7505e1c8ba3b38650e4ba5ff43f28557be3606a
    - SHA1:9c0a8ef9a44bed5951f59ecc76aeb066c830106a [weak]
    - MD5Sum:e8c49bfe078ba09eb437db5322d22e39 [weak]
   Release file created at: Wed, 04 Sep 2024 12:32:45 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Operating system version

Debian Bookworm

### Mullvad VPN app version

2024.5

### Additional Information

I installed Mullvad VPN on Debian successfully two days ago. Now I'm doing the exact same process on even the same machine and this error about "wrong file size" appears. I already waited several hours, also over night to let "the mirror sync", but honesty, this can’t take so long. What could be wrong here? 🤔

Thanks!

**Comment by lasermind** [comment]
Something seems to have happened, it does work again now.
If someone from the Mullvad team actually did something, I would love to hear what is was. 

Anyway, thanks!

**Comment by elrom** [comment]
This seems to have returned. I'm now encountering this.

**Comment by qfoxb** [comment]
also getting this

**Comment by alexandre-pecorilla** [comment]
Same here, also getting this.

**Comment by Vizzyy** [comment]
same here

**Comment by hulthe** [comment]
Strange. We'll look into this

**Comment by faern** [comment]
Probably a hosting issue and related to #6922

**Comment by faern** [comment]
This was a CDN caching issue on our end. This should have been resolved now. I'm closing this as completed. Please report if you still encounter this problem, now or later.

**Comment by megasanjay** [comment]
I seem to be seeing the same issue on Ubuntu but i'm getting different sizes than previous issues on this thread 

![image](https://github.com/user-attachments/assets/ade52673-23a2-479b-8127-35985e8e1d7a)

**Comment by thragusjr** [comment]
Seeing this on Debian 12 as well. Let me know if a new issue needs to be opened.

![image](https://github.com/user-attachments/assets/d12279fd-3533-44ab-a491-35efb51e3fb8)

**Comment by Flameancer** [comment]
@faern Was trying to update my system and I am getting the same issue also.
![image](https://github.com/user-attachments/assets/397f8627-03b0-49e9-a2e1-ca4549b99767)

**Comment by dgrant** [comment]
![image](https://github.com/user-attachments/assets/d203b1d1-9a49-494d-9ebc-baf3a847bc0d)

**Comment by ncorbuk** [comment]
I am getting this issue i am trying to install mullvad..... 
![Uploading Screenshot from 2024-10-10 08-40-02.png…]()
