### ISSUE TITLE
[Feature request] DAITA on iOS

### ISSUE THREAD

**Issue by thekeymaker33** [mullvad/mullvadvpn-app#6786]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Hi,

Is there any plan to add DAITA to iOS app?

### Alternative solutions

.

### Type of feature

- [X] Better privacy/anonymity
- [X] Better at circumventing censorship
- [ ] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [X] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by MrChocolatine** [comment]
I think it's on its way.

#6673
> This pull request first appeared in [ios/2024.7-build1](https://github.com/mullvad/mullvadvpn-app/releases/tag/ios/2024.7-build1)

**Comment by MarkusPettersson98** [comment]
Yes, as @MrChocolatine pointed out DAITA will be released for iOS in a future update :blush:
