### ISSUE TITLE
[Request] Support for `armhf` Architecture on RPI 2B

### ISSUE THREAD

**Issue by ncorder** [mullvad/mullvadvpn-app#6793]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Hello everyone,

I am having some issues installing Mullvad upon my Raspberry Pi 2B machine (running Diet Pi).

```
Hit:8 https://repository.mullvad.net/deb/stable bookworm InRelease
Reading package lists... Done
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://repository.mullvad.net/deb/stable bookworm InRelease' doesn't support architecture 'armhf'
```

It does not appear that the application is within a repository for `armhf`.
Are there any known solutions to this issue? 

Thank you so much for all of your time and support! As well as for creating such a wonderful application!
—Best

### Alternative solutions

As a user of Mullvad, I would be immensely grateful if a release for armhf machines such as the Raspberry Pi was made available within the repository. 

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by MarkusPettersson98** [comment]
Hi ncorder, we don't support `armhf` and currently have no plan to start doing so. You say that you are running an older Raspberry PI - may I ask if you happen to run a 32-bit user space? If so, we are *unable* to support it even if we wanted to. See https://github.com/mullvad/mullvadvpn-app/issues/4423 for more details. Thanks.

**Comment by ncorder** [comment]
> Hi ncorder, we don't support `armhf` and currently have no plan to start doing so. You say that you are running an older Raspberry PI - may I ask if you happen to run a 32-bit user space? If so, we are _unable_ to support it even if we wanted to. See #4423 for more details. Thanks.

I am not entirely certain I had assumed it was 64 bit but have now realized it is indeed not:

https://raspberrypi.stackexchange.com/questions/34715/is-raspbian-for-the-raspberry-pi-2-b-32-bit-or-a-64-bit-os

Thank you so much. I assume this likewise means that I cannot manually build/install this for my system.
