### ISSUE TITLE
[Android] VPN does not connect when a custom port for shadowsocks is set

### ISSUE THREAD

**Issue by gsture** [mullvad/mullvadvpn-app#6876]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When you enable shadowsocks and enter a custom port the vpn does not connect. Is mentions the error: "No servers match your settings". It does not matter which port number or server you select.

### Expected Behavior

Either connect or not having a option to select a port number.

### Steps to Reproduce

1. Enable shadowsocks
2. Set a port number
3. Try to connect to any server

### Failure Logs

Log1.txt

### Android version

GrapheneOS 14 (AP2A.240905.003)

### Device model

Pixel 8

### Mullvad VPN app version

2024.5 beta 2

**Comment by Pururun** [comment]
The majority of the servers only support ports in the range 51900-51949 for shadowsocks. There is a few, one for example is `fr-par-wg-301` that supports all valid ports, 0-65535.

It is unfortunately not possible at this stage to see which servers supports which ports in the app.

**Comment by gsture** [comment]
> The majority of the servers only support ports in the range 51900-51949 for shadowsocks. There is a few, one for example is `fr-par-wg-301` that supports all valid ports, 0-65535.
> 
> It is unfortunately not possible at this stage to see which servers supports which ports in the app.

Ok thank you. I didn't know that. I would suggest to mention this in the error message. Instead of "No servers match your settings" say something like "shadowsocks port out of range". I could see this being confusing to users. It's also not mentioned in the server list which might also be a good idea.

**Comment by Pururun** [comment]
> Ok thank you. I didn't know that. I would suggest to mention this in the error message. Instead of "No servers match your settings" say something like "shadowsocks port out of range". I could see this being confusing to users. It's also not mentioned in the server list which might also be a good idea.

Thanks for the suggestion. Yes, you are not the only one that have been confused so there will be some clairification in the future.

**Comment by strykenKN** [comment]
Hello,

I have the same problem. I have that Nothing 2a and as soon as I am in different networks Wifi or 4 or 5G I have no more connection when the network is changed. I then have to disconnect everything in the app and restart it, then it works again.

**Comment by gsture** [comment]
> Hello,
> 
> I have the same problem. I have that Nothing 2a and as soon as I am in different networks Wifi or 4 or 5G I have no more connection when the network is changed. I then have to disconnect everything in the app and restart it, then it works again.

I think what you are referring to is this issue which I also reported a while ago: https://github.com/mullvad/mullvadvpn-app/issues/6864

This issue was just about setting a custom port.
