### ISSUE TITLE
IME does not work correctly in creating custom listings

### ISSUE THREAD

**Issue by curlingchimpanzeeowl** [mullvad/mullvadvpn-app#6880]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When creating a custom listing, characters are entered in the name of the listing without being converted by the IME. Therefore, you cannot enter Japanese or Chinese characters.

### Expected Behavior

IME works correctly

### Steps to Reproduce

1. Attempt to create a custom listing
2. Enter a name for the listing

### Android version

14

### Device model

Pixel 7 Pro

### Mullvad VPN app version

2024.4

**Comment by kl** [comment]
Thank you for reporting this bug! We have fixed the issue and merged to main. The fix will be included in an upcoming release soon.
