### ISSUE TITLE
Build failure with containerized build on android

### ISSUE THREAD

**Issue by errge** [mullvad/mullvadvpn-app#6881]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Running `CONTAINER_RUNNER=docker ../building/containerized-build.sh android --dev-build` on an up-to-date standard debian installation doesn't finish.

### Expected Behavior

Build should finish

### Steps to Reproduce

1. install debian + docker.io
2. check out github repository
3. run `CONTAINER_RUNNER=docker ../building/containerized-build.sh android --dev-build`
4. build fails

### Failure Logs

```shell
Compiling wireguard-go-rs v0.0.0 (/build/wireguard-go-rs)
   Compiling shared_child v1.0.0
   Compiling os_pipe v1.1.5
   Compiling http v0.2.12
   Compiling hickory-resolver v0.24.1
   Compiling utf8parse v0.2.1
   Compiling err-context v0.1.0
   Compiling udp-over-tcp v0.3.0 (https://github.com/mullvad/udp-over-tcp?rev=87936ac29b68b902565955f138ab02294bcc8593#87936ac2)
error: failed to run custom build command for `wireguard-go-rs v0.0.0 (/build/wireguard-go-rs)`

Caused by:
  process didn't exit successfully: `/cargo-target/target/debug/build/wireguard-go-rs-e260ad314ed5bf05/build-script-build` (exit status: 1)
  --- stdout
  cargo::rustc-check-cfg=cfg(daita)
  cargo::rerun-if-changed=libwg
  cargo::rerun-if-changed=/build/android/app/build/extraJni/arm64-v8a

  --- stderr
  Error from ANDROID_ABI="arm64-v8a" ANDROID_ARCH_NAME="arm64" ANDROID_C_COMPILER="/opt/android/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang" CARGO_TARGET_DIR="/build/build/target" GOPATH="/build/build/android-go-path" LDFLAGS="-L/cargo-target/target/aarch64-linux-android/debug/build/wireguard-go-rs-476bb48ff73e9092/out -w -s" "make" "-C" "./libwg" "-f" "Android.mk"

  stdout:

  make: Entering directory '/build/wireguard-go-rs/libwg'
  mkdir -p /cargo-target/target/aarch64-linux-android/debug/build/wireguard-go-rs-476bb48ff73e9092/out
  # Build libmaybenot
  make --directory wireguard-go libmaybenot.a LIBDEST="/cargo-target/target/aarch64-linux-android/debug/build/wireguard-go-rs-476bb48ff73e9092/out" TARGET="aarch64-linux-android" CARGO_TARGET_DIR="/build/build/target"
  make[1]: Entering directory '/build/wireguard-go-rs/libwg/wireguard-go'
  make[1]: Leaving directory '/build/wireguard-go-rs/libwg/wireguard-go'
  make: Leaving directory '/build/wireguard-go-rs/libwg'


  -------
  stderr:

  make[1]: *** No rule to make target 'libmaybenot.a'.  Stop.
  make: *** [Android.mk:36: /cargo-target/target/aarch64-linux-android/debug/build/wireguard-go-rs-476bb48ff73e9092/out/libwg.so] Error 2


  -------
  Error: Command exited with a non-zero exit code: exit status: 2

  Caused by:
      Failed to execute command: ANDROID_ABI="arm64-v8a" ANDROID_ARCH_NAME="arm64" ANDROID_C_COMPILER="/opt/android/android-ndk-r27b/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang" CARGO_TARGET_DIR="/build/build/target" GOPATH="/build/build/android-go-path" LDFLAGS="-L/cargo-target/target/aarch64-linux-android/debug/build/wireguard-go-rs-476bb48ff73e9092/out -w -s" "make" "-C" "./libwg" "-f" "Android.mk"
warning: build failed, waiting for other jobs to finish...
```
```


### Android version

13

### Device model

Linux build process

### Mullvad VPN app version

git 980c8372e39331d12e58ccf00eca6abc1bcf5609

### Additional Information

_No response_

**Comment by hulthe** [comment]
Have you followed the steps in [README.md#checking-out-the-code](https://github.com/mullvad/mullvadvpn-app?tab=readme-ov-file#checking-out-the-code)? The build relies on several git submodules that need to be cloned.

**Comment by errge** [comment]
Thank you @hulthe for taking up this bug report.  I rechecked my clone, cleaned it up fully, deleted all the old docker volumes the build create, and made sure that the submodules are cloned out as discussed in the readme, sorry for missing this.

After that the build almost finished automatically, except for one fix that I needed to make.

The fix is about the fact that the build is running as root.

```
diff --git a/wireguard-go-rs/libwg/Android.mk b/wireguard-go-rs/libwg/Android.mk
index f847aa66d..4c9eeaab9 100644
--- a/wireguard-go-rs/libwg/Android.mk
+++ b/wireguard-go-rs/libwg/Android.mk
@@ -37,7 +37,7 @@ $(DESTDIR)/libwg.so:
        # Build wireguard-go
        go get -tags "linux android daita"
        chmod -fR +w "$(GOPATH)/pkg/mod"
-       go build -tags "linux android daita" -ldflags="-X main.socketDirectory=/data/data/$(ANDROID_PACKAGE_NAME)/cache/wireguard" -v -o "$@" -buildmode c-shared
+       go build -tags "linux android daita" -ldflags="-X main.socketDirectory=/data/data/$(ANDROID_PACKAGE_NAME)/cache/wireguard" -v -o "$@" -buildmode c-shared -buildvcs=false
        rm -f $(DESTDIR)/libwg.h
```

The build succeeded now, I will try out the resulting APK later.

My further comment would be that maybe the docker volume deletion should be documented for the created docker volumes:

```
228M	/var/lib/docker/volumes/cargo-registry
11G	/var/lib/docker/volumes/cargo-target
2.8G	/var/lib/docker/volumes/gradle-cache
```

They add up quite to something, and for a beginner this can remain hidden forever basically, and no amount of `git clean` or `rm -rf` removes it, and gives back the disk space.

Also the names of these volumes are suboptimal in the sense that they are too general for a dev-machine with docker.  They should be prefixed with `mullvad-build-` or something similar.

**Comment by hulthe** [comment]
Happy to help :)

> After that the build almost finished automatically, except for one fix that I needed to make.

Huh, hadn't run into that one before. I'll look into pulling your `-buildvcs` fix, thanks :+1:  

> docker volume deletion should be documented
> names of these volumes are suboptimal

Good feedback, I'll add add this to our backlog. Apparently my podman folder is 60GB...

**Comment by hulthe** [comment]
Closing this now, but feel free to re-open if you have more problems with your build :hammer:
