### ISSUE TITLE
DAITA not working

### ISSUE THREAD

**Issue by slammpete** [mullvad/mullvadvpn-app#6946]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

My ISP here in Colombia just increased my speeds too 500M down but it seems as though they no longer want people to use VPN's. Tried DAITA  and all other combos.

### Expected Behavior

VPN traffic should be able to avoid detection from ISP traffic analysis. 

### Steps to Reproduce

1. Turn off mullvad. Speedtest results 500M down , 30M up
2. ...Go to settings->vpn settings->choose wireguard protocol
3. ...Go into wireguard settings and enable DAITA
4. All other settings are on automatic. 
5. Speedtest results 20M down , 10M up
6. Repeated above steps and added obfuscation , different ports, quantum-reistant tunnel , and finally multihop. none of these helped and when i enabled multihop i could not connect to any of your servers.
7. With DAITA and quantum-resistance on together i cannot connect. 

### Operating system version

Linux user-systemproductname 6.10.11-2-MANJARO #1 SMP PREEMPT_DYNAMIC Thu Sep 26 03:28:26 UTC 2024 x86_64 GNU/Linux

### Mullvad VPN app version

2024.6-beta1 from AUR repository

### Additional Information

ahhhhhhhhhhhhhhhhh... help.

**Comment by slammpete** [comment]
I tried to include the failure logs but it did not allow me to due to the length. I have uploaded them here for you to download -

https://1fichier.com/?ip0bwlaxf1mlq8lipo6m

passsword - ReAdMePlease911

**Comment by slammpete** [comment]
Also not sure if this helps but my ISP is TIGO

**Comment by raksooo** [comment]
This sounds like a question for our support team, you'll reach them by using the "Report a problem" feature in the app or by emailing support@mullvadvpn.net.

**Comment by slammpete** [comment]
ok thanks, sorry about that
