### ISSUE TITLE
[macOS] iPhone Mirroring does not work on 2024.6-beta2

### ISSUE THREAD

**Issue by davidkamayor** [mullvad/mullvadvpn-app#6956]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

iPhone Mirroring doesn't load in latest beta (2024.6-beta2). I have tried enabling split tunneling as well as IPv6.

iPhone Mirroring works when VPN is disabled.

### Expected Behavior

iPhone mirroring should allow remote access to mobile device.

### Steps to Reproduce

1. Open iPhone Mirroring app

### Operating system version

macOS 15.0

### Mullvad VPN app version

2024.6-beta2

### Additional Information

Issue persists despite fixes for Apple services in 2024.6beta1 and beta2

https://github.com/mullvad/mullvadvpn-app/issues/6521

**Comment by drpoutine** [comment]
iPhone Mirroring relies on Continuity. If it's not added to the split tunnel then you'll need to enable `Local Network Sharing` and refresh your tunnel.

**Comment by davidkamayor** [comment]
Enabling local network sharing fixed the issue.
