### ISSUE TITLE
 File has unexpected size (900 != 902). Mirror sync in progress? [IP: 45.149.104.1 443]

### ISSUE THREAD

**Issue by ncorbuk** [mullvad/mullvadvpn-app#6958]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

See the screenshot provided
![Screenshot from 2024-10-10 08-45-21](https://github.com/user-attachments/assets/d25ad6fa-420e-4cdd-84bc-cb8b802ccb85)

### Expected Behavior

for it to work...

### Steps to Reproduce

# Download the Mullvad signing key
sudo curl -fsSLo /usr/share/keyrings/mullvad-keyring.asc https://repository.mullvad.net/deb/mullvad-keyring.asc

# Add the Mullvad repository server to apt
echo "deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=$( dpkg --print-architecture )] https://repository.mullvad.net/deb/stable $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/mullvad.list

# Install the package
sudo apt update
sudo apt install mullvad-vpn

### Operating system version

Pop!_OS 22.04 LTS x86_64 

### Additional Information

I am using OS: Pop!_OS 22.04 LTS x86_64 ...  though judging from this link here, i think it is on your end : https://github.com/mullvad/mullvadvpn-app/issues/6754

**Comment by ncorbuk** [comment]
seems to be all good now. i am now on mullvad vpn on laptop and mobile :+1:

**Comment by thragusjr** [comment]
All good for me as well

**Comment by raksooo** [comment]
Thanks for reporting! This issue is due to some issues with caching on our end and we're looking into getting it resolved. Since it's working now I'll close this.
