### ISSUE TITLE
Wireguard Obfuscation (Shadowsocks or UDP-over-TCP) no longer works on the latest android release

### ISSUE THREAD

**Issue by alizair** [mullvad/mullvadvpn-app#6963]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

The Wireguard Obfuscation Techniques (Shadowsocks and UDP-over-TCP) no longer work in the android app (version 2024.5) on the same network that I used to work on when I enabled UDP-over-TCP in the previous version (2024.4). To confirm that the network did not start to block vpn's with obfuscation techniques as well, I deleted the 2024.5 version and installed the 2024.4 version to see that it was connecting perfectly after I enabled the UDP-over-TCP obfuscation option. Neither the Shadowsocks or UDP-over-TCP techniques work as of now.

### Expected Behavior

The tunnel should be established at least when I enable the UDP-over-TCP option, since it used to work in the 2024.4 release. I will try to keep using the 2024.4 release until this issue is resolved.

### Steps to Reproduce

1. Connect to a network that does not allow a plain wireguard connection
2. Go to the settings and set the obfuscation setting to UDP-over-TCP (or Shadowsocks, both do not work for me)
3. Mullvad keeps on trying to connect but is unable to

### Android version

14 (GrapheneOS)

### Device model

Pixel 6

### Mullvad VPN app version

2024.5

**Comment by Pururun** [comment]
I tested this quickly on Pixel 7a and Android 14 and it works fine for me.

If possible could you provide some logs of your failed connection attempt? Settings -> Report Problem -> View Logs

**Comment by alizair** [comment]
> I tested this quickly on Pixel 7a and Android 14 and it works fine for me.
> 
> If possible could you provide some logs of your failed connection attempt? Settings -> Report Problem -> View Logs

It keeps on connecting but is unable to. Sure, I can send it tomorrow when I connect to that specific network I am talking about, since it does work on networks that don't block plain wireguard connections.

**Comment by alizair** [comment]
So here are the logs for trying to connect with both of the obfuscation methods.

[Shadowsocks Obfuscation.txt](https://github.com/user-attachments/files/17354769/Shadowsocks.Obfuscation.txt)
[UDP-over-TCP Obfuscation.txt](https://github.com/user-attachments/files/17354770/UDP-over-TCP.Obfuscation.txt)

**Comment by Pururun** [comment]
@alizair Thanks for your report. We have found the issue and a fix will be in the next release.

https://github.com/mullvad/mullvadvpn-app/pull/7004

Please open this issue again if the issue persist.

**Comment by Pururun** [comment]
Should be fixed by `2024.7`

**Comment by alizair** [comment]
Yes, thank you!

**Comment by Pururun** [comment]
> Yes, thank you!

Great that it works again and thanks again for your report!
