### ISSUE TITLE
Connection issue with LittleSnitch after update to 2024.6-beta2

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#6965]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

After updating to 2024.6-beta2, LittleSnitch takes a long time to switch profile (from "untrusted" just before Mullvad connects to "trusted" once VPN connection is active) and connections remain blocked as if no profile switching had been done (the "untrusted" profile blocks most connections).

Not sure where the issue really lies, but recent updates of LittleSnitch have not broken anything, while this specific switch to beta2 is breaking something in profile switching.

### Expected Behavior

As with all previous version of Mullvad, up until and including 2024.6-beta1, profile switching should be quick and connections should afterward be allowed.

### Steps to Reproduce

1. Stop wifi
2. Update from 2024.6-beta1 to 2024.6-beta2
3. Start wifi
4. LittleSnitch recognises non-VPN connection and start untrusted profile
5. Mullvad connects succesfully
6. After a long time, LittleSnitch recognises VPN connection and switches to trusted profile
7. Despite having moved to trusted profile, connections before as with untrusted profile (mostly blocked)
8. Disconnect, revert to 2024.6-beta1, all normal

### Operating system version

macOS 14.7.1

### Mullvad VPN app version

2024.6-beta2

### Additional Information

Using latest build of LittleSnitch

**Comment by raksooo** [comment]
Thank you for reporting this issue! We are aware of it and will look into it.

**Comment by ihateprogramming88** [comment]
Hi I have an issue related to this, I do have little snitch but updating to the latest beta completely breaks DNS for me, I can successfully connect to the VPN and the wifi but there is no success in trying to access webpages or any other destination on the internet

**Comment by ihateprogramming88** [comment]
I tested the new update 2024.6 on my MacBook and it doesn't resolve the connectivity issues it still doesn't connect to the internet

**Comment by ihateprogramming88** [comment]
Will test tomorrow and report back the results @frigeky00

**Comment by ihateprogramming88** [comment]
Issues resolved for me 2024.7-beta1

**Comment by CP42Kx07** [comment]
Turning off the Quantum-resistant tunnel option in Mullvad VPN WireGuard settings fixed the LS auto-profile non-switching problem for me in both 2024.6 & 2024.7beta1.

[Sonoma 14.7, Little Snitch 6.1.2]

**Comment by CP42Kx07** [comment]
I agree that APS is slow / flaky. I haven't tested with an alternative VPN but perhaps the issue is with Little Snitch rather than Mullvad VPN?

[MacBook Pro M1 Max, Sequoia 15.1, Mullvad VPN 2024.7, Little Snitch 6.1.2]
