### ISSUE TITLE
download server is slow

### ISSUE THREAD

**Issue by 3052** [mullvad/mullvadvpn-app#6969]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

~~~
> curl -O https://cdn.mullvad.net/app/desktop/releases/2024.5/MullvadVPN-2024.5.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  5  100M    5 5807k    0     0  70428      0  0:24:58  0:01:24  0:23:34  135k
~~~

### Expected Behavior

should be fast

### Steps to Reproduce

see above

**Comment by raksooo** [comment]
This issue-tracker is for app related issues. Please contact our support team at support@mullvadvpn.net for other questions and issues.
