### ISSUE TITLE
Linux Fedora Update Slow Curl Error (28)

### ISSUE THREAD

**Issue by samuelps26** [mullvad/mullvadvpn-app#6982]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

When I try to update with ```sudo dnf update -y``` the download is very slow. Speed is at low KB/s.
This is only the case, when I am connected to a German Server, or when I am not connected to mullvad at all. I live in Germany so probably the same download server.
After some time I get the curl error (28) wich says, that not enough has been downloaded in the last 30s.

Current solution:
When I am connected to a Mullvad server in the USA download speed is good and normal. (I have not tried any other locations)
I guess the download server in Germany is pretty bad?

### Expected Behavior

Dowload speed should be in the MB/s area

### Steps to Reproduce

1. Try do dowload or update Mullvad on Linux from a German location.

### Operating system version

Fedora Linux 40

### Mullvad VPN app version

2024.5

**Comment by dlon** [comment]
Thanks. Closing this as it isn't app related, I'll ask internally.
