### ISSUE TITLE
Reconnecting to VPN with advanced split tunneling does not restart nftables service

### ISSUE THREAD

**Issue by JohnnyRacer** [mullvad/mullvadvpn-app#7021]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

I have setup `nftables` to perform split routing for SSH traffic from [this guide from the Mullvad website](https://mullvad.net/en/help/split-tunneling-with-linux-advanced), and it works as expected. However, I noticed whenever the VPN connection was restarted the rules set by `nftables` would be ignored and SSH traffic would be blocked. This is amended by restarting the `nftables` service utilizing `systemctl restart  nftables.service`. 

### Expected Behavior

The `nftables.service` should be restarted on VPN connection change if it is present to facilitate split tunneling.

### Steps to Reproduce

`mullvad-vpn reconnect`
`sudo systemctl restart  nftables.service`
### Operating system version

Linux 5.15

### Mullvad VPN app version

mullvad-cli 2024.5

**Comment by dlon** [comment]
Precisely what rules are you adding to nftables, if you don't mind sharing?

Disconnecting/reconnecting should not affect any existing rules, unless they're in tables used by the app itself.

**Comment by JohnnyRacer** [comment]
This is the `/etc/nftables.conf`:
```
#!/usr/sbin/nft -f

include "/etc/nftables-migrate/localpassthrough.nft"
include "/etc/nftables-migrate/ruleset.nft"

flush ruleset

table inet filter {
	chain input {
		type filter hook input priority 0;
	}
	chain forward {
		type filter hook forward priority 0;
	}
	chain output {
		type filter hook output priority 0;
	}
}
```

Contents of `/etc/nftables-migrate/localpassthrough.nft`. Marks any local LAN IPs to be split and avoid the VPN tunnel.
```
table inet excludeTraffic {
  chain excludeLocal {
    type route hook output priority 0; policy accept;
    ip daddr 192.168.0.0/16 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
    ip daddr 10.0.0.0/8 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
    ip daddr 172.16.0.0/12 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
    ip daddr 127.0.0.0/8 ct mark set 0x00000f41 meta mark set 0x6d6f6c65; # loopback
  }
}

```

The '/etc/nftables-migrate/ruleset.nft' is just translated from the default `iptables` and does not influence the behavior of split tunneling for the VPN.

**Comment by dlon** [comment]
Are you sure that `systemctl restart nftables.service` does not flush the rules added by Mullvad? Given that you have `flush ruleset` in `/etc/nftables.conf`.

You need to allow inbound traffic to exclude SSH, and also make sure that the priority is low enough. Adapted from the guide:

```
table inet excludeTraffic {
  chain allowIncoming {
    type filter hook input priority -100; policy accept;
    tcp dport 22 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
  }
 
  chain allowOutgoing {
    type route hook output priority -100; policy accept;
    tcp sport 22 ct mark set 0x00000f41 meta mark set 0x6d6f6c65;
  }
}
```

**Comment by dlon** [comment]
Hope this helps. Please reopen the thread if you still believe I am mistaken.

**Comment by JohnnyRacer** [comment]
@dlon Strangely everything works fine if I just enable the `Local network sharing` option on the desktop app, no need to restart the `nftables` service, maybe the app was just overwriting the rules with this option off?
