### ISSUE TITLE
[Feature request] Setting the multihop entry server from cli

### ISSUE THREAD

**Issue by ghost** [mullvad/mullvadvpn-app#7023]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I'm not clear if I'm overlooking this, from what I've seen looking at the documentation and testing, it seems that it is only possible to specify the exit server when using multihop with cli. This is not desirable, as it can result in very inefficient routes.

### Alternative solutions

It seems that when multihop is activated it usually sets the previous location as the entry, but this has not always been the case.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by MrChocolatine** [comment]
https://mullvad.net/en/help/cli-command-wg

<img width="843" alt="image" src="https://github.com/user-attachments/assets/3e9d8766-14a2-4200-8461-22e2aca0e9d5">
