### ISSUE TITLE
Debian repository not signed

### ISSUE THREAD

**Issue by nwa573** [mullvad/mullvadvpn-app#7048]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

I followed the instructions at https://mullvad.net/en/help/install-mullvad-app-linux to add the stable repository, but when I run `sudo apt update` I get

W: GPG error: https://repository.mullvad.net/deb/stable bookworm InRelease: Unknown error executing apt-key
E: The repository 'https://repository.mullvad.net/deb/stable bookworm InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

### Expected Behavior

`sudo apt update` runs successfully

### Steps to Reproduce

Follow the Debian instructions at https://mullvad.net/en/help/install-mullvad-app-linux

### Operating system version

Debian 12.7

**Comment by faern** [comment]
We had apt repository server issues in parts of the world yesterday. Please try again today and see if it works better! Our repositories are signed.

**Comment by nwa573** [comment]
I'm still getting the same error. Is there any more debug info I can give you?

**Comment by strykenKN** [comment]
the same problem also exists under Ubuntu. I have already reported it here, but nobody seems to be interested, for whatever reason.

**Comment by nwa573** [comment]
I figured out the issue: my /usr/share/keyrings/mullvad-keyring.asc had permissions 0600; changing it to 0644 fixes things.
