### ISSUE TITLE
Accrescent

### ISSUE THREAD

**Issue by Jeffrey2307** [mullvad/mullvadvpn-app#7056]
### I have checked if others have suggested this already

- [ ] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

hey i would love to see the App on Accrescent Store (which is the most secure and private Store and better solution than Github) maybe you can apply there, because it would be the best and better solution and I would love to see you Guys there

### Alternative solutions

It would be more secure and private for the users

### Type of feature

- [X] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Rawa** [comment]
Issue already exists:
https://github.com/mullvad/mullvadvpn-app/issues/5606

**Comment by MrChocolatine** [comment]
>  I have checked this issue tracker to see if others have reported similar issues.

It does not seem you did.
