### ISSUE TITLE
OpenVPN & Multihop

### ISSUE THREAD

**Issue by Jeffrey2307** [mullvad/mullvadvpn-app#7057]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Hey I would love to see OpenVPN and Multihop on Android.

### Alternative solutions

Lockdown Mode like on Desktop would be nice too.

### Type of feature

- [X] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Jeffrey2307** [comment]
I know that but I hoped that it could come in the App

**Comment by MrChocolatine** [comment]
They recently confirmed multihop in mobile apps is coming, but for Wireguard:
https://github.com/mullvad/mullvadvpn-app/issues/6011#issuecomment-2410240825

**Comment by Jeffrey2307** [comment]
Oh okay thank you. I'm wondering if OpenVPN is not in the Android App, because it makes the Internet slower...

**Comment by MrChocolatine** [comment]
> I'm wondering if OpenVPN is not in the Android App

It is not indeed.

**Comment by Jeffrey2307** [comment]
I know and my guess is because of the latency...

**Comment by faern** [comment]
OpenVPN was not written with mobile devices in mind. WireGuard lends itself much better to network roaming, battery saving etc. OpenVPN needs to keep a constant connection alive etc.

We are not aiming to support OpenVPN on mobile. However, we are adding multihop and as many features as possible to the WireGuard tunneln on Android.
