### ISSUE TITLE
[Feature request] Mullvad as UnifiedPush distributor

### ISSUE THREAD

**Issue by serrq** [mullvad/mullvadvpn-app#7080]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

I was looking for a good UnifiedPush distributor (provider) and so I thought:

Why not Mullvad as safe service to push notifications over my devices (Element X needs of a distributor to run notifications service).

### Alternative solutions

No idea.

### Type of feature

- [X] Better privacy/anonymity
- [X] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [X] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by MarkusPettersson98** [comment]
Please, refrain from opening issues that are not related to the app here on GitHub. Feel free to contact us in some other way, but this is not the right place to request new products or services from Mullvad.
