### ISSUE TITLE
Verification and IP-Problem

### ISSUE THREAD

**Issue by PrivacyAndSecurity** [mullvad/mullvadvpn-app#7196]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Hey,

since a few Days I have this Problem that when I watch a bit YouTube Videos, I can't watch anymore, because it says, that I should login. I need to always close the Browser and then it works again, until a bit and then it happens again. And these are even not fsk 18 Videos. I don't know how this happens and I checked my VPN and tried to turn off most, but it don't change anything. And I have this Problem that sometimes I can't access YouTube because it says something about IP-Adress and I nedd to click several times in DuckDuckGo that it works finally again. I really don't know why these boths happen.

### Expected Behavior

I expected it to stop after trying again but sometimes it won't stop even tho I have nothing turned off that would cause this...

### Steps to Reproduce

Watching a bit/a lot YouTube Videos and when clicking on another Video it says that I should login and no Video can be opened in this moment. Every Video says that I should login. Only closing the Browsers fixes it sometimes or it came back after a bit of time.

### Android version

14

### Device model

XIAOMI POCO X3 NFC

### Mullvad VPN app version

2024.8

### Additional Information

It is like that since a few Weeks as I remember. But mostly since one to maximum to weeks. And I just got the standard settings. I even turned off dns content blockers but sometimes it happens still. I don't know why or what is causing that but it is not from the Browser, because it only did go fully away when I disconnected the VPN...I don't know if YouTube is going more aggressive now against VPN Clients but I noticed that after last Mullvad VPN Update or maybe the one before, that it happened after that.

**Comment by MarkusPettersson98** [comment]
Hi, thanks for reaching out! This seems more like an issue with the services that you use (YouTube) that they require you to login, presumably because they detect that you are connected to a VPN and want to identify you anyway. 

The easiest suggestion is to try different VPN servers and see if some work better than others. If you find a set of server that work well for you intended use case, you can cureate them in a dedicated custom list so that they are easily accessible in the Mullvad VPN app. 

If you are using Firefox and/or Chrome you can route YouTube traffic through one of our SOCKS5-proxies which might work better against services detecting that you are connected to a VPN: https://mullvad.net/en/help/socks5-proxy

I will close this issue since it is not app related. If you have further question, we might have a guide on our webpage: https://mullvad.net/en/help/guides. If you need further assistance, please contact our support.

**Comment by MarkusPettersson98** [comment]
No problem! I updated my reply with a link to our browser extensions which makes it very easy to use different SOCKS5-proxies per website :blush: Good luck!

**Comment by MarkusPettersson98** [comment]
> Thanks for the information @MarkusPettersson98. However I have a question. The guide's Firefox configuration reads:
> 
> > 7. To prevent DNS leaks you can enable Proxy DNS when using SOCKS v5. However note that the DNS content blockers in the Mullvad app won't work if you enable this setting.
> 
> Since I have no experience with SOCKS proxies, this made me wonder. If that option _isn't_ checked, or if I'm using _another software without such an option_, does that mean DNS leaks are expected when using a SOCKS proxy?
> 
> My use case is a third-party YouTube client which can have SOCKS configured for it. Would all the client's DNS requests now be exposed? Or will the DNS requests still use the system's DNS?
> 
> The guide raised my concerns by the passing comment I quoted above.
> 
> Thanks.
Hi, and thanks for your question!

In general, without interacting with the system's routing table (and preferably firewall), programs will most likely delegate DNS requests to the operating system. Some programs may perform DNS requests in other ways, such as forwarding them over a VPN or SOCKS5-proxy instead. Note that the forwarding itself does not necessarily need DNS to work, i.e. if the VPN/SOCKS5-proxy server has a static IP address.

Firefox's built-in SOCKS5 proxy can optionally proxy DNS (enabled by default afaict). This means that whenever the *browser* makes DNS requests, it can choose to make DNS lookups with or without the configured proxy, depending on how it has been configured. If another program performs a DNS request, firefox can not intervene and proxy their DNS request over SOCKS5.

In your case, if the program has built-in support for running a SOCKS5 proxy it can instead forward all of its traffic (including DNS) to the SOCKS5-server, thus delegating the task of performing DNS lookups to the server instead. As with firefox, it will probably not configure routes to make all system DNS requests go through the SOCKS5 proxy. This should be checked using a tool like Wireshark to confirm that it is working properly :blush:

Hope that helps! Happy new year :fireworks:
