### ISSUE TITLE
[Feature request] Publish Mullvad VPN on the Mac App Store

### ISSUE THREAD

**Issue by duck09** [mullvad/mullvadvpn-app#7228]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Consider publishing Mullvad VPN on the Mac App Store for two reasons:

- Will close https://github.com/mullvad/mullvadvpn-app/issues/4946 as using the macOS sandbox is a requirement for publishing an app on the Mac App Store. Sandboxing is a great security feature that can limit damage done to the user's system in case the app is compromised somehow.

- Will close https://github.com/mullvad/mullvadvpn-app/issues/6007 as the Mac App Store provides an auto-update mechanism making the update experience less clunky for macOS users.

### Alternative solutions

None.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [X] macOS
- [ ] Linux

**Comment by MarkusPettersson98** [comment]
Hi, thanks for the suggestion! We do not have this planned currently, but it is definitely something we have been talking about. I will close this issue in favor of the already existing issue https://github.com/mullvad/mullvadvpn-app/issues/3658, but thanks for posting some related issues here! :blush:

**Comment by MarkusPettersson98** [comment]
No problem, it happens to the best of us :D
