### ISSUE TITLE
[Feature Request]: Block potential of code injection via macOS' dynamic linker for improved security

### ISSUE THREAD

**Issue by duck09** [mullvad/mullvadvpn-app#7236]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

The user can enable a column in Activity Monitor to check for a flag called "Restricted" which is a flag that prevents programs from injecting code via macOS's [dynamic linker](https://pewpewthespells.com/blog/blocking_code_injection_on_ios_and_os_x.html). Ideally, this flag should be set for MullvadVPN to prevent code injection, but it is not.

### Alternative solutions

None.

### Type of feature

- [ ] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [ ] Easier to use
- [X] Other

### Operating System

- [ ] Android
- [ ] iOS
- [ ] Windows
- [X] macOS
- [ ] Linux

**Comment by faern** [comment]
I'm not sure I understand what this would protect against in practice? The attack, as I understand it, is if someone/something malicious runs the `mullvad-daemon` system service, the `mullvad` CLI, or the Electron frontend with environment variables set in such a way that the programs load malicious code from some shared library. For the attacker to succeed with this they would need to:
1. Place a shared library with the malicious code on the victim's machine
2. Be able to run processes on the victims machine. In the case of `mullvad-daemon` they even need to be root for it to do anything.

If an attacker can place binaries and run processes on the victim's machine, they are already compromised way beyond having their VPN tunnel settings or state changed.

Our security docs at https://github.com/mullvad/mullvadvpn-app/blob/main/docs/security.md#desktop-system-service mention this in passing as:
> Locally running malicious programs are outside of the app's threat model.

I'm closing this as out of scope. But if you feel this is a security risk in any way, please feel free to explain further how this could be a risk for a user of this app.
