### ISSUE TITLE
Remove notifications for the Beta releases.

### ISSUE THREAD

**Issue by Mr-Bajs** [mullvad/mullvadvpn-app#7295]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Been using MullvadVPN for Linux Mint. However sence Mullvad 2024.9-Beta1 my desktop gives me these notifications from the applet. 
I don't think apps in general should give continous notifications or mark the app as outdated just because the devs developed an beta. It sort of goes against the conventions of what an beta release is. I have no problem with warnings and notifications if i have an outdated version. 

Sure what an beta release is sort of arbitary term but from an user perspective an beta is a bug testning version of the comming release and in general not considerd as an stable version. Going beta should be an informed active decision of the user part and not by wrongfully make the user think it's running out of date version if it's not.

### Expected Behavior

.

### Steps to Reproduce

1. ...
2. ...
.

### Operating system version

Linux Mint 22

### Mullvad VPN app version

2024.8

**Comment by Serock3** [comment]
Hello! The update notification for the new beta version only appears if you are part of the beta-program. You can disable it by going to Settings -> support -> Beta program

![image](https://github.com/user-attachments/assets/4a08c10a-8f0e-44ad-a726-ad07aa824d82)

**Comment by BubiBalboa** [comment]
I came here with the same problem.

Why would this setting be under "Support" and not under UI Settings/notifications? 

It's very unusual to have any settings at all on the "Support" page of an app. I promise you there are tons of people annoyed with the beta notifications that can't find the setting to turn them off. 

Please consider moving this setting to a more intuitive place in the app.
