### ISSUE TITLE
[Feature request] Automatic Wireguard Key rotation 

### ISSUE THREAD

**Issue by pflanzenandi** [mullvad/mullvadvpn-app#7298]
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Add timer e.g. 24h for an automatic Wireguard Key rotation on the same device.

### Alternative solutions

Manually logout and reconnect to create a new device.

### Type of feature

- [X] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [ ] iOS
- [ ] Windows
- [ ] macOS
- [X] Linux

**Comment by MrChocolatine** [comment]
Wireguard keys are already automatically rotated on desktop and mobile.
On desktop you can customise the interval via their CLI.

https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2023.1
https://mullvad.net/en/help/cli-command-wg#other-commands
