### ISSUE TITLE
Docker port unreachable when the VPN is active (using wireguard)

### ISSUE THREAD

**Issue by yamrzou** [mullvad/mullvadvpn-app#733]
I am running an nginx container and mapping the container's port 80 to host port 8090 (using [this docker-compose.yml](https://github.com/webrecorder/webrecorder/blob/master/docker-compose.yml)  actually). If I activate the vpn via `wg-quick up mullvad-***` I can no more access `http://localhost:8089/`. Running `wg-quick down mullvad-***`, the app is again accessible. Not sure if it is a problem with the Wireguard configuration file or the docker-compose.yml file. 

Any idea what's going on?

**Comment by faern** [comment]
This repository (and its issues) is only for the Mullvad VPN app, not vanilla Wireguard, which `wg-quick` is a part of. Please contact support@mullvad.net for help with vanilla Wireguard.
