### ISSUE TITLE
Constantly getting asked to log in on YT to show " i'm not a bot "

### ISSUE THREAD

**Issue by moussechoco** [mullvad/mullvadvpn-app#7349]
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Using wireguard protocol from france location ( not happening on OpenVPN for now ) , i can't watch YT videos anymore without switching to some weird and unusual locations ( to me ) . Didn't happen before.
I am now receiving a message that asks me to log in to show i am not a bot.
Is there anything you could do on your side for that ? I tried using sock5 protocol, and everything i could.

Regards.

### Expected Behavior

Not being blocked by youtube using wireguard protocol.

### Steps to Reproduce

1. Connect from france and Bordeaux servers

2/. Try to watch a youtube video.

### Operating system version

Windows 10

### Mullvad VPN app version

2023.4

**Comment by dlon** [comment]
Hello! This question is best handled by our support team since it's not about the app itself. You can reach them by either using the "Report a problem" feature in the app or by sending an email to support@mullvadvpn.net.

**Comment by MrChocolatine** [comment]
I know this issue has been closed, but I simply wanted to say this is rather a global issue affecting more people than just Mullvad VPN

Using Youtube-dl, we/I have been dealing with that issue for several months now:
https://github.com/ytdl-org/youtube-dl/issues

The only workaround I have found is to switch servers, until I am lucky.
