### ISSUE TITLE
Connecting to daemon issue

### ISSUE THREAD

**Issue by therealearthe** [mullvad/mullvadvpn-app#766]
W: mullvad-vpn: hardening-no-relro opt/Mullvad VPN/libffmpeg.so
E: mullvad-vpn: embedded-library opt/Mullvad VPN/libnode.so: zlib
E: mullvad-vpn: embedded-library opt/Mullvad VPN/libnode.so: openssl
W: mullvad-vpn: hardening-no-relro opt/Mullvad VPN/libnode.so
E: mullvad-vpn: embedded-library opt/Mullvad VPN/mullvad-vpn: freetype
E: mullvad-vpn: embedded-library opt/Mullvad VPN/mullvad-vpn: libpng
E: mullvad-vpn: embedded-library opt/Mullvad VPN/mullvad-vpn: srtp
E: mullvad-vpn: embedded-library opt/Mullvad VPN/mullvad-vpn: libjpeg
W: mullvad-vpn: hardening-no-relro opt/Mullvad VPN/mullvad-vpn
E: mullvad-vpn: unstripped-binary-or-object opt/Mullvad VPN/resources/libtalpid_openvpn_plugin.so
E: mullvad-vpn: embedded-library opt/Mullvad VPN/resources/mullvad-daemon: openssl
E: mullvad-vpn: embedded-library opt/Mullvad VPN/resources/openvpn: openssl
E: mullvad-vpn: embedded-library opt/Mullvad VPN/resources/problem-report: openssl
E: mullvad-vpn: missing-dependency-on-libc needed by opt/Mullvad VPN/libffmpeg.so and 7 others
E: mullvad-vpn: non-etc-file-marked-as-conffile opt/Mullvad VPN/resources/mullvad-daemon.conf
E: mullvad-vpn: non-etc-file-marked-as-conffile opt/Mullvad VPN/resources/mullvad-daemon.service
E: mullvad-vpn: no-copyright-file
E: mullvad-vpn: description-synopsis-is-empty
W: mullvad-vpn: description-starts-with-leading-spaces
W: mullvad-vpn: unknown-section default
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/LICENSE.electron.txt
W: mullvad-vpn: extra-license-file opt/Mullvad VPN/LICENSE.electron.txt
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/LICENSES.chromium.html
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/blink_image_resources_200_percent.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/content_resources_200_percent.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/content_shell.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/icudtl.dat
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/libffmpeg.so
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/libnode.so
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/am.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ar.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/bg.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/bn.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ca.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/cs.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/da.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/de.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/el.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/en-GB.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/en-US.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/es-419.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/es.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/et.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/fa.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/fake-bidi.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/fi.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/fil.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/fr.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/gu.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/he.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/hi.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/hr.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/hu.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/id.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/it.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ja.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/kn.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ko.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/lt.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/lv.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ml.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/mr.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ms.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/nb.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/nl.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/pl.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/pt-BR.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/pt-PT.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ro.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ru.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/sk.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/sl.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/sr.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/sv.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/sw.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/ta.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/te.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/th.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/tr.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/uk.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/vi.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/zh-CN.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/locales/zh-TW.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/mullvad-vpn
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/natives_blob.bin
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/CHANGELOG.md
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/api_root_ca.pem
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/app.asar
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/ca.crt
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/electron.asar
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/libtalpid_openvpn_plugin.so
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/mullvad-daemon
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/mullvad-daemon.conf
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/mullvad-daemon.service
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/openvpn
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/problem-report
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/resources/relays.json
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/ui_resources_200_percent.pak
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/v8_context_snapshot.bin
E: mullvad-vpn: dir-or-file-in-opt opt/Mullvad VPN/views_resources_200_percent.pak
W: mullvad-vpn: binary-without-manpage usr/bin/mullvad
E: mullvad-vpn: unknown-control-interpreter control/postinst #!/usr/bin/env
E: mullvad-vpn: forbidden-postrm-interpreter #!/usr/bin/env
E: mullvad-vpn: unknown-control-interpreter control/preinst #!/usr/bin/env
E: mullvad-vpn: unknown-control-interpreter control/prerm #!/usr/bin/env
E: mullvad-vpn: shlib-with-executable-bit opt/Mullvad VPN/libffmpeg.so 0755
E: mullvad-vpn: shlib-with-executable-bit opt/Mullvad VPN/libnode.so 0755

Lintian finished with exit status 1

This is the lintian output for the latest version. The app installs, but then when I launch it it gets stuck to "Connecting to daemon". Using MX Linux WITH systemd.

**Comment by faern** [comment]
There is one known bug in the 2019.1 release regarding the UI connecting to the daemon. You could try the 2019.2-beta1 release and see if that fixes your issue: https://mullvad.net/download/beta/

That lintian output does not say why it fails to connect to the daemon. We would need `frontend.log` and possibly `daemon.log` from `/var/log/mullvad-vpn`. That also includes which version of the app you are running, which is also crucial in figuring out what problem you are having.

But this issue tracker is not really for help with using the app. Please contact support@mullvad.net for that. You can even send an automated problem report from within the app. Then our support will get the logs they need along with a custom message from you, describing the issue.

**Comment by therealearthe** [comment]
Ok, thanks for getting back. I thought it might help you guys discover the root problem. I'm using the latest version of the app, tried the beta, same outcome. I've sent a log from within the app too. You can close this, thank you.
