### ISSUE TITLE
[BUG] 2019.2 Installation: Fatal error during driver initialization: Failed to initialize plugin 'driverlogic': 0x0002D521

### ISSUE THREAD

**Issue by Clouds123** [mullvad/mullvadvpn-app#775]
As per title, during installation of 2019.2 I get a driver initialization error.

2019.1 installs fine.

**Comment by faern** [comment]
Thanks for reporting this.

Is this under Windows 7? If so, yes we have had multiple users report this error under that OS, and we are looking into the problem.

**Comment by Clouds123** [comment]
Windows 8.1 x64

**Comment by Moto68k** [comment]
Also experiencing the same issue, also on Windows 8.1 x64

**Comment by Diazonium** [comment]
Can confirm that this issue affects Windows 7. The installer seems to be unable to start the driver installation. I have a feeling that this is probably code/diver signing related, maybe older Windows versions lack the necessary cert, and thus unable to trust the driver sig?

**Comment by mvd-ows** [comment]
Fixed in 2019.3
