### ISSUE TITLE
[Feature Request] Split VPN traffic

### ISSUE THREAD

**Issue by hackedbyhackerman** [mullvad/mullvadvpn-app#781]
Im in need to be able to split my internet traffic. 

Lets say im gaming and a port is blocked on the VPN network, I then want my normal internet to act as the main source of internet for that application only (in this case, the game). 
Or sites that dosent allow VPN. I wanna then split my traffic to that application. 

This is a feature me and my friends and probably a lot more people want.

Thanks for all the hard work on this VPN!

**Comment by faern** [comment]
Hi. Thanks for the feedback. Split tunneling is what we call this feature, and it's on the roadmap. It will likely not allow you to split per application, but rather configure certain IP ranges to go outside the tunnel though. I can't give any estimate to when this might be implemented.

**Comment by hackedbyhackerman** [comment]
Nice! Thanks for letting us know @faern !

Being able to split per application would be very welcome tough! :)

**Comment by pundoo** [comment]
@faern This feature would be super useful. Please prioritize it if possible.
Meanwhile, when I set static routes to exclude some IP ranges from going through the VPN tunnel, how come it doesn't work? Is there some kind of a bug?

**Comment by faern** [comment]
@pundoo Because our leak protection makes sure nothing can leave the computer outside of the tunnel. In this case it's the firewall blocking all packets not going directly to the VPN server you are currently connected to.

**Comment by BRKsays** [comment]
Hi @faern , I have a situation where my (android) phone's ISP (Jio, India) has a TV app and the app will only stream live tv channels on the ISP's network. So using both the VPN and the TV is currently not possible. Would you kindly consider at least the option to exclude certain apps from the the vpn tunnel and let those app use the ISP network?

**Comment by mwelsch-tgm** [comment]
@BRKsays on your mobile device the wireguard app lets you exclude certain apps from the tunnel. Just download a wireguard config, edit the conf, tap on excluded apps, select your TV app amd save your settings. You can do the same with tunsafe iirc

**Comment by Mikaela** [comment]
I am having this problem with [Yggdrasil network](https://yggdrasil-network.github.io/) on Debian, whenever I `mullvad connect`, I stop having access to `0200::/7` which it squats on and pinging an Yggdrasil address results to `ping: sendmsg: Operation not permitted`.

Yggdrasil is a IPv6 mesh network that can also be used across the internet and I like how it gives me faster access to hosts behind CGNAT than Tor onion services (that I use as backups) and being IPv6 addresses I can give them more memorable names and use SSHFP records. Another benefit is that I can use the same address wherever I am having faster connections when both devices are on the same LAN.

I think this issue will also affect [Cjdns](https://github.com/cjdelisle/cjdns/blob/master/README.md) which is a similar project on `FC00::/8`.

**Comment by bradynpoulsen** [comment]
I'm needing this on a blacklist application basis (ie, Netflix, Hulu, Disney+, etc). Are there any reasons it is explicitly being avoided as described above?
I'm currently able to perform this using many other official VPNs (WireGuard, OpenVPN, OpenConnect, Cloudflare Warp, etc).

**Comment by Mikaela** [comment]
Has there been development towards supporting split VPN traffic?

I have ended up to situation where I have one laptop without Mullvad so I can access `0200::/7` for NATted family devices [outside of COVID-19 locked down region](https://www.poliisi.fi/coronavirus_info/restrictions_on_movement), maintain firewalled host outside of walking distance etc.

While I am managing, split VPN traffic would be more convenient for me and I imagine it would be practical in some working from home scenarios.

**Comment by faern** [comment]
It is being actively worked on for Linux and Windows currently. But it will be app based and not IP range based. So we will allow excluding certain applications from the tunnel, not say`0200::/7`.

**Comment by Mikaela** [comment]
Thank you :purple_heart:

Do I understand app based correctly that I will be able to e.g. let `/usr/bin/ssh` connect directly instead of it going through Mullvad or how will the apps be specified/identified? Will this be compatible with "Block when connection is not established" (sorry I am using the app in Finnish)?

I guess I will see when the feature is in release.

**Comment by Yumekui** [comment]
Got implemented in #1581

**Comment by AustinSHend** [comment]
How is this intended to be used? I'm on the 2020.5-beta2 release (compiled through [AUR](https://aur.archlinux.org/packages/mullvad-vpn-beta/)) and when calling
`sudo mullvad-exclude whoami` I get a result of `root`, when it should be dropping root privs before executing the following command. From the source code it seems that it's getting the user ID via getuid() and then using setuid() immediately after with the result, which won't trigger the built-in error but I suspect it's just getting a UID of "0" and then "dropping" to "0" again, instead of the regular user's UID. It seems to work fine otherwise, e.g. calling `sudo mullvad-exclude curl icanhazip.com` results in my non-VPN IP, but I'd rather not be giving root privs to arbitrary applications.

If this is dropping root privs on your machines successfully, maybe it is a local issue?

**Comment by Yumekui** [comment]
Tested it myself today. It doesn't seem to drop the root privileges for me neither. For now I am working around that by using `sudo mullvad-exclude sudo -u username command`.

**Comment by faern** [comment]
You are not supposed to call it with `sudo`. It does drop the privileges to whoever you call the program with. If you call it with `sudo` you call it as `root` and it will drop to `root`, which does not make any sense :)

Just like the `sudo` command itself `mullvad-exclude` has the `setuid` permission bit set. Meaning it will run as `root` (the file owner) even when called as another user. It then sets up the network splitting as `root` before dropping privileges to the original user again.

Just run it as `mullvad-exclude whoami` :)

**Comment by AustinSHend** [comment]
Running it without sudo doesn't work on my machine as it fails the permission check to set the cgroups.

**Comment by faern** [comment]
What if you manually run `sudo chmod u+s "/usr/bin/mullvad-exclude"` and then try again? Maybe the `setuid` permission bit was failed to be applied during install?

**Comment by AustinSHend** [comment]
I'm guessing that's probably the case. Maybe the AUR script needs to be updated with this step. I'm not at my normal machine at the moment but I'm spinning up a manjaro VM in a few minutes to check.

**Comment by Yumekui** [comment]
Manually setting the permission works for me. Since @AustinSHend and me  both use the AUR package, it could be an issue with that. I will spin up a ubuntu vm later and try it there.

**Comment by faern** [comment]
Ah, yes. You use the third party AUR stuff. I missed that detail. We don't officially support that. Hopefully they will updated that soon. Our own deb/rpm files sets the permission upon install.

**Comment by AustinSHend** [comment]
It's not so much an AUR issue as it just isn't in the build instructions. It probably should be soon for others to avoid this problem with manual compilation.

> Applications to exclude are instead supposed to be launched by running mullvad-exclude <file> <args>, which simply runs as root (**using the setuid flag**) in order to set the correct cgroup, and then drops root access before executing the file.

Could have potentially noticed this before and figured it out but yeah will have to notify the AUR maintainer to add this step and then at least the arch ecosystem will be working out-of-box.

**Comment by WeakTopology** [comment]
Instead of explicitly excluding programs, would it be possible to explicitly include them instead, with everything else avoiding the VPN?

Also, is there any online documentation for these features, e.g. `mullvad-exclude`? I couldn't find anything in the repo.

**Comment by faern** [comment]
> Instead of explicitly excluding programs, would it be possible to explicitly include them instead, with everything else avoiding the VPN?

We are currently not planning on implementing the inverse. The core of the app is designed around the idea that it will secure your entire computer and take control of every packet coming in and going out of it. And we have not seen much demand for just tunneling a few apps.

> Also, is there any online documentation for these features, e.g. mullvad-exclude? I couldn't find anything in the repo.

Not yet. Split tunneling is far from done. This is just a sneak peak more or less. We are working on introducing it to more platforms and it will be included in the GUI as well. When we get further with the feature it will be documented.

**Comment by WeakTopology** [comment]
> We are currently not planning on implementing the inverse. The core of the app is designed around the idea that it will secure your entire computer and take control of every packet coming in and going out of it. And we have not seen much demand for just tunneling a few apps.

Fair enough. That makes sense. FWIW one use case for the inverse would be a server that where only some services are required to go through the VPN.

**Comment by nalllen** [comment]
Here is another request for "reverse" split tunneling, i would like to only route a few programs through the vpn and let everything else run like normal.
quite annoying if you would have to select every single game to not use the vpn...

**Comment by Habush** [comment]
What's the status of split tunneling being part of the Mac app? I see the feature is supported for Linux and Android, any ETA for when it will be available on Mac or iOS? Thanks.

**Comment by faern** [comment]
macOS and iOS will be the last platforms to get this feature. We don't have an estimate for it yet, it's probably decently far in the future I'm afraid.

**Comment by crmb** [comment]
Any vague ETA for this (Windows) ? 2021 ? 
Trying to chose a VPN provider, this feature is a must.

**Comment by faern** [comment]
It is almost certain that this will land in 2021. Probably the first half of the year. We have an implementation that we are currently testing internally.

**Comment by kajlando** [comment]
Please consider supporting also IP split tunneling

**Comment by siavashnamiranian** [comment]
when vpn split will be add?

**Comment by WeakTopology** [comment]
> But yes, the plan is to be able to exclude a binary like for example ssh.

@faern Any advice on how to use split tunneling to make ssh connections bypass Mullvad (on Linux)? I tried modifying `/usr/lib/systemd/system/sshd.service`, changing

    ExecStart=/usr/bin/sshd -D

to

    ExecStart=/usr/bin/mullvad-exclude /usr/bin/sshd -D

Then

    # systemctl daemon-reload
    # systemctl restart sshd.service

But this didn't seem to work for me. (FWIW I tested with `mullvad-exclude curl icanhazip.com`, which works well.)

**Comment by faern** [comment]
The current solution does not allow splitting *listening sockets* that easily. The splitting is done on a per connection basis so the initial packet has to be outbound for the connection to be properly tagged as splitted. There are ways to work around this by manually setting up some firewall rules. I'll see if we can write some instructions for that and post here.

@pinkisemils ^

**Comment by pinkisemils** [comment]
To allow traffic from a specific port to bypass our firewall rules, you'll have to apply your own firewall rules that'll mark the traffic as _excluded_. 
```nft
table inet excludeTraffic {
  chain allowIncoming {
    type filter hook input priority -100; policy accept;
    tcp dport 22 ct mark set 0x00000f41;
  }
}
```
Write the rules to a file and then apply them via `sudo nft -f $pathToRules`. You might have to install `nftables` on Ubuntu or Fedora to have `nft` available.

**Comment by WeakTopology** [comment]
@pinkisemils That works brilliantly. Thank you!

**Comment by faern** [comment]
We have released a Windows beta with split tunneling support: [`2021.4-beta1`](https://github.com/mullvad/mullvadvpn-app/releases/tag/2021.4-beta1). So you can test it out now! Please report any issues, there likely are some given that it's still a beta.

Android and Linux already have split tunneling. So I'm going to close this issue now as it's too broad and most of what's requested here has been implemented now.

**Comment by WeakTopology** [comment]
@pinkisemils and @faern I've found that split tunnelling doesn't work fully in particular situations. For example, I have a work website that responds differently whether you connect directly via their network, or via an external ISP. When connected via their network, turning the VPN on obviously has the same result as if I were connected externally.

However, it seems that `mullvad-exclude firefox` doesn't fully replicate the "non-VPN" situation. I'm not entirely sure why, so I tested a few different things. I thought perhaps that when connected directly to their network (VPN totally disabled) their DNS was redirecting me to internal IPs? I tried turning VPN on, running `mullvad-exclude firefox`, then changing Firefox's Network Settings > "Enable DNS over HTTPS", set as their DNS. However this also failed. I guess I could create a virtual machine and `mullvad-exclude` the entire machine, but it seems a bit heavy (and I'm not even sure which DNS it would use). I'm not even sure if the DNS is the problem. Do you know of any other way to fully replicate "non-VPN" traffic?

**Comment by faern** [comment]
DNS is very messy, and at the moment DNS will go inside the tunnel even for excluded programs most of the time.

**Comment by WeakTopology** [comment]
@faern Ah bummer. Do you know if any browsers are capable of overriding this? Or some other alternative? I assume that the "DNS over HTTPS" setting in Firefox (and presumably Chome) isn't the right setting to be looking at?

**Comment by pinkisemils** [comment]
One hacky solution would be to use a hosts file to circumvent DNS altogether. You can also use our custom DNS setting to ensure that your work's DNS resolvers are used. You'd have to manually enable and disable this when connecting/disconnecting to your work's network. Bear in mind, when using custom DNS resolvers, you opt-in to leaking all of your DNS queries to the resolvers  you set yourself. 

As far as DNS over HTTPS goes, I presume that you want to reach a resolver that resides on the local network, and that resolver probably won't support DNS over HTTPS, in which case this won't be a good workaround.

**Comment by WeakTopology** [comment]
Thanks @pinkisemils. I hadn't noticed the custom DNS setting in the Mullvad app, but that works perfectly for my use case! I just put the Mullvad DNS `193.138.218.74` as the second custom DNS. It seems to work fine as a fallback, even though I'm using OpenVPN and I get the warning. It works fine even when I'm not on my work's network 🤷

**Comment by bhavints** [comment]
> To allow traffic from a specific port to bypass our firewall rules, you'll have to apply your own firewall rules that'll mark the traffic as _excluded_.
> 
> ```
> table inet excludeTraffic {
>   chain allowIncoming {
>     type filter hook input priority -100; policy accept;
>     tcp dport 22 ct mark set 0x00000f41;
>   }
> }
> ```
> 
> Write the rules to a file and then apply them via `sudo nft -f $pathToRules`. You might have to install `nftables` on Ubuntu or Fedora to have `nft` available.
> 
> EDIT: For the purposes of running sshd, you'd probably want these rules to be applied before `sshd` is started (although they can be applied after and sshd will still receive connections), so you'll probably want to create systemd unit to apply the rules during boot.

Hi, I am trying to apply this rule on an ssh client, but I keep getting "Connection refused" with the following rules. I verified the rules are active with nft list ruleset, and ssh works if I turn off VPN.

```
table inet excludeTraffic {
  chain allowIncoming {
    type filter hook input priority -100; policy accept;
    tcp dport 22 ct mark set 0x00000f41;
  }
  chain allowOutgoing {
    type filter hook input priority -100; policy accept;
    tcp sport 22 ct mark set 0x00000f41;
  }
}
```
