### ISSUE TITLE
macOS app reports 'Connection Not Secured' when "mullvad_exit_ip" is true

### ISSUE THREAD

**Issue by geekinaboxx** [mullvad/mullvadvpn-app#782]
On macOS version 2019.2

Steps to recreate:
* Set up a router to connect to Mullvad
* Verify (any) connection from a network client using https://am.i.mullvad.net/ (or the Mullvad API)
* Check the Mullvad macOS app. It will report 'unsecured connection' even though the client is connected to Mullvad via the router

Suggestion:
The macOS app should use the value of `mullvad_exit_ip` to determine whether to display 'unsecured connection' or 'secure connection'

**Comment by faern** [comment]
The status in the app, "unsecured connection", refers only to the state of the app on the device where it's running.

It would be very unsafe to just trust the `mullvad_exit_ip` of a request to am.i.mullvad.net. Say for example that you are on an evil network. They may route requests to am.i.mullvad.net via the VPN, to make it look like you go via VPN, but then they would route all other traffic outside of the VPN. Then the app would be lying if it said you were secure. Basically. If the app does not manage the tunnel on the computer, then it has no idea who has access to the packets as soon as they leave the computer.

The app will only say that the user is secure when it can reliably determine that all packets leaving the computer are encrypted and sent directly to a Mullvad relay, with no middle men.

**Comment by faern** [comment]
If you run Mullvad on your router and that is enough for your threat model. And you do not wish to have a tunnel-in-tunnel setup. Then you don't need to run the VPN app on your computer at all.

**Comment by geekinaboxx** [comment]
Thanks, @faern . I understand, now, why you wouldn't want to report the connection status in this way; makes sense. 

I wonder if there might be a case for a status 'between' red (unsecured) and green (secured) which, semantically, would mean "appear to be exiting via a Mullvad server, but could not verify that the app connection is secure". However, I know this would be confusing for users.

Perhaps the [SSID whitelist/blacklist mentioned here] (https://github.com/mullvad/mullvadvpn-app/issues/783) would be a good compromise here.
