### ISSUE TITLE
What protocol does this VPN use?

### ISSUE THREAD

**Issue by LuoZijun** [mullvad/mullvadvpn-app#80]
OpenVPN ?

**Comment by faern** [comment]
Yes. This program uses OpenVPN 2.4 underneath. With very strict encryption settings, only allowing a few of the strongest cipher suites etc.

**Comment by LuoZijun** [comment]
In some countries, the OpenVPN protocol is blocked.
Which means they can't connect to your server.

So, I think that is one dead protocol already. what do you say ?

**Comment by faern** [comment]
Yes. We are aware of this. There will be support for more protocols and other techniques in this app in the future.

Until then you can check out our website, https://mullvad.net. We support Wireguard and bridges and they work quite well in most censored countries. But that is of course if you do the setup yourself, and not use this app in its current state. Please contact support@mullvad.net for help and further questions related to Mullvad VPN services.

**Comment by LuoZijun** [comment]
As far as I know, the protocol used by Wireguard is running on UDP.
This means that this protocol faces three problems:

* UDP hole problem
* UDP traffic Control problem
* The protocol features obvious, can easily be blocked, just like OpenVPN fate

**Comment by LuoZijun** [comment]
If you ask me, what are the advantages of wireguard compared to OpenVPN in confronting Internet censorship?
My answer is: no advantage.

If you ask me, suppose I am a network censor, how easy is the shielding Wireguard protocol?
My answer is: "Very Easy".

**Comment by LuoZijun** [comment]
The good news is that I have a solution to the network protocol censorship.
But if the IP is blocked, I will be powerless.

**Comment by baimafeima** [comment]
> The good news is that I have a solution to the network protocol censorship.

@LuoZijun What obfuscation method do you recommend? To me, it looks like you are providing your own VPN services. Where in China are you based? I'll invite you for a cup of tea :) 

@faern It would be great to implement the openconnect protocol as too many companies rely on it and it cannot be blocked.

**Comment by LuoZijun** [comment]
@baimafeima 

> To me, it looks like you are providing your own VPN services.

For some legal considerations, this cannot happen.

> Where in China are you based? I'll invite you for a cup of tea :)

首先我让我的朋友分析了一些你的文本样本, 他告诉我, 他可以确定你所说的英文是中式英文(这不是贬义).

另外, 你提到"喝茶", 这在中文语境里面有着非常复杂的意义.

所以在这种情况下, 我无法告诉你更多关于我的信息.

First of all, I asked my friend to analyze some of your text samples. He told me that he can confirm that the English you speak is Chinese-English (this is not pejorative).

In addition, you mentioned "drinking tea," which has a very complicated meaning in the Chinese context.

So in this case, I can't tell you more infomation about me.

** From Google Translate **
