### ISSUE TITLE
[Feature Request] Blacklist Websites/URLs

### ISSUE THREAD

**Issue by nikolayhg** [mullvad/mullvadvpn-app#807]
Is it currently possible to blacklist websites or URLs with the app and how? If not, do you plan to add this feature?

**Comment by pronebird** [comment]
Black list for what purpose? Parental control? If so, I suppose there are better tools to achieve that.

**Comment by nikolayhg** [comment]
not parental control. I want to block access to certain websites, but if I do it on the application level, I would need to do that in all apps that may access them. If it could be done in the VPN client, that would be much easier and cleaner.

**Comment by faern** [comment]
The app does not deal with the application level stuff at all currently. We don't do any packet inspection etc.

Only way I see we could reasonably deal with this is by intercepting DNS and give bad answers for blocked domains. That could solve it for whole domains. But there is no way we could be doing it for individual URLs within a given domain.

**Comment by nikolayhg** [comment]
thanks for the feedback!

I decided to go for the app level controls, because it can be done now and this feature might not be of the most relevant and important. Closing the issue, if another user requests, I can reopen it.
