### ISSUE TITLE
No System tray icon in Gnome 3.32.0

### ISSUE THREAD

**Issue by Bendodroid** [mullvad/mullvadvpn-app#812]
I'm using Manjaro 18.0 with the 5.0.7-1 Kernel, the most recent updates and the 2019.3 version of the Mullvad app.

When starting the Mullvad app, there is no tray icon, it behaves like a standard application window, not like an app that sits in the system tray.
![image](https://user-images.githubusercontent.com/26770477/55961121-74f6cc80-5c6e-11e9-9b7c-6b8a2d8e0949.png)

It seems to be the issue since the tray-thing changed in Gnome (3.30?).
Quite annoying to open the app manually and drag it around like a normal window.

**Comment by faern** [comment]
Thanks for reporting this

**Comment by articlecat** [comment]
The issue persists on GNOME 3.34.1. The tray icon is missing on both X.Org and Wayland.

**Comment by Taijian** [comment]
This is not a Mullvad issue, this is a Gnome issue. You probably need to install a shell extension to display the tray icon, because Gnome has removed native support for them some releases ago. 

Try to use this: https://extensions.gnome.org/extension/615/appindicator-support/ - this works for me on gnome-shell 3.34.1 (wayland).

**Comment by Taijian** [comment]
Or, if you already have that, you are probably missing libappindicator-gtk2 - Mullvad is unfortunately still tied to some really old libs - gtk2, gconf <- python2...

**Comment by articlecat** [comment]
Using libappindicator-gtk3 as the dependency instead of libappindicator-gtk2 fixed the issue. Thanks!

**Comment by faern** [comment]
Thanks for verifying this. I'll see about getting `libappindicator-gtk3` listed as a default dependency for our deb/rpm artifacts :+1:

**Comment by faern** [comment]
Hmm.. The question is if we really want to add this as a hard dependency on all Linux platforms though. On my Fedora machines the app works fine without any `libappindicator*` package installed.

**Comment by nlordell** [comment]
> On my Fedora machines the app works fine without any libappindicator* package installed.

`libappindicator-gtk3` is part of the base Fedora install image (at least Fedora 31). At least for the RPM it can be added as a weak dependency.

**Comment by nlordell** [comment]
I see this problem as well in Fedora 31. `dnf install libappindicator-gtk3` also solves the problem. Note that for RPMs, the `libappindicator` dependency can be added as a "weak dependency".

**Comment by mjlbach** [comment]
I had to install libappindicator on fedora 33 in order to see the tray icon

**Comment by hulthe** [comment]
IIRC the Electron app depends on GTK3 nowadays. Is anyone here still experiencing this issue? If so, I'll reopen.
