### ISSUE TITLE
connot connect. out of time error while i have a fresh account number

### ISSUE THREAD

**Issue by jkmpariab** [mullvad/mullvadvpn-app#824]
*error:
"out of time 
you have no more vpn time left on this account. to by more credit on our website, you will need to access the internet with an unsecureed connection."

while i tried new freshed account many times on my "windows 10" and "windows 7" and ubuntu 18.04 but error is the same.

*version: 2019.3

please resolve this problem or show a work around
i need this vpn

**Comment by faern** [comment]
Please log in to your account on https://mullvad.net/ and check that you have time left on it. If you indeed have time left on the account, then please send a problem report to our support through the app. The problem report tool can be found under the settings (cog wheel icon)

**Comment by jkmpariab** [comment]
> Please log in to your account on https://mullvad.net/ and check that you have time left on it. If you indeed have time left on the account, then please send a problem report to our support through the app. The problem report tool can be found under the settings (cog wheel icon)

i logged in my fresh account number on mullvad.net and it says "Expired: 19 April 2019". but i obtained the account number just about a minute ago. what should i do now?

**Comment by pundoo** [comment]
@jkmpariab It appears they have discontinued the '3 HOUR TRIAL' feature. So you have to pay now!

@faern Can you confirm the trial discontinuation? I couldn't find any official statements regarding this. (or could it simply be just a bug on the server-side?)

**Comment by faern** [comment]
We are evaluating the trial accounts existence. So it's true that currently newly created accounts are not credited with three hours automatically.

I'm closing this issue since it's not app related, but rather a lack of credit on the account.
