### ISSUE TITLE
[Features Request] Snap Support

### ISSUE THREAD

**Issue by scafroglia93** [mullvad/mullvadvpn-app#847]
To evaluate the possibility of inserting the app inside Snap so as to have rapid updates

**Comment by vladimiry** [comment]
It's quite possible to pack the Electron-based app to the Snap container.

By the way, [electron-builder](https://github.com/electron-userland/electron-builder) just recently has got a significant Snap package preparing improvement with [20.44.1](https://github.com/electron-userland/electron-builder/releases/tag/v20.44.1) release.
