### ISSUE TITLE
[Feature Question] Wireguard for windows

### ISSUE THREAD

**Issue by l3jyeo** [mullvad/mullvadvpn-app#866]
Hello,

This blog post at https://mullvad.net/en/blog/2019/3/29/new-app-version-brings-wireguard-one-step-closer/ says that "support for Windows will be added as soon as WireGuard's official Windows release is available." Since Wiregaurd for windows is released now, is there going to be work putting Wireguard into windows client?

**Comment by faern** [comment]
Yes, we are working on that. It will be ready when it's ready.
