### ISSUE TITLE
[Feature Request] See which programs are using bandwidth

### ISSUE THREAD

**Issue by JimmyCushnie** [mullvad/mullvadvpn-app#942]
When you check which programs are using bandwidth through the OS, `OpenVPN Daemon` is reported as the only program using bandwidth. It would be nice to see what's actually using bandwidth, and how much of it.

**Comment by faern** [comment]
I'm sorry, but this is currently far outside our scope. We make sure device traffic goes through a tunnel securely. We don't monitor what programs send it, nor want to complicate the UI with things unrelated to setting up and configuring the tunnel itself.

**Comment by pronebird** [comment]
I haven't tried but you could probably use Little snitch or similar programs to see this kind of information.
