### ISSUE TITLE
Connection Issues After Restart or Boot

### ISSUE THREAD

**Issue by RobertStanford1** [mullvad/mullvadvpn-app#986]
Bug Title: 
**Issues connecting after restarting or powering on Mac**

Platform/Environment/Version:
**2019.6**

Description:
**Every time I restart my Mac or boot it from a shut down, Mullvad blocks all connections.**

Steps to Reproduce:
**Turn launch app on start-up and auto-connect on. Then, restart a Mac or power it on from shutdown and attempt to use the internet.**

Temporary Fix:
**Turn the WiFi connection off and wait approximately 15 seconds. Then, attempt to re-connect to a Mullvad server. If the re-connection attempt is made too quickly after start-up, the app will continue to block all connections.**

Client Settings:
Launch app on start-up: **Enabled**
Auto-connect: **Enabled**
Local Network Sharing: **Enabled**
Notifications: **Enabled**
Monochromatic Tray Icon: **Enabled**

Enable IPv6: **Disabled**
Block when Disconnected: **Disabled**
Network Protocols: **Automatic**
Bridge Mode: **Automatic**
Mssfix: **Default**

**Comment by RobertStanford1** [comment]
It should be noted that if my Mac is in sleep mode, Mullvad does not have this issue upon wake and the connection is always immediately successful.

**Comment by faern** [comment]
Thanks for the report! We are aware of some mac power/sleep issues where it can get stuck as blocked for some people. We will look into it!

**Comment by shashikantx** [comment]
I have been facing same problem too on Windows 10 Version 1903 Build .295
Can't connect after a restart. 
Updated to 2019.7 today, no improvements.

**Comment by brakenow** [comment]
> I have been facing same problem too on Windows 10 Version 1903 Build .295
> Can't connect after a restart.
> Updated to 2019.7 today, no improvements.
Same here. It's driving me crazy!

**Comment by faern** [comment]
I'm closing this issue since nothing new has been added in quite a while and quite a lot of offline detection and startup logic has changed since the issue was last touched. Hopefully it should work better on every platform now. Feel free to re-open or create a new issue if you are still having issues after restart or waking up from sleep etc.
